import Mettapedia.Analysis.AngularCurlVariation
import Mettapedia.Analysis.AngularCurlSpatialVariation
import Mettapedia.Analysis.AngularCurlVariationTests
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.FiniteAngularSourceWork
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.FilteredAngularSourceBalance
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.FilteredAngularSourceIntegral
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.AngularInviscidWorkLimit

/-! Dependency audit for signed angular source work and the initial-endpoint inequality. -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.AngularInviscidWorkLimit.inviscidAngularVariation
#print axioms Mettapedia.FluidDynamics.NavierStokes.AngularInviscidWorkLimit.integral_octicInviscidWork_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.AngularInviscidWorkLimit.resolved_work_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.AngularInviscidWorkLimit.tendsto_resolved_work
#print axioms Mettapedia.FluidDynamics.NavierStokes.AngularInviscidWorkLimit.no_decaying_work_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.AngularInviscidWorkLimit.positive_snapshot_no_decaying_work_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.AngularInviscidWorkLimit.sourceWork_resolved_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.AngularInviscidWorkLimit.positive_snapshot_no_decaying_sourceWork_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.AngularInviscidWorkLimit.positive_snapshot_beyond_every_threshold
#print axioms Mettapedia.Analysis.AngularCurlVariationTests.value_response
#print axioms Mettapedia.Analysis.AngularCurlVariationTests.jet_response
#print axioms Mettapedia.Analysis.AngularCurlVariationTests.full_response
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.variationalGradient
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.continuous_variationalGradient
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.integral_angularCurlDensityRate_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularSourceBalance.sourceWork
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularSourceBalance.sourceWork_eq_resolved_add_subgrid
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularSourceBalance.exists_coercive_source_threshold
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.amplitudeGradientRate
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.angularCurlRate_eq
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.curlJetAdjoint
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.inner_curlJet_eq
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.valueGradient
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.jetGradient
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.angularCurlDensityRate_eq_pairing
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.jetGradientRate
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.gradient_pairing_self
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.hasDerivAt_curlJetAdjoint
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.hasDerivAt_jetGradient
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.continuous_curlJetAdjoint
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.continuous_amplitudeGradient
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.continuous_valueGradient
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.continuous_jetGradient
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.continuous_jetGradientRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularSourceIntegral.continuous_inviscidRHS_component
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularSourceIntegral.continuousOn_sourceWork
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularSourceIntegral.continuousOn_retainedDissipation
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularSourceIntegral.exists_initial_energy_inequality
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularSourceWork.angularGradient
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularSourceWork.continuous_angularGradient
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularSourceWork.integral_densityRate_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularSourceWork.correctedGradient
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularSourceWork.continuous_correctedGradient
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularSourceWork.integral_correctedDensityRate_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularSourceWork.work_eq_pairing
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularSourceWork.integral_angularGradient_self
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularSourceWork.integral_correctedGradient_self
