import Mettapedia.Analysis.AngularCurlSecondVariation
import Mettapedia.Analysis.AngularCurlCurvatureBound
import Mettapedia.Analysis.AngularCurlCurvatureTests
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.FiniteAngularCurlDiffusion
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.FiniteBandAngularDiffusion
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.FilteredAngularViscousBalance

/-! Axiom audit for angular curvature and the actual filtered viscous balance. -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularViscousBalance.fullCurlGradient_viscous
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularViscousBalance.correctedDensityRate_viscous
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularViscousBalance.work
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularViscousBalance.work_add
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularViscousBalance.work_viscous
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularViscousBalance.hasDerivAt_correctedEnergy_viscous
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredAngularViscousBalance.exists_coercive_dissipative_threshold
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.norm_curlJet_le_sum
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.norm_angularJet_le
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.norm_angularCurl_le
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.norm_angularJetRate_le
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.norm_angularCurlRate_le
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.norm_angularJetSecondVariation_le
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.norm_angularCurlSecondVariation_le
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.angularCurlDensitySecondVariation_le_norm_sums
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.sum_norm_sq_le_three
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.angularCurlDensitySecondVariation_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.firstRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.curvature
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.secondRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.curvatureDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.densityLaplacian
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.hasDerivAt_density_shift
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.hasDerivAt_firstRate_shift
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.densityLaplacian_eq_sum
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.sum_third_eq_gradientLaplacian
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.viscousDensityRate_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.continuous_firstRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.continuous_curvature
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.continuous_secondRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.integral_densityLaplacian_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteAngularCurlDiffusion.integral_viscousDensityRate_eq
#print axioms Mettapedia.Analysis.AngularCurlCurvatureTests.value
#print axioms Mettapedia.Analysis.AngularCurlCurvatureTests.first
#print axioms Mettapedia.Analysis.AngularCurlCurvatureTests.second
#print axioms Mettapedia.Analysis.AngularCurlCurvatureTests.first_divergence
#print axioms Mettapedia.Analysis.AngularCurlCurvatureTests.second_symmetric
#print axioms Mettapedia.Analysis.AngularCurlCurvatureTests.second_divergence
#print axioms Mettapedia.Analysis.AngularCurlCurvatureTests.curvature_trace
#print axioms Mettapedia.Analysis.AngularCurlCurvatureTests.positive_curvature
#print axioms Mettapedia.Analysis.AngularCurlCurvatureTests.negative_curvature
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteBandAngularDiffusion.curvatureDensity_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteBandAngularDiffusion.integral_curvatureDensity_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteBandAngularDiffusion.exists_curvature_constant
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteBandAngularDiffusion.correctedViscousDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteBandAngularDiffusion.integral_correctedViscousDensity_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteBandAngularDiffusion.exists_diffusion_threshold
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.angularJetSecondVariation
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.angularCurlSecondVariation
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.angularCurlDensitySecondVariation
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.hasDerivAt_angularJetRate
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.hasDerivAt_angularCurlRate
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.hasDerivAt_angularCurlDensityRate
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.continuous_angularCurlSecondVariation
#print axioms Mettapedia.Analysis.AngularCurlDecomposition.continuous_angularCurlDensitySecondVariation
