import Mettapedia.Analysis.WeightedInnerProduct
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.ExchangedFluxAdjoint
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.ExchangedFluxVariationSeries
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.ExchangedFluxAdjointSeries
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.ExchangedFluxAdjointPairing
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.ExchangedFluxHeatAdjoint
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.ExchangedFluxAdjointGeometry
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.ExchangedFluxHeatDualBudget

/-! Axiom audit for the constructed adjoints and their actual heat-work bridge. -/

#print axioms Mettapedia.Analysis.WeightedInnerProduct.two_mul_abs_inner_le
#print axioms Mettapedia.Analysis.WeightedInnerProduct.two_mul_inner_le
#print axioms Mettapedia.Analysis.WeightedInnerProduct.two_mul_abs_inner_sum_le
#print axioms Mettapedia.Analysis.WeightedInnerProduct.lintegral_two_mul_abs_inner_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.curlCoefficientCLM
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.curlCoefficientCLM_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.outerTensorCLM
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.leftTensorCLM
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.rightTensorCLM
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.outerSlot
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.leftSlot
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.rightSlot
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.outerSlot_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.leftSlot_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.rightSlot_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.outerTest
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.leftTest
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.rightTest
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjoint.inner_variationMode_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxVariationSeries.norm_mixedMode_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxVariationSeries.summable_norm_mixedMode
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxVariationSeries.summable_norm_variationMode
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxVariationSeries.mixedMode_innerExchange
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxVariationSeries.tsum_mixedMode_innerExchange
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxVariationSeries.mixedMode_eq_zero_of_inner_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxVariationSeries.tsum_active_variationMode
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxVariationSeries.fluxVariation_eq_outer_add_twice_inner
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointSeries.norm_outerSlot_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointSeries.norm_leftSlot_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointSeries.norm_outerTest_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointSeries.norm_leftTest_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointSeries.summable_norm_outerTest
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointSeries.summable_norm_leftTest
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointSeries.coefficientTest
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointPairing.firstSecondExchange
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointPairing.summable_mixedPairing
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointPairing.outer_pairing_sum
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointPairing.left_pairing_sum
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointPairing.summable_coefficientPairing
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointPairing.inner_fluxVariation_eq_tsum
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatAdjoint.heatCoefficientTest
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatAdjoint.summable_fourierMoment_commutator
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatAdjoint.summable_heatCoefficientPairing
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatAdjoint.inner_commutatorVariation_eq_tsum
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatAdjoint.coefficientWorkDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatAdjoint.heatWorkDensity_eq_coefficientWorkDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatAdjoint.fullGramWork_eq_integral_coefficientWorkDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatAdjoint.integrableOn_coefficientWorkDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatAdjoint.intervalIntegrable_integral_coefficientWorkDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatAdjoint.full_coefficient_gram_energy_identity
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatAdjoint.exists_physical_local_coefficient_budget
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointGeometry.norm_mixedMode_le_projected_cross
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointGeometry.norm_outerSlot_le_projected_cross
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointGeometry.norm_outerTest_le_projected_cross
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointGeometry.norm_leftSlot_le_difference
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointGeometry.norm_leftTest_le_difference
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointGeometry.norm_differenceCLM_le_output
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointGeometry.norm_curlCoefficientCLM_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointGeometry.norm_difference_mul_curl_le_pair_frequency
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointGeometry.norm_leftTest_le_pair_frequency
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointGeometry.outerTest_eq_zero_of_cross_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointGeometry.differenceCLM_eq_zero_of_opposite
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxAdjointGeometry.tests_eq_zero_of_opposite
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatDualBudget.commutatorSquareIntegral
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatDualBudget.testSquareIntegral
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatDualBudget.negativeCommutatorCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatDualBudget.positiveTestCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatDualBudget.absolutePairingCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatDualBudget.lintegral_commutator_sq_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatDualBudget.commutatorSquareIntegral_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatDualBudget.negativeCommutatorCost_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatDualBudget.negativeCommutatorCost_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatDualBudget.coefficientPairingCost_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatDualBudget.absolutePairingCost_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatDualBudget.absolutePairingCost_le_initial_add_test
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxHeatDualBudget.exists_physical_local_adjoint_balance
