import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.ExchangedFluxLogarithmicHeatBudget

/-! Axiom audit of the dyadic commutator payment and actual logarithmic heat-test budget. -/

#print axioms Mettapedia.Analysis.IntegerDyadicShell.Lattice
#print axioms Mettapedia.Analysis.IntegerDyadicShell.height
#print axioms Mettapedia.Analysis.IntegerDyadicShell.index
#print axioms Mettapedia.Analysis.IntegerDyadicShell.cube
#print axioms Mettapedia.Analysis.IntegerDyadicShell.shell
#print axioms Mettapedia.Analysis.IntegerDyadicShell.coordinate_le_height
#print axioms Mettapedia.Analysis.IntegerDyadicShell.height_eq_zero_iff
#print axioms Mettapedia.Analysis.IntegerDyadicShell.mem_cube
#print axioms Mettapedia.Analysis.IntegerDyadicShell.mem_shell
#print axioms Mettapedia.Analysis.IntegerDyadicShell.ne_zero_of_mem_shell
#print axioms Mettapedia.Analysis.IntegerDyadicShell.mem_shell_index
#print axioms Mettapedia.Analysis.IntegerDyadicShell.index_eq_of_mem_shell
#print axioms Mettapedia.Analysis.IntegerDyadicShell.mem_shell_iff
#print axioms Mettapedia.Analysis.IntegerDyadicShell.card_cube
#print axioms Mettapedia.Analysis.IntegerDyadicShell.card_shell_le
#print axioms Mettapedia.Analysis.IntegerDyadicShell.tsum_shells
#print axioms Mettapedia.Analysis.IntegerDyadicShell.tsum_shells_le
#print axioms Mettapedia.Analysis.IntegerDyadicShell.summationWeight
#print axioms Mettapedia.Analysis.IntegerDyadicShell.summationWeight_pos
#print axioms Mettapedia.Analysis.IntegerDyadicShell.sum_summationWeight
#print axioms Mettapedia.Analysis.IntegerDyadicShell.hasSum_summationWeight
#print axioms Mettapedia.Analysis.IntegerDyadicShell.tsum_ofReal_summationWeight
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorShellBudget.height_le_norm_frequency
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorShellBudget.radius_le_norm_frequency
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorShellBudget.initialShellBudget
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorShellBudget.initialShellBudget_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorShellBudget.shellCommutatorCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorShellBudget.shellTestCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorShellBudget.coefficientCost_le_shell_radius
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorShellBudget.shellCommutatorCost_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatCost.nonlinearCommutator_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatCost.coefficientPairingCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatCost.shellPairingCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatCost.logarithmicTestCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatCost.coefficientPairingCost_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatCost.absolutePairingCost_eq_tsum_shells
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatCost.shellPairingCost_le_initial_add_test
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatCost.absolutePairingCost_le_of_allocation
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatCost.absolutePairingCost_le_initial_add_logarithmic
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatBudget.logarithmicFactor_le_three_mul_two_pow
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatBudget.logarithmicWeight_le_three_mul_frequencyWeight_sq
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatBudget.logarithmicWeight_ratio_tendsto_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatBudget.logarithmicTestCost_le_three_mul_positiveTestCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxLogarithmicHeatBudget.exists_physical_local_logarithmic_heat_budget
