import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.ExchangedFluxPowerHeatBudget

/-! Axiom audit of the nonquadratic commutator payment and its explicit frequency tradeoff. -/

#print axioms Mettapedia.Analysis.WeightedYoung.mul_le_weighted_rpow
#print axioms Mettapedia.Analysis.WeightedYoung.rpow_eight_thirds_le_sq_mul
#print axioms Mettapedia.Analysis.WeightedYoung.two_mul_abs_inner_le_bounded_eight_fifths
#print axioms Mettapedia.Analysis.WeightedYoung.lintegral_two_mul_abs_inner_le_bounded_eight_fifths
#print axioms Mettapedia.Analysis.FinitePowerInterpolation.sum_eight_fifths_le_card_one_fifth_mul_sum_sq
#print axioms Mettapedia.Analysis.FinitePowerInterpolation.card_factor_equality
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorPowerBudget.norm_frequency_le_six_mul_radius
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorPowerBudget.initialAmplitude
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorPowerBudget.initialAmplitude_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorPowerBudget.initialPowerShellBudget
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorPowerBudget.initialPowerShellBudget_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorPowerBudget.commutatorPowerIntegral
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorPowerBudget.shellCommutatorPowerCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorPowerBudget.norm_commutator_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorPowerBudget.norm_commutator_le_initial_shell
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorPowerBudget.commutatorPowerIntegral_le_square
#print axioms Mettapedia.FluidDynamics.NavierStokes.FourierHeatCommutatorPowerBudget.shellCommutatorPowerCost_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPowerHeatCost.testPowerIntegral
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPowerHeatCost.shellTestPowerCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPowerHeatCost.logarithmicTestPowerCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPowerHeatCost.normalized_allocation_rpow
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPowerHeatCost.coefficientPairingCost_le_square_add_power
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPowerHeatCost.shellPairingCost_le_initial_add_power
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPowerHeatCost.absolutePairingCost_le_of_allocation
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPowerHeatCost.absolutePairingCost_le_initial_add_logarithmic_power
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPowerHeatBudget.shell_power_cost_le_derivative_square
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPowerHeatBudget.exists_physical_local_power_heat_budget
