import Mettapedia.Analysis.FiniteEnvelopeSquareBound
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.ExchangedFluxTameAdjoint
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.ExchangedFluxTameHeatCost

/-! Axiom audit of additive adjoint derivative costs and the minimum heat envelope. -/

#print axioms Mettapedia.Analysis.FiniteEnvelopeSquareBound.norm_sum_sq_le
#print axioms Mettapedia.Analysis.FiniteEnvelopeSquareBound.sum_norm_sum_sq_le
#print axioms Mettapedia.Analysis.FiniteEnvelopeSquareBound.sum_norm_tsum_sq_le
#print axioms Mettapedia.Analysis.FiniteEnvelopeSquareBound.summable_norm_tsum_sq
#print axioms Mettapedia.Analysis.FiniteEnvelopeSquareBound.tsum_norm_tsum_sq_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.inputWeight
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.outputEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.tameEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.inputWeight_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.outputEnvelope_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.one_add_norm_sq_le_pairShift
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.norm_weighted_term_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.summable_inputWeight
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.tsum_inputWeight
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.summable_outputEnvelope_sq
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.sum_envelope_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.sum_weighted_series_sq_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.summable_weighted_series_sq
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.tsum_weighted_series_sq_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.tameEnvelope_mul
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.tsum_weighted_coefficientTest_sq_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.tsum_weighted_selectedTest_sq_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.norm_remainderTerm_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameAdjoint.tsum_weighted_remainderTest_sq_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameHeatCost.tameHeatEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameHeatCost.minHeatEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameHeatCost.weightedCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameHeatCost.weightedCost_le_of_tsum_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameHeatCost.tsum_weighted_heatTest_sq_le_tame
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameHeatCost.tsum_ofReal_weighted_heatTest_sq_le_min
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameHeatCost.positiveTestCost_le_minEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameHeatCost.tsum_weighted_selectedHeatTest_sq_le_tame
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameHeatCost.tsum_ofReal_weighted_selectedHeatTest_sq_le_min
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameHeatCost.selectedHeatCost_le_minEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxTameHeatCost.absolutePairingCost_le_initial_add_minEnvelope
