import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalParabolicProjectorBound
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalBottomGradientObstruction

/-! Axiom audit of the parabolic projector cancellation, bounds, and gradient obstruction. -/

#print axioms Mettapedia.Analysis.idempotent_defect_image_block
#print axioms Mettapedia.Analysis.idempotent_defect_complement_block
#print axioms Mettapedia.Analysis.SpectralRelationDerivatives.derivative_relation
#print axioms Mettapedia.Analysis.SpectralRelationDerivatives.second_derivative_relation
#print axioms Mettapedia.Analysis.SpectralRelationDerivatives.parabolic_relation
#print axioms Mettapedia.Analysis.KernelCrossTerm.exists_kernel_crossTerm_gt
#print axioms Mettapedia.Analysis.KernelCrossTerm.not_exists_projectedSquare_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomParabolicProjectorMotion.inner_bottom_plane_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomParabolicProjectorMotion.inner_plane_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomParabolicProjectorMotion.inner_strain_plane_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomParabolicProjectorMotion.norm_bottomCoupling_le_of_spectral_relation
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomParabolicProjectorMotion.norm_bottomCoupling_sub_smul_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomParabolicProjectorMotion.norm_bottomCoupling_le_of_parabolic_relation
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralRelation.strainCurve_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralRelation.contDiff_strainCurve
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralRelation.hasDerivAt_strainCurve
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralRelation.deriv_strainCurve
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralRelation.deriv_deriv_strainCurve
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralRelation.contDiffAt_bottomEigenvalueCurve
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralRelation.second_spectral_relation
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralRelation.laplacian_spectral_relation
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralBounds.hasDerivAt_projectorCurve
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralBounds.projectorFirst_tangent
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralBounds.projectorFirst_isSelfAdjoint
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralBounds.abs_bottomEigenvalueFirst_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralBounds.norm_projectorFirst_apply_bottom_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralBounds.norm_projectorFirst_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralBounds.strainGradientSquare_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralBounds.norm_bottomCoupling_mixedGradient_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalParabolicProjectorEquation.neg_planeRate_eq_deriv_bottomProjector
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalParabolicProjectorEquation.parabolicRate_constraint
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalParabolicProjectorEquation.parabolicRate_bottom_block
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalParabolicProjectorEquation.parabolicRate_plane_block
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalParabolicProjectorEquation.parabolicRate_spectral_relation
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalParabolicProjectorEquation.ae_ae_parabolicRate_equations
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalParabolicProjectorBound.ae_ae_couplingBound
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalParabolicProjectorBound.exists_physical_localBottomParabolicControl
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomGradientObstruction.not_exists_projectedGradient_bound
