import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalExcessDiffusionEnergy

/-!
# Axiom audit for local diffusion density and excess-only physical energy
-/

#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.excessCost_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.excessCost_le_limitingDiffusionCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.limitingDiffusionCost_le_half_residual_add_excessCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.excessCost_eq_zero_of_gap_dominates
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.excessCost_eq_zero_of_aligned
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.excessCost_eq_full_cost_of_topGap_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.measurable_excessCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.integrable_excessCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.integral_excessCost_le_limitingDiffusionCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.measurable_excessCost_spaceTime
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.intervalIntegrable_excessCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.integral_limitingDiffusionCost_le_half_residual_add_excessCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.integral_cost_le_half_residual_add_excess
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.meanEnergy_add_half_integral_residual_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.exists_physical_localExcessDiffusionEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalizedDiffusionIncrement.normalizedShiftCost_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalizedDiffusionIncrement.continuous_normalizedShiftCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalizedDiffusionIncrement.norm_normalizedShiftCost_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalizedDiffusionIncrement.tendsto_normalizedShiftCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalizedDiffusionIncrement.tendsto_integral_normalizedShiftCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalizedDiffusionIncrement.integral_centralUpper_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralDiffusionExcess.topGap_sq_mul_limitingWeight_le_residual
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralDiffusionExcess.excess_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralDiffusionExcess.excess_le_cost
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralDiffusionExcess.cost_le_half_residual_add_excess
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralDiffusionExcess.excess_eq_zero_of_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralDiffusionExcess.excess_eq_cost_of_topGap_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralDiffusionExcess.measurable_excess
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalStrainGradientDensity.continuous_strainGradient
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalStrainGradientDensity.continuous_strainGradientSquare
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalStrainGradientDensity.continuous_parametric_strainGradientSquare
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalStrainGradientDensity.strainGradientSquare_le_amplitude
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalizedLaplacianDiffusion.integral_joint_rate_le_centralUpper
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalizedLaplacianDiffusion.tendsto_integral_centralUpper
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalizedLaplacianDiffusion.integral_joint_rate_le_of_first_second_approx
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalDepletedDiffusionBudget.integral_laplacian_diffusion_local_paid
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalDiffusionWeightLimit.norm_limitingDiffusionCost_le_absolute
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalDiffusionWeightLimit.norm_diffusionCost_le_absolute
