import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalProjectorMotion

/-! Dependency audit for remainder-coupling projector motion and actual material transfer. -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectorMotion.norm_planeRate_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectorMotion.abs_inner_planeRate_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectorMotion.ae_ae_planeRate_bounds
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectorMotion.ae_ae_planeRate_young_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectorMotion.ae_ae_planeRate_gap_absorption
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.bottomVector_norm
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.apply_bottomVector
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.expandingPlaneProjector_apply_bottomVector
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.bottomCoupling_eq_rankOne
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.norm_bottomCoupling
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.norm_bottomCoupling_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.bottomCoupling_eq_zero_of_preserves_bottom
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.bottomCoupling_add_preserving
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.inner_remainder_bottom_eq_plane
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.strain_mul_bottomProjector
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.bottomProjector_derivative_equation
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.bottomGap_mul_norm_sq_le_rayleighExcess
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.inner_strainEquation_bottom
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.projectorMotion_energy_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.norm_bottomProjector_tangent_apply_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.norm_bottomProjector_tangent_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.norm_deriv_bottomEigenlineProjector_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.deriv_expandingPlaneProjector_eq_neg
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.norm_deriv_expandingPlaneProjector_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.deriv_expandingPlaneProjector_eq_zero_of_preserves_bottom
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.abs_inner_deriv_bottomProjector_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.abs_inner_deriv_expandingPlaneProjector_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.planeTransfer_le_weightedEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomProjectorMotion.abs_inner_deriv_expandingPlaneProjector_le_young
#print axioms Mettapedia.FluidDynamics.NavierStokes.RankOneProjectorTangent.lineProjector_isSelfAdjoint
#print axioms Mettapedia.FluidDynamics.NavierStokes.RankOneProjectorTangent.lineProjector_mul_self
#print axioms Mettapedia.FluidDynamics.NavierStokes.RankOneProjectorTangent.lineProjector_apply_self
#print axioms Mettapedia.FluidDynamics.NavierStokes.RankOneProjectorTangent.inner_tangent_self_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.RankOneProjectorTangent.tangent_eq_rankOne_sum
#print axioms Mettapedia.FluidDynamics.NavierStokes.RankOneProjectorTangent.norm_tangent_le_two_mul
