import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalDepletedAlignmentBudget

/-! Dependency audit for the continuous depleted source and its actual initial-data estimate. -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.StrainEigenvalueContinuity.lipschitzWith_thirdEigenvalue
#print axioms Mettapedia.FluidDynamics.NavierStokes.StrainEigenvalueContinuity.trace_eq_sum_orderedEigenvalues
#print axioms Mettapedia.FluidDynamics.NavierStokes.StrainEigenvalueContinuity.continuous_trace
#print axioms Mettapedia.FluidDynamics.NavierStokes.StrainEigenvalueContinuity.continuous_secondEigenvalue
#print axioms Mettapedia.FluidDynamics.NavierStokes.StrainEigenvalueContinuity.continuous_topGap
#print axioms Mettapedia.FluidDynamics.NavierStokes.StrainEigenvalueContinuity.continuous_bottomGap
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyEnvelope.topGap_mul_lineRemainder_sq_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyEnvelope.regularizedGap_mul_lineRemainder_sq_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyEnvelope.norm_lineRemainder_le_sqrt
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyEnvelope.abs_remainderAnisotropy_le_envelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyEnvelope.envelope_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyEnvelope.envelope_le_coarse
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyEnvelope.envelope_le_of_energy_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyEnvelope.envelope_eq_coarse_of_topGap_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyEnvelope.regularizedEnergy_aligned
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyEnvelope.envelope_le_quarter_coarse_of_aligned
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyEnvelope.continuous_envelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalDepletedAlignmentSource.depletedForcingEnvelope_le_signed
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalDepletedAlignmentSource.materialRate_depleted_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalDepletedAlignmentSource.continuous_depletedForcingEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalDepletedAlignmentSource.continuous_depletedForcingEnvelope_spaceTime
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalDepletedAlignmentSource.integral_materialRate_add_residual_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalDepletedAlignmentBudget.meanEnergy_add_integral_residual_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalDepletedAlignmentBudget.meanEnergy_add_integral_residual_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalDepletedAlignmentBudget.exists_physical_localDepletedAlignmentBudget
