import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalMeanAlignmentEstimate
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalAlignmentDifferential

/-! Dependency audit for actual full-field mean balances and tangent-curve differentiation. -/

#print axioms LocallyLipschitz.finsetSum
#print axioms LocallyLipschitz.pi
#print axioms LocallyLipschitz.mul_algebra
#print axioms LocallyLipschitz.hasDerivAt_comp_of_tangent
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalVorticityTime.norm_fullFourierField_uniform_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalVorticityTime.norm_curl_velocityRHS_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalVorticityTime.fullCurlField_hasDerivAt
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalVorticityTime.fullVorticity_hasDerivAt
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalVorticityTime.lipschitzOnWith_fullCurlField
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpaceTimeExtension.coefficients_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpaceTimeExtension.moment_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpaceTimeExtension.summable_moment
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpaceTimeExtension.exists_lipschitzWith_fullCurl_lift
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpaceTimeExtension.locallyLipschitz_fullVorticity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpaceTimeExtension.locallyLipschitz_coefficients
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpaceTimeExtension.locallyLipschitz_strain
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpaceTimeExtension.locallyLipschitz_alignmentEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpaceTimeExtension.continuous_alignmentEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMeanAlignmentBalance.velocity_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMeanAlignmentBalance.continuous_velocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMeanAlignmentBalance.locallyLipschitz_extendedVelocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMeanAlignmentBalance.divergence_extendedVelocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMeanAlignmentBalance.ae_hasDerivAt_extendedMean
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMeanAlignmentBalance.intervalIntegral_extendedMaterialRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMeanAlignmentBalance.frozenMaterialRate_extension_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMeanAlignmentBalance.ae_hasDerivAt_meanEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMeanAlignmentBalance.intervalIntegral_frozenMaterialRate_eq_energy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalEnergySubinterval.integral_le_of_energy_enstrophy_majorant
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMeanAlignmentEstimate.meanEnergy_add_integral_residual_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalInteriorTrajectory.exists_materialTrajectory_through
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalVorticityTangency.hasDerivAt_fullVorticity_path
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAlignmentDifferential.hasDerivAt_alignmentEnergy_path
