import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalSourceCommutator
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalExcessDiffusionEnergy
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.SpectralSourceCommutatorTests

/-!
# Axiom audit for commutator-sensitive physical alignment sources
-/

#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSourceCommutator.continuous_sourceCommutator
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSourceCommutator.continuous_sourceCommutator_spaceTime
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSourceCommutator.limitingForcingEnvelope_le_of_commutator_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSourceCommutator.limitingForcingEnvelope_le_refined
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSourceCommutator.nonviscousRemainder_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSourceCommutator.sourceCommutator_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorEnvelope.abs_remainderAnisotropy_le_envelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorEnvelope.abs_remainderAnisotropy_le_refinedBound
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorEnvelope.continuous_envelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorEnvelope.continuous_tiltBound
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorEnvelope.envelope_eq_coarse_of_topGap_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorEnvelope.envelope_le_coarse
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorEnvelope.envelope_le_previous
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorEnvelope.envelope_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorEnvelope.refinedBound_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorEnvelope.tiltBound_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorLimit.abs_remainderAnisotropy_le_limitingEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorLimit.limitingEnvelope_aligned
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorLimit.limitingEnvelope_eq_coarse_of_topGap_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorLimit.limitingEnvelope_le_coarse
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorLimit.limitingEnvelope_le_previous
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorLimit.limitingEnvelope_le_quadratic_of_commutator_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorLimit.limitingEnvelope_le_refined
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorLimit.limitingEnvelope_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorLimit.measurable_limitingEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralCommutatorLimit.tendsto_envelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.abs_anisotropy_le_regularized_commutator
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.abs_anisotropy_le_transverse
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.commutator_add
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.commutator_isotropic
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.commutator_mul
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.commutator_neg
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.commutator_self
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.continuous_commutator
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.inner_lineRemainder_left
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.norm_commutator_adjoint
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.norm_transverse_source_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.norm_transverse_source_le_regularized
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.residual_source_topVector
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.topGap_mul_norm_lineRemainder_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutator.topGap_mul_norm_transverse_source_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralSourceCommutatorTests.exists_commuting_zero_gap_source_with_nonzero_anisotropy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalDepletedAlignmentSource.materialRate_depleted_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAlignmentSourceLimit.intervalIntegrable_and_tendsto_integral_source
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.meanEnergy_add_half_integral_residual_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalExcessDiffusionEnergy.exists_physical_localExcessDiffusionEnergy
