import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalBottomSectorBudget

/-! Axiom audit of the signed sector identity and actual local damping estimate. -/

#print axioms Mettapedia.Analysis.OperatorQuadraticForm.isSymmetric_second_derivative
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.apply_idempotent
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.apply_complement
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.tangent_image_zero
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.tangent_complement_eq
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.tangent_cross_split
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.quadratic_split
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.quadratic_sum_squares
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.complement_symmetric
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.quadratic_image_defect
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.quadratic_complement_defect
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.gradient_completed_square
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.signed_diffusion_split
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.abs_cross_le
#print axioms Mettapedia.Analysis.OrthogonalProjectionParabolic.abs_cross_le_young
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialSpectralBounds.norm_projectorFirst_apply_bottomProjector_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomParabolicSectors.projectorSecond_isSelfAdjoint
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomParabolicSectors.projectorLaplacian_isSelfAdjoint
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomParabolicSectors.parabolicRate_isSelfAdjoint
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomParabolicSectors.completedGradientSquare_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomParabolicSectors.bottomFrameGradientSquare_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomParabolicSectors.abs_frameCross_le_young
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomParabolicSectors.signed_diffusion_split
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomParabolicSectors.materialRate_sub_diffusion_add_completedSquare_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomParabolicSectors.materialRate_sub_diffusion_add_damping_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomSectorBudget.materialRate_sector_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomSectorBudget.half_gap_le_dampingCoefficient
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomSectorBudget.SectorControl.half_gap_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomSectorBudget.ae_ae_sectorControl
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalBottomSectorBudget.exists_physical_localBottomSectorControl
