import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalLimitingAlignmentBudget
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalCoherentAlignmentRate

/-! Dependency audit for the source limit and actual coherent material rate. -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyLimit.limitingEnvelope_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyLimit.limitingEnvelope_le_coarse
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyLimit.abs_remainderAnisotropy_le_limitingEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyLimit.tendsto_envelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyLimit.limitingEnvelope_aligned
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyLimit.approximationParameter_pos
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyLimit.tendsto_approximationParameter
#print axioms Mettapedia.FluidDynamics.NavierStokes.SpectralAnisotropyLimit.measurable_limitingEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLimitingAlignmentSource.norm_depletedForcingEnvelope_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLimitingAlignmentSource.norm_limitingForcingEnvelope_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLimitingAlignmentSource.tendsto_depletedForcingEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLimitingAlignmentSource.continuous_absoluteSourceBound
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLimitingAlignmentSource.measurable_limitingForcingEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLimitingAlignmentSource.integrable_limitingForcingEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLimitingAlignmentSource.tendsto_integral_depletedForcingEnvelope
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLimitingAlignmentSource.continuous_absoluteSourceBound_spaceTime
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAlignmentSourceLimit.intervalIntegrable_and_tendsto_integral_source
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLimitingAlignmentBudget.meanEnergy_add_integral_residual_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLimitingAlignmentBudget.exists_physical_localLimitingAlignmentBudget
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalCoherentAlignmentRate.alignmentEnergy_zero_eq_inner_residual
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalCoherentAlignmentRate.alignmentEnergy_zero_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalCoherentAlignmentRate.alignmentEnergy_zero_of_residual_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalCoherentAlignmentRate.frozenMaterialRate_eq_zero_of_alignmentEnergy_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalCoherentAlignmentRate.materialRate_zero_eq_anisotropies_of_residual_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalCoherentAlignmentRate.ae_ae_materialRate_eq_regularizer_of_residual_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalCoherentAlignmentRate.ae_ae_anisotropy_add_viscous_eq_zero_of_residual_eq_zero
