import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalFilteredStrain
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.InfiniteConvectionEnergy
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.FilteredHighHighExample

/-! Axiom audit of actual filtering, all-input feedback and kinetic bounds. -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.InfiniteFilteredEquation.filtered_infiniteConvection
#print axioms Mettapedia.FluidDynamics.NavierStokes.InfiniteFilteredEquation.filtered_infiniteVelocityRHS_pressure
#print axioms Mettapedia.FluidDynamics.NavierStokes.InfiniteFilteredEquation.filtered_infiniteVelocityRHS
#print axioms Mettapedia.FluidDynamics.NavierStokes.InfiniteFilteredEquation.subgridConvection_sharp_of_mem
#print axioms Mettapedia.FluidDynamics.NavierStokes.InfiniteFilteredEquation.hasDerivAt_filtered_coefficients_finite
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalFilteredStrain.material_advection_add_correction
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalFilteredStrain.hasDerivAt_strain_matrix_material
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalFilteredStrain.hasDerivAt_strainAlong
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredHighHighExample.input_frequencies
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredHighHighExample.exists_nonzero_feedback_from_unresolved_velocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.InfiniteConvectionEnergy.norm_weightedConvection_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.InfiniteConvectionEnergy.norm_infiniteConvection_le_kineticEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.InfiniteConvectionEnergy.norm_subgridForce_sharp_le_kineticEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.InfiniteConvectionEnergy.norm_infinitePressureCoeff_le_kineticEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.InfiniteConvectionEnergy.local_kineticEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.InfiniteConvectionEnergy.norm_reconstructed_subgridForce_le_kineticEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.InfiniteConvectionEnergy.norm_local_reconstructed_subgridForce_le
