import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalSpectralDefectControl

/-! Axiom audit of top curvature, actual spectral diffusion, and physical-data control. -/

#print axioms Mettapedia.Analysis.deriv_deriv_smul_const_sub
#print axioms Mettapedia.Analysis.second_derivative_nonneg_of_isLocalMin
#print axioms Mettapedia.FluidDynamics.NavierStokes.StrainSpectralInvariants.characteristicValue_top_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.StrainSpectralInvariants.characteristicValue_top_derivative
#print axioms Mettapedia.FluidDynamics.NavierStokes.TopEigenvalueSmoothness.contDiffAt_topEigenvalue
#print axioms Mettapedia.FluidDynamics.NavierStokes.TopEigenvalueSmoothness.rayleigh_second_derivative
#print axioms Mettapedia.FluidDynamics.NavierStokes.TopEigenvalueSmoothness.rayleigh_second_derivative_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialTopEigenvalue.contDiffAt_eigenvalueCurve
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialTopEigenvalue.rayleigh_strainSecond_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpatialTopEigenvalue.curvature_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectDiffusion.energy_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectDiffusion.gradientSquare_coercive
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectDiffusion.contDiffAt_gapCurve
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectDiffusion.deriv_gapCurve
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectDiffusion.deriv_deriv_gapCurve
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectDiffusion.energySecond_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectDiffusion.energyLaplacian_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectBalance.materialRate_viscous_split
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectBalance.materialRate_sub_diffusion_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectBalance.gradientProduction_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectBalance.materialRate_sub_diffusion_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectBalance.hasDerivAt_frozenEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectControl.control
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectControl.exists_physical_localSpectralDefectControl
