import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalTopPlaneRate

/-! Dependency audit for ordered spectral rates and actual signed top-plane transport. -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.StrainEigenvalueRates.thirdEigenvalue_derivative_eq_of_hasDerivAt
#print axioms Mettapedia.FluidDynamics.NavierStokes.StrainEigenvalueRates.hasDerivAt_thirdEigenvalue_of_differentiableAt
#print axioms Mettapedia.FluidDynamics.NavierStokes.StrainEigenvalueRates.hasDerivAt_trace
#print axioms Mettapedia.FluidDynamics.NavierStokes.StrainEigenvalueRates.hasDerivAt_secondEigenvalue
#print axioms Mettapedia.FluidDynamics.NavierStokes.StrainEigenvalueRates.hasDerivAt_topGap
#print axioms Mettapedia.FluidDynamics.NavierStokes.TopPlaneGapTransport.inner_strainEquation_diagonal
#print axioms Mettapedia.FluidDynamics.NavierStokes.TopPlaneGapTransport.hasDerivAt_topGap_strainEquation
#print axioms Mettapedia.FluidDynamics.NavierStokes.TopPlaneGapTransport.remainder_diagonal_difference_eq_gapRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.TopPlaneGapTransport.remainderAnisotropy_expandingPlane_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.TopPlaneGapTransport.remainderAnisotropy_expandingPlane_eq_planeSource
#print axioms Mettapedia.FluidDynamics.NavierStokes.TopPlaneGapTransport.abs_remainderAnisotropy_sub_planeSource_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralFunctionDifferentiability.ae_ae_extended_scalarDifferentiable
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralFunctionDifferentiability.scalarDifferentiable_of_extension
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralFunctionDifferentiability.ae_ae_scalarDifferentiable
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalTopPlaneRate.hasDerivAt_frozenTopGap
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalTopPlaneRate.abs_jointAnisotropy_sub_planeSource_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalTopPlaneRate.ae_ae_abs_jointAnisotropy_sub_planeSource_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalTopPlaneRate.ae_ae_materialRate_add_residual_le_gapSource
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomSpectralProjectorPolynomial.bottomProjectorNumerator_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomSpectralProjectorPolynomial.bottomEigenlineProjector_eq_polynomial
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomSpectralProjectorPolynomial.differentiableAt_bottomEigenlineProjector
#print axioms Mettapedia.FluidDynamics.NavierStokes.BottomSpectralProjectorPolynomial.differentiableAt_expandingPlaneProjector
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalTopPlaneRate.ae_ae_differentiableAt_frozenProjectors
