import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalAlignmentRegularization

/-! Dependency audit for the actual local initial-data alignment budget. -/

#print axioms intervalIntegral.endpoint_estimate_of_interior
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicMaterialDifferentiability.differentiableAt_materialPath_of_real_fderiv
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicMaterialDifferentiability.ae_ae_differentiableAt_materialPath
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalFrozenAlignmentRate.frozenMaterialRate_eq_materialRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAESpectralDifferentiability.ae_ae_extended_spectralDifferentiable
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAESpectralDifferentiability.spectralDifferentiable_of_extension
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAESpectralDifferentiability.ae_ae_spectralDifferentiable
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAlignmentEnergyBudget.ae_ae_frozenMaterialRate_eq_materialRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAlignmentEnergyBudget.ae_integrable_materialRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAlignmentEnergyBudget.intervalIntegral_materialRate_eq_energy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAlignmentEnergyBudget.meanEnergy_add_integral_residual_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalInitialAlignmentBudget.meanEnergy_add_integral_residual_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalInitialAlignmentBudget.exists_physical_localAlignmentBudget
#print axioms Mettapedia.FluidDynamics.NavierStokes.RegularizedSpectralEnergySplitting.regularizedEnergy_eq_zero_add
#print axioms Mettapedia.FluidDynamics.NavierStokes.RegularizedSpectralEnergySplitting.linearRate_eq_zero_add
#print axioms Mettapedia.FluidDynamics.NavierStokes.RegularizedSpectralEnergySplitting.hasDerivAt_regularizedEnergy_sub_norm_sq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAlignmentRegularization.materialRate_eq_zero_add
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAlignmentRegularization.signedForcingEnvelope_eq_zero_add
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAlignmentRegularization.meanEnergy_eq_zero_add
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAlignmentRegularization.hasDerivAt_norm_fullVorticity_sq_path
