import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalSmoothMeanChannels

/-! Audit of actual mean evolution and the joint signed time identity. -/

#print axioms Mettapedia.Analysis.SmoothAmplitudePairing.locallyLipschitz_retainedStretch_even
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanRegularity.integral_density_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanRegularity.continuous_extendedDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanRegularity.locallyLipschitz_extendedDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanRegularity.frozenMaterialRate_extension_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanRegularity.absolutelyContinuousOnInterval_mean
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanBalance.frozenMaterialRate_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanBalance.ae_hasDerivAt_mean
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanBalance.integral_explicitRate_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanBalance.integral_source_eq_initial_add_weighted_rate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanChannels.explicitRate_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanChannels.continuous_diffusionRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanChannels.integral_diffusionRate_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanChannels.integrable_nonviscousRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanChannels.meanRate_eq_jointRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanChannels.ae_meanRate_eq_jointRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanChannels.ae_hasDerivAt_source
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSmoothMeanChannels.integral_source_eq_initial_add_weighted_channels
