import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalSpectralResidualBudget

/-! Axiom audit of the actual material spectral-defect and residual estimates. -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMaterialStrain.hasDerivAt_strainAlong
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMaterialStrain.continuous_laplacianStrain_spaceTime
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMaterialStrain.contDiffOn_strainAlong
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMaterialStrain.contDiffOn_vorticityAlong
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefect.integrated_defectAlong_identity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefect.integrated_defectAlong_budget
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectSources.spinAlong_vorticityAlong
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectSources.anisotropyAlong_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralDefectSources.spectralDefect_source_increment
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralResidual.hasDerivAt_spectralResidual
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralResidual.topEigenvalue_symmetricStrainAlong_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralResidual.ae_hasDerivAt_residualAlong
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralResidualBudget.absolutelyContinuousOnInterval_residualAlong
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralResidualBudget.intervalIntegrable_sourceAlong
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalSpectralResidualBudget.norm_residualAlong_le_initial_add_integral
