import Mettapedia.Analysis.LongitudinalHelicityBudgetTests
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalLongitudinalHelicityBudget

/-! # Dependency audit of longitudinally depleted helicity absorption -/

#print axioms Mettapedia.Analysis.LongitudinalHelicityBudget.amplitudeGradientSquare
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudget.longitudinalAmplitude
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudget.directionalHelicityDensity
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudget.amplitudeGradientSquare_nonneg
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudget.longitudinalAmplitude_sq_le
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudget.longitudinalAmplitude_eq_zero_of_amplitudeGradientSquare_eq_zero
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudget.directionalHelicityDensity_nonneg
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudget.directionalHelicityDensity_le
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudget.directionalHelicityDensity_eq_zero_of_longitudinalAmplitude_eq_zero
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudget.directionalHelicityDensity_le_normal_component
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudget.longitudinalDefect_sq
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudget.abs_longitudinalDefect_le
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudget.measurable_directionalHelicityDensity
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudgetTests.transverseJet
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudgetTests.transverseJet_divergence_zero
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudgetTests.transverseJet_amplitudeGradientSquare_one
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudgetTests.transverseJet_longitudinalAmplitude_zero
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudgetTests.transverseJet_helicity_one
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudgetTests.transverseJet_directionalHelicity_zero
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudgetTests.transverseJet_helicityDensity_one
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudgetTests.transverseJet_strict_improvement
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudgetTests.alignedJet_directionalHelicity_one
#print axioms Mettapedia.Analysis.LongitudinalHelicityBudgetTests.zero_vorticity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLongitudinalHelicityBudget.directionalHelicityMoment
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLongitudinalHelicityBudget.directionalHelicityMoment_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLongitudinalHelicityBudget.integrable_directionalHelicityDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLongitudinalHelicityBudget.directionalHelicityMoment_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLongitudinalHelicityBudget.directionalHelicityMoment_eq_zero_of_no_longitudinal_variation
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLongitudinalHelicityBudget.abs_longitudinalHelicityIntegral_le_directional
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLongitudinalHelicityBudget.stretching_add_spectral_le_directional
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLongitudinalHelicityBudget.measurable_directionalHelicityDensity_spaceTime
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLongitudinalHelicityBudget.intervalIntegrable_directionalHelicityMoment
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalLongitudinalHelicityBudget.energy_add_spectral_integral_le_directional
