import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LerayStretchExchange
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LongitudinalExchangeFluxFourier

/-! Axiom audit for exchange cancellation and the physical infinite flux series. -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.LerayStretchExchange.lerayMode_sub
#print axioms Mettapedia.FluidDynamics.NavierStokes.LerayStretchExchange.lerayMode_of_transverse
#print axioms Mettapedia.FluidDynamics.NavierStokes.LerayStretchExchange.lerayMode_wavevector
#print axioms Mettapedia.FluidDynamics.NavierStokes.LerayStretchExchange.lerayMode_neg
#print axioms Mettapedia.FluidDynamics.NavierStokes.LerayStretchExchange.stretch_pair_eq_leray_cross
#print axioms Mettapedia.FluidDynamics.NavierStokes.LerayStretchExchange.stretch_pair_add_exchange
#print axioms Mettapedia.FluidDynamics.NavierStokes.LerayStretchExchange.lerayMode_neg_frequency
#print axioms Mettapedia.FluidDynamics.NavierStokes.LerayStretchExchange.coefficientVec_lerayMode
#print axioms Mettapedia.FluidDynamics.NavierStokes.LerayStretchExchange.norm_lerayMode_sub_le_output
#print axioms Mettapedia.FluidDynamics.NavierStokes.LerayStretchExchange.norm_stretch_pair_add_exchange_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LerayStretchExchange.norm_lerayMode_sub_le_output_max
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.innerExchange
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.innerExchange_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.tripleFrequency_innerExchange
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.exchangeCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.combinedMode
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.exchangeMode
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.exchangeMode_eq_average
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.summable_combinedMode
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.summable_exchangeMode
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.tsum_exchangeMode
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.projectedFlux_inviscid_eq_exchangeSeries
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.exchangeCoeff_eq_leray_difference
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.sum_norm_projected_rankOne_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.exchangeCoeff_eq_projected
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.sum_exchangeCoeff_energy_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.sum_exchangeCoeff_energy_le_low_output
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalExchangeFluxFourier.jointSeriesCost_eq_exchangeSeries
