import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LongitudinalViscousFluxFourier

/-! Foundational dependency audit for the actual gradient projection symbol,
coefficient energy, and physical infinite viscous pair series. -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.realModeCLM
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.realMode
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.realMode_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.hasDerivAt_realMode
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.modeJet
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.contraction
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.projectedCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.potentialCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.projectedCoeff_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.potential_derivative
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.contraction_projectedCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.residual_derivative_sum
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.gradientProjection_realMode
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.summable_realModes
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.realFields_eq_tsum
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.gradientProjection_fullFourier
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.summable_projectedModes
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.gradientProjection_indexedFourier
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.contraction_rankOne
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.summable_indexedProjectedModes
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.projectedCoeff_rankOne_of_transverse
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxSymbol.gradientProjection_rankOne_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxPair.sum_norm_projectedCoeff_sq
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxPair.contraction_smul
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxPair.projectedCoeff_smul
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxPair.frequencyPairing
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxPair.viscousPairCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxPair.viscousPairCoeff_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxPair.projected_viscousPair_of_transverse
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxPair.projected_viscousPair_eq_zero_of_cross_transverse
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxProduct.coordinateSmul
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxProduct.pairCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxProduct.summable_norm_pairCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxProduct.fullFourierField_pairCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxProduct.productField
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxProduct.productField_eq_pairField
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxProduct.gradientProjection_productField
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxProduct.curlGradientProduct
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxProduct.curlGradientProduct_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.PeriodicGradientFluxProduct.gradientProjection_curlGradientProduct
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalViscousFluxFourier.viscousFluxField
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalViscousFluxFourier.viscousFluxField_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalViscousFluxFourier.depletedPairCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalViscousFluxFourier.projected_pair_eq_depleted
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalViscousFluxFourier.summable_depletedPairModes
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalViscousFluxFourier.gradientProjection_viscousFluxField
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalViscousFluxFourier.fluxField_eq_inviscid_add_viscous
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalViscousFluxFourier.projectedFlux_eq_inviscid_add_viscous
#print axioms Mettapedia.FluidDynamics.NavierStokes.LongitudinalViscousFluxFourier.projectedFluxSquare_eq_pairSeries
