import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.MixedGradientTests

/-!
# Kernel dependency audit for the weighted div–curl source budget

The audit includes the actual-field identities, radial/angular recombination,
constructed velocity supremum, regularized-center dynamics, and exact-flow tests.
It does not assert an initial-data bound for the remaining source costs.
-/

#print axioms Mettapedia.Analysis.UnitTorusContinuousRate.integral_rate_eq_zero
#print axioms Mettapedia.Analysis.UnitTorusContinuousRate.integral_rate_mul
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedDivCurl.advection
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedDivCurl.advectionGradient
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedDivCurl.gradientSquare
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedDivCurl.continuous_advection
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedDivCurl.continuous_advectionGradient
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedDivCurl.continuous_gradientSquare
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedDivCurl.hasDerivAt_advection_shift
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedDivCurl.gradientSquare_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedDivCurl.integral_weighted_divergence_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedDivCurl.integral_weighted_gradientSquare_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedDivCurl.integral_gradientSquare_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedDivCurl.mixedGradientCost_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMixedGradientBudget.sixthMoment
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMixedGradientBudget.advectionSquareIntegral
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMixedGradientBudget.weightedFlux
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMixedGradientBudget.continuous_weightedFlux
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMixedGradientBudget.weightedFlux_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMixedGradientBudget.mixedGradientCost_eq_add_flux
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMixedGradientBudget.mixedGradientCost_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalMixedGradientBudget.weightedSource_le_dissipation_advection
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAdvectionEnstrophy.velocitySupNorm
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAdvectionEnstrophy.norm_velocity_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAdvectionEnstrophy.advection_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAdvectionEnstrophy.norm_advection_sq_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAdvectionEnstrophy.advectionSquareIntegral_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAdvectionEnstrophy.advectionSquareIntegral_le_kineticEnstrophy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAdvectionEnstrophy.sixthMoment_le_one_add_meanEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalAdvectionEnstrophy.weightedSource_le_velocity_enstrophy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterSourceBudget.centerSource
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterSourceBudget.centerStretchFeedback
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterSourceBudget.centerViscousRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterSourceBudget.centerRate_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterSourceBudget.hasDerivAt_center_decomposed
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterSourceBudget.weightedCenterSource
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterSourceBudget.weighted_centerSource_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterSourceBudget.continuous_centerSource
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterSourceBudget.weightedCenterSource_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterSourceBudget.weightedCenterSource_le_dissipation_advection
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterSourceBudget.weightedCenterSource_le_velocity_enstrophy
#print axioms Mettapedia.FluidDynamics.NavierStokes.MixedGradientTests.advection_parallel_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.MixedGradientTests.advection_heatCoefficients_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.MixedGradientTests.mixedGradientCost_parallel_eq_sixthMoment
#print axioms Mettapedia.FluidDynamics.NavierStokes.MixedGradientTests.mixedGradientCost_heatCoefficients_eq_sixthMoment
#print axioms Mettapedia.FluidDynamics.NavierStokes.MixedGradientTests.centerSource_parallel_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.MixedGradientTests.centerStretchFeedback_parallel_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.MixedGradientTests.weightedCenterSource_heatCoefficients_eq_zero
