import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.MovingProjectionIntegratingFactor
import Mettapedia.Analysis.RegularizedProjectionParameterTests

/-! Axiom audit for moving regularization, actual mean balance, and bounded scale correction. -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionIntegratingFactor.factor
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionIntegratingFactor.factor_bounds
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionIntegratingFactor.hasDerivAt_factor
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionIntegratingFactor.differentiableAt_correctedEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionIntegratingFactor.deriv_weighted_correctedEnergy_add_dissipation_le
#print axioms Mettapedia.Analysis.ReciprocalScaleCost.integral_rate_div_sq_eq_inv_sub
#print axioms Mettapedia.Analysis.ReciprocalScaleCost.integral_abs_rate_div_sq_eq_inv_sub_of_nonneg
#print axioms Mettapedia.Analysis.ReciprocalScaleCost.integral_abs_rate_div_sq_le_inv_of_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionBudget.deriv_mean_eq_fixed_add_scale
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionBudget.continuous_normalization
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionBudget.continuous_normalizationRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionBudget.deriv_correctedEnergy_eq_fixed_add_scale
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionBudget.deriv_correctedEnergy_add_dissipation_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionBudget.deriv_correctedEnergy_add_dissipation_le_logarithmic_rate
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionBudget.deriv_correctedEnergy_add_dissipation_le_fixed_band
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionBudget.normalizationRate_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionBudget.integral_fixed_band_scale_coefficient_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionBudget.integral_initial_band_scale_coefficient_le_one
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionBudget.log_normalization_sub_le_integral_relative_speed
#print axioms Mettapedia.Analysis.LogarithmicScaleCost.integral_rate_div_eq_log_sub
#print axioms Mettapedia.Analysis.LogarithmicScaleCost.log_sub_le_integral_abs_rate
#print axioms Mettapedia.Analysis.LogarithmicScaleCost.integral_abs_rate_eq_log_sub_of_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionMean.movingRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionMean.continuous_density
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionMean.continuous_rate
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionMean.integral_movingRate_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionMean.hasDerivAt_density
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionMean.hasDerivAt_mean
#print axioms Mettapedia.FluidDynamics.NavierStokes.MovingProjectionMean.mean_balance
#print axioms Mettapedia.Analysis.RegularizedProjectionParameterTests.aligned_scaleRate_negative
#print axioms Mettapedia.Analysis.RegularizedProjectionParameterTests.aligned_scaleRate_positive
#print axioms Mettapedia.Analysis.RegularizedProjectionParameterTests.constant_scaleRate
#print axioms Mettapedia.Analysis.RegularizedProjectionParameter.hasDerivAt_coefficient
#print axioms Mettapedia.Analysis.RegularizedProjectionParameter.hasDerivAt_energy
#print axioms Mettapedia.Analysis.RegularizedProjectionParameter.hasDerivAt_weightedEnergy
#print axioms Mettapedia.Analysis.RegularizedProjectionParameter.normalizedDensity
#print axioms Mettapedia.Analysis.RegularizedProjectionParameter.scaleRate
#print axioms Mettapedia.Analysis.RegularizedProjectionParameter.hasDerivAt_normalizedDensity
#print axioms Mettapedia.Analysis.RegularizedProjectionParameter.abs_scaleRate_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionScaleMotion.scaleDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionScaleMotion.scaleWork
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionScaleMotion.continuous_scaleDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionScaleMotion.abs_scaleDensity_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionScaleMotion.abs_scaleWork_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionScaleMotion.abs_scaleWork_le_logarithmic_rate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionScaleMotion.abs_scaleWork_le_fixed_band
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionScaleMotion.normalizationRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionScaleMotion.hasDerivAt_normalization
