import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeAlignmentDynamics
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeStrainSpectralFrame
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakePeriodicOperatorKernel
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeCoherentStretchFactorization
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeSmoothCoherentStretchSymbol
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeUniformKernelFamily
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeBilinearPeriodization
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeFiniteFourierBilinearTransfer
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeDyadicKernelScaling
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeSquareDyadicFiniteTransfer
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeFrozenFrameKernelTransfer
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakePhysicalFrameKernelTransfer
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeAnnularChartCutoff
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeAnnularUniformKernel
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeAnnularMultiplierAssembly
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeAnnularFrozenFrameTransfer
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeAnnularPhysicalFrameTransfer
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeAnnularSectorProjector
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeSquareDyadicSectorProjector
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeAxialFrameConstruction
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeStrainAxialFrame
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeComplexMisalignmentExpansion
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeComplexCoherentPDEIdentification
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakePhysicalMisalignmentSplit
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeFullStrainFrame
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeMisalignmentEnergyBridge
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeTransverseEnergyFreezing
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeTransverseEnergyCoercivity
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeCellAggregation
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeFiniteFourierLocalization
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeBufferedAnnularMultiplier
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeBufferedAnnularFrozenFrameTransfer
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeBufferedAnnularPhysicalFrameTransfer
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeLocalizedBufferedTransfer
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeBilinearActionStability
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeBufferedLocalizationStability
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeSmoothCutoffFourierTail
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeConcreteSmoothCellCutoff
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeConcreteSpatialCoverTransfer
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeArbitraryDataBlocks
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeArbitraryDataMisalignment
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeConcreteCoverEnergy
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeConcreteWeightedFreezing
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeSpectralProjectorRegularity
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeSpectralClusterDichotomy
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeExpandingPlaneResidence
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeDyadicDirectionEvolution
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeFourierStretchingEvolution

/-!
# Seal audit for the coherent-field and alignment-dynamics tranche

This file keeps the axiom boundary of the new load-bearing results visible to
the Lean compiler.  It adds no assumptions and proves no mathematical step.
-/

#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakePeriodicOperatorKernel.not_realization_mass_le_aperture_of_symbol_fixes_unit
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeCoherentStretchFactorization.stretchAmp_coherentProject_scaled_eq_delta_smul
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSmoothCoherentStretchSymbol.fourier_normalizedStretchTensorKernel
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeAlignmentDynamics.gapWeightedAlignmentResidence_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeStrainSpectralFrame.constructedFrame_smallGap_or_alignmentEnergy_coercive
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeUniformKernelFamily.exists_uniform_normalizedStretchTensorKernel_mass
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeBilinearPeriodization.frequencyPairUnitTorusFourierCoeff_periodizedNormalizedStretchTensorKernel
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeBilinearPeriodization.unitTorusPeriodizedStretch_action_monomials
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeBilinearPeriodization.exists_uniform_unitTorusStretch_bilinear_aperture_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFiniteFourierBilinearTransfer.unitTorusPeriodizedStretch_action_finiteFourierReconstruction_eq_coherent
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFiniteFourierBilinearTransfer.exists_uniform_finiteFourierStretch_bilinear_aperture_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeDyadicKernelScaling.fourier_isotropicFrequencyPairKernelRescaling
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeDyadicKernelScaling.setIntegral_character_periodizedIsotropicNormalizedStretchTensorKernel
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeDyadicKernelScaling.frequencyPairToBilinearKernelCoordinates_measurePreserving
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeDyadicKernelScaling.integral_norm_anisotropicNormalizedStretchTensorKernel
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeDyadicKernelScaling.fourier_anisotropicNormalizedStretchTensorKernel
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeDyadicKernelScaling.setIntegral_character_periodizedSquareDyadicNormalizedStretchTensorKernel
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeDyadicKernelScaling.exists_uniform_periodizedSquareDyadicNormalizedStretchTensorKernel_mass
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSquareDyadicFiniteTransfer.frequencyPairUnitTorusFourierCoeff_periodizedSquareDyadicNormalizedStretchTensorKernel
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSquareDyadicFiniteTransfer.unitTorusPeriodizedSquareDyadicNormalizedStretch_action_finiteFourierReconstruction_eq_coherent
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSquareDyadicFiniteTransfer.exists_uniform_finiteFourierSquareDyadicStretch_bilinear_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFrozenFrameKernelTransfer.fourier_rotatedSquareDyadicCoverKernel
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFrozenFrameKernelTransfer.setIntegral_character_periodizedRotatedSquareDyadicNormalizedStretchTensorKernel
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFrozenFrameKernelTransfer.exists_uniform_frozenFrameFiniteFourierSquareDyadicStretch_bilinear_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFrozenFrameKernelTransfer.orientedFrameEuclideanLinearIsometryEquiv
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFrozenFrameKernelTransfer.unitTorusPeriodizedOrientedFrameSquareDyadicNormalizedStretch_action_finiteFourierReconstruction_eq_coherent
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFrozenFrameKernelTransfer.exists_uniform_orientedFrameFiniteFourierSquareDyadicStretch_bilinear_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakePhysicalFrameKernelTransfer.complexifyRealLinearEquiv_symm_apply_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakePhysicalFrameKernelTransfer.physicalOrientedFrameSquareDyadicKernelAction_finiteFourierReconstruction_eq_coherent
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakePhysicalFrameKernelTransfer.exists_uniform_variablePhysicalFrameSquareDyadicStretch_bilinear_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeAnnularChartCutoff.annularFourChartInner_eq_one_of_mem_normalizedAnnulus
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeAnnularUniformKernel.exists_uniform_tensorKernel_mass_for_cutoff
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeAnnularUniformKernel.exists_uniform_annularTensorKernel_mass
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeAnnularMultiplierAssembly.apply_annularFourChartTensorSymbol_eq_coherent
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeAnnularMultiplierAssembly.exists_uniform_annularFourChartTensorKernel_mass
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeAnnularFrozenFrameTransfer.unitTorusRotatedAnnularSquareDyadic_action_eq_coherent
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeAnnularFrozenFrameTransfer.exists_uniform_frozenFrameAnnularSquareDyadic_bilinear_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeAnnularPhysicalFrameTransfer.exists_uniform_variablePhysicalFrameAnnularSquareDyadic_bilinear_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeAnnularSectorProjector.frozenFrameSquareDyadicFrequencyPairChart_orientedFrame
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeAnnularSectorProjector.physicalAnnularAction_on_sectorProjections_eq_coherent
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSquareDyadicSectorProjector.normalized_mem_of_mem_realSquarePancakeConeAnnulus
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSquareDyadicSectorProjector.physicalAnnularAction_on_squareDyadicPancakeSectorProjections_eq_coherent
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeAxialFrameConstruction.axialFrameOfUnit_toFun_self
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeStrainAxialFrame.compressiveAxialFrame_maps_direction_to_ez
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeStrainAxialFrame.exists_uniform_strainFrameAnnularSquareDyadic_bilinear_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeComplexMisalignmentExpansion.finiteComplexStretchingSum_eq_coherent_add_misalignment
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeComplexMisalignmentExpansion.norm_finiteComplexStretchingSum_le_coherent_add_misalignment
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeComplexCoherentPDEIdentification.aperture_smul_coherentProjectedNormalizedStretch_eq_complexStretch
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeComplexCoherentPDEIdentification.physicalAnnularAction_on_squareDyadicSector_eq_complexPDE
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakePhysicalMisalignmentSplit.realFrequencyComplexStretch_eq_coherent_add_misalignment
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakePhysicalMisalignmentSplit.physicalFiniteFramePancakeStretchingSum_eq_kernel_add_misalignment
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakePhysicalMisalignmentSplit.exists_uniform_strainFramePhysicalPancakeSplit_bilinear_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFullStrainFrame.fullStrainFrame_maps_expandingDirection_to_ex
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFullStrainFrame.fullStrainFrame_inverseComplex_ex_eq_expandingDirection
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFullStrainFrame.exists_uniform_fullStrainFramePhysicalPancakeSplit_bilinear_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeMisalignmentEnergyBridge.complexEuclideanNormSq_misalignment_le_transverseEnergyEx
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeMisalignmentEnergyBridge.integral_normSq_finiteScalarFourierReconstruction
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeMisalignmentEnergyBridge.fullStrainFrame_sectorModes_sum_complexMisalignment_le_integral
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeTransverseEnergyFreezing.abs_constructedTopEigenvalue_sub_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeTransverseEnergyFreezing.fullStrainFrame_integral_nearCollision_or_transverseEnergy_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeTransverseEnergyFreezing.sectorMisalignment_smallFrozenGap_or_le_frozenIntegral
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeTransverseEnergyCoercivity.gap_mul_complexTransverseLineEnergy_le_complexStrainDefect
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeTransverseEnergyCoercivity.complexStrainDefect_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeTransverseEnergyCoercivity.gap_mul_integral_fullStrainFrame_transverseEnergy_le_defect
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeTransverseEnergyCoercivity.smallFrozenGap_or_gap_mul_sectorMisalignment_le_defect
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeCellAggregation.sum_separated_cellRemainder_le_all_cellEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeCellAggregation.sum_setIntegral_le_overlap_mul_integral
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeCellAggregation.sum_integral_weight_mul_local_le_overlap_mul_integral
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFiniteFourierLocalization.finiteScalar_mul_finiteFourierReconstruction
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFiniteFourierLocalization.outputMode_eq_cutoff_add_field
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFiniteFourierLocalization.outputMode_mem_expandedNormalizedPancakeAnnulus
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFiniteFourierLocalization.integral_localizedEnergy_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeBufferedAnnularMultiplier.localizationFourChartInner_eq_one_of_mem_buffer
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeBufferedAnnularMultiplier.apply_localizationFourChartTensorSymbol_eq_coherent
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeBufferedAnnularMultiplier.exists_uniform_localizationFourChartTensorKernel_mass
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeBufferedAnnularFrozenFrameTransfer.unitTorusRotatedLocalizationSquareDyadic_action_eq_coherent
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeBufferedAnnularFrozenFrameTransfer.exists_uniform_frozenFrameLocalizationSquareDyadic_bilinear_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeBufferedAnnularPhysicalFrameTransfer.exists_uniform_variablePhysicalFrameLocalizationSquareDyadic_bilinear_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFiniteFourierLocalization.finiteFourierReconstruction_convolutionCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeLocalizedBufferedTransfer.physicalLocalizationAction_on_cutoffProducts_eq_coherent
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeLocalizedBufferedTransfer.exists_uniform_physicalLocalization_bilinear_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeBilinearActionStability.norm_torusBilinearKernelAction_sub_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeBufferedLocalizationStability.exists_uniform_physicalLocalization_stability
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeBufferedLocalizationStability.exists_uniform_cutoffApproximation_stability
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSmoothCutoffFourierTail.exists_finiteFourierApproximation_sup
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSmoothCutoffFourierTail.eventually_mode_mem_localizationShift_uniformFrame
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSmoothCutoffFourierTail.exists_eventually_margin_finiteFourierApproximation_uniformFrame
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeConcreteSmoothCellCutoff.summable_mFourierCoeff_torusCellCutoff
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeConcreteSmoothCellCutoff.exists_uniform_spatialCoverFourierApproximation
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeConcreteSpatialCoverTransfer.exists_spatialCoverFourierPackage
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeConcreteSpatialCoverTransfer.exists_uniform_actualSpatialCells_to_coherent
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeArbitraryDataBlocks.dyadicShellModes_subset_canonical_squareDyadicShells
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeArbitraryDataBlocks.dyadicShellBlock_eq_four_pancake_shares
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeArbitraryDataBlocks.zeroModeEnergy_add_tsum_dyadicShellEnergy_l2FourierVelocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeArbitraryDataBlocks.intervalIntegrable_dyadicShellEnergyTimeProfile_of_continuous_uncurry
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeArbitraryDataBlocks.exists_uniform_actualSpatialCells_to_coherent_on_periodicFieldBlocks
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeArbitraryDataMisalignment.arbitraryDataSquareDyadicPancakeStretchingSum_eq_kernel_add_misalignment
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeArbitraryDataMisalignment.exists_uniform_arbitraryDataSquareDyadicPancakeSplit_bilinear_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeArbitraryDataMisalignment.intervalIntegrable_arbitraryDataSquareDyadicPancakeMisalignmentEnergyTimeProfile
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeArbitraryDataMisalignment.arbitraryDataSquareDyadicPancake_smallFrozenGap_or_misalignment_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeConcreteCoverEnergy.concreteSpatialCover_integral_sandwich
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeConcreteCoverEnergy.arbitraryDataMisalignmentEnergy_le_smoothCoverTransverse_and_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeConcreteCoverEnergy.spatialCell_gap_mul_transverseEnergy_le_defect
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeConcreteCoverEnergy.gap_mul_sum_spatialCoverTransverseEnergy_le_globalDefect
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeConcreteWeightedFreezing.fullStrainFrame_weightedIntegral_smallFrozenGap_or_transverseEnergy_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeConcreteWeightedFreezing.spatialCell_gap_mul_observationTransverse_le_frozenDefect
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeConcreteWeightedFreezing.arbitraryDataMisalignmentEnergy_le_cellwiseFrozenDefect
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSpectralProjectorRegularity.SymmetricStrain.norm_topEigenlineProjector_sub_le_of_norm_sub_lt_half_topGap
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSpectralProjectorRegularity.SymmetricStrain.measurable_topEigenlineProjector_restrict_of_topGap_pos
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSpectralProjectorRegularity.SymmetricStrain.intervalIntegrable_complexTopTransverseEnergy_of_topGap_pos
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSpectralClusterDichotomy.abs_constructedBottomEigenvalue_sub_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSpectralClusterDichotomy.SymmetricStrain.measurable_expandingPlaneProjector_restrict_of_bottomGap_pos
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSpectralClusterDichotomy.complexStrainDefect_eq_topGap_mul_middle_add_width_mul_bottom
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeSpectralClusterDichotomy.traceFree_smallTopGap_bottomSeparated_or_complexRayleigh_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeExpandingPlaneResidence.bottomGap_mul_expandingPlaneEnergy_le_rayleighExcess
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeExpandingPlaneResidence.bottomGapWeightedContractingResidence_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeDyadicDirectionEvolution.hasDerivAt_squareDyadicPancakeRealBlock_of_components
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeDyadicDirectionEvolution.dyadicPancakeDirectionDerivative_eq_strain_add_residual
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeDyadicDirectionEvolution.dyadicPancakeDirectionDerivative_eq_strain_add_evolutionRemainder_add_projectionDefect
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFourierStretchingEvolution.finiteFourierReconstruction_stretchingConvolutionCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeFourierStretchingEvolution.dyadicPancakeDirectionDerivative_eq_finiteStretchingChannels
