import Mettapedia.Analysis.ProjectionCurvatureBoundTests
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.FilteredProjectionViscousBalance
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.FiniteVorticityProjectedBernstein

/-! # Axiom audit for the upper curvature and projected weighted Bernstein bounds -/

#print axioms Mettapedia.Analysis.WeightedProjectionCurvatureBound.norm_residual_sq_le
#print axioms Mettapedia.Analysis.WeightedProjectionCurvatureBound.coefficient_sq_mul_norm_sq_le
#print axioms Mettapedia.Analysis.WeightedProjectionCurvatureBound.norm_sub_sq_le_twice
#print axioms Mettapedia.Analysis.WeightedProjectionCurvatureBound.weighted_relativeRate_sq_le
#print axioms Mettapedia.Analysis.WeightedProjectionCurvatureBound.weightedCurvature_le
#print axioms Mettapedia.Analysis.UnitTorusQuarticSecondEnergy.quarticSecond
#print axioms Mettapedia.Analysis.UnitTorusQuarticSecondEnergy.hasDerivAt_quarticFirst
#print axioms Mettapedia.Analysis.UnitTorusQuarticSecondEnergy.integral_mixed_identity
#print axioms Mettapedia.Analysis.UnitTorusQuarticSecondEnergy.integral_quarticSecond_sq
#print axioms Mettapedia.Analysis.UnitTorusQuarticSecondEnergy.integral_weightedFirst_fourth_le
#print axioms Mettapedia.Analysis.UnitTorusQuarticSecondEnergy.integral_weightedSecond_sq_le
#print axioms Mettapedia.Analysis.ProjectionCurvatureBoundTests.positive_weightedCurvature
#print axioms Mettapedia.Analysis.ProjectionCurvatureBoundTests.quarticSecond_cancellation
#print axioms Mettapedia.Analysis.ProjectionCurvatureBoundTests.no_pointwise_weightedSecond_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.curvatureCostDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.curvatureCost
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.curvatureCostDensity_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.curvatureCost_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.weightedCurvatureDensity_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.continuous_curvatureCostDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.integral_weightedCurvatureDensity_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.octicViscousDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.octicViscousDensity_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.integrable_octicViscousDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.integral_octicViscousDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.correctedViscousDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.integrable_weightedViscousRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.integral_correctedViscousDensity_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalProjectionCurvatureBudget.integral_correctedViscousDensity_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredProjectionViscousBalance.viscous_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredProjectionViscousBalance.fullVorticity_viscous
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredProjectionViscousBalance.correctedDensityRate_viscous
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredProjectionViscousBalance.work
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredProjectionViscousBalance.integrable_workDensity
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredProjectionViscousBalance.work_add
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredProjectionViscousBalance.work_viscous
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredProjectionViscousBalance.hasDerivAt_meanCorrectedEnergy_viscous
#print axioms Mettapedia.FluidDynamics.NavierStokes.FilteredProjectionViscousBalance.deriv_meanCorrectedEnergy_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ScalarQuarticBernstein.hasRadius_derivative
#print axioms Mettapedia.FluidDynamics.NavierStokes.ScalarQuarticBernstein.integral_coordinateDerivative_sq_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.ScalarQuarticBernstein.fourthPowerCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.ScalarQuarticBernstein.fourierPolynomial_fourthPowerCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.ScalarQuarticBernstein.hasRadius_fourthPower
#print axioms Mettapedia.FluidDynamics.NavierStokes.ScalarQuarticBernstein.integral_weightedSecond_sq_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteVorticityProjectedBernstein.projectedCurlCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteVorticityProjectedBernstein.fourierPolynomial_projectedCurlCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteVorticityProjectedBernstein.hasRadius_projectedCurlCoeff
#print axioms Mettapedia.FluidDynamics.NavierStokes.FiniteVorticityProjectedBernstein.integral_projected_second_sq_le
