import Mettapedia.Analysis.RadialPancakeCoherenceTests
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalRadialNormalEvolution

/-! # Foundational checks for coherent radial bounds and normal-component dynamics -/

#print axioms Mettapedia.Analysis.RadialPancakeCoherence.abs_amplitudePair_le
#print axioms Mettapedia.Analysis.RadialPancakeCoherence.normalMoment_le_of_tilt
#print axioms Mettapedia.Analysis.RadialPancakeCoherence.normalPairRate_eq
#print axioms Mettapedia.Analysis.RadialPancakeCoherence.squareRate_le_of_compressive
#print axioms Mettapedia.Analysis.RadialPancakeCoherence.hasDerivAt_weightedHeight
#print axioms Mettapedia.Analysis.RadialPancakeCoherence.weightedHeightRate_eq
#print axioms Mettapedia.Analysis.RadialPancakeCoherence.weightedHeightRate_common
#print axioms Mettapedia.Analysis.RadialPancakeCoherence.commonAmplitudeRate_eq_normal_defects
#print axioms Mettapedia.Analysis.RadialPancakeCoherence.abs_commonAmplitudeRate_le
#print axioms Mettapedia.Analysis.RadialPancakeCoherence.abs_coherentRate_le
#print axioms Mettapedia.Analysis.RadialPancakeCoherence.coherentRate_eq_zero_of_plane
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRadialCoherentBound.inner_gradient_add_inner_gradient
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRadialCoherentBound.abs_inner_gradient_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRadialCoherentBound.symmetric_normal_action
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRadialCoherentBound.abs_coherent_rate_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRadialCoherentBound.materialRate_le_coherentCost_add_signed_remainder
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRadialCoherentBound.coherent_rate_eq_zero_of_plane
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRadialNormalEvolution.normalForcing_at_left
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRadialNormalEvolution.normalRate_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRadialNormalEvolution.hasDerivAt_normalHeight_path
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRadialNormalEvolution.hasDerivAt_sq_normalHeight_path
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRadialNormalEvolution.normalSquareRate_le_of_compressive
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRadialNormalEvolution.normalMoment_eq_weightedNormalHeight
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRadialNormalEvolution.hasDerivAt_weightedNormalHeight_path
#print axioms Mettapedia.Analysis.RadialPancakeCoherenceTests.zero_normalMoment
#print axioms Mettapedia.Analysis.RadialPancakeCoherenceTests.tilted_normal_produces_coherent_growth
#print axioms Mettapedia.Analysis.RadialPancakeCoherenceTests.zero_normal
#print axioms Mettapedia.Analysis.RadialPancakeCoherenceTests.pancake_symmetric
#print axioms Mettapedia.Analysis.RadialPancakeCoherenceTests.pancake_trace
#print axioms Mettapedia.Analysis.RadialPancakeCoherenceTests.pancake_normal
#print axioms Mettapedia.Analysis.RadialPancakeCoherenceTests.initial_heights
#print axioms Mettapedia.Analysis.RadialPancakeCoherenceTests.not_weighted_damping_of_normal_damping
#print axioms Mettapedia.Analysis.RadialPancakeCoherenceTests.weighted_growth_firstVariation
#print axioms Mettapedia.Analysis.RadialPancakeCoherenceTests.unweighted_decay_firstVariation
