import Mettapedia.Analysis.RegularizedProjection
import Mettapedia.Analysis.RegularizedProjectionTests
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.VelocityRHSMoments
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalHelicityCenterEvolution
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalRegularizedHelicityBudget

/-! # Dependency audit of regularized helicity payment and material evolution -/

#print axioms Mettapedia.Analysis.WeightedCurlCancellation.norm_curlJet_sq_le
#print axioms Mettapedia.Analysis.RegularizedProjection.coefficient
#print axioms Mettapedia.Analysis.RegularizedProjection.residual
#print axioms Mettapedia.Analysis.RegularizedProjection.energy
#print axioms Mettapedia.Analysis.RegularizedProjection.inner_residual
#print axioms Mettapedia.Analysis.RegularizedProjection.energy_nonneg
#print axioms Mettapedia.Analysis.RegularizedProjection.objective_eq_energy_add_sq
#print axioms Mettapedia.Analysis.RegularizedProjection.energy_le_objective
#print axioms Mettapedia.Analysis.RegularizedProjection.energy_le_norm_sq
#print axioms Mettapedia.Analysis.RegularizedProjection.energy_eq
#print axioms Mettapedia.Analysis.RegularizedProjection.inner_residual_sq_le
#print axioms Mettapedia.Analysis.RegularizedProjection.hasDerivAt_coefficient
#print axioms Mettapedia.Analysis.RegularizedProjection.hasDerivAt_energy
#print axioms Mettapedia.Analysis.RegularizedProjectionTests.coefficient_at_zero
#print axioms Mettapedia.Analysis.RegularizedProjectionTests.energy_at_zero
#print axioms Mettapedia.Analysis.RegularizedProjectionTests.sharp_inner_residual
#print axioms Mettapedia.Analysis.RegularizedProjectionTests.midpoint_convexity_fails
#print axioms Mettapedia.Analysis.RegularizedProjectionTests.moving_minimum_derivative
#print axioms Mettapedia.FluidDynamics.NavierStokes.VelocityRHSMoments.one_add_norm_output_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.VelocityRHSMoments.weighted_outputFiber_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.VelocityRHSMoments.weighted_infiniteConvection_component_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.VelocityRHSMoments.fourierMoment_infiniteConvection_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.VelocityRHSMoments.fourierMoment_infiniteVelocityRHS_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.VelocityRHSMoments.summable_fourierMoment_infiniteVelocityRHS
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.fourierMoment_doubleCurl_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.norm_doubleCurl_velocityRHS_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.doubleCurlSeries_material
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.curlVorticityMaterialRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.infiniteVelocityRHS_eq_zero_add_viscous
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.doubleCurl_velocityRHS_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.curlVorticityMaterialRate_eq_inviscid_add_diffusion
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.hasDerivAt_curlVorticityAlong
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.regularizedCenterMaterialRate
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.regularizedCenterMaterialRate_add
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.regularizedCenterMaterialRate_smul
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.regularizedCenterMaterialRate_eq_defect
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.regularizedCenterMaterialRate_proportional
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.hasDerivAt_regularizedCenter_material
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.regularizedResidualEnergy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalHelicityCenterEvolution.hasDerivAt_regularizedResidualEnergy_material
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRegularizedHelicityBudget.centeredHelicityDensity_le_palinstrophy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRegularizedHelicityBudget.centeredDirectionalDensity_le_palinstrophy
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRegularizedHelicityBudget.abs_centeredDefect_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRegularizedHelicityBudget.abs_centeredIntegral_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRegularizedHelicityBudget.stretching_add_sources_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRegularizedHelicityBudget.signedRemainder
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRegularizedHelicityBudget.signedRemainder_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRegularizedHelicityBudget.stretching_add_remainder_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRegularizedHelicityBudget.continuousOn_centeredIntegral
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRegularizedHelicityBudget.continuousOn_signedRemainder
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalRegularizedHelicityBudget.energy_add_remainder_integral_le
