import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.StretchingFluxHeatWork

/-! Axiom audit for the physical variation and material-resolved heat work. -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPolarization.mixedMode_add_first
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPolarization.mixedMode_add_second
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPolarization.mixedMode_add_third
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPolarization.mixedMode_neg_first
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPolarization.mixedMode_neg_second
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPolarization.mixedMode_neg_third
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPolarization.variationMode_eq_polarization
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPolarization.summable_fourierMoment_neg
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPolarization.summable_fourierMoment_add
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPolarization.fluxVariation_eq_polarized_series
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPolarization.neg_tsum_mode_eq_projectedFlux
#print axioms Mettapedia.FluidDynamics.NavierStokes.ExchangedFluxPolarization.fluxVariation_eq_polarization
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxVariation.realField_add
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxVariation.realField_sub
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxVariation.vorticityField_add
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxVariation.vorticityField_sub
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxVariation.velocityDerivativeField_add
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxVariation.velocityDerivativeField_sub
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxVariation.stretchingVariationField
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxVariation.variationField
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxVariation.variationField_eq_polarization
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxVariation.projected_variationField_eq_polarization
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxVariation.fluxVariation_eq_projected_variationField
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxVariation.variationField_velocityRHS
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHeatWork.infiniteVelocityRHS_transverse
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHeatWork.fluxVariation_velocityRHS
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHeatWork.inner_fluxVariation_velocityRHS
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHeatWork.inner_fluxVariation_velocityRHS_add_dissipation
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHeatWork.inner_inviscidVariation_eq_spatial_work
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHeatWork.materialHeatWork
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHeatWork.coefficientWorkDensity_eq_materialHeatWork
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHeatWork.fullGramWork_eq_integral_materialHeatWork
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHeatWork.integrableOn_materialHeatWork
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHeatWork.intervalIntegrable_integral_materialHeatWork
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHeatWork.full_material_heat_gram_energy_identity
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHeatWork.exists_physical_local_material_heat_balance
