import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.StretchingFluxHorizontalParity
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.TwoShearViscousCoefficientEvaluation

/-! Axiom audit for mixed flux coefficients, full-convolution parity, and rational normalization. -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxMixedCoefficients.mixedTerm
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxMixedCoefficients.mixedInteraction
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxMixedCoefficients.mixedCoefficients
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxMixedCoefficients.variationCoefficients
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxMixedCoefficients.mixedCoefficients_self
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxMixedCoefficients.summable_norm_mixedTerm
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxMixedCoefficients.summable_norm_mixedInteraction
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxMixedCoefficients.summable_norm_mixedCoefficients
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxMixedCoefficients.summable_norm_variationCoefficients
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxMixedCoefficients.fullFourierField_mixedInteraction
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxMixedCoefficients.realField_mixedCoefficients
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxMixedCoefficients.realField_variationCoefficients
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxMixedCoefficients.projected_variation_work_eq_tsum
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.horizontalClass
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.HasHorizontalParity
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.horizontalClass_triple
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.curl_eq_zero_of_coefficient_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.mixedTerm_eq_zero_of_parity
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.mixedCoefficients_parity
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.flux_parity
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.variation_parity
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.inviscidRHS_parity
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.projected_variation_work_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.spectralRHSWork_inviscid_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.twoShear_parity
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.twoShear_inviscid_work_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.StretchingFluxHorizontalParity.twoShear_full_work_eq_heat
#print axioms Mettapedia.FluidDynamics.NavierStokes.RationalStretchingFlux.RationalCoefficient
#print axioms Mettapedia.FluidDynamics.NavierStokes.RationalStretchingFlux.RationalVelocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.RationalStretchingFlux.imaginaryLift
#print axioms Mettapedia.FluidDynamics.NavierStokes.RationalStretchingFlux.rationalCurl
#print axioms Mettapedia.FluidDynamics.NavierStokes.RationalStretchingFlux.curl_imaginaryLift
#print axioms Mettapedia.FluidDynamics.NavierStokes.RationalStretchingFlux.derivative_imaginaryLift
#print axioms Mettapedia.FluidDynamics.NavierStokes.RationalStretchingFlux.rationalInteraction
#print axioms Mettapedia.FluidDynamics.NavierStokes.RationalStretchingFlux.interaction_imaginaryLift
#print axioms Mettapedia.FluidDynamics.NavierStokes.RationalStretchingFlux.rationalFluxCoefficient
#print axioms Mettapedia.FluidDynamics.NavierStokes.RationalStretchingFlux.coefficients_imaginaryLift
#print axioms Mettapedia.FluidDynamics.NavierStokes.RationalStretchingFlux.rationalDivergenceCoefficient
#print axioms Mettapedia.FluidDynamics.NavierStokes.RationalStretchingFlux.divergence_imaginaryLift
#print axioms Mettapedia.FluidDynamics.NavierStokes.TwoShearViscousCoefficientEvaluation.rationalData
#print axioms Mettapedia.FluidDynamics.NavierStokes.TwoShearViscousCoefficientEvaluation.imaginaryLift_rationalData
#print axioms Mettapedia.FluidDynamics.NavierStokes.TwoShearViscousCoefficientEvaluation.rationalData_supported
#print axioms Mettapedia.FluidDynamics.NavierStokes.TwoShearViscousCoefficientEvaluation.longitudinal_modes_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.TwoShearViscousCoefficientEvaluation.sum_modes
#print axioms Mettapedia.FluidDynamics.NavierStokes.TwoShearViscousCoefficientEvaluation.rational_divergence_mode_zero_one_one
#print axioms Mettapedia.FluidDynamics.NavierStokes.TwoShearViscousCoefficientEvaluation.divergence_mode_zero_one_one
