import Mettapedia.Analysis.WeightedCurlCancellationTests
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.LocalWeightedCurlCancellation

/-! # Dependency audit of full-field weighted curl/strain cancellation -/

#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.summable_fourierMoment_curl
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.fullVorticity_curl_eq_curlJet
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.sum_fullCurlGradient_diagonal_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.inner_fullStrain_curl_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.integral_weighted_strain_doubleCurl_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.integral_strain_doubleCurl_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.fourierCurl_fourierCurl_eq_neg_laplacian
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.fullFourierField_negativeLaplacian_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.integral_strain_negativeLaplacian_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.integral_sixth_weighted_strain_negativeLaplacian_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.longitudinalHelicityIntegral
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.weightedStrainSpectralDefect
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.stretching_spectral_identity
#print axioms Mettapedia.FluidDynamics.NavierStokes.LocalWeightedCurlCancellation.longitudinalHelicityIntegral_eq_zero_of_no_longitudinal_variation
#print axioms Mettapedia.Analysis.WeightedCurlCancellationTests.a
#print axioms Mettapedia.Analysis.WeightedCurlCancellationTests.D
#print axioms Mettapedia.Analysis.WeightedCurlCancellationTests.curlJet_D
#print axioms Mettapedia.Analysis.WeightedCurlCancellationTests.divergence_D
#print axioms Mettapedia.Analysis.WeightedCurlCancellationTests.norm_a_sq
#print axioms Mettapedia.Analysis.WeightedCurlCancellationTests.unweighted_fluxRate_zero
#print axioms Mettapedia.Analysis.WeightedCurlCancellationTests.sixth_weight_fluxRate_six
#print axioms Mettapedia.Analysis.WeightedCurlCancellationTests.fluxRate_zero_vorticity
#print axioms Mettapedia.Analysis.WeightedCurlCancellation.curlJet
#print axioms Mettapedia.Analysis.WeightedCurlCancellation.curl_inner_transport
#print axioms Mettapedia.Analysis.WeightedCurlCancellation.weightRate
#print axioms Mettapedia.Analysis.WeightedCurlCancellation.flux
#print axioms Mettapedia.Analysis.WeightedCurlCancellation.fluxRate
#print axioms Mettapedia.Analysis.WeightedCurlCancellation.hasDerivAt_flux
#print axioms Mettapedia.Analysis.WeightedCurlCancellation.sum_fluxRate
#print axioms Mettapedia.Analysis.WeightedCurlCancellation.contDiff_flux
#print axioms Mettapedia.Analysis.WeightedCurlCancellation.integral_weighted_curl_gradient_eq
#print axioms Mettapedia.Analysis.WeightedCurlCancellation.integral_curl_gradient_eq_zero
#print axioms Mettapedia.Analysis.WeightedCurlCancellation.integral_sixth_weighted_curl_gradient_eq
