import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionWindowedSeeded
import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionWindowedSampleKernels
import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionWindowedShiftKernels
import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionWindowedSaturatedConstantMagnitude
import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionWindowedSaturatedInvariantCandidate
import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionWindowedSaturatedInvariantBridge
import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionWindowedSaturatedVariants
import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionZeroData
import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionTargetTransfers
import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionCounterexamplesBasic
import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionCounterexamplesAffineShear
import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionCounterexamplesHeatShearCore
import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionCounterexamplesHeatShearDrifts
import Mettapedia.FluidDynamics.NavierStokes.ContinuationRegressionCounterexamplesHeatShearTransport

/-!
# Navier-Stokes continuation regression umbrella

The continuation regression harness is split by semantic layer: windowed seeded
frontiers, kernel frontiers, saturated invariant fronts, saturated variants,
zero-data and finite-energy repair checks, target transfers, and counterexample
families. This file preserves the historical import path.
-/
