import Mettapedia.Combinatorics.Matching.Labeled

/-!
# Circuit partitions generated by two perfect matchings

Two perfect matchings on the same finite carrier form a two-regular incidence
system when their roles are retained.  Alternating once through the second
matching and once through the first gives a permutation.  Its orbits are the
two orientations of the alternating circuits (including the degenerate case
where the matchings share an edge).

This representation deliberately does not take the union of the matching
graphs: a simple-graph union would collapse a shared pair of role-distinct
edges.  Labels on the two matchings can instead be summed around an oriented
orbit, giving the weight of the corresponding alternating circuit.
-/

namespace MatchingParity

namespace CircuitPartition

universe u v

variable {V : Type u} [Fintype V] [DecidableEq V]

/-- One alternating step: first follow `second`, then follow `first`. -/
def step (first second : Pairing V) : Equiv.Perm V :=
  first.toPerm * second.toPerm

omit [Fintype V] [DecidableEq V] in
@[simp]
theorem step_apply (first second : Pairing V) (vertex : V) :
    step first second vertex = first.partner (second.partner vertex) :=
  rfl

/-- The oriented half of the alternating circuit containing `root`.  The full
undirected circuit has a second, oppositely oriented orbit obtained by applying
either pairing. -/
def orientedOrbit (first second : Pairing V) (root : V) : Finset V :=
  Finset.univ.filter fun vertex => (step first second).SameCycle root vertex

@[simp]
theorem mem_orientedOrbit (first second : Pairing V) (root vertex : V) :
    vertex ∈ orientedOrbit first second root ↔
      (step first second).SameCycle root vertex := by
  simp [orientedOrbit]

/-- Choosing another root in the same oriented orbit does not change the
orbit. -/
theorem orientedOrbit_eq_of_sameCycle (first second : Pairing V) {root other : V}
    (h : (step first second).SameCycle root other) :
    orientedOrbit first second root = orientedOrbit first second other := by
  ext vertex
  simp only [mem_orientedOrbit]
  constructor
  · exact fun hv => h.symm.trans hv
  · exact fun hv => h.trans hv

omit [Fintype V] [DecidableEq V] in
/-- Conjugating the alternating step by the second pairing reverses it. -/
theorem second_conj_step_eq_inv (first second : Pairing V) :
    second.toPerm * step first second * second.toPerm =
      (step first second)⁻¹ := by
  calc
    second.toPerm * step first second * second.toPerm
        = second.toPerm * first.toPerm *
            (second.toPerm * second.toPerm) := by
              simp only [step]
              group
    _ = second.toPerm * first.toPerm := by
      rw [second.toPerm_mul_self, mul_one]
    _ = second.toPerm⁻¹ * first.toPerm⁻¹ := by
      rw [first.toPerm_inv, second.toPerm_inv]
    _ = (step first second)⁻¹ := by
      rw [step, mul_inv_rev]

omit [Fintype V] [DecidableEq V] in
/-- Applying the first pairing takes an oriented orbit to the opposite
orientation of the same alternating circuit. -/
theorem sameCycle_first_partner_iff (first second : Pairing V) (x y : V) :
    (step first second).SameCycle (first.partner x) (first.partner y) ↔
      (step first second).SameCycle x y := by
  change (step first second).SameCycle (first.toPerm x) (first.toPerm y) ↔ _
  have h := Equiv.Perm.sameCycle_conj
    (f := step first second) (g := first.toPerm)
    (x := first.toPerm x) (y := first.toPerm y)
  rw [first.toPerm_inv] at h
  have hconj : first.toPerm * step first second * first.toPerm =
      (step first second)⁻¹ := by
    simpa only [step] using first.conj_comp_eq_inv second
  rw [hconj] at h
  simpa only [Equiv.Perm.sameCycle_inv, Pairing.toPerm_apply,
    first.partner_partner] using h

omit [Fintype V] [DecidableEq V] in
/-- The analogous orientation-reversal law for the second pairing. -/
theorem sameCycle_second_partner_iff (first second : Pairing V) (x y : V) :
    (step first second).SameCycle (second.partner x) (second.partner y) ↔
      (step first second).SameCycle x y := by
  change (step first second).SameCycle (second.toPerm x) (second.toPerm y) ↔ _
  have h := Equiv.Perm.sameCycle_conj
    (f := step first second) (g := second.toPerm)
    (x := second.toPerm x) (y := second.toPerm y)
  rw [second.toPerm_inv, second_conj_step_eq_inv] at h
  simpa only [Equiv.Perm.sameCycle_inv, Pairing.toPerm_apply,
    second.partner_partner] using h

/-- The first pairing gives an equivalence between the two oriented halves of
one alternating circuit. -/
def firstPartnerEquiv (first second : Pairing V) (root : V) :
    {vertex // vertex ∈ orientedOrbit first second root} ≃
      {vertex // vertex ∈ orientedOrbit first second (first.partner root)} where
  toFun vertex := ⟨first.partner vertex, by
    apply (mem_orientedOrbit _ _ _ _).2
    rw [sameCycle_first_partner_iff]
    exact (mem_orientedOrbit _ _ _ _).1 vertex.property⟩
  invFun vertex := ⟨first.partner vertex, by
    apply (mem_orientedOrbit _ _ _ _).2
    rw [← sameCycle_first_partner_iff]
    simpa only [first.partner_partner] using
      (mem_orientedOrbit _ _ _ _).1 vertex.property⟩
  left_inv vertex := Subtype.ext (first.partner_partner vertex)
  right_inv vertex := Subtype.ext (first.partner_partner vertex)

/-- The second pairing gives the same orientation-reversing equivalence. -/
def secondPartnerEquiv (first second : Pairing V) (root : V) :
    {vertex // vertex ∈ orientedOrbit first second root} ≃
      {vertex // vertex ∈ orientedOrbit first second (second.partner root)} where
  toFun vertex := ⟨second.partner vertex, by
    apply (mem_orientedOrbit _ _ _ _).2
    rw [sameCycle_second_partner_iff]
    exact (mem_orientedOrbit _ _ _ _).1 vertex.property⟩
  invFun vertex := ⟨second.partner vertex, by
    apply (mem_orientedOrbit _ _ _ _).2
    rw [← sameCycle_second_partner_iff]
    simpa only [second.partner_partner] using
      (mem_orientedOrbit _ _ _ _).1 vertex.property⟩
  left_inv vertex := Subtype.ext (second.partner_partner vertex)
  right_inv vertex := Subtype.ext (second.partner_partner vertex)

omit [Fintype V] [DecidableEq V] in
/-- The roots obtained by applying the two pairings lie in the same opposite
oriented orbit. -/
theorem sameCycle_first_partner_second_partner (first second : Pairing V)
    (root : V) :
    (step first second).SameCycle (first.partner root) (second.partner root) := by
  symm
  refine ⟨1, ?_⟩
  simp only [zpow_one, step_apply]
  rw [second.partner_partner]

/-- The two descriptions of the opposite orientation have the same carrier. -/
theorem orientedOrbit_first_partner_eq_second_partner
    (first second : Pairing V) (root : V) :
    orientedOrbit first second (first.partner root) =
      orientedOrbit first second (second.partner root) :=
  orientedOrbit_eq_of_sameCycle first second
    (sameCycle_first_partner_second_partner first second root)

omit [Fintype V] [DecidableEq V] in
/-- Moving the first pairing past an alternating-step power reverses the
direction of that power. -/
theorem first_mul_step_pow (first second : Pairing V) (exponent : Nat) :
    first.toPerm * ((step first second) ^ exponent) =
      ((step first second)⁻¹ ^ exponent) * first.toPerm := by
  have hconj : first.toPerm * step first second * first.toPerm =
      (step first second)⁻¹ := by
    simpa only [step] using first.conj_comp_eq_inv second
  have hfirstStep : first.toPerm * step first second =
      (step first second)⁻¹ * first.toPerm := by
    calc
      first.toPerm * step first second =
          (first.toPerm * step first second * first.toPerm) *
            first.toPerm := by
              rw [mul_assoc, first.toPerm_mul_self, mul_one]
      _ = (step first second)⁻¹ * first.toPerm := by rw [hconj]
  induction exponent with
  | zero => simp
  | succ exponent ih =>
      calc
        first.toPerm * (step first second) ^ (exponent + 1) =
            first.toPerm * ((step first second) ^ exponent *
              step first second) := by rw [pow_succ]
        _ = (first.toPerm * (step first second) ^ exponent) *
              step first second := by rw [mul_assoc]
        _ = (((step first second)⁻¹ ^ exponent) * first.toPerm) *
              step first second := by rw [ih]
        _ = ((step first second)⁻¹ ^ exponent) *
              (first.toPerm * step first second) := by rw [mul_assoc]
        _ = ((step first second)⁻¹ ^ exponent) *
              ((step first second)⁻¹ * first.toPerm) := by rw [hfirstStep]
        _ = (((step first second)⁻¹ ^ exponent) *
              (step first second)⁻¹) * first.toPerm := by rw [mul_assoc]
        _ = ((step first second)⁻¹ ^ (exponent + 1)) *
              first.toPerm := by rw [pow_succ]

omit [DecidableEq V] in
/-- The two oriented halves of an alternating circuit are distinct.  If an
alternating-step power carried `root` to its first partner, splitting the
power into even and odd cases would respectively give a fixed point of the
first or second pairing. -/
theorem not_sameCycle_first_partner
    (first second : Pairing V) (root : V) :
    ¬ (step first second).SameCycle root (first.partner root) := by
  intro hcycle
  obtain ⟨n, hn⟩ := hcycle.exists_nat_pow_eq
  rcases Nat.even_or_odd' n with ⟨k, rfl | rfl⟩
  · apply first.partner_ne (((step first second) ^ k) root)
    change first.toPerm (((step first second) ^ k) root) =
      ((step first second) ^ k) root
    rw [← Equiv.Perm.mul_apply, first_mul_step_pow,
      Equiv.Perm.mul_apply]
    change ((step first second)⁻¹ ^ k) (first.partner root) =
      ((step first second) ^ k) root
    rw [← hn, ← Equiv.Perm.mul_apply]
    simpa only [Equiv.Perm.mul_apply] using
      congrArg (fun p : Equiv.Perm V => p root)
        (show ((step first second)⁻¹ ^ k) *
            (step first second) ^ (2 * k) =
          (step first second) ^ k by group)
  · apply second.partner_ne (((step first second) ^ k) root)
    change second.toPerm (((step first second) ^ k) root) =
      ((step first second) ^ k) root
    have hfirstStep : first.toPerm * step first second = second.toPerm := by
      simp only [step]
      rw [← mul_assoc, first.toPerm_mul_self, one_mul]
    have hsecondMove : second.toPerm * ((step first second) ^ k) =
        ((step first second)⁻¹ ^ (k + 1)) * first.toPerm := by
      calc
        second.toPerm * (step first second) ^ k =
            (first.toPerm * step first second) *
              (step first second) ^ k := by rw [hfirstStep]
        _ = first.toPerm *
              (step first second * (step first second) ^ k) := by rw [mul_assoc]
        _ = first.toPerm * (step first second) ^ (k + 1) := by
          rw [pow_succ']
        _ = ((step first second)⁻¹ ^ (k + 1)) * first.toPerm :=
          first_mul_step_pow _ _ _
    rw [← Equiv.Perm.mul_apply, hsecondMove, Equiv.Perm.mul_apply]
    change ((step first second)⁻¹ ^ (k + 1)) (first.partner root) =
      ((step first second) ^ k) root
    rw [← hn, ← Equiv.Perm.mul_apply]
    simpa only [Equiv.Perm.mul_apply] using
      congrArg (fun p : Equiv.Perm V => p root)
        (show ((step first second)⁻¹ ^ (k + 1)) *
            (step first second) ^ (2 * k + 1) =
          (step first second) ^ k by group)

/-- The two oriented orbit carriers of one alternating circuit are disjoint. -/
theorem disjoint_orientedOrbit_first_partner
    (first second : Pairing V) (root : V) :
    Disjoint (orientedOrbit first second root)
      (orientedOrbit first second (first.partner root)) := by
  rw [Finset.disjoint_left]
  intro vertex hroot hopposite
  apply not_sameCycle_first_partner first second root
  exact ((mem_orientedOrbit first second root vertex).1 hroot).trans
    ((mem_orientedOrbit first second (first.partner root) vertex).1
      hopposite).symm

/-! ### Oriented halves and the undirected alternating component -/

omit [DecidableEq V] in
/-- The equivalence relation generated by the two matching edges is the union
of the two orientations of an alternating circuit.  The first disjunct keeps
the chosen orientation; the second reaches the opposite orientation through
one `first` edge.

This is the graph-free transversal statement needed when an alternating
circuit is assembled from physical paths: one oriented orbit chooses one end
of every path represented by the `first` matching. -/
theorem eqvGen_alternatingStep_iff_sameCycle_or_firstPartner
    (first second : Pairing V) (root vertex : V) :
    Relation.EqvGen
        (fun left right =>
          right = first.partner left ∨ right = second.partner left)
        root vertex ↔
      (step first second).SameCycle root vertex ∨
        (step first second).SameCycle root (first.partner vertex) := by
  let sameUndirected : V → V → Prop := fun left right =>
    (step first second).SameCycle left right ∨
      (step first second).SameCycle left (first.partner right)
  have hsymm : ∀ {left right}, sameUndirected left right →
      sameUndirected right left := by
    intro left right h
    rcases h with hsame | hopposite
    · exact Or.inl hsame.symm
    · right
      have hpartner : (step first second).SameCycle
          (first.partner left) right := by
        apply (sameCycle_first_partner_iff first second
          (first.partner left) right).1
        simpa only [first.partner_partner] using hopposite
      exact hpartner.symm
  have htrans : ∀ {left middle right},
      sameUndirected left middle → sameUndirected middle right →
        sameUndirected left right := by
    intro left middle right hleft hright
    rcases hleft with hleft | hleft <;>
      rcases hright with hright | hright
    · exact Or.inl (hleft.trans hright)
    · exact Or.inr (hleft.trans hright)
    · right
      have hpartner : (step first second).SameCycle
          (first.partner middle) (first.partner right) :=
        (sameCycle_first_partner_iff first second middle right).2 hright
      exact hleft.trans hpartner
    · left
      have hpartner : (step first second).SameCycle
          (first.partner middle) right := by
        apply (sameCycle_first_partner_iff first second
          (first.partner middle) right).1
        simpa only [first.partner_partner] using hright
      exact hleft.trans hpartner
  constructor
  · intro hreach
    change sameUndirected root vertex
    induction hreach with
    | rel left right hedge =>
        rcases hedge with rfl | rfl
        · right
          simpa only [first.partner_partner] using
            (Equiv.Perm.SameCycle.rfl (f := step first second) (x := left))
        · right
          exact ⟨1, by simp only [zpow_one, step_apply]⟩
    | refl =>
        exact Or.inl
          (Equiv.Perm.SameCycle.rfl (f := step first second) (x := _))
    | symm _ _ _ ih => exact hsymm ih
    | trans _ _ _ _ _ ihLeft ihRight => exact htrans ihLeft ihRight
  · intro h
    have hsameCycle : ∀ {left right},
        (step first second).SameCycle left right →
          Relation.EqvGen
            (fun x y =>
              y = first.partner x ∨ y = second.partner x)
            left right := by
      intro left right hcycle
      obtain ⟨power, hpower⟩ := hcycle.exists_nat_pow_eq
      have hpowers : ∀ exponent : Nat,
          Relation.EqvGen
            (fun x y =>
              y = first.partner x ∨ y = second.partner x)
            left (((step first second) ^ exponent) left) := by
        intro exponent
        induction exponent with
        | zero =>
            simpa using Relation.EqvGen.refl left
        | succ exponent ih =>
            let current := ((step first second) ^ exponent) left
            have hsecond : Relation.EqvGen
                (fun x y =>
                  y = first.partner x ∨ y = second.partner x)
                current (second.partner current) :=
              Relation.EqvGen.rel _ _ (Or.inr rfl)
            have hfirst : Relation.EqvGen
                (fun x y =>
                  y = first.partner x ∨ y = second.partner x)
                (second.partner current)
                (first.partner (second.partner current)) :=
              Relation.EqvGen.rel _ _ (Or.inl rfl)
            have hnext := Relation.EqvGen.trans _ _ _
              (Relation.EqvGen.trans _ _ _ ih hsecond) hfirst
            simpa only [current, step_apply, pow_succ', Equiv.Perm.mul_apply]
              using hnext
      simpa only [hpower] using hpowers power
    rcases h with hsame | hopposite
    · exact hsameCycle hsame
    · exact Relation.EqvGen.trans root (first.partner vertex) vertex
        (hsameCycle hopposite)
        (Relation.EqvGen.symm _ _
          (Relation.EqvGen.rel vertex (first.partner vertex) (Or.inl rfl)))

variable {A : Type v} [AddCommMonoid A]

/-- Sum one matching's edge labels over an oriented circuit.  Each edge of
that role occurs exactly once in the oriented orbit. -/
def orientedLabelSum (first second : Pairing V) (label : V → A) (root : V) : A :=
  ∑ vertex : {vertex // vertex ∈ orientedOrbit first second root}, label vertex

/-- The total labelled weight of an alternating circuit. -/
def orientedWeight (first second : LabeledPairing V A) (root : V) : A :=
  orientedLabelSum first.toPairing second.toPairing first.label root +
    orientedLabelSum first.toPairing second.toPairing second.label root

/-- Re-rooting within one orientation preserves every label sum. -/
theorem orientedLabelSum_eq_of_sameCycle (first second : Pairing V)
    (label : V → A) {root other : V}
    (h : (step first second).SameCycle root other) :
    orientedLabelSum first second label root =
      orientedLabelSum first second label other := by
  rw [orientedLabelSum, orientedLabelSum,
    orientedOrbit_eq_of_sameCycle first second h]

/-- Consequently the total circuit weight is independent of its root within
one orientation. -/
theorem orientedWeight_eq_of_sameCycle (first second : LabeledPairing V A)
    {root other : V}
    (h : (step first.toPairing second.toPairing).SameCycle root other) :
    orientedWeight first second root = orientedWeight first second other := by
  unfold orientedWeight
  rw [orientedLabelSum_eq_of_sameCycle _ _ _ h,
    orientedLabelSum_eq_of_sameCycle _ _ _ h]

/-- Reversing orientation through the first matching preserves the sum of the
first matching's labels. -/
theorem firstLabelSum_eq_first_partner
    (first second : LabeledPairing V A) (root : V) :
    orientedLabelSum first.toPairing second.toPairing first.label root =
      orientedLabelSum first.toPairing second.toPairing first.label
        (first.partner root) := by
  refine Fintype.sum_equiv
    (firstPartnerEquiv first.toPairing second.toPairing root)
    (fun vertex => first.label vertex)
    (fun vertex => first.label vertex) ?_
  intro vertex
  exact (first.label_partner vertex).symm

/-- Reversing orientation through the second matching preserves the sum of the
second matching's labels. -/
theorem secondLabelSum_eq_second_partner
    (first second : LabeledPairing V A) (root : V) :
    orientedLabelSum first.toPairing second.toPairing second.label root =
      orientedLabelSum first.toPairing second.toPairing second.label
        (second.partner root) := by
  refine Fintype.sum_equiv
    (secondPartnerEquiv first.toPairing second.toPairing root)
    (fun vertex => second.label vertex)
    (fun vertex => second.label vertex) ?_
  intro vertex
  exact (second.label_partner vertex).symm

/-- **Orientation independence of alternating-circuit weight.**  Applying
either matching moves the root to the opposite oriented orbit but leaves the
total weight unchanged. -/
theorem orientedWeight_first_partner
    (first second : LabeledPairing V A) (root : V) :
    orientedWeight first second (first.partner root) =
      orientedWeight first second root := by
  unfold orientedWeight
  have hfirst := firstLabelSum_eq_first_partner first second root
  have hsecond :
      orientedLabelSum first.toPairing second.toPairing second.label root =
        orientedLabelSum first.toPairing second.toPairing second.label
          (first.partner root) := by
    calc
      orientedLabelSum first.toPairing second.toPairing second.label root
          = orientedLabelSum first.toPairing second.toPairing second.label
              (second.partner root) :=
        secondLabelSum_eq_second_partner first second root
      _ = orientedLabelSum first.toPairing second.toPairing second.label
              (first.partner root) :=
        orientedLabelSum_eq_of_sameCycle _ _ _
          (sameCycle_first_partner_second_partner
            first.toPairing second.toPairing root).symm
  rw [hfirst, hsecond]

/-- The same orientation-independence law rooted through the second matching. -/
theorem orientedWeight_second_partner
    (first second : LabeledPairing V A) (root : V) :
    orientedWeight first second (second.partner root) =
      orientedWeight first second root := by
  calc
    orientedWeight first second (second.partner root)
        = orientedWeight first second (first.partner root) :=
      orientedWeight_eq_of_sameCycle first second
        (sameCycle_first_partner_second_partner
          first.toPairing second.toPairing root).symm
    _ = orientedWeight first second root :=
      orientedWeight_first_partner first second root

/-! ### Parity of a circuit assembled from return paths and local edges -/

/-- Circuit parity when the first matching records path-length parity and every
edge of the second, local matching has length one. -/
def circuitParity (returns : LabeledPairing.ParityPairing V)
    (localPairing : Pairing V) (root : V) : ZMod 2 :=
  orientedWeight returns (LabeledPairing.const localPairing 1) root

/-- The circuit-parity formula: add the parities of the external return paths
and one for every local matching edge in the oriented circuit. -/
theorem circuitParity_eq (returns : LabeledPairing.ParityPairing V)
    (localPairing : Pairing V) (root : V) :
    circuitParity returns localPairing root =
      orientedLabelSum returns.toPairing localPairing returns.label root +
        (orientedOrbit returns.toPairing localPairing root).card := by
  change
    orientedLabelSum returns.toPairing localPairing returns.label root +
        orientedLabelSum returns.toPairing localPairing (fun _ => 1) root =
      orientedLabelSum returns.toPairing localPairing returns.label root +
        (orientedOrbit returns.toPairing localPairing root).card
  congr 1
  simp [orientedLabelSum]

/-- If every return edge has odd label, its contribution cancels the unit
contribution of the corresponding local edge on every alternating circuit. -/
theorem circuitParity_eq_zero_of_label_eq_one
    (returns : LabeledPairing.ParityPairing V)
    (localPairing : Pairing V) (root : V)
    (hlabel : ∀ vertex : V, returns.label vertex = 1) :
    circuitParity returns localPairing root = 0 := by
  rw [circuitParity_eq]
  simp only [orientedLabelSum, hlabel, Finset.sum_const, nsmul_eq_mul]
  change
    ((Fintype.card
        {vertex // vertex ∈ orientedOrbit returns.toPairing localPairing root} :
      Nat) : ZMod 2) * 1 +
      ((orientedOrbit returns.toPairing localPairing root).card : ZMod 2) = 0
  rw [Fintype.card_coe]
  simp only [mul_one]
  exact ZModModule.add_self (G := ZMod 2) _

/-- In particular, assigning the constant odd label to an arbitrary return
matching makes every circuit even, independently of the local matching. -/
theorem circuitParity_const_one_eq_zero
    (returns localPairing : Pairing V) (root : V) :
    circuitParity (LabeledPairing.const returns (1 : ZMod 2))
        localPairing root = 0 :=
  circuitParity_eq_zero_of_label_eq_one
    (LabeledPairing.const returns (1 : ZMod 2)) localPairing root
    (fun _ => rfl)

/-- Circuit parity is independent of the root within one orientation. -/
theorem circuitParity_eq_of_sameCycle
    (returns : LabeledPairing.ParityPairing V) (localPairing : Pairing V)
    {root other : V}
    (h : (step returns.toPairing localPairing).SameCycle root other) :
    circuitParity returns localPairing root =
      circuitParity returns localPairing other :=
  orientedWeight_eq_of_sameCycle returns
    (LabeledPairing.const localPairing 1) h

/-- Circuit parity is independent of orientation. -/
theorem circuitParity_partner
    (returns : LabeledPairing.ParityPairing V) (localPairing : Pairing V)
    (root : V) :
    circuitParity returns localPairing (returns.partner root) =
      circuitParity returns localPairing root :=
  orientedWeight_first_partner returns
    (LabeledPairing.const localPairing 1) root

end CircuitPartition

end MatchingParity
