:- initialization(main, main).

choose(a) :- !.
choose(b).

p(a, b).

dcg_pair(X) --> [X, X].
dcg_guarded(X) --> { X = a }, [X].
dcg_choice --> [a] ; [b].
dcg_hello --> "ab".
dcg_emit(Cs) --> Cs.
dcg_one --> [a].
dcg_via(Input) :- phrase(dcg_one, Input).
dcg_via_rest(Input, Rest) :- phrase(dcg_one, Input, Rest).
dcg_delegate(Goal) --> Goal.
dcg_cut_outer(a) :- phrase(!, []), fail.
dcg_cut_outer(c).

emit(Label, Goal, Template) :-
    findall(Template, Goal, Answers),
    atomic_list_concat(Answers, ',', Joined),
    format('~w=~w~n', [Label, Joined]).

emit_raised(Label, Goal) :-
    catch((Goal, Result = completed), Error, Result = raised(Error)),
    format('~w=~w~n', [Label, Result]).

emit_count(Label, Goal) :-
    findall(1, Goal, Answers),
    length(Answers, Count),
    format('~w=~w~n', [Label, Count]).

emit_compare_error(Label, Goal) :-
    catch((Goal -> Outcome = success ; Outcome = failure),
          Error, Outcome = error(Error)),
    (   Outcome = error(error(domain_error(order, _), _))
    ->  Kind = 'domain_error(order)'
    ;   Outcome = error(error(type_error(atom, _), _))
    ->  Kind = 'type_error(atom)'
    ;   Kind = Outcome
    ),
    format('~w=~w~n', [Label, Kind]).

emit_bags(Label, Goal, Bag) :-
    findall(Bag, Goal, Answers),
    maplist(term_string, Answers, Rendered),
    atomic_list_concat(Rendered, ';', Joined),
    format('~w=~w~n', [Label, Joined]).

main(_) :-
    emit(source_order, (X = a ; X = b), X),
    emit(restore_before_right, (Y = a, fail ; var(Y), Y = b), Y),
    emit(cut_prunes_right, (Z = a, ! ; Z = b), Z),
    emit(callee_cut_retains_caller, (choose(W) ; W = c), W),
    emit(if_first_success, ((I = a ; I = b) -> true ; I = c), I),
    emit(if_then_failure, ((J = a ; J = b) -> fail ; J = c), J),
    emit(if_false_else, (fail -> K = a ; K = c), K),
    emit(if_condition_cut_else,
        (((L = a, !, fail ; L = b)) -> true ; L = c), L),
    emit(if_then_cut_outer,
        ((true -> (M = a, !) ; M = b) ; M = c), M),
    emit(soft_if_condition_answers,
        ((N = a ; N = b) *-> true ; N = c), N),
    emit(soft_if_then_retry,
        ((O = a ; O = b) *-> O = b ; O = c), O),
    emit(soft_if_false_else, (fail *-> P = a ; P = c), P),
    emit(soft_if_condition_cut_else,
        (((Q = a, !, fail ; Q = b)) *-> true ; Q = c), Q),
    emit(soft_if_then_cut_outer,
        ((true *-> (R = a, !) ; R = b) ; R = c), R),
    emit(once_first, once((S = a ; S = b)), S),
    emit(once_failure, once(fail), _T),
    emit(once_cut_caller,
        (once((U = a, !, fail ; U = b)) ; U = c), U),
    emit(once_then_cut_outer,
        ((once(true), V = a, !) ; V = c), V),
    emit(once_restore_caller,
        (once((W = a, fail)) ; (var(W), W = b)), W),
    emit(memberchk_first, memberchk(MC0, [a,b]), MC0),
    emit(memberchk_dynamic, call(memberchk(MC1, [a,b])), MC1),
    emit(memberchk_restores,
        memberchk(pair(MC2,MC2), [pair(a,b),pair(c,c)]), MC2),
    emit(meta_dynamic_disj, call((X = a ; X = b)), X),
    emit(meta_cut_retains_caller,
        (call((Y = a, !, fail ; Y = b)) ; Y = c), Y),
    emit(call_three, call(p, a, b), 1),
    emit(heap_built_callable, (G = p(a, b), call(G)), 1),
    emit_count(neg_rejects_success, \+ true),
    emit_count(neg_accepts_failure, \+ fail),
    emit(neg_restores_trial_bindings,
        (\+ (X = a, fail), var(X), X = b), X),
    emit(neg_cut_retains_caller,
        (\+ (!, true) ; X = c), X),
    emit_count(not_unify_distinct_atoms, a \= b),
    emit_count(not_unify_variable_atom, _NotUnifyVar \= a),
    emit(not_unify_restores_trial_bindings,
        (NU \= a ; var(NU), NU = b), NU),
    emit_count(meta_nonvar_bound, call(nonvar(a))),
    emit_count(meta_nonvar_variable, call(nonvar(_MetaVar))),
    emit_count(meta_forall_succeeds,
        call(forall((FX = a ; FX = b), FX \= c))),
    emit_count(meta_forall_fails,
        call(forall((FY = a ; FY = b), FY = a))),
    emit(meta_forall_restores_bindings,
        (call(forall(FZ = a, true)), var(FZ), FZ = c), FZ),
    emit_count(term_atom_accepts_atom, atom(a)),
    emit_count(term_atom_rejects_integer, atom(1)),
    emit_count(term_atom_rejects_list_nil, atom([])),
    emit_count(term_atomic_accepts_string, atomic("a")),
    emit_count(term_atomic_rejects_compound, atomic(pair(a, b))),
    emit_count(term_compound_accepts_pair, compound(pair(a, b))),
    emit_count(term_compound_rejects_atom, compound(a)),
    emit_count(term_number_accepts_integer, number(1)),
    emit_count(term_number_accepts_float, number(0.0)),
    emit_count(term_number_rejects_atom, number(a)),
    emit_count(term_string_accepts_string, string("a")),
    emit_count(term_string_rejects_atom, string(a)),
    emit_count(term_meta_atom_accepts_atom, call(atom(a))),
    emit_count(term_reference_atomic_not_atom,
        (retractall(p(_)), assertz(p(a), Ref), atomic(Ref), \+ atom(Ref))),
    emit_count(ground_nested_compound, ground(pair(a, [1,b]))),
    emit_count(ground_unbound_variable, ground(_GroundVar)),
    emit_count(ground_nested_free_leaf, ground(pair(a, _GroundLeaf))),
    emit_count(ground_rational_cycle,
        (GroundCycle = f(GroundCycle), ground(GroundCycle))),
    emit_count(ground_rational_free_leaf,
        (GroundOpen = f(GroundOpen, _GroundOpenLeaf), ground(GroundOpen))),
    emit_count(is_list_finite, is_list([a,b])),
    emit_count(is_list_improper, is_list([a|tail])),
    emit_count(is_list_variable, is_list(_ListVar)),
    emit_count(is_list_rational_spine,
        (ListCycle = [a|ListCycle], is_list(ListCycle))),
    emit_count(is_list_cyclic_head,
        (CyclicHead = f(CyclicHead), is_list([CyclicHead]))),
    emit_count(atom_codes_forward, atom_codes('aλ', [97,955])),
    emit(atom_codes_reverse, atom_codes(AtomCodesReverse, [97,955]),
        AtomCodesReverse),
    emit(atom_codes_binds_element, atom_codes(a, [AtomCode]), AtomCode),
    emit_count(atom_codes_mismatch, atom_codes(a, [98])),
    emit_count(string_codes_forward, string_codes("aλ", [97,955])),
    emit(string_codes_reverse, string_codes(StringCodesReverse, [97,955]),
        StringCodesReverse),
    emit_count(atom_chars_forward, atom_chars('aλ', [a,'λ'])),
    emit(atom_chars_reverse, atom_chars(AtomCharsReverse, [a,'λ']),
        AtomCharsReverse),
    emit(atom_chars_reverse_codes,
        atom_chars(AtomCharsReverseCodes, [97,955]), AtomCharsReverseCodes),
    emit(atom_chars_reverse_string,
        atom_chars(AtomCharsReverseString, "aλ"), AtomCharsReverseString),
    emit_count(atom_chars_bound_codes, atom_chars('aλ', [97,955])),
    emit_count(atom_chars_bound_string, atom_chars('aλ', "aλ")),
    emit(atom_chars_binds_element, atom_chars(a, [AtomChar]), AtomChar),
    emit_count(atom_chars_mismatch, atom_chars(a, [b])),
    emit(atom_string_forward, atom_string('aλ', AtomStringForward),
        AtomStringForward),
    emit(atom_string_reverse_string,
        atom_string(AtomStringReverseString, "aλ"), AtomStringReverseString),
    emit(atom_string_reverse_atom,
        atom_string(AtomStringReverseAtom, 'aλ'), AtomStringReverseAtom),
    emit_count(atom_string_mismatch, atom_string(a, "b")),
    emit(atom_string_meta_reverse,
        call(atom_string(AtomStringMetaReverse, "a")), AtomStringMetaReverse),
    emit_count(number_codes_forward_integer, number_codes(-42, [45,52,50])),
    emit(number_codes_reverse_integer, number_codes(NC0, [52,50]), NC0),
    emit(number_codes_reverse_negative, number_codes(NC1, [45,49]), NC1),
    emit_count(number_codes_reverse_float,
        (number_codes(NC2, [49,46,53]), NC2 == 1.5)),
    emit_count(number_codes_reverse_negative_float,
        (number_codes(NCN, [45,49,46,53]), NCN == -1.5)),
    emit_count(number_codes_reverse_exponent,
        (number_codes(NC3, [49,101,50]), NC3 == 100.0)),
    emit_count(number_codes_mismatch, number_codes(12, [49,51])),
    emit(number_codes_meta_reverse, call(number_codes(NC4, [52,50])), NC4),
    emit_count(code_type_space, code_type(32, space)),
    emit_count(code_type_newline_space, code_type(10, space)),
    emit_count(code_type_letter_not_space, code_type(65, space)),
    emit_count(code_type_digit, code_type(57, digit)),
    emit_count(code_type_letter_not_digit, code_type(65, digit)),
    emit_count(code_type_meta_space, call(code_type(32, space))),
    emit_count(identity_same_variable, X == X),
    emit_count(identity_distinct_variables, _IX == _IY),
    emit_count(nonidentity_distinct_variables, _NIX \== _NIY),
    emit_count(identity_separate_compounds, pair(a, b) == pair(a, b)),
    emit_count(identity_different_compounds, pair(a, b) == pair(a, c)),
    emit_count(identity_variable_sharing, pair(SX, SX) == pair(_SY, _SZ)),
    emit_count(identity_equal_rational_cycles,
        (RX = f(RX), RY = f(RY), RX == RY)),
    emit_count(identity_different_rational_cycles,
        (DX = f(DX), DY = g(DY), DX == DY)),
    emit(identity_failure_no_bind,
        (IX == a ; var(IX), IX = b), IX),
    emit_count(identity_meta_same_variable, call(MX == MX)),
    emit_count(identity_numeric_types, 1 == 1.0),
    emit_count(identity_equal_strings, "a" == "a"),
    emit_count(identity_atom_zero_compound, f == f()),
    emit_count(nonidentity_different_compounds, pair(a, b) \== pair(a, c)),
    emit_count(univ_decompose_compound,
        (pair(a, b) =.. L0, L0 = [pair, a, b])),
    emit_count(univ_construct_compound,
        (U0 =.. [pair, a, b], U0 = pair(a, b))),
    emit_count(univ_decompose_atom, (a =.. L1, L1 = [a])),
    emit_count(univ_construct_atom, (U1 =.. [a], U1 = a)),
    emit_count(univ_decompose_integer, (1 =.. L2, L2 = [1])),
    emit_count(univ_construct_sharing,
        (U2 =.. [pair, Shared0, Shared0], U2 = pair(Left0, Right0),
         Left0 == Right0)),
    emit_count(univ_decompose_sharing,
        (pair(Shared1, Shared1) =.. [pair, Left1, Right1],
         Left1 == Right1)),
    emit_count(univ_meta_construct,
        (call(U3 =.. [pair, a, b]), U3 = pair(a, b))),
    emit_count(copy_term_preserves_sharing,
        (copy_term(pair(CS, CS), pair(CL, CR)), CL == CR)),
    emit_count(copy_term_separates_source,
        (copy_term(CSource, CCopy), CSource \== CCopy)),
    emit_count(copy_term_successive_separate,
        (copy_term(COrigin, CFirst), copy_term(COrigin, CSecond),
         CFirst \== CSecond)),
    emit_count(copy_term_current_instantiation,
        (CCurrent = a, copy_term(pair(CCurrent, CCurrent), CResult),
         CResult == pair(a, a))),
    emit_count(copy_term_meta,
        (call(copy_term(pair(CM, CM), pair(CML, CMR))), CML == CMR)),
    emit_count(term_variables_order_identity,
        (term_variables(pair(TY, TX), TVars0),
         TVars0 = [TLeft0, TRight0], TLeft0 == TY, TRight0 == TX)),
    emit_count(term_variables_deduplicates,
        (term_variables(pair(TS, TS), TVars1),
         TVars1 = [TOnly], TOnly == TS)),
    emit_count(term_variables_ground_empty,
        term_variables(pair(a, b), [])),
    emit_count(term_variables_rational_leaf,
        (TR = f(TR, TLeaf), term_variables(TR, TVars2),
         TVars2 = [TFound], TFound == TLeaf)),
    emit_count(term_variables_output_mismatch,
        term_variables(pair(TM0, _TM1), [TM0])),
    emit_count(term_variables_meta,
        (call(term_variables(pair(_TM2, _TM3), TVars3)),
         TVars3 = [_, _])),
    emit_count(numbervars_order_sharing,
        (numbervars(pair(NVX, pair(NVX, NVY)), 0, NVEnd),
         NVX = '$VAR'(0), NVY = '$VAR'(1), NVEnd = 2)),
    emit_count(numbervars_singletons,
        (numbervars(pair(NSX, pair(NSX, NSY)), 0, NSEnd,
           [singletons(true)]),
         NSX = '$VAR'(0), NSY = '$VAR'('_'), NSEnd = 1)),
    emit_count(numbervars_start_five,
        (numbervars(pair(N5X, pair(N5X, N5Y)), 5, N5End,
           [singletons(true)]),
         N5X = '$VAR'(5), N5Y = '$VAR'('_'), N5End = 6)),
    emit_count(numbervars_singletons_false,
        (numbervars(pair(NFX, NFY), 0, NFEnd, [singletons(false)]),
         NFX = '$VAR'(0), NFY = '$VAR'(1), NFEnd = 2)),
    emit_count(numbervars_shared_application,
        (NShared = box(NSharedLeaf),
         numbervars(pair(NShared, NShared), 0, NSharedEnd,
           [singletons(true)]),
         NSharedLeaf = '$VAR'(0), NSharedEnd = 1)),
    emit_count(numbervars_cycle_disables_singletons,
        (NCycle = f(NCycle, NCycleLeaf),
         numbervars(NCycle, 0, NCycleEnd, [singletons(true)]),
         NCycleLeaf = '$VAR'(0), NCycleEnd = 1)),
    emit_count(numbervars_backtracks,
        (numbervars(pair(NBX, NBY), 0, _NBEnd), fail
         ; var(NBX), var(NBY))),
    emit_count(numbervars_end_mismatch,
        numbervars(pair(_NMX, _NMY), 0, 3)),
    emit_count(numbervars_meta,
        (call(numbervars(pair(_NMetaX, _NMetaY), 0, NMetaEnd)),
         NMetaEnd = 2)),
    emit(term_hash_atom, term_hash(a, THAtom), THAtom),
    emit(term_hash_integer, term_hash(1, THInteger), THInteger),
    emit(term_hash_negative_integer, term_hash(-1, THNegativeInteger),
        THNegativeInteger),
    emit(term_hash_string, term_hash("x", THString), THString),
    emit(term_hash_compound, term_hash(f(a,1), THCompound), THCompound),
    emit(term_hash_list, term_hash([a,b], THList), THList),
    emit(term_hash_float, term_hash(1.0, THFloat), THFloat),
    emit(term_hash_negative_zero, term_hash(-0.0, THNegativeZero),
        THNegativeZero),
    emit(term_hash_unicode_atom, term_hash('λ', THUnicodeAtom), THUnicodeAtom),
    emit(term_hash_latin_one_atom, term_hash('é', THLatinOneAtom),
        THLatinOneAtom),
    emit(term_hash_unicode_string, term_hash("λ", THUnicodeString),
        THUnicodeString),
    emit(term_hash_latin_one_string, term_hash("é", THLatinOneString),
        THLatinOneString),
    emit(term_hash_mixed_wide_string, term_hash("éλ", THMixedWideString),
        THMixedWideString),
    atom_codes(THAtom255, [255]),
    atom_codes(THAtom256, [256]),
    string_codes(THString255, [255]),
    string_codes(THString256, [256]),
    atom_codes(THAtomMixedBoundary, [255,256]),
    string_codes(THStringMixedBoundary, [255,256]),
    emit(term_hash_atom_u00ff, term_hash(THAtom255, THAtom255Hash),
        THAtom255Hash),
    emit(term_hash_atom_u0100, term_hash(THAtom256, THAtom256Hash),
        THAtom256Hash),
    emit(term_hash_string_u00ff, term_hash(THString255, THString255Hash),
        THString255Hash),
    emit(term_hash_string_u0100, term_hash(THString256, THString256Hash),
        THString256Hash),
    emit(term_hash_atom_mixed_boundary,
        term_hash(THAtomMixedBoundary, THAtomMixedBoundaryHash),
        THAtomMixedBoundaryHash),
    emit(term_hash_string_mixed_boundary,
        term_hash(THStringMixedBoundary, THStringMixedBoundaryHash),
        THStringMixedBoundaryHash),
    emit(term_hash_shared,
        (THSharedTerm = box(a),
         term_hash(pair(THSharedTerm, THSharedTerm), THShared)), THShared),
    emit(term_hash_duplicated,
        term_hash(pair(box(a),box(a)), THDuplicated), THDuplicated),
    emit(term_hash_cycle,
        (THCycle = f(THCycle), term_hash(THCycle, THCycleHash)), THCycleHash),
    emit(term_hash_outer_cycle,
        (THOuterCycle = g(THOuterCycle),
         term_hash(pair(THOuterCycle,a), THOuterCycleHash)), THOuterCycleHash),
    emit(term_hash_shared_cycle,
        (THSharedCycle = f(THSharedCycle),
         term_hash(pair(THSharedCycle,THSharedCycle), THSharedCycleHash)),
        THSharedCycleHash),
    emit_count(term_hash_nonground,
        (term_hash(pair(_THVar,a), THUnbound), var(THUnbound))),
    emit_count(term_hash_nonground_bound_output,
        term_hash(pair(_THBoundVar,a), 7)),
    emit_count(term_hash_mismatch, term_hash(a, 0)),
    emit_count(term_hash_meta,
        (call(term_hash(a, THMeta)), THMeta = 45085902)),
    emit(term_hash_normalized_key,
        (copy_term(pair(THX,pair(THX,_THY)), THCopy),
         numbervars(THCopy, 0, _, [singletons(true)]),
         term_hash(THCopy, THNormalized)),
        THNormalized),
    emit_count(functor_decompose_compound,
        functor(pair(a,b), pair, 2)),
    emit_count(functor_decompose_atomic,
        functor(7, 7, 0)),
    emit_count(functor_construct_compound,
        functor(_FunctorCompound, pair, 2)),
    emit_count(functor_construct_distinct,
        (functor(FreshCompound, pair, 2),
         FreshCompound = pair(FreshLeft, FreshRight),
         var(FreshLeft), var(FreshRight), FreshLeft \== FreshRight)),
    emit_count(functor_construct_atomic,
        functor(7, 7, 0)),
    emit_count(functor_rational_root,
        (RationalFunctor = f(RationalFunctor),
         functor(RationalFunctor, f, 1))),
    emit_count(functor_output_mismatch,
        functor(pair(a,b), wrong, 2)),
    emit_count(functor_meta,
        call(functor(_MetaFunctor, pair, 2))),
    emit_count(nb_setval_duplicates_source,
        (nb_setval(copy, f(NBCopySource)), NBCopySource = source,
         nb_getval(copy, NBCopyStored), NBCopyStored = f(stored))),
    emit_count(nb_getval_shares_variables,
        (nb_setval(shared, f(_NBShared)), nb_getval(shared, NBFirst),
         nb_getval(shared, NBSecond), NBFirst == NBSecond)),
    emit_count(nb_getval_bindings_backtrack,
        (nb_setval(trailed, f(_NBTrailed)),
         ((nb_getval(trailed, NBLeft), NBLeft = f(left), fail) ; true),
         nb_getval(trailed, NBRight), NBRight = f(right))),
    emit_count(nb_setval_survives_older_choice,
        (((nb_setval(persistent, f(_NBPersistent)), fail) ; true),
         nb_getval(persistent, NBAfter), NBAfter = f(after))),
    emit_count(nb_delete_survives_older_choice,
        (nb_setval(deleted, value),
         ((nb_delete(deleted), fail) ; true),
         catch(nb_getval(deleted, _NBDeleted),
               error(existence_error(variable, deleted), _), true))),
    emit_count(nb_delete_missing_succeeds,
        nb_delete(already_absent)),
    emit(integer_addition, (IA is 2 + 3), IA),
    emit(integer_nested, (IN is (2 + 3) * 4), IN),
    emit(integer_subtraction, (IS is 3 - 5), IS),
    emit(integer_mod_negative_dividend, (IM0 is -5 mod 3), IM0),
    emit(integer_mod_negative_divisor, (IM1 is 5 mod -3), IM1),
    emit_count(integer_is_mismatch, 4 is 2 + 3),
    emit_count(integer_comparisons,
        (1 < 2, 2 =< 2, 3 > 2, 3 >= 3, 2 + 3 =:= 5, 5 =\= 6)),
    emit(integer_comparison_caller, (2 < 1 ; IC = b), IC),
    emit(integer_meta_addition, (call(IMA is 2 + 3)), IMA),
    emit(length_finite, length([a,b,c], LengthFinite), LengthFinite),
    emit_count(length_matching, length([a,b], 2)),
    emit_count(length_mismatching, length([a,b], 1)),
    emit_count(current_predicate_known, current_predicate(p/2)),
    emit_count(current_predicate_missing, current_predicate(q/2)),
    emit_count(current_predicate_after_assert,
        (retractall(p(_)), assertz(p(a)), current_predicate(p/1))),
    emit(catch_ground, catch(throw(ball), X, X = ball), X),
    emit_raised(catch_throw_time_reject,
        catch((Y = body, throw(ball)), Y, true)),
    emit_raised(catch_recovery_rethrow,
        catch(throw(a), Z, throw(b))),
    emit(catch_guard_cut_caller,
        (catch((A = a, !, fail), never, true) ; A = c), A),
    emit(catch_recovery_cut_caller,
        (catch(throw(a), a, (!, fail)) ; B = c), B),
    emit(catch_guard_answers,
        catch((C = a ; C = b), never, fail), C),
    emit_raised(catch_nested_throw_time_reject,
        catch(catch((X0 = body, throw(ball)), nope, fail), X0, true)),
    emit_count(catch_copy_separates_caller,
        catch(throw(box(D)), box(E), (E = a, var(D)))),
    emit_count(catch_copy_preserves_sharing,
        catch(throw(pair(F, F)), pair(H, I), (H = a, I = b))),
    emit_count(catch_copy_preserves_separation,
        catch(throw(pair(J, K)), pair(L, N), (L = a, N = b))),
    emit_count(throw_variable_instantiation_error,
        catch(throw(_),
            error(instantiation_error,
                context(system:throw/1, _)),
            true)),
    emit_bags(findall_order_multiplicity,
        findall(X, (X = a ; X = b ; X = a), Bag), Bag),
    emit_bags(findall_binding_isolation,
        (findall(X, X = a, Bag), var(X)), Bag),
    emit_bags(findall_empty,
        findall(_X, fail, Bag), Bag),
    emit_bags(findall_cut_retains_caller,
        (findall(X, (X = a, ! ; X = b), Bag) ; Bag = [c]), Bag),
    emit_bags(findall_exception_discards_partial,
        catch(findall(X, (X = a ; throw(ball)), Bag), ball,
            Bag = [caught]), Bag),
    emit_count(findall_copy_fresh_shared,
        (findall(pair(Y, Y), (true ; true), CopyBag),
          CopyBag = [pair(A, A), pair(B, B)], A \== B)),
    emit_count(findall_copy_separation,
        (findall(pair(Y, Z), true, [pair(C, D)]), C \== D)),
    emit(transaction_first_solution,
        (transaction((TX = a ; TX = b)) ; TX = c), TX),
    emit(transaction_meta_first_solution,
        call(transaction((TM = a ; TM = b))), TM),
    emit(transaction_success_commits,
        (retractall(p(_)), transaction(assertz(p(a))), p(TS)), TS),
    emit(transaction_failure_rolls_back,
        (retractall(p(_)), (transaction((assertz(p(a)), fail)) ; true),
         p(TF)), TF),
    emit(transaction_exception_rolls_back,
        (retractall(p(_)),
         catch(transaction((assertz(p(a)), throw(ball))), ball, true),
         p(TE)), TE),
    emit(transaction_caught_inside_commits,
        (retractall(p(_)),
         transaction((assertz(p(a)), catch(throw(ball), ball, true))),
         p(TC)), TC),
    emit(transaction_outer_rollback_undoes_inner_commit,
        (retractall(p(_)),
         (transaction((transaction(assertz(p(b))), fail)) ; true),
         p(TO)), TO),
    emit(transaction_inner_rollback_preserves_outer,
        (retractall(p(_)),
         transaction((assertz(p(a)),
           (transaction((assertz(p(b)), fail)) ; true))),
         p(TI)), TI),
    emit(db_assertz_then_call,
        (retractall(p(_)), assertz(p(a)), p(X)), X),
    emit(db_failed_branch_persists,
        (retractall(p(_)), (assertz(p(a)), fail ; true), p(X)), X),
    emit(db_asserta_assertz_order,
        (retractall(p(_)), assertz(p(b)), asserta(p(a)), p(X)), X),
    emit_count(db_assertz_ref_bound,
        (retractall(p(_)), assertz(p(a), Ref), nonvar(Ref))),
    emit_count(db_asserta_ref_bound,
        (retractall(p(_)), asserta(p(a), Ref), nonvar(Ref))),
    emit_count(db_assert_refs_distinct,
        (retractall(p(_)), assertz(p(a), Ref), assertz(p(b), OtherRef),
         Ref \= OtherRef)),
    emit_count(db_assert_ref_roundtrip,
        (retractall(p(_)), retractall(saved(_)), assertz(p(a), Ref),
         assertz(saved(Ref)), saved(OtherRef), Ref = OtherRef)),
    emit(db_retract_source_order,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)), retract(p(X))), X),
    emit(db_retract_cut_prunes_later,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)), retract(p(X)), !), X),
    emit(db_retract_fact_skips_rule,
        (retractall(p(_)), assertz((p(a) :- q(a))), assertz(p(b)),
         retract(p(X))), X),
    emit(db_retract_failed_branch_persists,
        (retractall(p(_)), assertz(p(a)),
         (retract(p(a)), fail ; true), p(X)), X),
    emit_count(db_retract_snapshot_no_drift,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)),
         findall(X,
           (retract(p(X)),
            (X = a -> assertz(p(c)), fail ; true)),
           Answers),
         Answers = [b], findall(Y, p(Y), [c]))),
    emit(db_retract_snapshot_retains_erased,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)),
         retract(p(X)),
         (X = a -> retract(p(b)), fail ; true)), X),
    emit(db_clause_source_order,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)),
         clause(p(X), true, _ClauseRef1)), X),
    emit(db_clause_bound_reference,
        (retractall(p(_)), assertz(p(a), _First), assertz(p(b), Ref),
         clause(p(X), true, Ref)), X),
    emit(db_clause_rule_body,
        (retractall(p(_)), assertz((p(a) :- q(a))),
         clause(p(a), q(Y), _ClauseRef2)), Y),
    emit(db_clause_cut_prunes_later,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)),
         clause(p(X), true, _ClauseRef3), !), X),
    emit_count(db_clause_reference_roundtrip,
        (retractall(p(_)), assertz(p(a), Ref),
         clause(p(a), true, OtherRef), Ref = OtherRef)),
    emit(db_clause_snapshot_no_drift,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)),
         clause(p(X), true, _ClauseRef4),
         (X = a -> assertz(p(c)), fail ; true)), X),
    emit(db_clause_snapshot_retains_erased,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)),
         clause(p(X), true, _ClauseRef5),
         (X = a -> retract(p(b)), fail ; true)), X),
    emit_count(db_snapshot_no_drift,
        (retractall(p(_)), retractall(driver), assertz(p(old)),
         assertz((driver :- p(_), assertz(p(new)), fail)),
         findall(1, driver, Answers), Answers = [])),
    emit(db_snapshot_later_call,
        (retractall(p(_)), retractall(driver), assertz(p(old)),
         assertz((driver :- p(_), assertz(p(new)), fail)),
         \+ driver, p(X)), X),
    emit(compare_atoms, compare(X, a, b), X),
    emit(compare_equal_compounds, compare(X, f(a), f(a)), X),
    emit(compare_compound_arity, compare(X, f(a), f(a,b)), X),
    emit_count(compare_prebound_mismatch, compare(>, a, b)),
    emit_compare_error(compare_invalid_order_atom, compare(foo, a, b)),
    emit_compare_error(compare_invalid_order_integer, compare(1, a, b)),
    emit_compare_error(compare_invalid_order_compound, compare(f(x), a, b)),
    emit_count(dcg_terminal_sharing, phrase(dcg_pair(a), [a, a])),
    emit_count(dcg_braced_goal, phrase(dcg_guarded(a), [a])),
    emit_count(dcg_disjunction, phrase(dcg_choice, [b])),
    emit_count(dcg_string_terminal, phrase(dcg_hello, [97, 98])),
    emit_count(dcg_variable_list, phrase(dcg_emit([a,b]), [a,b])),
    emit_count(dcg_variable_list_sharing,
        \+ phrase(dcg_emit([X,X]), [a,b])),
    emit_count(dcg_variable_string, phrase(dcg_emit("ab"), [97,98])),
    emit_count(dcg_phrase_two, dcg_via([a])),
    emit_count(dcg_phrase_three_rest, dcg_via_rest([a,b], [b])),
    emit_count(dcg_variable_braced,
        phrase(dcg_delegate({a=a}), [])),
    emit_count(dcg_dynamic_cut_caller,
        findall(X, dcg_cut_outer(X), [c])).
