:- initialization(main, main).

choose(a) :- !.
choose(b).

p(a, b).

emit(Label, Goal, Template) :-
    findall(Template, Goal, Answers),
    atomic_list_concat(Answers, ',', Joined),
    format('~w=~w~n', [Label, Joined]).

emit_raised(Label, Goal) :-
    catch((Goal, Result = completed), Error, Result = raised(Error)),
    format('~w=~w~n', [Label, Result]).

emit_count(Label, Goal) :-
    findall(1, Goal, Answers),
    length(Answers, Count),
    format('~w=~w~n', [Label, Count]).

emit_bags(Label, Goal, Bag) :-
    findall(Bag, Goal, Answers),
    maplist(term_string, Answers, Rendered),
    atomic_list_concat(Rendered, ';', Joined),
    format('~w=~w~n', [Label, Joined]).

main(_) :-
    emit(source_order, (X = a ; X = b), X),
    emit(restore_before_right, (Y = a, fail ; var(Y), Y = b), Y),
    emit(cut_prunes_right, (Z = a, ! ; Z = b), Z),
    emit(callee_cut_retains_caller, (choose(W) ; W = c), W),
    emit(if_first_success, ((I = a ; I = b) -> true ; I = c), I),
    emit(if_then_failure, ((J = a ; J = b) -> fail ; J = c), J),
    emit(if_false_else, (fail -> K = a ; K = c), K),
    emit(if_condition_cut_else,
        (((L = a, !, fail ; L = b)) -> true ; L = c), L),
    emit(if_then_cut_outer,
        ((true -> (M = a, !) ; M = b) ; M = c), M),
    emit(soft_if_condition_answers,
        ((N = a ; N = b) *-> true ; N = c), N),
    emit(soft_if_then_retry,
        ((O = a ; O = b) *-> O = b ; O = c), O),
    emit(soft_if_false_else, (fail *-> P = a ; P = c), P),
    emit(soft_if_condition_cut_else,
        (((Q = a, !, fail ; Q = b)) *-> true ; Q = c), Q),
    emit(soft_if_then_cut_outer,
        ((true *-> (R = a, !) ; R = b) ; R = c), R),
    emit(once_first, once((S = a ; S = b)), S),
    emit(once_failure, once(fail), _T),
    emit(once_cut_caller,
        (once((U = a, !, fail ; U = b)) ; U = c), U),
    emit(once_then_cut_outer,
        ((once(true), V = a, !) ; V = c), V),
    emit(once_restore_caller,
        (once((W = a, fail)) ; (var(W), W = b)), W),
    emit(meta_dynamic_disj, call((X = a ; X = b)), X),
    emit(meta_cut_retains_caller,
        (call((Y = a, !, fail ; Y = b)) ; Y = c), Y),
    emit(call_three, call(p, a, b), 1),
    emit(heap_built_callable, (G = p(a, b), call(G)), 1),
    emit_count(neg_rejects_success, \+ true),
    emit_count(neg_accepts_failure, \+ fail),
    emit(neg_restores_trial_bindings,
        (\+ (X = a, fail), var(X), X = b), X),
    emit(neg_cut_retains_caller,
        (\+ (!, true) ; X = c), X),
    emit_count(not_unify_distinct_atoms, a \= b),
    emit_count(not_unify_variable_atom, _NotUnifyVar \= a),
    emit(not_unify_restores_trial_bindings,
        (NU \= a ; var(NU), NU = b), NU),
    emit_count(meta_nonvar_bound, call(nonvar(a))),
    emit_count(meta_nonvar_variable, call(nonvar(_MetaVar))),
    emit_count(meta_forall_succeeds,
        call(forall((FX = a ; FX = b), FX \= c))),
    emit_count(meta_forall_fails,
        call(forall((FY = a ; FY = b), FY = a))),
    emit(meta_forall_restores_bindings,
        (call(forall(FZ = a, true)), var(FZ), FZ = c), FZ),
    emit_count(term_atom_accepts_atom, atom(a)),
    emit_count(term_atom_rejects_integer, atom(1)),
    emit_count(term_atomic_accepts_string, atomic("a")),
    emit_count(term_atomic_rejects_compound, atomic(pair(a, b))),
    emit_count(term_compound_accepts_pair, compound(pair(a, b))),
    emit_count(term_compound_rejects_atom, compound(a)),
    emit_count(term_number_accepts_integer, number(1)),
    emit_count(term_number_accepts_float, number(0.0)),
    emit_count(term_number_rejects_atom, number(a)),
    emit_count(term_string_accepts_string, string("a")),
    emit_count(term_string_rejects_atom, string(a)),
    emit_count(term_meta_atom_accepts_atom, call(atom(a))),
    emit_count(term_reference_atomic_not_atom,
        (retractall(p(_)), assertz(p(a), Ref), atomic(Ref), \+ atom(Ref))),
    emit(catch_ground, catch(throw(ball), X, X = ball), X),
    emit_raised(catch_throw_time_reject,
        catch((Y = body, throw(ball)), Y, true)),
    emit_raised(catch_recovery_rethrow,
        catch(throw(a), Z, throw(b))),
    emit(catch_guard_cut_caller,
        (catch((A = a, !, fail), never, true) ; A = c), A),
    emit(catch_recovery_cut_caller,
        (catch(throw(a), a, (!, fail)) ; B = c), B),
    emit(catch_guard_answers,
        catch((C = a ; C = b), never, fail), C),
    emit_raised(catch_nested_throw_time_reject,
        catch(catch((X0 = body, throw(ball)), nope, fail), X0, true)),
    emit_count(catch_copy_separates_caller,
        catch(throw(box(D)), box(E), (E = a, var(D)))),
    emit_count(catch_copy_preserves_sharing,
        catch(throw(pair(F, F)), pair(H, I), (H = a, I = b))),
    emit_count(catch_copy_preserves_separation,
        catch(throw(pair(J, K)), pair(L, N), (L = a, N = b))),
    emit_count(throw_variable_instantiation_error,
        catch(throw(_),
            error(instantiation_error,
                context(system:throw/1, _)),
            true)),
    emit_bags(findall_order_multiplicity,
        findall(X, (X = a ; X = b ; X = a), Bag), Bag),
    emit_bags(findall_binding_isolation,
        (findall(X, X = a, Bag), var(X)), Bag),
    emit_bags(findall_empty,
        findall(_X, fail, Bag), Bag),
    emit_bags(findall_cut_retains_caller,
        (findall(X, (X = a, ! ; X = b), Bag) ; Bag = [c]), Bag),
    emit_bags(findall_exception_discards_partial,
        catch(findall(X, (X = a ; throw(ball)), Bag), ball,
            Bag = [caught]), Bag),
    emit_count(findall_copy_fresh_shared,
        (findall(pair(Y, Y), (true ; true), CopyBag),
          CopyBag = [pair(A, A), pair(B, B)], A \== B)),
    emit_count(findall_copy_separation,
        (findall(pair(Y, Z), true, [pair(C, D)]), C \== D)),
    emit(db_assertz_then_call,
        (retractall(p(_)), assertz(p(a)), p(X)), X),
    emit(db_failed_branch_persists,
        (retractall(p(_)), (assertz(p(a)), fail ; true), p(X)), X),
    emit(db_asserta_assertz_order,
        (retractall(p(_)), assertz(p(b)), asserta(p(a)), p(X)), X),
    emit_count(db_assertz_ref_bound,
        (retractall(p(_)), assertz(p(a), Ref), nonvar(Ref))),
    emit_count(db_asserta_ref_bound,
        (retractall(p(_)), asserta(p(a), Ref), nonvar(Ref))),
    emit_count(db_assert_refs_distinct,
        (retractall(p(_)), assertz(p(a), Ref), assertz(p(b), OtherRef),
         Ref \= OtherRef)),
    emit_count(db_assert_ref_roundtrip,
        (retractall(p(_)), retractall(saved(_)), assertz(p(a), Ref),
         assertz(saved(Ref)), saved(OtherRef), Ref = OtherRef)),
    emit(db_retract_source_order,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)), retract(p(X))), X),
    emit(db_retract_cut_prunes_later,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)), retract(p(X)), !), X),
    emit(db_retract_fact_skips_rule,
        (retractall(p(_)), assertz((p(a) :- q(a))), assertz(p(b)),
         retract(p(X))), X),
    emit(db_retract_failed_branch_persists,
        (retractall(p(_)), assertz(p(a)),
         (retract(p(a)), fail ; true), p(X)), X),
    emit_count(db_retract_snapshot_no_drift,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)),
         findall(X,
           (retract(p(X)),
            (X = a -> assertz(p(c)), fail ; true)),
           Answers),
         Answers = [b], findall(Y, p(Y), [c]))),
    emit(db_retract_snapshot_retains_erased,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)),
         retract(p(X)),
         (X = a -> retract(p(b)), fail ; true)), X),
    emit(db_clause_source_order,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)),
         clause(p(X), true, _ClauseRef1)), X),
    emit(db_clause_bound_reference,
        (retractall(p(_)), assertz(p(a), _First), assertz(p(b), Ref),
         clause(p(X), true, Ref)), X),
    emit(db_clause_rule_body,
        (retractall(p(_)), assertz((p(a) :- q(a))),
         clause(p(a), q(Y), _ClauseRef2)), Y),
    emit(db_clause_cut_prunes_later,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)),
         clause(p(X), true, _ClauseRef3), !), X),
    emit_count(db_clause_reference_roundtrip,
        (retractall(p(_)), assertz(p(a), Ref),
         clause(p(a), true, OtherRef), Ref = OtherRef)),
    emit(db_clause_snapshot_no_drift,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)),
         clause(p(X), true, _ClauseRef4),
         (X = a -> assertz(p(c)), fail ; true)), X),
    emit(db_clause_snapshot_retains_erased,
        (retractall(p(_)), assertz(p(a)), assertz(p(b)),
         clause(p(X), true, _ClauseRef5),
         (X = a -> retract(p(b)), fail ; true)), X),
    emit_count(db_snapshot_no_drift,
        (retractall(p(_)), retractall(driver), assertz(p(old)),
         assertz((driver :- p(_), assertz(p(new)), fail)),
         findall(1, driver, Answers), Answers = [])),
    emit(db_snapshot_later_call,
        (retractall(p(_)), retractall(driver), assertz(p(old)),
         assertz((driver :- p(_), assertz(p(new)), fail)),
         \+ driver, p(X)), X).
