import NavierStokes.R3.HeatKernelCommutator
import NavierStokes.ViscousPropagator
import NavierStokes.PeriodicViscosityUniqueness
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeCoherentPairEstimate
import MettapediaNS.WholeSpaceBKM
import MettapediaNS.WholeSpaceViscousEnergy
import MettapediaNS.AlmostOrthogonality

/-!
# Direct upstream dependency audit

These declarations are imported from the pinned upstream package. Their
proofs are not copied or reimplemented. The audit does not assert that the
hypotheses of these estimates have been established for arbitrary-data
unforced Navier–Stokes solutions.
-/

#print axioms NavierStokesR3.Comparison.riesz_commutator_eq_heatKernel
#print axioms NavierStokesR3.Comparison.riesz_commutator_pair_bound
#print axioms NavierStokesR3.Comparison.cancelledTimeKernel_integral_swap
#print axioms NavierStokes.ViscousPropagator.high_harmonic_propagator_estimate
#print axioms NavierStokes.PeriodicViscosityUniqueness.classical_uniqueness_on_Icc
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeCoherentPairEstimate.sigmaSq_coherent_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.curlField_eq_vectorCurl
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.spatialBKMIntegrand_curl_eq_vorticityNorm
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.spatialEssentialSupNorm_curl_eq_ofReal_vorticityNorm
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.norm_fderiv_le_spatialBKMIntegrand
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.norm_fderiv_le_transportedVorticityBKMIntegrand
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.continuous_spatialBKMIntegrand_curl
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.h3_energyProduction_add_dissipation_le_spatialBKMIntegrand
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.laplacianField_field
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.integerEnergyProduction_laplacianField
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.navierStokesRhs_field
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.integerEnergyProduction_navierStokesRhs
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.h3_energyProduction_add_dissipation_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.h3_energyProduction_le_of_nonneg
#print axioms Mettapedia.Analysis.OperatorAlmostOrthogonality.norm_sum_le_of_adjoint_comp
#print axioms Mettapedia.Analysis.OperatorAlmostOrthogonality.norm_sum_le_of_star_mul
