import NavierStokes.R3.HeatKernelCommutator
import NavierStokes.ViscousPropagator
import NavierStokes.PeriodicViscosityUniqueness
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeCoherentPairEstimate
import MettapediaNS.WholeSpaceBKM
import MettapediaNS.WholeSpaceViscousEnergy
import MettapediaNS.AlmostOrthogonality
import MettapediaNS.QuadraticSingularIntegral
import MettapediaNS.WholeSpaceBiotSavart
import MettapediaNS.NewtonianHessianPrincipalValue
import MettapediaNS.WholeSpaceStrain
import MettapediaNS.WholeSpaceBiotSavartRegularity

/-!
# Direct upstream dependency audit

These declarations are imported from the pinned upstream package. Their
proofs are not copied or reimplemented. The audit does not assert that the
hypotheses of these estimates have been established for arbitrary-data
unforced Navier–Stokes solutions.
-/

#print axioms NavierStokesR3.Comparison.riesz_commutator_eq_heatKernel
#print axioms NavierStokesR3.Comparison.riesz_commutator_pair_bound
#print axioms NavierStokesR3.Comparison.cancelledTimeKernel_integral_swap
#print axioms NavierStokes.ViscousPropagator.high_harmonic_propagator_estimate
#print axioms NavierStokes.PeriodicViscosityUniqueness.classical_uniqueness_on_Icc
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeCoherentPairEstimate.sigmaSq_coherent_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.curlField_eq_vectorCurl
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.spatialBKMIntegrand_curl_eq_vorticityNorm
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.spatialEssentialSupNorm_curl_eq_ofReal_vorticityNorm
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.norm_fderiv_le_spatialBKMIntegrand
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.norm_fderiv_le_transportedVorticityBKMIntegrand
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.continuous_spatialBKMIntegrand_curl
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.h3_energyProduction_add_dissipation_le_spatialBKMIntegrand
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.laplacianField_field
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.integerEnergyProduction_laplacianField
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.navierStokesRhs_field
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.integerEnergyProduction_navierStokesRhs
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.h3_energyProduction_add_dissipation_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.h3_energyProduction_le_of_nonneg
#print axioms Mettapedia.Analysis.OperatorAlmostOrthogonality.norm_sum_le_of_adjoint_comp
#print axioms Mettapedia.Analysis.OperatorAlmostOrthogonality.norm_sum_le_of_star_mul
#print axioms NS.Lit.CZ.truncated_Lp_uniform
#print axioms NS.Lit.CZ.pvOp_Lp
#print axioms NS.Lit.CZ.smoothTruncate_Lp_uniform
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.homKer_coordinateProduct
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.homKer_coordinateSquareDifference
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.exists_truncated_lpBound_coordinateProduct
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.exists_truncated_lpBound_coordinateSquareDifference
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.exists_pv_eLpNorm_bound_coordinateProduct
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.exists_pv_eLpNorm_bound_coordinateSquareDifference
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.exists_smoothTruncated_lpBound_coordinateProduct
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.exists_smoothTruncated_lpBound_coordinateSquareDifference
#print axioms EulerBlowup.Ring3D.Lit3.potential_theory_R3
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.curl3_eq_vectorCurl
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.div3_eq_divergence
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.contDiff_velocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.memLp_velocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.divergence_velocity_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.vectorCurl_velocity_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.curlField_velocity_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.newtonianHessian_eq_integral
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.velocity_partial_eq_integrals
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.partial_gradG3
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.partial_gradG3_eq_coordinateProduct
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.partial_gradG3_sub_eq_coordinateSquareDifference
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.integral_radial_mul_homKer_eq_zero_of_isometry
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.tendsto_integral_regularizedHessian
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.regularizedHessian_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.tendsto_integral_hessianMultiplier_mul
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.tendsto_regularizedPrincipalValue
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.integral_ball_hessianMultiplier_homKer_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.tendsto_integral_regularizedKernel
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.regularizedHessian_eq_coordinateProduct
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.regularizedHessian_sub_eq_coordinateSquareDifference
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.newtonianHessian_eq_principalValue
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.newtonianHessian_sub_eq_principalValue
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.exists_eLpNorm_newtonianHessian_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.exists_eLpNorm_newtonianHessian_sub_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.strainRateApply_axis_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.velocity_partial_eq_hessians
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.strain_diagonal_eq_hessians
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.strain_cyclic_eq_hessians
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.strain_diagonal_eq_principalValue
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.strain_cyclic_eq_principalValue
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.exists_eLpNorm_strain_entry_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.strainOperator_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.continuous_strainOperator
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.norm_linearMap_le_sum_axes
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.norm_strainOperator_le_sum_entries
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.exists_eLpNorm_strainOperator_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.memLp_strainOperator
#print axioms EulerComparatorRecovery.iteratedFDeriv_memLp_of_curl_compact
#print axioms EulerComparatorRecovery.smoothL2Field_of_curl_compact
#print axioms EulerOrdinarySobolev.pressureField_mem_gradient
#print axioms EulerMeanPressure.gradientSpace_radial_potential
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.pressurePotential_spec
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.projectedNavierStokesRhs_field
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.laplacianField_mem_solenoidal
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.projectedNavierStokesRhs_mem_solenoidal
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.divergence_projectedNavierStokesRhs_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.h3_projectedProduction_add_dissipation_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.hasCompactSupport_vectorCurl_velocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.smoothVelocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.memLp_iteratedFDeriv_velocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.smoothVelocity_mem_solenoidal
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.spatialBKMIntegrand_eq_vorticityNorm
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.norm_fderiv_velocity_le_spatialBKMIntegrand
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.h3_projectedProduction_velocity_le
