import NavierStokes.R3.HeatKernelCommutator
import NavierStokes.ViscousPropagator
import NavierStokes.PeriodicViscosityUniqueness
import Mettapedia.FluidDynamics.NavierStokes.StochasticLagrangian.PancakeCoherentPairEstimate
import MettapediaNS.WholeSpaceBKM
import MettapediaNS.WholeSpaceViscousEnergy
import MettapediaNS.AlmostOrthogonality
import MettapediaNS.QuadraticSingularIntegral
import MettapediaNS.WholeSpaceBiotSavart
import MettapediaNS.NewtonianHessianPrincipalValue
import MettapediaNS.WholeSpaceStrain
import MettapediaNS.WholeSpaceBiotSavartRegularity
import MettapediaNS.WholeSpacePressureFlux
import MettapediaNS.RieszDoubleCommutator
import MettapediaNS.WholeSpaceUnforcedEnergy
import MettapediaNS.PressureHessianLocalization
import MettapediaNS.GaussianHeatIncrement
import MettapediaNS.GaussianHeatWeakStress
import MettapediaNS.GaussianHeatFourier

/-!
# Direct upstream dependency audit

These declarations are imported from the pinned upstream package. Their
proofs are not copied or reimplemented. The audit does not assert that the
hypotheses of these estimates have been established for arbitrary-data
unforced Navier–Stokes solutions.
-/

#print axioms NavierStokesR3.Comparison.riesz_commutator_eq_heatKernel
#print axioms NavierStokesR3.Comparison.riesz_commutator_pair_bound
#print axioms NavierStokesR3.Comparison.cancelledTimeKernel_integral_swap
#print axioms NavierStokes.ViscousPropagator.high_harmonic_propagator_estimate
#print axioms NavierStokes.PeriodicViscosityUniqueness.classical_uniqueness_on_Icc
#print axioms Mettapedia.FluidDynamics.NavierStokes.PancakeCoherentPairEstimate.sigmaSq_coherent_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.curlField_eq_vectorCurl
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.spatialBKMIntegrand_curl_eq_vorticityNorm
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.spatialEssentialSupNorm_curl_eq_ofReal_vorticityNorm
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.norm_fderiv_le_spatialBKMIntegrand
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.norm_fderiv_le_transportedVorticityBKMIntegrand
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.continuous_spatialBKMIntegrand_curl
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBKM.h3_energyProduction_add_dissipation_le_spatialBKMIntegrand
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.laplacianField_field
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.integerEnergyProduction_laplacianField
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.navierStokesRhs_field
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.integerEnergyProduction_navierStokesRhs
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.h3_energyProduction_add_dissipation_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.h3_energyProduction_le_of_nonneg
#print axioms Mettapedia.Analysis.OperatorAlmostOrthogonality.norm_sum_le_of_adjoint_comp
#print axioms Mettapedia.Analysis.OperatorAlmostOrthogonality.norm_sum_le_of_star_mul
#print axioms NS.Lit.CZ.truncated_Lp_uniform
#print axioms NS.Lit.CZ.pvOp_Lp
#print axioms NS.Lit.CZ.smoothTruncate_Lp_uniform
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.homKer_coordinateProduct
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.homKer_coordinateSquareDifference
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.exists_truncated_lpBound_coordinateProduct
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.exists_truncated_lpBound_coordinateSquareDifference
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.exists_pv_eLpNorm_bound_coordinateProduct
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.exists_pv_eLpNorm_bound_coordinateSquareDifference
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.exists_smoothTruncated_lpBound_coordinateProduct
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.exists_smoothTruncated_lpBound_coordinateSquareDifference
#print axioms EulerBlowup.Ring3D.Lit3.potential_theory_R3
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.curl3_eq_vectorCurl
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.div3_eq_divergence
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.contDiff_velocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.memLp_velocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.divergence_velocity_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.vectorCurl_velocity_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.curlField_velocity_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.newtonianHessian_eq_integral
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.velocity_partial_eq_integrals
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.partial_gradG3
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.partial_gradG3_eq_coordinateProduct
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.partial_gradG3_sub_eq_coordinateSquareDifference
#print axioms Mettapedia.Analysis.QuadraticSingularIntegral.integral_radial_mul_homKer_eq_zero_of_isometry
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.tendsto_integral_regularizedHessian
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.regularizedHessian_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.tendsto_integral_hessianMultiplier_mul
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.tendsto_regularizedPrincipalValue
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.integral_ball_hessianMultiplier_homKer_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.tendsto_integral_regularizedKernel
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.regularizedHessian_eq_coordinateProduct
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.regularizedHessian_sub_eq_coordinateSquareDifference
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.newtonianHessian_eq_principalValue
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.newtonianHessian_sub_eq_principalValue
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.exists_eLpNorm_newtonianHessian_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.exists_eLpNorm_newtonianHessian_sub_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.strainRateApply_axis_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.velocity_partial_eq_hessians
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.strain_diagonal_eq_hessians
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.strain_cyclic_eq_hessians
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.strain_diagonal_eq_principalValue
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.strain_cyclic_eq_principalValue
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.exists_eLpNorm_strain_entry_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.strainOperator_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.continuous_strainOperator
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.norm_linearMap_le_sum_axes
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.norm_strainOperator_le_sum_entries
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.exists_eLpNorm_strainOperator_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.memLp_strainOperator
#print axioms EulerComparatorRecovery.iteratedFDeriv_memLp_of_curl_compact
#print axioms EulerComparatorRecovery.smoothL2Field_of_curl_compact
#print axioms EulerOrdinarySobolev.pressureField_mem_gradient
#print axioms EulerMeanPressure.gradientSpace_radial_potential
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.pressurePotential_spec
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.projectedNavierStokesRhs_field
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.laplacianField_mem_solenoidal
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.projectedNavierStokesRhs_mem_solenoidal
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.divergence_projectedNavierStokesRhs_eq_zero
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceViscousEnergy.h3_projectedProduction_add_dissipation_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.hasCompactSupport_vectorCurl_velocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.smoothVelocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.memLp_iteratedFDeriv_velocity
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.smoothVelocity_mem_solenoidal
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.spatialBKMIntegrand_eq_vorticityNorm
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.norm_fderiv_velocity_le_spatialBKMIntegrand
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceBiotSavart.h3_projectedProduction_velocity_le
#print axioms NavierStokesR3.HarmonicTestFunctionals.eq_zero_of_compact_harmonic
#print axioms NavierStokesR3.PressureFluxIdentity.pressure_flux_eq_of_gradient_identification
#print axioms NavierStokesR3.PressureFlux.exists_uniform_canonicalCutoffFlux_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpacePressureRecovery.contDiff_velocityTangent
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpacePressureRecovery.temporalDerivative_velocityTangent
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpacePressureRecovery.spatialDivergence_velocityTangent
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpacePressureRecovery.navierStokesResidual_velocityTangent_one
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpacePressureRecovery.integral_pressureField_mul
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpacePressureRecovery.integral_pressureField_mul_laplacian
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpacePressureRecovery.integral_pressureField_mul_eq_rieszPair
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpacePressureRecovery.memLp_three_field
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpacePressureRecovery.integral_pressurePotential_flux_eq_rieszPair
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpacePressureRecovery.integral_pressurePotential_flux_eq_canonicalCutoffFlux
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpacePressureRecovery.exists_uniform_cutoff_pressureFlux_bound
#print axioms NavierStokesR3.RieszTestOperators.rieszTest_selfAdjoint
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.kernel_eq_integral
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.measurable_kernel
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.norm_kernel_le
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.riesz_double_commutator_eq_integral
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.radial_secondDifference_le
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.memLp_radialMajorant
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.lpNorm_radialMajorant
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.norm_kernel_le_radialMajorant
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.kernel_section_memLp
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.integrable_kernel_smul
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.norm_integral_kernel_smul_le
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.norm_riesz_double_commutator_le
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.localization_defect_eq_double_commutator
#print axioms Mettapedia.Analysis.RieszDoubleCommutator.norm_localization_defect_le
#print axioms NavierStokesR3.Comparison.tensorDiff_norm_integral_le
#print axioms NavierStokesR3.H3Comparison.difference_rate_le
#print axioms NavierStokesR3.H3Comparison.integral_inner_pressureGradient_zero
#print axioms NavierStokesR3.H3Comparison.StrongSolutionOnIcc.pressureGradient_memLp
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureLocalizationDifference.localizationDefect_eq_second_sub_first
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureLocalizationDifference.firstDifference_eq_integral
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureLocalizationDifference.secondDifference_eq_integral
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureLocalizationDifference.norm_secondDifference_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureLocalizationDifference.norm_firstDifference_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureLocalizationDifference.velocityTensor_integrable_and_lpNorm_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureLocalizationDifference.norm_secondDifference_velocityTensor_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureLocalizationDifference.localizationDefect_velocityTensor
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureLocalizationDifference.norm_localizationDefect_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceUnforcedEnergy.energy_rate_nonpos
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceUnforcedEnergy.l2Sq_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceUnforcedEnergy.classical_memLp_and_l2Sq_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceUnforcedEnergy.norm_secondPressureDifference_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceUnforcedEnergy.norm_sum_secondPressureDifference_le_initial
#print axioms EulerOrdinarySobolev.vorticityField_apply
#print axioms EulerOrdinarySobolev.solenoidalField_toLp
#print axioms EulerOrdinarySobolev.solenoidalField_word
#print axioms EulerOrdinarySobolev.scalarProduct_directional
#print axioms NavierStokesR3.CompactEnergy.integral_mul_partial
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceStretchingFlux.stretching_field
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceStretchingFlux.fluxColumn_field
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceStretchingFlux.projectedColumn
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceStretchingFlux.projectedColumn_toLp
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceStretchingFlux.projectedColumn_mem_gradient
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceStretchingFlux.receiver
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceStretchingFlux.receiver_field
#print axioms Mettapedia.FluidDynamics.NavierStokes.WholeSpaceStretchingFlux.pressure_contraction_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureHessianReceiver.hessianTest_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureHessianReceiver.integral_pressureHessian_mul_eq_rieszPair
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureHessianReceiver.partial_partial_cutoff_mul
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureHessianReceiver.localizedReceiver_contDiff
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureHessianReceiver.localizedReceiver_compact
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureHessianReceiver.receiverTest
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureHessianReceiver.receiverTest_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureHessianReceiver.pressureWork_eq_rieszPair
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureHessianLocalization.weightedHessianTest_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureHessianLocalization.cutoffDerivativeTest_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureHessianLocalization.pressurePair_localized_hessian_eq
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureHessianLocalization.weightedHessianTest_square_relations
#print axioms Mettapedia.FluidDynamics.NavierStokes.PressureHessianLocalization.norm_sum_secondDifference_hessian_le_initial
#print axioms ProbabilityTheory.covarianceBilin_apply_pi
#print axioms ProbabilityTheory.covarianceBilin_self_nonneg
#print axioms ProbabilityTheory.variance_le_expectation_sq
#print axioms MeasureTheory.integral_convolution
#print axioms EulerLpParameterIntegral.integral_memLp_and_bound
#print axioms EulerLpBochnerRealization.field_memLp
#print axioms EulerOrdinaryMollifier.translation_increment
#print axioms EulerWholeSpaceGaussian.norm_sq_kernel_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.displacementMeasure_isProbability
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.displacementMeasure_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.memLp_displacement
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.integral_displacement_eq_average
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.average_component
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.stress_eq_covariance
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.stressBilin_apply
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.stress_quadratic_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.stress_symmetric
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.stress_diagonal_nonneg
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.average_memLp_and_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.average_eq_convolution
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.average_integrable
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.integral_average
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.stress_trace
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.stress_trace_integrable
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.integral_stress_trace
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.integral_stress_trace_le_energy
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.stress_trace_le_increment
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.displacement_secondMoment
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.translation_increment_ae
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.integral_translation_increment_sq_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.gaussian_increment_integrable
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.integral_stress_trace_le_derivative_energy
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.integral_stress_trace_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.fluctuation_memLp
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.stress_eq_integral_fluctuation
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.stress_trace_eq_integral_fluctuation
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.contraction_eq_integral_quadratic
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.norm_contraction_le_trace
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.contraction_le_trace_of_quadratic_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.contraction_selfAdjointPart
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.norm_contraction_le_selfAdjointPart_trace
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.stress_integrable
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.contraction_aestronglyMeasurable
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.contraction_integrable
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.norm_integral_contraction_le
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.stressAction_integrable
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.projectedStressAction_integrable
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.stressAction_eq_strain
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.norm_stressAction_le_trace
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.norm_stressAction_le_of_strain_bound
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.norm_projectedStressAction_le_energy
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.norm_projectedStressAction_le_derivative_energy
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.norm_projectedStressAction_le_initial
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.kernel_eq_heatKernel
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.fourier_kernel
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.average_fourierChar
#print axioms Mettapedia.FluidDynamics.NavierStokes.GaussianHeatCovariance.mFourierCoeff_periodized_kernel
