import MainTheorem
import MinimalSupport
import NoCancellation
import StarNormalForm
import GraphMatchingBridge
import Mettapedia.Combinatorics.Matching

/-! # Axiom audit
Every top-level conditional theorem, with its dependency cone printed. -/

#print axioms MainTheorem.krenn_gu_of_three_regularity
#print axioms MainTheorem.no_ghz_above_four
#print axioms MainTheorem.krenn_gu_of_liveDegree
#print axioms MinimalSupport.krenn_gu_of_minimalLiveDegree
#print axioms NoCancellation.krenn_gu_of_mixedSurvives
#print axioms NoCancellation.krenn_gu_of_certifiedPartition
#print axioms NoCancellation.krenn_gu_of_colourDegreeOne
#print axioms CycleCoordinates.no_three_regular_uniform
#print axioms MatchingParity.Pairing.toSubgraph_isPerfectMatching
#print axioms MatchingParity.Pairing.toSubgraph_ofPerfectMatching_adj
#print axioms MatchingParity.Pairing.exchange_toSubgraph_isPerfectMatching

/-! Reusable theory promoted to MeTTapedia. -/
#print axioms MatchingSum.pmSum_expand
#print axioms MatchingCrossing.exists_crossing
#print axioms MatchingCrossing.pmSum_four_two_terms
#print axioms MatchingCrossing.pmSum_six_three_dead
#print axioms MatchingRestriction.matchable_split_of_invariant
#print axioms MatchingHall.pmSum_eq_zero_of_internal_dead
#print axioms MatchingNonvanishing.pmSum_ne_zero_of_unique_matching
#print axioms MatchingNonvanishing.pmSum_ne_zero_of_two_matchings
#print axioms MatchingNonvanishing.certified_forced_pair
#print axioms MatchingParity.Pairing.kempeExchange_isPerfectMatching
#print axioms MatchingLoopless.amplitude_ignore_loops
#print axioms MatchingSupport.liveNeighbours_deloop
#print axioms MatchingBlockRank.block_split
#print axioms MatchingFourVertices.pairing_four_cases
#print axioms MatchingFourVertices.zero_edge_of_pairing_four_ne
#print axioms MixedColouring.perm_of_mixColouring
#print axioms MixedColouring.mixColouring_of_disconnected
#print axioms MixedColouring.exists_mixed_model
#print axioms CycleCoordinates.exists_mixed

/-! Receiving-colour detour compatibility. -/
#print axioms NoCancellation.certified_quad_cross_relation
#print axioms StarNormalForm.certified_detour_cross_relation
#print axioms StarNormalForm.detour_port_reuse_forces_size_one_circuits
#print axioms StarNormalForm.thirdColour_thirdColour
#print axioms StarNormalForm.exists_detourPorts
#print axioms StarNormalForm.same_side_reuse_size_one_circuit
#print axioms StarNormalForm.crossed_one_port_dichotomy
#print axioms StarNormalForm.double_certified_detour_overlap_normal_form
#print axioms StarNormalForm.receiving_pair_normal_form
#print axioms StarNormalForm.excess_site_receiving_pair_normal_form
#print axioms MatchingCrossing.exists_dead_pair_detour_on
#print axioms MatchingCrossing.four_le_card_of_dead_pair_detour
#print axioms MatchingCrossing.dead_pair_detour_card_two
#print axioms MatchingCrossing.dead_pair_detour_card_four
#print axioms StarNormalForm.disjoint_detours_force_outward_routes
#print axioms StarNormalForm.eight_le_card_of_disjoint_detours
#print axioms StarNormalForm.disjoint_detours_card_eight_exhaustion
#print axioms StarNormalForm.receiving_pair_routed_normal_form
#print axioms StarNormalForm.excess_site_receiving_pair_routed
#print axioms StarNormalForm.CrossedOnePortCap.r_ne_q
#print axioms StarNormalForm.exists_crossedCapTails
#print axioms StarNormalForm.six_le_card_of_crossedCapTails
#print axioms StarNormalForm.crossedCapTails_card_six
#print axioms StarNormalForm.seven_le_card_of_distinct_tails
#print axioms StarNormalForm.crossedCapTails_card_eight
#print axioms StarNormalForm.disjoint_detours_octet_synchronized
#print axioms StarNormalForm.exists_disjointDetourOctet
#print axioms StarNormalForm.pair_overlap_trichotomy
#print axioms StarNormalForm.outward_route_overlap
#print axioms StarNormalForm.outward_route_overlap_sized
#print axioms StarNormalForm.ten_le_card_of_two_beyond_octet
#print axioms StarNormalForm.routed_pair_dead_with_live_arms
#print axioms StarNormalForm.certificate_does_not_transfer_upward
#print axioms StarNormalForm.routing_iteration_obstruction
#print axioms StarNormalForm.excess_site_routing_network
