import Mettapedia.GraphTheory.FourColor.ClassicalCertificateReductionMetadataDataChunk22
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateReductionMetadataCatalogue

namespace Mettapedia.GraphTheory.FourColor

namespace ClassicalCertificateReductionMetadataCheck

open ClassicalCertificateReductionMetadataCatalogue
open ClassicalCertificateReductionMetadataCatalogue.Certificate
open ClassicalCertificateReductionMetadataData

set_option maxRecDepth 1000000
set_option maxHeartbeats 100000000

theorem classicalReductionMetadataBlock091_checker :
    localBlockBoolean classicalReductionMetadataChunk22 3 = true := by
  rfl

end ClassicalCertificateReductionMetadataCheck

end Mettapedia.GraphTheory.FourColor
