import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitProductData
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup000
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup001
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup002
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup003
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup004
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup005
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup006
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup007
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup008
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup009
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup010
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup011
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup012
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup013
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup014
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup015
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup016
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup017
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup018
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup019
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup020
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup021
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup022
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup023
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroup024

namespace Mettapedia.GraphTheory.FourColor

namespace ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagData

open ClassicalCertificateTraceResponseRankSummaryDag
open ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagGroups

set_option maxRecDepth 1000000
set_option maxHeartbeats 200000000

/-- Shared rank-independent product states for every positive orbit layer of
catalogue configuration `cf020`. -/
def twentiethCatalogueOrbitRankSummaryDag :
    ClassicalCertificateTraceResponseRankSummaryDag.Code where
  nodeCount := 102140
  nodeGroups := #[twentiethCatalogueOrbitRankSummaryDagGroup000, twentiethCatalogueOrbitRankSummaryDagGroup001, twentiethCatalogueOrbitRankSummaryDagGroup002, twentiethCatalogueOrbitRankSummaryDagGroup003, twentiethCatalogueOrbitRankSummaryDagGroup004, twentiethCatalogueOrbitRankSummaryDagGroup005, twentiethCatalogueOrbitRankSummaryDagGroup006, twentiethCatalogueOrbitRankSummaryDagGroup007, twentiethCatalogueOrbitRankSummaryDagGroup008, twentiethCatalogueOrbitRankSummaryDagGroup009, twentiethCatalogueOrbitRankSummaryDagGroup010, twentiethCatalogueOrbitRankSummaryDagGroup011, twentiethCatalogueOrbitRankSummaryDagGroup012, twentiethCatalogueOrbitRankSummaryDagGroup013, twentiethCatalogueOrbitRankSummaryDagGroup014, twentiethCatalogueOrbitRankSummaryDagGroup015, twentiethCatalogueOrbitRankSummaryDagGroup016, twentiethCatalogueOrbitRankSummaryDagGroup017, twentiethCatalogueOrbitRankSummaryDagGroup018, twentiethCatalogueOrbitRankSummaryDagGroup019, twentiethCatalogueOrbitRankSummaryDagGroup020, twentiethCatalogueOrbitRankSummaryDagGroup021, twentiethCatalogueOrbitRankSummaryDagGroup022, twentiethCatalogueOrbitRankSummaryDagGroup023, twentiethCatalogueOrbitRankSummaryDagGroup024]
  layerRoots := [0, 56669, 75598, 89018, 94868, 98219, 99830, 101269, 101671, 101935, 102139]

end ClassicalCertificateCatalogueTwentyOrbitRankSummaryDagData

end Mettapedia.GraphTheory.FourColor
