import Mettapedia.GraphTheory.FourColor.ClassicalCertificateReductionMetadataDataChunk28
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateContractValidityDataChunk28
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateContractValidityCatalogue

namespace Mettapedia.GraphTheory.FourColor

namespace ClassicalCertificateContractValidityCheck

open ClassicalCertificateContractValidityCatalogue.Catalogue
open ClassicalCertificateContractValidityData
open ClassicalCertificateReductionMetadataData

set_option maxRecDepth 1000000
set_option maxHeartbeats 100000000

theorem classicalContractValidityBlock114_checker :
    localBlockBoolean classicalReductionMetadataChunk28
      classicalContractValidityChunk28 2 = true := by
  rfl

end ClassicalCertificateContractValidityCheck

end Mettapedia.GraphTheory.FourColor
