import Mettapedia.GraphTheory.FourColor.ClassicalCertificateReductionMetadataDataChunk14
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateContractValidityDataChunk14
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateContractValidityCatalogue

namespace Mettapedia.GraphTheory.FourColor

namespace ClassicalCertificateContractValidityCheck

open ClassicalCertificateContractValidityCatalogue.Catalogue
open ClassicalCertificateContractValidityData
open ClassicalCertificateReductionMetadataData

set_option maxRecDepth 1000000
set_option maxHeartbeats 100000000

theorem classicalContractValidityBlock058_checker :
    localBlockBoolean classicalReductionMetadataChunk14
      classicalContractValidityChunk14 2 = true := by
  rfl

end ClassicalCertificateContractValidityCheck

end Mettapedia.GraphTheory.FourColor
