import Mettapedia.GraphTheory.FourColor.ClassicalCertificateReductionMetadataDataChunk35
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateReductionMetadataCatalogue

namespace Mettapedia.GraphTheory.FourColor

namespace ClassicalCertificateReductionMetadataCheck

open ClassicalCertificateReductionMetadataCatalogue
open ClassicalCertificateReductionMetadataCatalogue.Certificate
open ClassicalCertificateReductionMetadataData

set_option maxRecDepth 1000000
set_option maxHeartbeats 100000000

theorem classicalReductionMetadataBlock143_checker :
    localBlockBoolean classicalReductionMetadataChunk35 3 = true := by
  rfl

end ClassicalCertificateReductionMetadataCheck

end Mettapedia.GraphTheory.FourColor
