import Mettapedia.GraphTheory.FourColor.ClassicalCertificateReductionMetadataDataChunk38
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateContractValidityDataChunk38
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateContractValidityCatalogue

namespace Mettapedia.GraphTheory.FourColor

namespace ClassicalCertificateContractValidityCheck

open ClassicalCertificateContractValidityCatalogue.Catalogue
open ClassicalCertificateContractValidityData
open ClassicalCertificateReductionMetadataData

set_option maxRecDepth 1000000
set_option maxHeartbeats 100000000

theorem classicalContractValidityBlock153_checker :
    localBlockBoolean classicalReductionMetadataChunk38
      classicalContractValidityChunk38 1 = true := by
  rfl

end ClassicalCertificateContractValidityCheck

end Mettapedia.GraphTheory.FourColor
