import Mettapedia.GraphTheory.FourColor.ClassicalCertificateReductionMetadataDataChunk34
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateContractValidityDataChunk34
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateContractValidityCatalogue

namespace Mettapedia.GraphTheory.FourColor

namespace ClassicalCertificateContractValidityCheck

open ClassicalCertificateContractValidityCatalogue.Catalogue
open ClassicalCertificateContractValidityData
open ClassicalCertificateReductionMetadataData

set_option maxRecDepth 1000000
set_option maxHeartbeats 100000000

theorem classicalContractValidityBlock139_checker :
    localBlockBoolean classicalReductionMetadataChunk34
      classicalContractValidityChunk34 3 = true := by
  rfl

end ClassicalCertificateContractValidityCheck

end Mettapedia.GraphTheory.FourColor
