import Mettapedia.GraphTheory.FourColor.ClassicalCertificateReductionMetadataDataChunk00
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateContractValidityDataChunk00
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateContractValidityCatalogue

namespace Mettapedia.GraphTheory.FourColor

namespace ClassicalCertificateContractValidityCheck

open ClassicalCertificateContractValidityCatalogue.Catalogue
open ClassicalCertificateContractValidityData
open ClassicalCertificateReductionMetadataData

set_option maxRecDepth 1000000
set_option maxHeartbeats 100000000

theorem classicalContractValidityBlock000_checker :
    localBlockBoolean classicalReductionMetadataChunk00
      classicalContractValidityChunk00 0 = true := by
  rfl

end ClassicalCertificateContractValidityCheck

end Mettapedia.GraphTheory.FourColor
