import Mettapedia.GraphTheory.FourColor.ClassicalCertificateReductionMetadataDataChunk29
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateContractValidityDataChunk29
import Mettapedia.GraphTheory.FourColor.ClassicalCertificateContractValidityCatalogue

namespace Mettapedia.GraphTheory.FourColor

namespace ClassicalCertificateContractValidityCheck

open ClassicalCertificateContractValidityCatalogue.Catalogue
open ClassicalCertificateContractValidityData
open ClassicalCertificateReductionMetadataData

set_option maxRecDepth 1000000
set_option maxHeartbeats 100000000

theorem classicalContractValidityBlock119_checker :
    localBlockBoolean classicalReductionMetadataChunk29
      classicalContractValidityChunk29 3 = true := by
  rfl

end ClassicalCertificateContractValidityCheck

end Mettapedia.GraphTheory.FourColor
