import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block3Chunk0ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block3Chunk1ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block3Chunk2ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block3Chunk3ComponentCertificate

namespace Mettapedia.GraphTheory.FourColor

/-!
# Goertzel Lemma 8.18: second large `TTT` fiber, block 3

This module aggregates four 16-row component-certificate chunks for the fourth
64-row part of the second size-512 fixed-input fiber of the `TTT`/`mode09`
representative target.
-/

namespace GoertzelLemma818TripleTauLargeFiber8Block3ComponentCertificate

open GoertzelLemma818TripleTauLargeFiber8Block3Chunk0ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber8Block3Chunk1ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber8Block3Chunk2ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber8Block3Chunk3ComponentCertificate

def tttLargeFiber8Block3ComponentCertificateAudit : Bool :=
  tttLargeFiber8Block3Chunk0ComponentCertificateAudit &&
    tttLargeFiber8Block3Chunk1ComponentCertificateAudit &&
    tttLargeFiber8Block3Chunk2ComponentCertificateAudit &&
    tttLargeFiber8Block3Chunk3ComponentCertificateAudit

theorem tttLargeFiber8Block3ComponentCertificateAudit_ok :
    tttLargeFiber8Block3ComponentCertificateAudit = true := by
  simp [tttLargeFiber8Block3ComponentCertificateAudit,
    tttLargeFiber8Block3Chunk0ComponentCertificateAudit_ok,
    tttLargeFiber8Block3Chunk1ComponentCertificateAudit_ok,
    tttLargeFiber8Block3Chunk2ComponentCertificateAudit_ok,
    tttLargeFiber8Block3Chunk3ComponentCertificateAudit_ok]

end GoertzelLemma818TripleTauLargeFiber8Block3ComponentCertificate

end Mettapedia.GraphTheory.FourColor
