import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber4Block6Chunk0ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber4Block6Chunk1ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber4Block6Chunk2ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber4Block6Chunk3ComponentCertificate

namespace Mettapedia.GraphTheory.FourColor

/-!
# Goertzel Lemma 8.18: first large `TTT` fiber, block 6

This module aggregates four 16-row component-certificate chunks for one
64-row part of the first size-512 fixed-input fiber of the `TTT`/`mode09`
representative target.
-/

namespace GoertzelLemma818TripleTauLargeFiber4Block6ComponentCertificate

open GoertzelLemma818TripleTauLargeFiber4Block6Chunk0ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber4Block6Chunk1ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber4Block6Chunk2ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber4Block6Chunk3ComponentCertificate

def tttLargeFiber4Block6ComponentCertificateAudit : Bool :=
  tttLargeFiber4Block6Chunk0ComponentCertificateAudit &&
    tttLargeFiber4Block6Chunk1ComponentCertificateAudit &&
    tttLargeFiber4Block6Chunk2ComponentCertificateAudit &&
    tttLargeFiber4Block6Chunk3ComponentCertificateAudit

theorem tttLargeFiber4Block6ComponentCertificateAudit_ok :
    tttLargeFiber4Block6ComponentCertificateAudit = true := by
  simp [tttLargeFiber4Block6ComponentCertificateAudit,
    tttLargeFiber4Block6Chunk0ComponentCertificateAudit_ok,
    tttLargeFiber4Block6Chunk1ComponentCertificateAudit_ok,
    tttLargeFiber4Block6Chunk2ComponentCertificateAudit_ok,
    tttLargeFiber4Block6Chunk3ComponentCertificateAudit_ok]

end GoertzelLemma818TripleTauLargeFiber4Block6ComponentCertificate

end Mettapedia.GraphTheory.FourColor
