import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block0Chunk0ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block0Chunk1ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block0Chunk2ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block0Chunk3ComponentCertificate

namespace Mettapedia.GraphTheory.FourColor

/-!
# Goertzel Lemma 8.18: second large `TTT` fiber, block 0

This module aggregates four 16-row component-certificate chunks for the first
64-row part of the second size-512 fixed-input fiber of the `TTT`/`mode09`
representative target.
-/

namespace GoertzelLemma818TripleTauLargeFiber8Block0ComponentCertificate

open GoertzelLemma818TripleTauLargeFiber8Block0Chunk0ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber8Block0Chunk1ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber8Block0Chunk2ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber8Block0Chunk3ComponentCertificate

def tttLargeFiber8Block0ComponentCertificateAudit : Bool :=
  tttLargeFiber8Block0Chunk0ComponentCertificateAudit &&
    tttLargeFiber8Block0Chunk1ComponentCertificateAudit &&
    tttLargeFiber8Block0Chunk2ComponentCertificateAudit &&
    tttLargeFiber8Block0Chunk3ComponentCertificateAudit

theorem tttLargeFiber8Block0ComponentCertificateAudit_ok :
    tttLargeFiber8Block0ComponentCertificateAudit = true := by
  simp [tttLargeFiber8Block0ComponentCertificateAudit,
    tttLargeFiber8Block0Chunk0ComponentCertificateAudit_ok,
    tttLargeFiber8Block0Chunk1ComponentCertificateAudit_ok,
    tttLargeFiber8Block0Chunk2ComponentCertificateAudit_ok,
    tttLargeFiber8Block0Chunk3ComponentCertificateAudit_ok]

end GoertzelLemma818TripleTauLargeFiber8Block0ComponentCertificate

end Mettapedia.GraphTheory.FourColor
