import Mettapedia.GraphTheory.FourColor.GoertzelV24ResidualExchange
import Mettapedia.GraphTheory.FourColor.GoertzelV24TaitMatchingPair

/-!
# The alternating component generated by two perfect matchings

The equivalence relation generated by the two partner involutions partitions
the vertices into alternating components.  Starting at a vertex where the
matchings disagree, its component is closed under both matchings, every vertex
in it is another disagreement, and it has at least four vertices.

In a cubic Tait counterexample two supported perfect matchings share an edge.
Consequently a disagreement component is proper: the endpoints of a shared
edge lie outside it.  This is the exact generic locality available before any
planar or wall geometry is used; no bounded diameter or bounded cardinality is
asserted.
-/

namespace Mettapedia.GraphTheory.FourColor

namespace GoertzelV24AlternatingMatchingComponent

open GoertzelV24TaitMatchingPair
open GoertzelV24ResidualExchange
open MatchingParity
open SimpleGraph
open scoped symmDiff

noncomputable section

variable {V : Type*} [Fintype V] [DecidableEq V]

/-- One step along either of two partner involutions. -/
def AlternatingStep (sigma tau : Pairing V) (left right : V) : Prop :=
  right = sigma.partner left ∨ right = tau.partner left

/-- The vertex set of the alternating component generated by `root`. -/
noncomputable def alternatingComponent
    (sigma tau : Pairing V) (root : V) : Finset V := by
  classical
  exact Finset.univ.filter fun vertex =>
    Relation.EqvGen (AlternatingStep sigma tau) root vertex

@[simp]
theorem mem_alternatingComponent_iff
    (sigma tau : Pairing V) (root vertex : V) :
    vertex ∈ alternatingComponent sigma tau root ↔
      Relation.EqvGen (AlternatingStep sigma tau) root vertex := by
  classical
  simp [alternatingComponent]

@[simp]
theorem root_mem_alternatingComponent
    (sigma tau : Pairing V) (root : V) :
    root ∈ alternatingComponent sigma tau root := by
  rw [mem_alternatingComponent_iff]
  exact Relation.EqvGen.refl _

/-- Disagreement is constant along an alternating component. -/
theorem disagreement_iff_of_eqvGen
    (sigma tau : Pairing V) {left right : V}
    (hreach : Relation.EqvGen (AlternatingStep sigma tau) left right) :
    sigma.partner left ≠ tau.partner left ↔
      sigma.partner right ≠ tau.partner right := by
  induction hreach with
  | rel left right hstep =>
      rcases hstep with hstep | hstep
      · subst right
        constructor
        · exact disagree_closed_left sigma tau
        · intro h
          have hprop :=
            disagree_closed_left sigma tau
              (x := sigma.partner left) h
          simpa only [sigma.partner_partner] using hprop
      · subst right
        constructor
        · exact disagree_closed_right sigma tau
        · intro h
          have hprop :=
            disagree_closed_right sigma tau
              (x := tau.partner left) h
          simpa only [tau.partner_partner] using hprop
  | refl => exact Iff.rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ihLeft ihRight => exact ihLeft.trans ihRight

/-- A component rooted at a disagreement contains only disagreements. -/
theorem disagreement_of_mem_alternatingComponent
    (sigma tau : Pairing V) {root vertex : V}
    (hroot : sigma.partner root ≠ tau.partner root)
    (hvertex : vertex ∈ alternatingComponent sigma tau root) :
    sigma.partner vertex ≠ tau.partner vertex := by
  rw [mem_alternatingComponent_iff] at hvertex
  exact (disagreement_iff_of_eqvGen sigma tau hvertex).mp hroot

/-- The generated component is closed under the first matching. -/
theorem alternatingComponent_closed_first
    (sigma tau : Pairing V) (root : V) :
    ∀ vertex ∈ alternatingComponent sigma tau root,
      sigma.partner vertex ∈ alternatingComponent sigma tau root := by
  intro vertex hvertex
  rw [mem_alternatingComponent_iff] at hvertex ⊢
  exact Relation.EqvGen.trans root vertex (sigma.partner vertex)
    hvertex (Relation.EqvGen.rel vertex _ (Or.inl rfl))

/-- The generated component is closed under the second matching. -/
theorem alternatingComponent_closed_second
    (sigma tau : Pairing V) (root : V) :
    ∀ vertex ∈ alternatingComponent sigma tau root,
      tau.partner vertex ∈ alternatingComponent sigma tau root := by
  intro vertex hvertex
  rw [mem_alternatingComponent_iff] at hvertex ⊢
  exact Relation.EqvGen.trans root vertex (tau.partner vertex)
    hvertex (Relation.EqvGen.rel vertex _ (Or.inr rfl))

/-- A nontrivial alternating component has at least four vertices. -/
theorem four_le_card_alternatingComponent
    (sigma tau : Pairing V) {root : V}
    (hroot : sigma.partner root ≠ tau.partner root) :
    4 ≤ (alternatingComponent sigma tau root).card := by
  exact four_le_card_of_closed_disagree sigma tau
    (alternatingComponent_closed_first sigma tau root)
    (alternatingComponent_closed_second sigma tau root)
    (root_mem_alternatingComponent sigma tau root) hroot

/-- Any vertex where the pairings agree lies outside a component rooted at a
disagreement. -/
theorem not_mem_alternatingComponent_of_agreement
    (sigma tau : Pairing V) {root vertex : V}
    (hroot : sigma.partner root ≠ tau.partner root)
    (hvertex : sigma.partner vertex = tau.partner vertex) :
    vertex ∉ alternatingComponent sigma tau root := by
  intro hmem
  exact disagreement_of_mem_alternatingComponent sigma tau hroot hmem hvertex

/-! ## The graph carried by a matching disagreement -/

/-- The symmetric-difference graph of two pairings.  Its non-isolated
components are the alternating cycles on which the pairings disagree. -/
def alternatingGraph (sigma tau : Pairing V) : SimpleGraph V :=
  pairingGraph sigma ∆ pairingGraph tau

@[simp]
theorem alternatingGraph_adj
    (sigma tau : Pairing V) {left right : V} :
    (alternatingGraph sigma tau).Adj left right ↔
      (sigma.partner left = right ∧ tau.partner left ≠ right) ∨
      (tau.partner left = right ∧ sigma.partner left ≠ right) := by
  simp [alternatingGraph, symmDiff_def]

/-- A symmetric difference of two pairings is a disjoint union of simple
cycles and isolated vertices. -/
theorem alternatingGraph_isCycles (sigma tau : Pairing V) :
    (alternatingGraph sigma tau).IsCycles := by
  let hSigma : sigma.SupportedBy (⊤ : SimpleGraph V) := by
    intro vertex
    simpa using (sigma.partner_ne vertex).symm
  let hTau : tau.SupportedBy (⊤ : SimpleGraph V) := by
    intro vertex
    simpa using (tau.partner_ne vertex).symm
  have h := SimpleGraph.Subgraph.IsPerfectMatching.symmDiff_isCycles
    (sigma.toSubgraph_isPerfectMatching hSigma)
    (tau.toSubgraph_isPerfectMatching hTau)
  have hSigmaGraph :
      (sigma.toSubgraph hSigma).spanningCoe = pairingGraph sigma := by
    ext left right
    simp [pairingGraph]
  have hTauGraph :
      (tau.toSubgraph hTau).spanningCoe = pairingGraph tau := by
    ext left right
    simp [pairingGraph]
  simpa [alternatingGraph, hSigmaGraph, hTauGraph] using h

/-- If both pairings use ambient edges, so does their alternating graph. -/
theorem alternatingGraph_le
    {G : SimpleGraph V} (sigma tau : Pairing V)
    (hSigma : sigma.SupportedBy G) (hTau : tau.SupportedBy G) :
    alternatingGraph sigma tau ≤ G := by
  intro left right hadj
  rw [alternatingGraph_adj] at hadj
  rcases hadj with ⟨hSigmaEdge, _⟩ | ⟨hTauEdge, _⟩
  · exact hSigmaEdge ▸ hSigma left
  · exact hTauEdge ▸ hTau left

/-- At a disagreement, the second pairing edge belongs to the alternating
graph. -/
theorem alternatingGraph_adj_second
    (sigma tau : Pairing V) {vertex : V}
    (hvertex : sigma.partner vertex ≠ tau.partner vertex) :
    (alternatingGraph sigma tau).Adj vertex (tau.partner vertex) := by
  rw [alternatingGraph_adj]
  exact Or.inr ⟨rfl, hvertex⟩

/-- Every generated alternating step from a disagreement is a path step in
the matching symmetric-difference graph. -/
theorem alternatingGraph_reachable_of_eqvGen
    (sigma tau : Pairing V) {left right : V}
    (hleft : sigma.partner left ≠ tau.partner left)
    (hreach : Relation.EqvGen (AlternatingStep sigma tau) left right) :
    (alternatingGraph sigma tau).Reachable left right := by
  induction hreach with
  | rel left right hstep =>
      rcases hstep with hstep | hstep
      · subst right
        have hadj :
            (alternatingGraph sigma tau).Adj left
              (sigma.partner left) := by
          rw [alternatingGraph_adj]
          exact Or.inl ⟨rfl, hleft.symm⟩
        exact hadj.reachable
      · subst right
        exact (alternatingGraph_adj_second sigma tau hleft).reachable
  | refl => exact SimpleGraph.Reachable.rfl
  | @symm left right hreach ih =>
      have hleft' : sigma.partner left ≠ tau.partner left :=
        (disagreement_iff_of_eqvGen sigma tau hreach).mpr hleft
      exact (ih hleft').symm
  | @trans left middle right hleftMiddle hmiddleRight ihLeft ihRight =>
      have hmiddle : sigma.partner middle ≠ tau.partner middle :=
        (disagreement_iff_of_eqvGen sigma tau hleftMiddle).mp hleft
      exact (ihLeft hleft).trans (ihRight hmiddle)

/-- Conversely, every path in the alternating graph is generated by the two
partner involutions. -/
theorem eqvGen_of_alternatingGraph_reachable
    (sigma tau : Pairing V) {left right : V}
    (hreach : (alternatingGraph sigma tau).Reachable left right) :
    Relation.EqvGen (AlternatingStep sigma tau) left right := by
  rw [SimpleGraph.reachable_iff_reflTransGen] at hreach
  induction hreach with
  | refl => exact Relation.EqvGen.refl _
  | @tail middle right hprefix hadj ih =>
      rw [alternatingGraph_adj] at hadj
      have hstep : AlternatingStep sigma tau middle right := by
        rcases hadj with ⟨hSigmaEdge, _⟩ | ⟨hTauEdge, _⟩
        · exact Or.inl hSigmaEdge.symm
        · exact Or.inr hTauEdge.symm
      exact Relation.EqvGen.trans _ _ _ ih
        (Relation.EqvGen.rel _ _ hstep)

/-- For a disagreement root, the previously defined algebraic component is
exactly the connected component of the matching symmetric-difference graph. -/
theorem mem_alternatingComponent_iff_mem_connectedComponent
    (sigma tau : Pairing V) {root vertex : V}
    (hroot : sigma.partner root ≠ tau.partner root) :
    vertex ∈ alternatingComponent sigma tau root ↔
      vertex ∈ (alternatingGraph sigma tau).connectedComponentMk root := by
  change vertex ∈ alternatingComponent sigma tau root ↔
    vertex ∈
      ((alternatingGraph sigma tau).connectedComponentMk root).supp
  rw [mem_alternatingComponent_iff,
    SimpleGraph.ConnectedComponent.mem_supp_iff]
  constructor
  · intro hreach
    exact (SimpleGraph.ConnectedComponent.sound
      (alternatingGraph_reachable_of_eqvGen sigma tau hroot hreach)).symm
  · intro hcomponent
    exact eqvGen_of_alternatingGraph_reachable sigma tau
      (SimpleGraph.ConnectedComponent.exact hcomponent).symm

/-- A disagreement component is not merely an abstract orbit: it is exactly
the vertex support of a simple alternating cycle in every ambient graph that
supports both pairings.  The cycle contains the second pairing edge at the
root, and every one of its edges belongs to the matching symmetric
difference. -/
theorem exists_ambient_alternatingCycle
    {G : SimpleGraph V} (sigma tau : Pairing V)
    (hSigma : sigma.SupportedBy G) (hTau : tau.SupportedBy G)
    {root : V} (hroot : sigma.partner root ≠ tau.partner root) :
    ∃ cycle : G.Walk root root,
      cycle.IsCycle ∧
        s(root, tau.partner root) ∈ cycle.edges ∧
        cycle.support.toFinset = alternatingComponent sigma tau root ∧
        ∀ edge ∈ cycle.edges,
          edge ∈ (alternatingGraph sigma tau).edgeSet := by
  letI : (alternatingGraph sigma tau).LocallyFinite :=
    fun _ => Fintype.ofFinite _
  let component :=
    (alternatingGraph sigma tau).connectedComponentMk root
  have hrootComponent : root ∈ component.supp :=
    SimpleGraph.ConnectedComponent.connectedComponentMk_mem
  have hrootAdj :
      (alternatingGraph sigma tau).Adj root (tau.partner root) :=
    alternatingGraph_adj_second sigma tau hroot
  have hrootNeighbor :
      ((alternatingGraph sigma tau).neighborSet root).Nonempty :=
    ⟨tau.partner root, hrootAdj⟩
  obtain ⟨componentCycle, hcycle, hcycleVerts⟩ :=
    SimpleGraph.IsCycles.exists_cycle_toSubgraph_verts_eq_connectedComponentSupp
      (alternatingGraph_isCycles sigma tau)
      (c := component) hrootComponent hrootNeighbor
  have hrootInCycle : root ∈ componentCycle.toSubgraph.verts := by
    rw [hcycleVerts]
    exact hrootComponent
  have hcentralInCycle :
      s(root, tau.partner root) ∈ componentCycle.edges := by
    apply componentCycle.adj_toSubgraph_iff_mem_edges.mp
    exact (hcycle.adj_toSubgraph_iff_of_isCycles
      (alternatingGraph_isCycles sigma tau) hrootInCycle _).2 hrootAdj
  have hsupport :
      componentCycle.support.toFinset =
        alternatingComponent sigma tau root := by
    ext vertex
    simp only [List.mem_toFinset]
    rw [← componentCycle.mem_verts_toSubgraph, hcycleVerts]
    exact (mem_alternatingComponent_iff_mem_connectedComponent
      sigma tau hroot).symm
  let ambientCycle :=
    componentCycle.mapLe (alternatingGraph_le sigma tau hSigma hTau)
  refine ⟨ambientCycle,
    hcycle.mapLe (alternatingGraph_le sigma tau hSigma hTau), ?_, ?_, ?_⟩
  · simpa only [ambientCycle, SimpleGraph.Walk.edges_mapLe_eq_edges]
      using hcentralInCycle
  · simpa only [ambientCycle, SimpleGraph.Walk.support_mapLe_eq_support]
      using hsupport
  · intro edge hedge
    apply componentCycle.edges_subset_edgeSet
    simpa only [ambientCycle, SimpleGraph.Walk.edges_mapLe_eq_edges]
      using hedge

variable {G : SimpleGraph V} [Fintype G.edgeSet] [G.LocallyFinite]

/-- In a cubic Tait counterexample, a disagreement component of two supported
matchings is proper.  A shared matching edge supplies two vertices outside the
component. -/
theorem exists_shared_edge_outside_alternatingComponent
    (hG : HasCubicIncidentEdgeTriples G)
    (hnot : ¬ TaitColorable G)
    (sigma tau : Pairing V)
    (hSigma : sigma.SupportedBy G) (hTau : tau.SupportedBy G)
    {root : V} (hroot : sigma.partner root ≠ tau.partner root) :
    ∃ vertex : V,
      sigma.partner vertex = tau.partner vertex ∧
      vertex ∉ alternatingComponent sigma tau root ∧
      sigma.partner vertex ∉ alternatingComponent sigma tau root := by
  obtain ⟨vertex, hagree⟩ :=
    exists_shared_edge_of_not_taitColorable
      hG hnot sigma tau hSigma hTau
  have hpartnerAgree :
      sigma.partner (sigma.partner vertex) =
        tau.partner (sigma.partner vertex) := by
    rw [sigma.partner_partner]
    have h := congrArg tau.partner hagree
    rw [tau.partner_partner] at h
    exact h.symm
  exact ⟨vertex, hagree,
    not_mem_alternatingComponent_of_agreement
      sigma tau hroot hagree,
    not_mem_alternatingComponent_of_agreement
      sigma tau hroot hpartnerAgree⟩

end

end GoertzelV24AlternatingMatchingComponent

end Mettapedia.GraphTheory.FourColor
