import Mettapedia.GraphTheory.FourColor.GoertzelV24TaitMatchingPair

/-!
# The alternating component generated by two perfect matchings

The equivalence relation generated by the two partner involutions partitions
the vertices into alternating components.  Starting at a vertex where the
matchings disagree, its component is closed under both matchings, every vertex
in it is another disagreement, and it has at least four vertices.

In a cubic Tait counterexample two supported perfect matchings share an edge.
Consequently a disagreement component is proper: the endpoints of a shared
edge lie outside it.  This is the exact generic locality available before any
planar or wall geometry is used; no bounded diameter or bounded cardinality is
asserted.
-/

namespace Mettapedia.GraphTheory.FourColor

namespace GoertzelV24AlternatingMatchingComponent

open GoertzelV24TaitMatchingPair
open MatchingParity
open SimpleGraph

noncomputable section

variable {V : Type*} [Fintype V] [DecidableEq V]

/-- One step along either of two partner involutions. -/
def AlternatingStep (sigma tau : Pairing V) (left right : V) : Prop :=
  right = sigma.partner left ∨ right = tau.partner left

/-- The vertex set of the alternating component generated by `root`. -/
noncomputable def alternatingComponent
    (sigma tau : Pairing V) (root : V) : Finset V := by
  classical
  exact Finset.univ.filter fun vertex =>
    Relation.EqvGen (AlternatingStep sigma tau) root vertex

@[simp]
theorem mem_alternatingComponent_iff
    (sigma tau : Pairing V) (root vertex : V) :
    vertex ∈ alternatingComponent sigma tau root ↔
      Relation.EqvGen (AlternatingStep sigma tau) root vertex := by
  classical
  simp [alternatingComponent]

@[simp]
theorem root_mem_alternatingComponent
    (sigma tau : Pairing V) (root : V) :
    root ∈ alternatingComponent sigma tau root := by
  rw [mem_alternatingComponent_iff]
  exact Relation.EqvGen.refl _

/-- Disagreement is constant along an alternating component. -/
theorem disagreement_iff_of_eqvGen
    (sigma tau : Pairing V) {left right : V}
    (hreach : Relation.EqvGen (AlternatingStep sigma tau) left right) :
    sigma.partner left ≠ tau.partner left ↔
      sigma.partner right ≠ tau.partner right := by
  induction hreach with
  | rel left right hstep =>
      rcases hstep with hstep | hstep
      · subst right
        constructor
        · exact disagree_closed_left sigma tau
        · intro h
          have hprop :=
            disagree_closed_left sigma tau
              (x := sigma.partner left) h
          simpa only [sigma.partner_partner] using hprop
      · subst right
        constructor
        · exact disagree_closed_right sigma tau
        · intro h
          have hprop :=
            disagree_closed_right sigma tau
              (x := tau.partner left) h
          simpa only [tau.partner_partner] using hprop
  | refl => exact Iff.rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ihLeft ihRight => exact ihLeft.trans ihRight

/-- A component rooted at a disagreement contains only disagreements. -/
theorem disagreement_of_mem_alternatingComponent
    (sigma tau : Pairing V) {root vertex : V}
    (hroot : sigma.partner root ≠ tau.partner root)
    (hvertex : vertex ∈ alternatingComponent sigma tau root) :
    sigma.partner vertex ≠ tau.partner vertex := by
  rw [mem_alternatingComponent_iff] at hvertex
  exact (disagreement_iff_of_eqvGen sigma tau hvertex).mp hroot

/-- The generated component is closed under the first matching. -/
theorem alternatingComponent_closed_first
    (sigma tau : Pairing V) (root : V) :
    ∀ vertex ∈ alternatingComponent sigma tau root,
      sigma.partner vertex ∈ alternatingComponent sigma tau root := by
  intro vertex hvertex
  rw [mem_alternatingComponent_iff] at hvertex ⊢
  exact Relation.EqvGen.trans root vertex (sigma.partner vertex)
    hvertex (Relation.EqvGen.rel vertex _ (Or.inl rfl))

/-- The generated component is closed under the second matching. -/
theorem alternatingComponent_closed_second
    (sigma tau : Pairing V) (root : V) :
    ∀ vertex ∈ alternatingComponent sigma tau root,
      tau.partner vertex ∈ alternatingComponent sigma tau root := by
  intro vertex hvertex
  rw [mem_alternatingComponent_iff] at hvertex ⊢
  exact Relation.EqvGen.trans root vertex (tau.partner vertex)
    hvertex (Relation.EqvGen.rel vertex _ (Or.inr rfl))

/-- A nontrivial alternating component has at least four vertices. -/
theorem four_le_card_alternatingComponent
    (sigma tau : Pairing V) {root : V}
    (hroot : sigma.partner root ≠ tau.partner root) :
    4 ≤ (alternatingComponent sigma tau root).card := by
  exact four_le_card_of_closed_disagree sigma tau
    (alternatingComponent_closed_first sigma tau root)
    (alternatingComponent_closed_second sigma tau root)
    (root_mem_alternatingComponent sigma tau root) hroot

/-- Any vertex where the pairings agree lies outside a component rooted at a
disagreement. -/
theorem not_mem_alternatingComponent_of_agreement
    (sigma tau : Pairing V) {root vertex : V}
    (hroot : sigma.partner root ≠ tau.partner root)
    (hvertex : sigma.partner vertex = tau.partner vertex) :
    vertex ∉ alternatingComponent sigma tau root := by
  intro hmem
  exact disagreement_of_mem_alternatingComponent sigma tau hroot hmem hvertex

variable {G : SimpleGraph V} [Fintype G.edgeSet] [G.LocallyFinite]

/-- In a cubic Tait counterexample, a disagreement component of two supported
matchings is proper.  A shared matching edge supplies two vertices outside the
component. -/
theorem exists_shared_edge_outside_alternatingComponent
    (hG : HasCubicIncidentEdgeTriples G)
    (hnot : ¬ TaitColorable G)
    (sigma tau : Pairing V)
    (hSigma : sigma.SupportedBy G) (hTau : tau.SupportedBy G)
    {root : V} (hroot : sigma.partner root ≠ tau.partner root) :
    ∃ vertex : V,
      sigma.partner vertex = tau.partner vertex ∧
      vertex ∉ alternatingComponent sigma tau root ∧
      sigma.partner vertex ∉ alternatingComponent sigma tau root := by
  obtain ⟨vertex, hagree⟩ :=
    exists_shared_edge_of_not_taitColorable
      hG hnot sigma tau hSigma hTau
  have hpartnerAgree :
      sigma.partner (sigma.partner vertex) =
        tau.partner (sigma.partner vertex) := by
    rw [sigma.partner_partner]
    have h := congrArg tau.partner hagree
    rw [tau.partner_partner] at h
    exact h.symm
  exact ⟨vertex, hagree,
    not_mem_alternatingComponent_of_agreement
      sigma tau hroot hagree,
    not_mem_alternatingComponent_of_agreement
      sigma tau hroot hpartnerAgree⟩

end

end GoertzelV24AlternatingMatchingComponent

end Mettapedia.GraphTheory.FourColor
