import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber70Block4Chunk0ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber70Block4Chunk1ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber70Block4Chunk2ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber70Block4Chunk3ComponentCertificate

namespace Mettapedia.GraphTheory.FourColor

/-!
# Goertzel Lemma 8.18: `TTT` large fiber 70 block 4 aggregate

This module aggregates chunk certificates for rows 256 through 319 of one
size-512 fixed-input fiber of the `TTT`/`mode09` representative target.
-/

namespace GoertzelLemma818TripleTauLargeFiber70Block4ComponentCertificate

open GoertzelLemma818TripleTauLargeFiber70Block4Chunk0ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber70Block4Chunk1ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber70Block4Chunk2ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber70Block4Chunk3ComponentCertificate

def tttLargeFiber70Block4ComponentCertificateAudit : Bool :=
  tttLargeFiber70Block4Chunk0ComponentCertificateAudit &&
    tttLargeFiber70Block4Chunk1ComponentCertificateAudit &&
    tttLargeFiber70Block4Chunk2ComponentCertificateAudit &&
    tttLargeFiber70Block4Chunk3ComponentCertificateAudit

theorem tttLargeFiber70Block4ComponentCertificateAudit_ok :
    tttLargeFiber70Block4ComponentCertificateAudit = true := by
  simp [tttLargeFiber70Block4ComponentCertificateAudit,
    tttLargeFiber70Block4Chunk0ComponentCertificateAudit_ok,
    tttLargeFiber70Block4Chunk1ComponentCertificateAudit_ok,
    tttLargeFiber70Block4Chunk2ComponentCertificateAudit_ok,
    tttLargeFiber70Block4Chunk3ComponentCertificateAudit_ok]

end GoertzelLemma818TripleTauLargeFiber70Block4ComponentCertificate

end Mettapedia.GraphTheory.FourColor
