import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber10Block4Chunk0ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber10Block4Chunk1ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber10Block4Chunk2ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber10Block4Chunk3ComponentCertificate

namespace Mettapedia.GraphTheory.FourColor

/-!
# Goertzel Lemma 8.18: third large `TTT` fiber, block 4

This module aggregates four 16-row component-certificate chunks for rows 256
through 319 of the third size-512 fixed-input fiber of the `TTT`/`mode09`
representative target.
-/

namespace GoertzelLemma818TripleTauLargeFiber10Block4ComponentCertificate

open GoertzelLemma818TripleTauLargeFiber10Block4Chunk0ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber10Block4Chunk1ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber10Block4Chunk2ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber10Block4Chunk3ComponentCertificate

def tttLargeFiber10Block4ComponentCertificateAudit : Bool :=
  tttLargeFiber10Block4Chunk0ComponentCertificateAudit &&
    tttLargeFiber10Block4Chunk1ComponentCertificateAudit &&
    tttLargeFiber10Block4Chunk2ComponentCertificateAudit &&
    tttLargeFiber10Block4Chunk3ComponentCertificateAudit

theorem tttLargeFiber10Block4ComponentCertificateAudit_ok :
    tttLargeFiber10Block4ComponentCertificateAudit = true := by
  simp [tttLargeFiber10Block4ComponentCertificateAudit,
    tttLargeFiber10Block4Chunk0ComponentCertificateAudit_ok,
    tttLargeFiber10Block4Chunk1ComponentCertificateAudit_ok,
    tttLargeFiber10Block4Chunk2ComponentCertificateAudit_ok,
    tttLargeFiber10Block4Chunk3ComponentCertificateAudit_ok]

end GoertzelLemma818TripleTauLargeFiber10Block4ComponentCertificate

end Mettapedia.GraphTheory.FourColor
