import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber20Block7Chunk0ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber20Block7Chunk1ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber20Block7Chunk2ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber20Block7Chunk3ComponentCertificate

namespace Mettapedia.GraphTheory.FourColor

/-!
# Goertzel Lemma 8.18: `TTT` large fiber 20 block 7 aggregate

This module aggregates chunk certificates for rows 448 through 511 of one
size-512 fixed-input fiber of the `TTT`/`mode09` representative target.
-/

namespace GoertzelLemma818TripleTauLargeFiber20Block7ComponentCertificate

open GoertzelLemma818TripleTauLargeFiber20Block7Chunk0ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber20Block7Chunk1ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber20Block7Chunk2ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber20Block7Chunk3ComponentCertificate

def tttLargeFiber20Block7ComponentCertificateAudit : Bool :=
  tttLargeFiber20Block7Chunk0ComponentCertificateAudit &&
    tttLargeFiber20Block7Chunk1ComponentCertificateAudit &&
    tttLargeFiber20Block7Chunk2ComponentCertificateAudit &&
    tttLargeFiber20Block7Chunk3ComponentCertificateAudit

theorem tttLargeFiber20Block7ComponentCertificateAudit_ok :
    tttLargeFiber20Block7ComponentCertificateAudit = true := by
  simp [tttLargeFiber20Block7ComponentCertificateAudit,
    tttLargeFiber20Block7Chunk0ComponentCertificateAudit_ok,
    tttLargeFiber20Block7Chunk1ComponentCertificateAudit_ok,
    tttLargeFiber20Block7Chunk2ComponentCertificateAudit_ok,
    tttLargeFiber20Block7Chunk3ComponentCertificateAudit_ok]

end GoertzelLemma818TripleTauLargeFiber20Block7ComponentCertificate

end Mettapedia.GraphTheory.FourColor
