import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber36Block5Chunk0ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber36Block5Chunk1ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber36Block5Chunk2ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber36Block5Chunk3ComponentCertificate

namespace Mettapedia.GraphTheory.FourColor

/-!
# Goertzel Lemma 8.18: `TTT` large fiber 36 block 5 aggregate

This module aggregates chunk certificates for rows 320 through 383 of one
size-512 fixed-input fiber of the `TTT`/`mode09` representative target.
-/

namespace GoertzelLemma818TripleTauLargeFiber36Block5ComponentCertificate

open GoertzelLemma818TripleTauLargeFiber36Block5Chunk0ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber36Block5Chunk1ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber36Block5Chunk2ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber36Block5Chunk3ComponentCertificate

def tttLargeFiber36Block5ComponentCertificateAudit : Bool :=
  tttLargeFiber36Block5Chunk0ComponentCertificateAudit &&
    tttLargeFiber36Block5Chunk1ComponentCertificateAudit &&
    tttLargeFiber36Block5Chunk2ComponentCertificateAudit &&
    tttLargeFiber36Block5Chunk3ComponentCertificateAudit

theorem tttLargeFiber36Block5ComponentCertificateAudit_ok :
    tttLargeFiber36Block5ComponentCertificateAudit = true := by
  simp [tttLargeFiber36Block5ComponentCertificateAudit,
    tttLargeFiber36Block5Chunk0ComponentCertificateAudit_ok,
    tttLargeFiber36Block5Chunk1ComponentCertificateAudit_ok,
    tttLargeFiber36Block5Chunk2ComponentCertificateAudit_ok,
    tttLargeFiber36Block5Chunk3ComponentCertificateAudit_ok]

end GoertzelLemma818TripleTauLargeFiber36Block5ComponentCertificate

end Mettapedia.GraphTheory.FourColor
