import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block2Chunk0ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block2Chunk1ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block2Chunk2ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block2Chunk3ComponentCertificate

namespace Mettapedia.GraphTheory.FourColor

/-!
# Goertzel Lemma 8.18: second large `TTT` fiber, block 2

This module aggregates four 16-row component-certificate chunks for the third
64-row part of the second size-512 fixed-input fiber of the `TTT`/`mode09`
representative target.
-/

namespace GoertzelLemma818TripleTauLargeFiber8Block2ComponentCertificate

open GoertzelLemma818TripleTauLargeFiber8Block2Chunk0ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber8Block2Chunk1ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber8Block2Chunk2ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber8Block2Chunk3ComponentCertificate

def tttLargeFiber8Block2ComponentCertificateAudit : Bool :=
  tttLargeFiber8Block2Chunk0ComponentCertificateAudit &&
    tttLargeFiber8Block2Chunk1ComponentCertificateAudit &&
    tttLargeFiber8Block2Chunk2ComponentCertificateAudit &&
    tttLargeFiber8Block2Chunk3ComponentCertificateAudit

theorem tttLargeFiber8Block2ComponentCertificateAudit_ok :
    tttLargeFiber8Block2ComponentCertificateAudit = true := by
  simp [tttLargeFiber8Block2ComponentCertificateAudit,
    tttLargeFiber8Block2Chunk0ComponentCertificateAudit_ok,
    tttLargeFiber8Block2Chunk1ComponentCertificateAudit_ok,
    tttLargeFiber8Block2Chunk2ComponentCertificateAudit_ok,
    tttLargeFiber8Block2Chunk3ComponentCertificateAudit_ok]

end GoertzelLemma818TripleTauLargeFiber8Block2ComponentCertificate

end Mettapedia.GraphTheory.FourColor
