import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block1Chunk0ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block1Chunk1ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block1Chunk2ComponentCertificate
import Mettapedia.GraphTheory.FourColor.GoertzelLemma818TripleTauLargeFiber8Block1Chunk3ComponentCertificate

namespace Mettapedia.GraphTheory.FourColor

/-!
# Goertzel Lemma 8.18: second large `TTT` fiber, block 1

This module aggregates four 16-row component-certificate chunks for the second
64-row part of the second size-512 fixed-input fiber of the `TTT`/`mode09`
representative target.
-/

namespace GoertzelLemma818TripleTauLargeFiber8Block1ComponentCertificate

open GoertzelLemma818TripleTauLargeFiber8Block1Chunk0ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber8Block1Chunk1ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber8Block1Chunk2ComponentCertificate
open GoertzelLemma818TripleTauLargeFiber8Block1Chunk3ComponentCertificate

def tttLargeFiber8Block1ComponentCertificateAudit : Bool :=
  tttLargeFiber8Block1Chunk0ComponentCertificateAudit &&
    tttLargeFiber8Block1Chunk1ComponentCertificateAudit &&
    tttLargeFiber8Block1Chunk2ComponentCertificateAudit &&
    tttLargeFiber8Block1Chunk3ComponentCertificateAudit

theorem tttLargeFiber8Block1ComponentCertificateAudit_ok :
    tttLargeFiber8Block1ComponentCertificateAudit = true := by
  simp [tttLargeFiber8Block1ComponentCertificateAudit,
    tttLargeFiber8Block1Chunk0ComponentCertificateAudit_ok,
    tttLargeFiber8Block1Chunk1ComponentCertificateAudit_ok,
    tttLargeFiber8Block1Chunk2ComponentCertificateAudit_ok,
    tttLargeFiber8Block1Chunk3ComponentCertificateAudit_ok]

end GoertzelLemma818TripleTauLargeFiber8Block1ComponentCertificate

end Mettapedia.GraphTheory.FourColor
