import Mettapedia.Computability.PNP.ApproximateDecorrelationFoundationRegression
import Mettapedia.Computability.PNP.ApproximateDecorrelationCoupledRegression
import Mettapedia.Computability.PNP.ApproximateDecorrelationFiniteCoinRegressionFiberCounts
import Mettapedia.Computability.PNP.ApproximateDecorrelationFiniteCoinRegressionBalanceBlockers
import Mettapedia.Computability.PNP.ApproximateDecorrelationFiniteCoinRegressionToleranceBounds
import Mettapedia.Computability.PNP.ApproximateDecorrelationFiniteCoinRegressionBalanceThresholds
import Mettapedia.Computability.PNP.ApproximateDecorrelationFiniteCoinRegressionZeroTolerance
import Mettapedia.Computability.PNP.ApproximateDecorrelationCoinRetainedRegression
import Mettapedia.Computability.PNP.ApproximateDecorrelationSideRetainedRegression
import Mettapedia.Computability.PNP.ApproximateDecorrelationPostprocessedSideRegressionSourceCounts
import Mettapedia.Computability.PNP.ApproximateDecorrelationPostprocessedSideRegressionSkewMaps
import Mettapedia.Computability.PNP.ApproximateDecorrelationPostprocessedSideRegressionMatching
import Mettapedia.Computability.PNP.ApproximateDecorrelationPostprocessedSideRegressionOutputEquiv
import Mettapedia.Computability.PNP.ApproximateDecorrelationPostprocessedFibersRegressionPostprocessedSide
import Mettapedia.Computability.PNP.ApproximateDecorrelationPostprocessedFibersRegressionCoinwiseOutput
import Mettapedia.Computability.PNP.ApproximateDecorrelationPostprocessedFibersRegressionCoinwiseSource
import Mettapedia.Computability.PNP.ApproximateDecorrelationPostprocessedFibersRegressionZeroTolerance

/-!
# Regression checks for approximate decorrelation obstructions

The approximate-decorrelation regression wrappers are split by semantic layer:
finite-count foundations, coupled/deterministic recoding, finite-coin
cancellation, retained coin/side channels, postprocessed-side matching, and
fiber-level blockers.  This file preserves the historical import path.
-/
