import Mettapedia.Computability.PNP.CruxSynthesisRegressionLedgerBroad
import Mettapedia.Computability.PNP.CruxSynthesisRegressionLedgerFiniteCoinStack
import Mettapedia.Computability.PNP.CruxSynthesisRegressionLedgerResidualSideInformationSubrepairs
import Mettapedia.Computability.PNP.CruxSynthesisRegressionLedgerResidualSideInformationWitnesses
import Mettapedia.Computability.PNP.CruxSynthesisRegressionLedgerResidualSideInformationPackages
import Mettapedia.Computability.PNP.CruxSynthesisRegressionLedgerRandomizedResidual
import Mettapedia.Computability.PNP.CruxKpolyBridgeGapLedger
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolySubrepairsObservedSupport
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolySubrepairsActualLocalBoundedSample
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolySubrepairsBitFallback
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolySubrepairsCoverEquivalences
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolySubrepairsRecoveryThresholds
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBridgeExamplesData
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBridgeExamplesWidth
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBridgeExamplesPayload
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBridgeExamplesCardinality
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBridgeExamplesThresholds
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBridgeExamplesRegions
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBridgeStatus
import Mettapedia.Computability.PNP.CruxSynthesisRegressionPacketStatusCurrent
import Mettapedia.Computability.PNP.CruxSynthesisRegressionPacketStatusResidualPromoted
import Mettapedia.Computability.PNP.CruxSynthesisRegressionPacketStatusRandomizedResidualPromoted
import Mettapedia.Computability.PNP.CruxSynthesisRegressionPacketStatusApproximateDecorrelationPromoted
import Mettapedia.Computability.PNP.CruxSynthesisRegressionPacketStatusKpolyPromoted
import Mettapedia.Computability.PNP.CruxSynthesisRegressionPacketStatusV13Route
import Mettapedia.Computability.PNP.CruxSynthesisRegressionPacketStatusUncoveredStacks
import Mettapedia.Computability.PNP.CruxSynthesisRegressionResidualGlobalAnchors
import Mettapedia.Computability.PNP.CruxSynthesisRegressionResidualCollisionMass
import Mettapedia.Computability.PNP.CruxSynthesisRegressionResidualCounterexamplesPure
import Mettapedia.Computability.PNP.CruxSynthesisRegressionResidualCounterexamplesOrbitInvisible
import Mettapedia.Computability.PNP.CruxSynthesisRegressionResidualCounterexamplesBalancedWitness
import Mettapedia.Computability.PNP.CruxSynthesisRegressionResidualCounterexamplesSupportedPackages
import Mettapedia.Computability.PNP.CruxSynthesisRegressionResidualExactPostSwitch
import Mettapedia.Computability.PNP.CruxSynthesisRegressionResidualAdvantageConsequences
import Mettapedia.Computability.PNP.CruxSynthesisRegressionResidualSupportedPackages
import Mettapedia.Computability.PNP.CruxSynthesisRegressionRandomizedResidualAnchorsSideChannel
import Mettapedia.Computability.PNP.CruxSynthesisRegressionRandomizedResidualAnchorsPostSwitchFork
import Mettapedia.Computability.PNP.CruxSynthesisRegressionRandomizedResidualAnchorsFiniteCoin
import Mettapedia.Computability.PNP.CruxSynthesisRegressionRandomizedResidualAnchorsPostSwitchFiniteCoin
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyVisibleABObstructions
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyVisibleABInvariant
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyVisibleBridgeInterfaces
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyVisibleClockedPayload
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyVisiblePluginFamilies
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyVisibleActualLocalExamples
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBoundedSampleBase
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBoundedSampleFallbackFamily
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBoundedSampleBitFallbackCovers
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBoundedSampleBitFallbackZeroSample
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBoundedSampleBitFallbackExactDecoderObstructions
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBoundedSampleBitFallbackBudgets
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyBoundedSampleTerminalObstructions
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolySupportRuleObserved
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolySupportRuleUniformSection
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolySupportRuleExactDecoder
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolySupportRulePropertyDecoder
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolySupportRulePointQuery
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolySupportRuleAdaptiveQuery
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolySupportRuleCardinality
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolySupportRuleOneBlock
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyFiniteCoverEquivalences
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyFiniteCoverFactorThrough
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyFiniteCoverABPullback
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyFiniteCoverCardinality
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyFiniteCoverInjectiveFactorThrough
import Mettapedia.Computability.PNP.CruxSynthesisRegressionKpolyFiniteCoverExactVisibleObstructions
import Mettapedia.Computability.PNP.CruxSynthesisRegressionFiniteCoinAnchorsCore
import Mettapedia.Computability.PNP.CruxSynthesisRegressionFiniteCoinAnchorsPostprocessedSide
import Mettapedia.Computability.PNP.CruxSynthesisRegressionFiniteCoinAnchorsObstructions
import Mettapedia.Computability.PNP.CruxSynthesisRegressionFiniteCoinAnchorsRetained

/-!
# Regression checks for the PNP crux synthesis bridge

This module preserves the historical `CruxSynthesisRegression` import path for
final
packet-status checks.  Ledger, Kpoly subrepair, concrete Kpoly example, Kpoly
bridge-status, packet-status, residual-anchor, randomized-residual-anchor, Kpoly-obstruction-anchor, and finite-coin-anchor
checks live in focused sibling modules.
-/

namespace Mettapedia.Computability.PNP.CruxSynthesisRegression

open Mettapedia.Computability.PNP
universe u v w z

theorem current_pnp_packet_kpoly_compression_bridge_uncovered_regression :
    ¬ currentPNPLocalCruxPacket.covers .kpolyCompressionBridge := by
  exact kpolyCompressionBridge_uncovered_currentPNPLocalCruxPacket

theorem current_pnp_packet_clocked_finite_uniform_kernel_covered_regression :
    currentPNPLocalCruxPacket.covers .clockedFiniteUniformKernel := by
  exact clockedFiniteUniformKernel_covered_currentPNPLocalCruxPacket

theorem current_pnp_stop_grade_iff_gaps_covered_for_extensions_regression
    {packet : PNPCruxPacket}
    (hExtends : packet.Extends currentPNPLocalCruxPacket) :
    packet.StopGrade ↔ packet.CoversList currentPNPUncoveredRepairClasses := by
  exact stopGrade_iff_covers_currentPNP_gaps_of_extends_current hExtends

theorem current_pnp_extension_missing_gaps_blocks_stop_grade_regression
    {packet : PNPCruxPacket}
    (hExtends : packet.Extends currentPNPLocalCruxPacket)
    (hNotGaps : ¬ packet.CoversList currentPNPUncoveredRepairClasses) :
    ¬ packet.StopGrade := by
  exact not_stopGrade_of_not_covers_currentPNP_gaps_of_extends_current
    hExtends hNotGaps

theorem current_pnp_gap_completed_packet_stop_grade_regression :
    currentPNPGapCompletedPacket.StopGrade := by
  exact stopGrade_currentPNPGapCompletedPacket

theorem current_pnp_gap_completed_packet_covers_next_marginal_target_regression :
    currentPNPGapCompletedPacket.covers currentPNPNextMarginalTarget := by
  exact currentPNPGapCompletedPacket_covers_currentPNPNextMarginalTarget

end Mettapedia.Computability.PNP.CruxSynthesisRegression
