import Mettapedia.Computability.PNP.PNPv13NeutralSyntaxCouplingObstruction

namespace Mettapedia.Computability.PNP

#check V13FiniteCoupling.probability_add_probability_not
#check V13FiniteCoupling.event_of_probability_one_of_mass_pos
#check V13FiniteCoupling.exists_mass_pos
#check V13FiniteCoupling.no_rigid_match_with_opposite_phase_marginals
#check V13M4OpenConstructionObligations.targetBit_rigid_on_supported_publicFiber
#check V13D48GlobalNeutralSkeletonMatching
#check v13D48GlobalNeutralSkeletonMatching_false_of_publicTargetRigidity
#check v13OpenConstruction_rejects_D48GlobalNeutralSkeletonMatching

#print axioms V13FiniteCoupling.probability_add_probability_not
#print axioms V13FiniteCoupling.event_of_probability_one_of_mass_pos
#print axioms V13FiniteCoupling.exists_mass_pos
#print axioms V13FiniteCoupling.no_rigid_match_with_opposite_phase_marginals
#print axioms V13M4OpenConstructionObligations.targetBit_rigid_on_supported_publicFiber
#print axioms V13D48GlobalNeutralSkeletonMatching
#print axioms v13D48GlobalNeutralSkeletonMatching_false_of_publicTargetRigidity
#print axioms v13OpenConstruction_rejects_D48GlobalNeutralSkeletonMatching

end Mettapedia.Computability.PNP
