import Mettapedia.Computability.PNP.CruxSynthesisRegression
import Mettapedia.Computability.PNP.CoarseProjectionObstructionRegression
import Mettapedia.Computability.PNP.KpolyQuantaleShortcutRemovalCanaryRegression
import Mettapedia.Computability.PNP.PNPv13AtomicBudgetLedgerAuditorCanariesRegression
import Mettapedia.Computability.PNP.PNPv13CDENFNormalizerCanariesRegression
import Mettapedia.Computability.PNP.PNPv13FiniteGibbsDobrushinCanariesRegression
import Mettapedia.Computability.PNP.PNPv13FaithfulM4SpecRegression
import Mettapedia.Computability.PNP.PublicNeutralityRedTeamRegression
import Mettapedia.Computability.PNP.PNPv13SwitchedHistoryProductAuditorCanariesRegression
import Mettapedia.Computability.PNP.PNPv13TraceFactorizationCanariesRegression
import Mettapedia.Computability.PNP.PNPSteelmanConditionalRegression
import Mettapedia.Computability.PNP.V13ObserverLadderRegression
import Mettapedia.Computability.PNP.V13CDENFRegression
import Mettapedia.Computability.PNP.V13ConditionalClashRegression
import Mettapedia.Computability.PNP.V13EvidenceSpineRegression
import Mettapedia.Computability.PNP.V13FaithfulnessAuditRegression
import Mettapedia.Computability.PNP.V13FaithfulM4ConstructionRegression
import Mettapedia.Computability.PNP.V13FaithfulQuantitativeFrontiersRegression
import Mettapedia.Computability.PNP.V13GaugeBufferedLockedInterfaceRegression
import Mettapedia.Computability.PNP.V13InterfaceBatteryRegression
import Mettapedia.Computability.PNP.V13PhaseEConcreteRegression
import Mettapedia.Computability.PNP.V13PhaseEScaledRegression
import Mettapedia.Computability.PNP.V13RealRungOneAdaptiveRowsRegression
import Mettapedia.Computability.PNP.V13RealRungOneLinearRegression
import Mettapedia.Computability.PNP.V13RealRungOneQRowBoundRegression
import Mettapedia.Computability.PNP.V13RealRungOneRowObserversRegression
import Mettapedia.Computability.PNP.V13RealRungOneStaticRowsRegression
import Mettapedia.Computability.PNP.V13RealRungThreeGaugeSwitchRegression
import Mettapedia.Computability.PNP.V13RealRungTwoBitJuntaRegression
import Mettapedia.Computability.PNP.V14ToyEndgameRegression
import Mettapedia.Computability.PNP.V14PublicReadToyRegression
import Mettapedia.Computability.PNP.V15RealEnsembleSpineRegression
import Mettapedia.Computability.PNP.V15RealLinearCNFEnsembleRegression
import Mettapedia.Computability.PNP.V15SmallSingleMessageCNFEnsembleRegression
import Mettapedia.Computability.PNP.WeaknessCalculusRegression
import Mettapedia.Computability.PNP.Barriers.Regression

/-!
# PNP regression aggregator

This is a non-default regression target for the PNP lane.  It imports the
broad crux-synthesis regression umbrella while keeping the live PNP entrypoint
focused on route surfaces and proof-state bookkeeping.
-/

namespace Mettapedia.Computability.PNP.Regression

end Mettapedia.Computability.PNP.Regression
