import Mettapedia.Computability.PNP.V13RealRungOneQRowBound

namespace Mettapedia.Computability.PNP

set_option autoImplicit false

#check V13RealLinearAdaptiveQRowExperiment
#check V13RealLinearCausalRowObserver
#check V13RealLinearCausalRowObserver.staticBranch
#check V13RealLinearCausalRowObserver.toAdaptive
#check V13RealLinearCausalRowObserver.branch_eq_of_same_branchRowsTranscript
#check V13RealLinearCausalRowObserver.decision_eq_of_same_branchRowsTranscript
#check v13RealLinearUniformCausalQRowExperiment
#check v13RealLinearAdaptiveQRowSuccess
#check v13RealLinearUniformCausalQRowSuccess
#check v13RealLinearAdaptiveQRowBlockedMass
#check v13RealLinearAdaptiveQRowGeneratedMass
#check v13RealLinearQRowEpsilon
#check v13RealLinearQRowDeferredDecisionEpsilon
#check v13RealLinearQRowDeferredDecisionEpsilon_nonnegative
#check v13RealLinearQRowEpsilon_le_deferredDecisionEpsilon_of_pos
#check v13RealLinear_sum_range_two_pow
#check v13RealLinear_sum_fin_deferredDecisionWeights
#check v13F2LinearEquivToLinearEquiv
#check v13F2LinearEquivLinearEquivEquiv
#check v13F2LinearEquivGLEquiv
#check v13F2LinearEquiv_card_eq_gl
#check v13F2LinearEquiv_card_formula
#check v13F2LinearEquiv_card_formula_rat
#check v13RealLinear_one_sub_sum_le_prod_one_sub
#check v13RealLinear_tail_product_ge_three_quarters
#check v13RealLinear_gl_density_product_ge_quarter
#check v13RealLinear_density_times_full_product
#check v13F2LinearEquiv_card_density_quarter
#check V13RealLinearAdaptiveQRowExperiment.branchRows_card_le
#check V13RealLinearRowCombination
#check v13RealLinearRowCombinationEval
#check V13RealLinearRowsGenerateTarget
#check v13RealLinear_not_rowsGenerateTarget_of_rows_card_zero
#check V13RealLinearRowTrace
#check v13RealLinearRowTraceRows
#check V13RealLinearSequentialRowTranscript
#check V13RealLinearSequentialRowObserver
#check v13RealLinearSequentialRowRunAux
#check v13RealLinearSequentialRowTranscriptOf
#check v13RealLinearSequentialRowTraceOf
#check v13RealLinearSequentialRowPrefixTranscriptOf
#check v13RealLinearSequentialRowPrefixTraceOf
#check v13RealLinearSequentialRowRunAuxWithRowView
#check v13RealLinearSequentialRowPrefixTranscriptOfWithRowView
#check v13RealLinearSequentialRowPrefixTraceOfWithRowView
#check v13RealLinearSequentialRowRunAuxWithRowView_length
#check v13RealLinearSequentialRowRunAuxWithRowView_add
#check v13RealLinearSequentialRowPrefixTranscriptOfWithRowView_length
#check v13RealLinearSequentialRowPrefixTranscriptRowsWithRowView_card_le
#check v13RealLinearSequentialRowPrefixTranscriptOfWithRowView_succ
#check v13RealLinearSequentialRowRunAuxWithRowView_congr
#check v13RealLinearSequentialRowRunAuxWithRowView_rows_mono
#check v13RealLinearSequentialRowRunAuxWithRowView_eq_of_final_rows_eq
#check v13RealLinearSequentialRowPrefixTranscriptOfWithRowView_eq_of_final_rows_eq
#check v13RealLinearSequentialRowRunAux_eq_withRowView
#check v13RealLinearSequentialRowPrefixTranscriptOf_eq_withRowView
#check v13RealLinearSequentialRowPrefixTraceOf_eq_withRowView
#check v13RealLinearSequentialRowTranscriptRows
#check v13RealLinearSequentialRowTranscriptRows_card_le_length
#check v13RealLinearSequentialRowRunAux_length
#check v13RealLinearSequentialRowRunAux_add
#check v13RealLinearSequentialRowRunAux_eq_append
#check v13RealLinearSequentialRowRunAux_take_initial
#check v13RealLinearSequentialRowPrefixTranscriptOf_length
#check v13RealLinearSequentialRowPrefixTraceOf_length
#check v13RealLinearSequentialRowPrefixTranscriptRows_card_le
#check v13RealLinearSequentialRowPrefixTranscriptOf_succ
#check v13RealLinearSequentialRowPrefixTraceOf_succ
#check v13RealLinearSequentialRowTranscriptOf_take_eq_prefix
#check v13RealLinearSequentialRowTraceOf_take_eq_prefix
#check v13RealLinearSequentialRowTranscriptOf_length
#check v13RealLinearSequentialRowTraceOf_length
#check v13RealLinearSequentialRowRunAux_rows_mono
#check v13RealLinearRowsTranscript_eq_rowView_of_mem
#check v13RealLinearSequentialRowRunAux_eq_of_final_rowsTranscript_eq
#check v13RealLinearSequentialRowTranscriptOf_eq_of_rowsTranscript_eq
#check V13RealLinearSequentialRowObserver.toCausal
#check v13RealLinearRowTracePrefixRows
#check v13RealLinearRowTracePrefixRows_zero
#check v13RealLinearRowTracePrefixRows_length
#check v13RealLinearRowTracePrefixRows_card_le
#check v13RealLinearSequentialRowTracePrefixRows_eq_prefixTranscriptRows
#check v13RealLinearSequentialRowTraceOf_get_eq_chooseRow
#check v13RealLinearRowTracePrefixRows_succ
#check V13RealLinearRowTraceNewCapture
#check v13RealLinearRowTrace_not_generate_at_zero
#check v13RealLinearRowTraceNewCaptureCover
#check v13RealLinearRowTraceNewCaptureCover_of_traceRows
#check v13RealLinear_rowCombination_card
#check v13RealLinear_rowCombination_card_le_of_rows_card_le
#check v13RealLinear_rowCombination_card_le_for_branch
#check v13RealLinear_rowsBlockTarget_of_rowsGenerateTarget
#check v13RealLinear_rowsGenerateTarget_of_rowsBlockTarget
#check v13RealLinear_rowsBlockTarget_iff_rowsGenerateTarget
#check v13RealLinear_rowsGenerateTarget_singleton_iff
#check v13RealLinear_singletonRowCombination_eq_one_of_generates
#check V13RealLinearTargetRows
#check v13RealLinear_mem_targetRows_iff
#check v13RealLinear_targetRows_card_le_one
#check v13RealLinearZeroAtRowShear_targetRows_empty_of_nonzero
#check v13FinSpare
#check v13FinSpare_ne
#check v13RealLinearNoTargetRowShear
#check v13RealLinearNoTargetRowShear_targetRows_empty
#check v13RealLinearNoTargetRowShear_rowFunctional_ne_target
#check v13RealLinearNoTargetRowShear_row_not_mem_targetRows
#check v13RealLinearNoTargetRowShear_rowFunctional_ne_activeTarget
#check v13RealLinearRowFunctional_injective
#check v13RealLinearFunctionalFintype
#check v13RealLinearFunctional_card
#check V13RealLinearRowFunctionalTable
#check v13RealLinearRowFunctionalTableOfEquiv
#check v13RealLinearRowFunctionalTable_card
#check v13RealLinearRowFunctionalTable_card_le_four_mul_equiv
#check v13RealLinearRowFunctionalTableOfEquiv_injective
#check v13RealLinearFunctionalTableRowView
#check v13RealLinearFunctionalTableSequentialRowPrefixTranscriptOf
#check v13RealLinearFunctionalTableSequentialRowPrefixTraceOf
#check v13RealLinearFunctionalTableRowView_of_equiv
#check v13RealLinearFunctionalTableSequentialRowPrefixTranscriptOf_equiv
#check v13RealLinearFunctionalTableSequentialRowPrefixTraceOf_equiv
#check v13RealLinearFunctionalTableSequentialRowPrefixTranscriptOf_update_eq
#check v13RealLinearFunctionalTableSequentialRowPrefixTraceOf_update_eq
#check V13RealLinearFunctionalTableWorld
#check v13RealLinearFunctionalTableSequentialWorldPrefixTranscript
#check v13RealLinearFunctionalTableSequentialWorldPrefixRows
#check v13RealLinearFunctionalTableSequentialWorldNextRow
#check V13RealLinearFunctionalTableSequentialFreshTargetCosetHit
#check v13RealLinearFunctionalTableSequentialWorldPrefixRows_card_le
#check v13RealLinearFunctionalTableSequentialWorldPrefixTranscript_update_eq
#check v13RealLinearFunctionalTableSequentialWorldPrefixRows_update_eq
#check v13RealLinearFunctionalTableSequentialWorldNextRow_update_eq
#check v13RealLinearFunctionalTableSequentialWorldPrefixRows_succ
#check v13RealLinearRowFunctionalTableFintype
#check V13RealLinearFunctionalTableRowsSpan
#check V13RealLinearFunctionalTableTargetCosetHit
#check v13RealLinearFunctionalTableRowsSpan_eq_of_eq_on_rows
#check v13RealLinearFunctionalTableRowsSpanCombination
#check v13RealLinearFunctionalTableRowsSpanCombination_surjective
#check v13RealLinearFunctionalTableRowsSpan_card_le
#check V13RealLinearFunctionalTableRowsGenerateTarget
#check v13RealLinearTargetFunctional_ne_zero
#check v13RealLinearFunctionalTable_not_rowsGenerateTarget_of_rows_card_zero
#check v13RealLinearFunctionalTable_range_insert
#check v13RealLinearFunctionalTableTargetCosetHit_of_insert_generates
#check V13RealLinearFunctionalTableSequentialGenerated
#check v13RealLinearFunctionalTableRowsGenerateTarget_of_rowsGenerateTarget
#check V13RealLinearFunctionalTableTargetCoset
#check v13RealLinearFunctionalTableTargetCosetToSpan
#check v13RealLinearFunctionalTableTargetCosetToSpan_injective
#check v13RealLinearFunctionalTableTargetCosetEmbedding
#check v13RealLinearFunctionalTableTargetCoset_card_le_span
#check v13RealLinearFunctionalTableTargetCoset_card_le
#check v13RealLinearFunctionalTableSequentialTargetCosetSigma_card_le
#check v13RealLinearFunctionalTableFreshCosetHitSwitchToFun
#check v13RealLinearFunctionalTableFreshCosetHitSwitch
#check v13RealLinearFunctionalTableSequentialFreshTargetCosetHitSwitchToFun
#check v13RealLinearFunctionalTableSequentialFreshTargetCosetHitSwitch
#check v13RealLinearFunctionalTableSequentialFreshTargetCosetHit_card_mul_two_pow_le
#check v13RealLinearFunctionalTableSequentialGenerated_freshTargetCosetHit_cover
#check v13RealLinear_sum_fin_two_pow_mul
#check v13RealLinearFunctionalTableSequentialGenerated_card_mul_two_pow_le
#check v13RealLinearUniformSequentialWorldToFunctionalTableWorld
#check v13RealLinearUniformSequentialWorldToFunctionalTableWorld_injective
#check v13RealLinearFunctionalTableWorld_card_le_four_mul_uniformWorld
#check v13RealLinearUniformSequentialGenerated_functionalTableGenerated
#check v13RealLinearUniformSequentialGeneratedToFunctionalTableGenerated
#check v13RealLinearUniformSequentialGenerated_card_mul_two_pow_le_transfer
#check v13RealLinearUniformSequentialGeneratedMass_le_transfer
#check v13RealLinearFunctionalTableTargetCosetHit_card_mul_functional_le
#check v13RealLinearFunctionalTableTargetCosetHit_card_mul_two_pow_le
#check v13RealLinearFunctionalTableTargetCosetHit_card_mul_two_pow_le_of_rows_card_le
#check V13RealLinearRowsFunctionalSpan
#check v13RealLinearRowsGenerateTarget_iff_targetFunctional_mem_span
#check V13RealLinearRowFunctionalTargetCosetHit
#check v13RealLinear_rowFunctional_range_insert
#check v13RealLinear_rowFunctionalTargetCosetHit_of_insert_generates
#check V13RealLinearRowTraceCosetHit
#check v13RealLinearRowTraceCosetHit_of_newCapture
#check v13RealLinearRowsFunctionalSpanCombination
#check v13RealLinearRowsFunctionalSpanCombination_surjective
#check v13RealLinearRowsFunctionalSpan_card_le
#check V13RealLinearRowsFunctionalTargetCoset
#check v13RealLinearFunctionalTableTargetCosetHit_of_rowFunctionalTargetCosetHit
#check v13RealLinearRowsFunctionalTargetCosetToSpan
#check v13RealLinearRowsFunctionalTargetCosetToSpan_injective
#check v13RealLinearRowsFunctionalTargetCosetEmbedding
#check v13RealLinearRowsFunctionalTargetCoset_card_le_span
#check v13RealLinearRowsFunctionalTargetCoset_card_le
#check v13RealLinearRowTraceNewCapture_get_not_mem
#check v13RealLinearFunctionalTableTargetCosetHit_of_rowTraceNewCapture
#check v13RealLinearSequentialRowTraceNewCapture_chooseRow_not_mem
#check v13RealLinearSequentialRowTraceNewCapture_prefixRows_card_le
#check v13RealLinearSequentialRowTraceNewCapture_functionalTableTargetCosetHit
#check v13RealLinearRowFunctionalTargetCosetElement_of_hit
#check V13RealLinearRowTracePrefixTargetCosetRows
#check v13RealLinearRowTracePrefixTargetCosetRowsEmbedding
#check v13RealLinearRowTracePrefixTargetCosetRows_card_le_coset
#check v13RealLinearRowTracePrefixTargetCoset_card_le
#check v13RealLinearRowTracePrefixTargetCosetRows_card_le
#check v13RealLinearRowsTranscript_singleton_eq_of_row_match
#check v13RealLinearNoTargetRowShear_bridgeTranscripts_of_row_matches
#check v13RealLinearZeroAtShearSum_singleBit
#check v13RealLinearNoTargetRowShear_exists_bridgeX_for_row_target_bits
#check v13RealLinearNoTargetRowShear_branchRows_ne_of_activeRowIndex_of_bridgeMapFamily
#check v13RealLinearTargetRowChoice
#check v13RealLinearTargetRowObserver
#check v13RealLinear_targetRowObserver_generated_iff_targetRows_nonempty
#check V13RealLinearUniformTargetRowOccurrence
#check V13RealLinearUniformFixedTargetRowOccurrence
#check V13RealLinearRowIndexedFixedTargetRowOccurrenceWorld
#check v13RealLinearRowIndexedFixedTargetRowOccurrenceWorldEquiv
#check v13RealLinearFixedTargetRowOccurrenceSwapEquiv
#check v13RealLinearFixedTargetRowOccurrence_card_eq_of_swap
#check v13RealLinearUniformTargetRowOccurrenceMass
#check v13RealLinearShear01
#check v13RealLinearShear10
#check v13RealLinearShear01Swap
#check v13RealLinearSwapShear10
#check v13RealLinearSwapShear10_targetRows_zero_empty
#check V13RealLinearAdaptiveQRowExperiment.not_generated_of_targetRows_empty
#check v13RealLinear_fin2_rows_card_le_one_cases
#check v13RealLinearSwapShear10_not_generated_one_budget
#check v13RealLinearSwapShear10_branchRows_cases
#check v13RealLinearSwapShear10_branchRows_ne_empty_of_singletonWitness
#check v13RealLinearSwapShear10_branchRows_ne_empty_of_activeRowIndex
#check v13RealLinearSwapShear10_branchRows_ne_zero_of_singletonOneWitness
#check v13RealLinearSwapShear10_branchRows_ne_zero_of_activeRowOne
#check v13RealLinearSwapShear10_branchRows_ne_one_of_singletonZeroWitness
#check v13RealLinearSwapShear10_branchRows_ne_one_of_activeRowZero
#check v13RealLinearUniformCausalOneRowActiveRowPairExclusion_two_zero
#check v13RealLinearTargetRowOccurrenceFour
#check v13RealLinearTargetRowOccurrenceFour_injective
#check v13RealLinearUniformTargetRowOccurrence_card_four_le
#check v13RealLinearUniformTargetRowOccurrenceMass_two_zero_gt_half
#check V13RealLinearNonzeroF2Vec2
#check v13RealLinearNonzeroF2Vec2_card
#check v13RealLinearNonzeroF2Vec2_ne_card_le_two
#check v13_zmod2_cases
#check v13RealLinear_f2vec2_cases
#check v13RealLinear_f2vec2_eq_singleBit_one_of_ne_zero_of_coord_zero
#check v13RealLinear_f2vec2_eq_singleBit_zero_of_ne_zero_of_coord_one_zero
#check v13RealLinear_equiv_two_ext
#check V13RealLinearTwoBasisImagePairs
#check v13RealLinearTwoBasisImagePairs_card_le_six
#check v13RealLinear_f2_equiv_two_card_le_six
#check v13RealLinear_f2_equiv_two_card_four_le
#check v13RealLinearUniformTargetRowOccurrenceMass_two_zero_gt_half_unconditional
#check v13RealLinear_targetRowObserverGeneratedEquivOccurrenceProd
#check v13RealLinear_targetRowObserverGenerated_card_eq
#check v13RealLinear_targetRowObserverGeneratedMass_eq_occurrenceMass
#check V13RealLinearAdaptiveQRowExperiment.blocked_iff_generated
#check V13RealLinearAdaptiveQRowExperiment.generated_one_budget_exists_target_row
#check V13RealLinearAdaptiveQRowExperiment.generated_one_budget_exists_singleton_target_row
#check V13RealLinearAdaptiveQRowExperiment.targetRows_nonempty_of_generated_one_budget
#check v13RealLinearUniformCausalOneRowGenerated_exists_targetRow_cylinder
#check v13RealLinearUniformCausalOneRowGenerated_exists_generated_cylinder
#check v13RealLinearAdaptiveQRowBlockedGeneratedEquiv
#check v13RealLinearAdaptiveQRowBlockedMass_eq_generatedMass
#check v13RealLinearAdaptiveQRowGeneratedMass_le_one
#check v13RealLinear_qrow_one_le_epsilon_of_m_le_q
#check v13RealLinearAdaptiveQRowGeneratedMass_eq_zero_of_zero_budget
#check v13RealLinearAdaptiveRowSpanCountingBound_of_m_le_q
#check V13RealLinearAdaptiveRowSpanCountingBound
#check V13RealLinearUniformInvertibleRowSpanCountingBound
#check v13RealLinearUniformInvertibleRowSpanCountingBound_of_zero_budget
#check v13RealLinearUniformInvertibleRowSpanCountingBound_of_m_le_q
#check V13RealLinearUniformCausalRowSpanCountingBound
#check v13RealLinearUniformCausalRowSpanCountingBound_of_generated_counting
#check v13RealLinearUniformCausalRowSpanCountingBound_of_zero_budget
#check v13RealLinearUniformCausalRowSpanCountingBound_of_m_le_q
#check v13RealLinear_targetRowObserver_spanCountingBound_fails_two_zero
#check v13RealLinear_targetRowObserver_spanCountingBound_fails_two_zero_unconditional
#check v13RealLinearUniformAdaptiveQRowSuccess
#check V13RealLinearAdaptiveKernelFlipSurchargeBound
#check v13RealLinear_adaptiveKernelFlipSurchargeBound
#check v13RealLinear_adaptive_qrow_success_bound_of_spanCounting
#check V13RealLinearAdaptiveDeferredDecisionGeneratedMassBound
#check V13RealLinearAdaptiveDeferredDecisionCountingBound
#check v13RealLinearAdaptiveDeferredDecisionGeneratedMassBound_of_counting
#check V13RealLinearAdaptiveDeferredDecisionNewCaptureCover
#check V13RealLinearAdaptiveDeferredDecisionNewCaptureCountingBound
#check V13RealLinearAdaptiveDeferredDecisionNewCaptureBound
#check V13RealLinearAdaptiveQRowTraceRealizesBranchRows
#check v13RealLinearAdaptiveQRowBranchRowsTrace
#check v13RealLinearAdaptiveQRowBranchRowsTrace_realizesBranchRows
#check v13RealLinearUniformSequentialQRowTrace
#check v13RealLinearUniformSequentialQRowTrace_realizesBranchRows
#check V13RealLinearAdaptiveQRowTraceFirstNewCapture
#check V13RealLinearAdaptiveQRowTraceFirstCosetHit
#check V13RealLinearAdaptiveQRowTraceCosetHitCountingBound
#check v13RealLinearAdaptiveQRowTraceFirstNewCapture_imp_cosetHit
#check v13RealLinearAdaptiveDeferredDecisionNewCaptureCover_of_rowTrace
#check v13RealLinearAdaptiveDeferredDecisionNewCaptureCountingBound_of_rowTraceCosetHit
#check v13RealLinearAdaptiveDeferredDecisionCountingBound_of_newCapture
#check v13RealLinearAdaptiveDeferredDecisionCountingBound_of_rowTraceNewCapture
#check v13RealLinearAdaptiveDeferredDecisionCountingBound_of_rowTraceCosetHit
#check v13RealLinear_adaptive_qrow_success_bound_of_deferredDecision
#check v13RealLinear_adaptive_qrow_success_bound_of_deferredDecisionCounting
#check v13RealLinear_adaptive_qrow_success_bound_of_deferredDecisionNewCapture
#check v13RealLinear_uniform_adaptive_qrow_success_bound_of_spanCounting
#check v13RealLinear_uniform_causal_qrow_success_bound_of_spanCounting
#check V13RealLinearUniformCausalDeferredDecisionGeneratedMassBound
#check V13RealLinearUniformCausalDeferredDecisionCountingBound
#check V13RealLinearUniformCausalDeferredDecisionNewCaptureBound
#check v13RealLinearUniformCausalQRowBranchRowsTrace
#check v13RealLinearUniformCausalQRowBranchRowsTrace_realizesBranchRows
#check V13RealLinearUniformCausalDeferredDecisionTraceCosetHitCountingBound
#check V13RealLinearUniformSequentialDeferredDecisionTraceCosetHitCountingBound
#check V13RealLinearUniformCausalDeferredDecisionCountingBound_of_traceCosetHit
#check V13RealLinearUniformSequentialDeferredDecisionCountingBound_of_traceCosetHit
#check V13RealLinearUniformCausalDeferredDecisionCountingBound_of_newCapture
#check v13RealLinear_uniform_causal_qrow_success_bound_of_deferredDecision
#check v13RealLinear_uniform_causal_qrow_success_bound_of_deferredDecisionCounting
#check v13RealLinear_uniform_causal_qrow_success_bound_of_deferredDecisionNewCapture
#check v13RealLinearUniformSequentialQRowSuccess
#check v13RealLinear_uniform_sequential_qrow_success_bound_of_transfer
#check v13RealLinear_uniform_sequential_qrow_success_bound_of_deferredDecisionTraceCosetHit
#check v13RealLinear_uniform_zero_row_success_bound
#check v13RealLinear_uniform_causal_zero_row_success_bound
#check v13RealLinear_uniform_high_budget_success_bound
#check v13RealLinear_uniform_causal_high_budget_success_bound
#check V13RealLinearUniformCausalLowPositiveRowSpanCountingBound
#check V13RealLinearUniformCausalLowPositiveCompletionCountingBound
#check V13RealLinearAdaptiveQRowGeneratedCoefficient
#check V13RealLinearAdaptiveQRowGeneratedCoefficientFiber
#check V13RealLinearRowsTargetCoefficient
#check v13RealLinearRowsTargetCoefficient_subsingleton
#check v13RealLinear_rowsTargetCoefficient_card_le_one
#check v13RealLinear_rowsTargetCoefficient_card_eq_one_of_rowsGenerateTarget
#check v13RealLinear_rowsTargetCoefficient_card_eq_zero_of_not_rowsGenerateTarget
#check V13RealLinearAdaptiveQRowGeneratedTargetCoefficientFiber
#check V13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetCell
#check V13RealLinearAdaptiveQRowRowsetFiber
#check V13RealLinearBudgetedRowset
#check V13RealLinearRowsTranscriptSpace
#check V13RealLinearAdaptiveQRowRowsetTranscriptCell
#check V13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetProductCell
#check V13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCell
#check V13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCellCorrect
#check v13RealLinearAdaptiveQRowRowsetFiber_card_eq_zero_of_q_lt_rows_card
#check v13RealLinearAdaptiveQRowRowsetFiberEquivSigmaTranscriptCell
#check v13RealLinearAdaptiveQRowRowsetFiber_card_eq_sum_transcriptCells
#check V13RealLinearRowsUnreadAssignment
#check v13RealLinearRowsUnreadAssignment_card
#check v13RealLinearRowsTranscriptCompletion
#check v13RealLinearRowsTranscriptCompletion_of_mem
#check v13RealLinearRowsTranscriptCompletion_of_not_mem
#check v13RealLinearAdaptiveQRowRowsetTranscriptCellToUnreadAssignment
#check v13RealLinearAdaptiveQRowRowsetTranscriptCell_card_le_unreadAssignments
#check V13RealLinearAdaptiveQRowGeneratedFiber
#check v13RealLinearAdaptiveQRowGeneratedEquivSigmaFiber
#check v13RealLinearAdaptiveQRowGenerated_card_eq_sum_fibers
#check V13RealLinearAdaptiveQRowGeneratedBudgetedRowsetCell
#check v13RealLinearAdaptiveQRowGeneratedFiber_card_eq_sum_budgetedRowsetCells
#check v13RealLinearAdaptiveQRowGeneratedBudgetedRowsetCellEquivFiber
#check v13RealLinearAdaptiveQRowGeneratedBudgetedRowsetCell_card_eq_fiber_of_rowsGenerateTarget
#check v13RealLinearAdaptiveQRowGeneratedBudgetedRowsetCell_card_eq_zero_of_not_rowsGenerateTarget
#check v13RealLinearAdaptiveQRow_budgetedRowsetCell_sum_eq_targetGeneratingRowsetFibers
#check v13RealLinearAdaptiveQRowGenerated_card_eq_sum_targetGeneratingBudgetedRowsetFibers
#check v13RealLinearAdaptiveQRow_rowsetProduct_eq_sum_transcriptCells
#check v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCell_card_eq_product
#check v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCell_card_le_transcriptCell
#check v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCell_card_eq_zero_or_transcriptCell
#check v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCell_card_eq_transcriptCell_of_rowsGenerateTarget
#check v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCell_card_eq_zero_of_not_rowsGenerateTarget
#check v13RealLinearAdaptiveQRow_budgetedRowsetTranscriptProductCell_sum_eq_targetGeneratingTranscriptCells
#check v13RealLinearAdaptiveQRow_rowsetProduct_eq_sum_transcriptProductCells
#check v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCell_generated
#check v13RealLinearUniformCausal_rowsetTranscriptCell_branch_eq
#check v13RealLinearRowsTargetCoefficient_target_eq_of_rowsTranscript_eq
#check v13RealLinearUniformCausal_rowsetTranscriptCell_target_eq_of_coefficient
#check v13RealLinearUniformCausal_rowsetTranscriptCell_decision_eq
#check v13RealLinearUniformCausal_rowsetTranscriptCell_correct_iff_of_coefficient
#check v13RealLinearUniformCausal_rowsetTranscriptProductCell_correct_iff
#check v13RealLinearUniformCausal_rowsetTranscriptProductCell_correctCard_eq_zero_or_card
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCellAverageBound
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCellAverageBound_of_productCellAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductCellAverageBound_of_targetGeneratingTranscriptCellAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductCellAverageBound_iff_targetGeneratingTranscriptCellAverage
#check V13RealLinearUniformCausalTargetGeneratingBudgetedRowsetTranscriptCylinderIndex
#check V13RealLinearUniformCausalTargetGeneratingBudgetedRowsetTranscriptCylinder
#check V13RealLinearUniformCausalActiveTargetGeneratingBudgetedRowsetTranscriptCylinderIndex
#check v13RealLinearUniformCausalActiveTargetGeneratingBudgetedRowsetTranscriptCylinderIndexFintype
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderCapacityBound
#check v13RealLinearUniformCausal_targetGeneratingBudgetedRowsetTranscriptCylinder_sum_eq
#check v13RealLinearUniformCausal_targetGeneratingBudgetedRowsetTranscriptCylinder_card_le_capacity
#check v13RealLinearRowsUnreadAssignmentToActiveTargetGeneratingBudgetedRowsetTranscriptCylinder
#check v13RealLinearUniformCausal_activeTargetGeneratingBudgetedRowsetTranscriptCylinder_capacity_le_card
#check v13RealLinearUniformCausal_activeTargetGeneratingBudgetedRowsetTranscriptCylinder_card_eq_capacity
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound_of_capacity
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderCapacityBound_of_packing
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderCapacityBound_iff_packing
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound_of_transcriptCellAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCellAverageBound_of_cylinderPacking
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound_iff_transcriptCellAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetFiberAverageBound_of_cylinderPacking
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound_of_fiberAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound_iff_fiberAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetFiberAverageBound
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCellAverageBound_of_fiberAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetFiberAverageBound_of_transcriptCellAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCellAverageBound_iff_fiberAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetFiberAverageBound_of_completionCounting
#check V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_targetGeneratingBudgetedRowsetFiberAverage
#check V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_iff_targetGeneratingBudgetedRowsetFiberAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductCellCorrectAverageBound
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductCellCorrectAverageBound_of_productCellAverage
#check v13RealLinearRowsTargetCoefficientEmbedding
#check v13RealLinear_rowsTargetCoefficient_card_le_rowCombination
#check v13RealLinear_rowsTargetCoefficient_card_le_of_rows_card_le
#check v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetCellEquivProduct
#check v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetCell_card_eq_product
#check v13RealLinearAdaptiveQRow_rowsetProduct_sum_eq_budgeted
#check v13RealLinearAdaptiveQRowGeneratedTargetCoefficientFiberEquivSigmaRowsetCell
#check v13RealLinearAdaptiveQRowGeneratedTargetCoefficientFiber_card_eq_sum_rowsetCells
#check v13RealLinearAdaptiveQRowGeneratedCoefficientFiberEquivTargetCoefficientFiber
#check v13RealLinearAdaptiveQRowGeneratedCoefficientFiber_card_eq_targetCoefficientFiber
#check v13RealLinearAdaptiveQRowGeneratedCoefficient_card_eq_sum_fibers
#check v13RealLinearAdaptiveQRowGenerated_card_le_coefficient
#check V13RealLinearUniformCausalLowPositiveCoefficientCountingBound
#check V13RealLinearUniformCausalLowPositiveFiberCoefficientCountingBound
#check V13RealLinearUniformCausalTwoOrMoreRowSpanCountingBound
#check V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound
#check V13RealLinearUniformCausalTwoOrMoreDeferredDecisionCountingBound
#check V13RealLinearUniformCausalTwoOrMoreDeferredDecisionNewCaptureBound
#check V13RealLinearUniformCausalTwoOrMoreDeferredDecisionTraceCosetHitCountingBound
#check V13RealLinearUniformCausalTwoOrMoreDeferredDecisionCountingBound_of_newCapture
#check V13RealLinearUniformCausalTwoOrMoreDeferredDecisionCountingBound_of_traceCosetHit
#check V13RealLinearUniformCausalTwoOrMoreDeferredDecisionCountingBound_of_completionCounting
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreDeferredDecisionCountingBound
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreDeferredDecisionNewCaptureBound
#check V13RealLinearUniformCausalTwoOrMoreCoefficientCountingBound
#check V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound
#check V13RealLinearUniformCausalTwoOrMoreFiberAverageCoefficientBound
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientFiberAverageBound
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetAverageBound
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetProductAverageBound
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetProductAverageBound
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductAverageBound
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductCellAverageBound
#check v13RealLinear_f2vec_card
#check v13RealLinearCausalSingleRowObserver
#check v13RealLinearFixedTargetRowOccurrenceZeroEmbedding
#check v13RealLinearFixedTargetRowOccurrence_zero_card_le_two
#check v13RealLinearFixedTargetRowOccurrenceOneOneEmbedding
#check v13RealLinearFixedTargetRowOccurrence_one_one_card_le_two
#check v13RealLinearFixedTargetRowOccurrenceZeroOneEmbedding
#check v13RealLinearFixedTargetRowOccurrence_zero_one_card_le_two
#check v13RealLinearFixedTargetRowOccurrenceOneZeroEmbedding
#check v13RealLinearFixedTargetRowOccurrence_one_zero_card_le_two
#check v13RealLinearFixedTargetRowOccurrence_two_card_le_two
#check V13RealLinearZeroAt
#check v13RealLinearZeroAtProdBitEquiv
#check v13RealLinear_zeroAt_card_mul_two
#check V13RealLinearBitAt
#check v13RealLinearBitAtZeroAtEquiv
#check v13RealLinear_bitAt_card_mul_two
#check V13RealLinearUniformFixedTargetRowBitCylinder
#check v13RealLinearFixedTargetRowBitCylinderEquiv
#check v13RealLinearFixedTargetRowBitCylinder_card_eq
#check v13RealLinearZeroAtRowShear
#check v13RealLinearFixedTargetRowOccurrenceZeroAtEmbedding
#check v13RealLinearFixedTargetRowOccurrence_mul_zeroAt_card_le
#check v13RealLinearFixedTargetRowOccurrence_counting
#check v13RealLinearFixedTargetRowBitCylinder_card_le_equiv
#check v13RealLinearFixedTargetRowBitCylinder_counting
#check v13RealLinearRowIndexedFixedTargetRowOccurrenceWorld_card_eq_sum
#check v13RealLinearRowIndexedFixedTargetRowOccurrenceWorld_card_le
#check v13RealLinearUniformOneRowGeneratedToRowIndexedFixedOccurrence
#check v13RealLinearUniformOneRowGenerated_card_le_rowIndexedFixedOccurrence
#check v13RealLinearUniformOneRowGenerated_counting_with_rowFactor
#check v13RealLinearUniformCausalOneRowGenerated_counting_with_rowFactor
#check V13RealLinearUniformOneRowGeneratedCylinderIndex
#check V13RealLinearUniformOneRowGeneratedCylinderCover
#check v13RealLinearUniformOneRowGeneratedToActiveBitCylinderCover
#check v13RealLinearUniformOneRowGenerated_card_le_activeBitCylinderCover
#check v13RealLinearUniformOneRowGenerated_counting_by_activeBitCylinderIndex
#check v13RealLinearUniformCausalOneRowGenerated_counting_by_activeBitCylinderIndex
#check V13RealLinearUniformOneRowGeneratedRowIndex
#check v13RealLinearUniformCausalOneRow_branchRows_ne_empty_of_singletonWitness
#check v13RealLinearUniformCausalOneRow_branchRows_ne_empty_of_activeRowIndex
#check v13RealLinearUniformCausalOneRow_branchRows_eq_singleton_of_activeRowIndex
#check v13RealLinearNoTargetRowShear_not_generated_one_budget
#check v13RealLinearNoTargetRowShear_branchRows_eq_singleton_of_activeRowIndex
#check V13RealLinearUniformCausalOneRowNoTargetRestMismatchExclusion
#check v13RealLinearUniformCausalOneRow_restActiveSingleton_collision_of_bridge
#check v13RealLinearNoTargetRowShear_branchRows_ne_of_activeRowIndex_of_bridgeFamily
#check v13RealLinearNoTargetHardBridgeMap
#check v13RealLinearNoTargetHardBridgeMap_activeRow
#check v13RealLinearNoTargetHardBridgeMap_targetRow
#check v13RealLinearNoTargetRowShear_exists_bridgeMap_for_rows
#check v13RealLinearNoTargetRowShear_branchRows_ne_of_activeRowIndex_of_bridgeMapFamily
#check v13RealLinearNoTargetRowShear_branchRows_ne_of_activeRowIndex
#check V13RealLinearUniformCausalOneRowNoTargetRestMismatchExclusion_proved
#check v13RealLinearUniformOneRowGeneratedCylinderIndexToRowBit
#check v13RealLinearUniformOneRowGeneratedCylinderIndex_card_le_rowIndex_mul_two
#check V13RealLinearUniformCausalOneRowActiveBitCylinderIndexBound
#check V13RealLinearUniformCausalOneRowActiveRowIndexBound
#check V13RealLinearUniformCausalOneRowActiveRowPairExclusion
#check V13RealLinearUniformCausalOneRowActiveRowIndexBound_of_pairExclusion
#check V13RealLinearUniformCausalOneRowActiveRowPairExclusion_of_indexBound
#check V13RealLinearUniformCausalOneRowActiveRowIndexBound_iff_pairExclusion
#check V13RealLinearUniformCausalOneRowActiveBitCylinderIndexBound_of_rowIndexBound
#check V13RealLinearUniformCausalOneRowActiveRowPairExclusion_of_noTargetRestMismatch
#check V13RealLinearUniformCausalOneRowActiveRowIndexBound_of_noTargetRestMismatch
#check V13RealLinearUniformCausalOneRowActiveBitCylinderIndexBound_of_noTargetRestMismatch
#check v13RealLinearUniformCausalOneRowGenerated_counting_of_activeBitCylinderIndex_le_two
#check v13RealLinearUniformCausalOneRowGenerated_counting_of_activeBitCylinderIndexBound
#check v13RealLinearUniformCausalOneRowGenerated_counting_of_activeRowIndexBound
#check v13RealLinearUniformCausalOneRowGenerated_counting_of_activeRowPairExclusion
#check v13RealLinearUniformCausalOneRowGenerated_counting_of_noTargetRestMismatch
#check v13RealLinearUniformCausalOneRowRowSpanCountingBound_of_activeBitCylinderIndexBound
#check v13RealLinearUniformCausalOneRowRowSpanCountingBound_of_activeRowIndexBound
#check v13RealLinearUniformCausalOneRowRowSpanCountingBound_of_activeRowPairExclusion
#check v13RealLinearUniformCausalOneRowRowSpanCountingBound_of_noTargetRestMismatch
#check v13RealLinear_uniform_causal_one_row_success_bound_of_activeBitCylinderIndexBound
#check v13RealLinear_uniform_causal_one_row_success_bound_of_activeRowIndexBound
#check v13RealLinear_uniform_causal_one_row_success_bound_of_activeRowPairExclusion
#check v13RealLinear_uniform_causal_one_row_success_bound_of_noTargetRestMismatch
#check V13RealLinearUniformCausalOneRowActiveRowPairExclusion_proved
#check V13RealLinearUniformCausalOneRowActiveRowIndexBound_proved
#check V13RealLinearUniformCausalOneRowActiveBitCylinderIndexBound_proved
#check v13RealLinearUniformCausalOneRowGenerated_counting_proved
#check v13RealLinearUniformCausalOneRowRowSpanCountingBound_proved
#check v13RealLinear_uniform_causal_one_row_success_bound
#check v13RealLinearUniformCausalOneRowActiveRowIndexBound_two_zero
#check v13RealLinearUniformCausalOneRowActiveBitCylinderIndexBound_two_zero
#check v13RealLinearUniformCausalOneRowGenerated_counting_two_zero
#check v13RealLinearUniformCausalRowSpanCountingBound_one_two_zero
#check v13RealLinear_uniform_causal_qrow_success_bound_one_two_zero
#check v13RealLinear_causalSingleRowGeneratedCoefficientEquivFixedOccurrenceProd
#check v13RealLinear_causalSingleRowGeneratedCoefficient_card_eq
#check V13RealLinearUniformFixedTargetRowOccurrenceCountingBound
#check v13RealLinearUniformFixedTargetRowOccurrenceCountingBound_proved
#check V13RealLinearUniformRepresentativeFixedTargetRowOccurrenceCountingBound
#check V13RealLinearUniformRepresentativeFixedTargetRowOccurrenceCountingBound_of_fixed
#check V13RealLinearUniformFixedTargetRowOccurrenceCountingBound_of_representative
#check V13RealLinearUniformFixedTargetRowOccurrenceCountingBound_iff_representative
#check v13RealLinearUniformRepresentativeFixedTargetRowOccurrenceCountingBound_proved
#check v13RealLinear_causalSingleRow_coefficientCounting_of_fixedTargetRowOccurrenceCounting
#check v13RealLinear_causalSingleRow_coefficientCounting_of_representativeFixedTargetRowOccurrenceCounting
#check v13RealLinear_causalSingleRow_coefficientCounting
#check v13RealLinear_causalSingleRow_generated_counting
#check v13RealLinear_causalSingleRow_rowSpanCountingBound
#check v13RealLinear_causalSingleRow_success_bound
#check v13RealLinear_fixedTargetRowOccurrence_zero_two_counting
#check v13RealLinear_fixedTargetRowOccurrence_two_counting
#check v13RealLinear_causalSingleRow_zero_two_coefficientCounting
#check v13RealLinear_causalSingleRow_two_coefficientCounting
#check v13RealLinearCausalSingleRowIdentityFiberEmbedding
#check v13RealLinearCausalSingleRowIdentityFiber_card_four_le
#check v13RealLinearUniformCausalLowPositiveFiberCoefficientCountingBound_fails_two_identity
#check v13RealLinearUniformCausalLowPositiveCoefficientCountingBound_of_fiberCounting
#check v13RealLinearUniformCausalLowPositiveCompletionCountingBound_of_coefficientCounting
#check v13RealLinearUniformCausalLowPositiveRowSpanCountingBound_of_completionCounting
#check v13RealLinearUniformCausalLowPositiveCompletionCountingBound_of_rowSpanCounting
#check V13RealLinearUniformCausalLowPositiveRowSpanCountingBound_iff_completionCounting
#check V13RealLinearUniformCausalLowPositiveRowSpanCountingBound_of_twoOrMore
#check V13RealLinearUniformCausalLowPositiveCompletionCountingBound_of_twoOrMore
#check V13RealLinearUniformCausalLowPositiveRowSpanCountingBound_of_twoOrMoreBound
#check V13RealLinearUniformCausalTwoOrMoreRowSpanCountingBound_of_lowPositive
#check V13RealLinearUniformCausalLowPositiveRowSpanCountingBound_iff_twoOrMore
#check V13RealLinearUniformCausalLowPositiveCompletionCountingBound_of_twoOrMoreBound
#check V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_lowPositive
#check V13RealLinearUniformCausalLowPositiveCompletionCountingBound_iff_twoOrMore
#check V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_coefficientCounting
#check V13RealLinearUniformCausalLowPositiveCompletionCountingBound_of_twoOrMoreCoefficientCounting
#check V13RealLinearUniformCausalTwoOrMoreCoefficientCountingBound_of_compression
#check V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_counting
#check V13RealLinearUniformCausalTwoOrMoreCoefficientCountingBound_iff_compression
#check V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_coefficientCompression
#check V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_fiberAverage
#check V13RealLinearUniformCausalTwoOrMoreFiberAverageCoefficientBound_of_compression
#check V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_iff_fiberAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientFiberAverageBound_of_fiberAverageCoefficient
#check V13RealLinearUniformCausalTwoOrMoreFiberAverageCoefficientBound_of_targetCoefficientFiberAverage
#check V13RealLinearUniformCausalTwoOrMoreFiberAverageCoefficientBound_iff_targetCoefficientFiberAverage
#check V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_targetCoefficientFiberAverage
#check V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_targetCoefficientFiberAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetAverageBound_of_targetCoefficientFiberAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientFiberAverageBound_of_rowsetAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientFiberAverageBound_iff_rowsetAverage
#check V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_targetCoefficientRowsetAverage
#check V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_targetCoefficientRowsetAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetProductAverageBound_of_rowsetAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetAverageBound_of_productAverage
#check V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetAverageBound_iff_productAverage
#check V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_targetCoefficientRowsetProductAverage
#check V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_targetCoefficientRowsetProductAverage
#check V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_targetCoefficientBudgetedRowsetTranscriptProductCellAverage
#check V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_targetCoefficientBudgetedRowsetTranscriptProductCellAverage
#check V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_fiberAverageCoefficient
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetGeneratingBudgetedRowsetTranscriptCellAverageBound
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetGeneratingBudgetedRowsetFiberAverageBound
#check v13RealLinear_uniform_causal_qrow_success_bound_of_lowPositiveSpanCounting
#check v13RealLinear_uniform_causal_qrow_success_bound_of_completionCounting
#check v13RealLinear_uniform_causal_qrow_success_bound_of_coefficientCounting
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreSpanCounting
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreCompletionCounting
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreRowSpanCountingBound
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreCompletionCountingBound
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreCoefficientCountingBound
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreCoefficientCompressionBound
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreFiberAverageCoefficientBound
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientFiberAverageBound
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientRowsetAverageBound
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientRowsetProductAverageBound
#check v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductCellAverageBound
#check v13RealLinear_qrow_epsilon_nonnegative

def v13RealLinearQRowBoundRegression_staticConstant :
    V13RealLinearStaticRowObserver 2 0 where
  rows := ∅
  decide := fun _ => 0
  readBudget := by simp
  factorsThroughRows := by
    intro omega₀ omega₁ hsame
    rfl

def v13RealLinearQRowBoundRegression_adaptiveConstant :
    V13RealLinearAdaptiveRowObserver 2 0 where
  Branch := Unit
  branch := fun _ => ()
  staticBranch := fun _ => v13RealLinearQRowBoundRegression_staticConstant
  decide := fun _ => 0
  branchDecision := by
    intro omega
    rfl
  branchStable := by
    intro A x w b hbranch hkernel
    cases b
    rfl

def v13RealLinearQRowBoundRegression_causalConstant :
    V13RealLinearCausalRowObserver 2 0 where
  Branch := Unit
  branch := fun _ => ()
  rows := fun _ => ∅
  decideFromTranscript := fun _ _ => 0
  readBudget := by
    intro b
    cases b
    simp
  branchCausal := by
    intro public₀ public₁ b hbranch htranscript
    cases b
    rfl

def v13RealLinearQRowBoundRegression_experiment :
    V13RealLinearAdaptiveQRowExperiment 2 0 Unit where
  sampleA := fun _ => v13RealLinearIdentity 2
  observer := v13RealLinearQRowBoundRegression_adaptiveConstant

theorem v13RealLinearQRowBoundRegression_epsilon_nonnegative :
    0 ≤ v13RealLinearQRowEpsilon 0 2 :=
  v13RealLinear_qrow_epsilon_nonnegative 0 2

theorem v13RealLinearQRowBoundRegression_conditional_shape
    (hcount :
      V13RealLinearAdaptiveRowSpanCountingBound
        v13RealLinearQRowBoundRegression_experiment 0) :
    v13RealLinearAdaptiveQRowSuccess
        v13RealLinearQRowBoundRegression_experiment 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_adaptive_qrow_success_bound_of_spanCounting
      v13RealLinearQRowBoundRegression_experiment 0 hcount

theorem v13RealLinearQRowBoundRegression_uniform_conditional_shape
    (hcount :
      V13RealLinearUniformInvertibleRowSpanCountingBound
        v13RealLinearQRowBoundRegression_adaptiveConstant 0) :
    v13RealLinearUniformAdaptiveQRowSuccess
        v13RealLinearQRowBoundRegression_adaptiveConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_adaptive_qrow_success_bound_of_spanCounting
      v13RealLinearQRowBoundRegression_adaptiveConstant 0 hcount

theorem v13RealLinearQRowBoundRegression_causal_zero_shape :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_zero_row_success_bound
      v13RealLinearQRowBoundRegression_causalConstant 0

theorem v13RealLinearQRowBoundRegression_causal_global_shape
    (hcount : V13RealLinearUniformCausalLowPositiveRowSpanCountingBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_lowPositiveSpanCounting
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem v13RealLinearQRowBoundRegression_causal_completion_shape
    (hcount : V13RealLinearUniformCausalLowPositiveCompletionCountingBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_completionCounting
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem v13RealLinearQRowBoundRegression_causal_coefficient_shape
    (hcount : V13RealLinearUniformCausalLowPositiveCoefficientCountingBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_coefficientCounting
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem v13RealLinearQRowBoundRegression_causal_fiber_shape
    (hcount :
      V13RealLinearUniformCausalLowPositiveFiberCoefficientCountingBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_coefficientCounting
      (v13RealLinearUniformCausalLowPositiveCoefficientCountingBound_of_fiberCounting
        hcount)
      v13RealLinearQRowBoundRegression_causalConstant 0

theorem v13RealLinearQRowBoundRegression_causal_targetCoefficientFiber_shape
    (hcount :
      V13RealLinearUniformCausalTwoOrMoreTargetCoefficientFiberAverageBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientFiberAverageBound
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem v13RealLinearQRowBoundRegression_causal_targetCoefficientRowset_shape
    (hcount :
      V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetAverageBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientRowsetAverageBound
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem v13RealLinearQRowBoundRegression_causal_targetCoefficientRowsetProduct_shape
    (hcount :
      V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetProductAverageBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientRowsetProductAverageBound
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem v13RealLinearQRowBoundRegression_causal_targetCoefficientBudgetedRowsetProduct_shape
    (hcount :
      V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetProductAverageBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientBudgetedRowsetProductAverageBound
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem
    v13RealLinearQRowBoundRegression_causal_targetCoefficientBudgetedRowsetTranscriptProduct_shape
    (hcount :
      V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductAverageBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductAverageBound
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem
    v13RealLinearQRowBoundRegression_causal_targetCoefficientBudgetedRowsetTranscriptProductCell_shape
    (hcount :
      V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductCellAverageBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductCellAverageBound
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem
    v13RealLinearQRowBoundRegression_causal_targetGeneratingBudgetedRowsetTranscriptCell_shape
    (hcount :
      V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCellAverageBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetGeneratingBudgetedRowsetTranscriptCellAverageBound
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem
    v13RealLinearQRowBoundRegression_causal_targetGeneratingBudgetedRowsetTranscriptCylinder_shape
    (hcount :
      V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem
    v13RealLinearQRowBoundRegression_causal_targetGeneratingBudgetedRowsetTranscriptCylinderCapacity_shape
    (hcount :
      V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderCapacityBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderCapacityBound
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem
    v13RealLinearQRowBoundRegression_causal_targetGeneratingBudgetedRowsetFiber_shape
    (hcount :
      V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetFiberAverageBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetGeneratingBudgetedRowsetFiberAverageBound
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

#print axioms v13RealLinear_adaptiveKernelFlipSurchargeBound
#print axioms v13RealLinear_rowCombination_card_le_for_branch
#print axioms v13RealLinear_rowsBlockTarget_of_rowsGenerateTarget
#print axioms v13RealLinear_rowsGenerateTarget_of_rowsBlockTarget
#print axioms v13RealLinear_rowsBlockTarget_iff_rowsGenerateTarget
#print axioms v13RealLinear_rowsGenerateTarget_singleton_iff
#print axioms v13RealLinear_targetRows_card_le_one
#print axioms v13RealLinearZeroAtRowShear_targetRows_empty_of_nonzero
#print axioms v13FinSpare_ne
#print axioms v13RealLinearNoTargetRowShear_targetRows_empty
#print axioms v13RealLinearNoTargetRowShear_rowFunctional_ne_target
#print axioms v13RealLinearNoTargetRowShear_row_not_mem_targetRows
#print axioms v13RealLinearNoTargetRowShear_rowFunctional_ne_activeTarget
#print axioms v13RealLinearRowsTranscript_singleton_eq_of_row_match
#print axioms v13RealLinearNoTargetRowShear_bridgeTranscripts_of_row_matches
#print axioms v13RealLinearZeroAtShearSum_singleBit
#print axioms v13RealLinearNoTargetRowShear_exists_bridgeX_for_row_target_bits
#print axioms v13RealLinearNoTargetRowShear_branchRows_ne_of_activeRowIndex_of_bridgeMapFamily
#print axioms v13RealLinear_targetRowObserver_generated_iff_targetRows_nonempty
#print axioms v13RealLinearUniformTargetRowOccurrence_card_four_le
#print axioms v13RealLinearSwapShear10_targetRows_zero_empty
#print axioms V13RealLinearAdaptiveQRowExperiment.not_generated_of_targetRows_empty
#print axioms v13RealLinear_fin2_rows_card_le_one_cases
#print axioms v13RealLinearSwapShear10_not_generated_one_budget
#print axioms v13RealLinearSwapShear10_branchRows_cases
#print axioms v13RealLinearSwapShear10_branchRows_ne_empty_of_singletonWitness
#print axioms v13RealLinearSwapShear10_branchRows_ne_empty_of_activeRowIndex
#print axioms v13RealLinearSwapShear10_branchRows_ne_zero_of_singletonOneWitness
#print axioms v13RealLinearSwapShear10_branchRows_ne_zero_of_activeRowOne
#print axioms v13RealLinearSwapShear10_branchRows_ne_one_of_singletonZeroWitness
#print axioms v13RealLinearSwapShear10_branchRows_ne_one_of_activeRowZero
#print axioms v13RealLinearUniformCausalOneRowActiveRowPairExclusion_two_zero
#print axioms v13RealLinearShear01_targetRows_one_empty
#print axioms v13RealLinearShear01_not_generated_one_budget_one
#print axioms v13RealLinearShear01_branchRows_cases
#print axioms v13RealLinearShear01_branchRows_ne_empty_of_singletonWitness_one
#print axioms v13RealLinearShear01_branchRows_ne_empty_of_activeRowIndex_one
#print axioms v13RealLinearShear01_branchRows_ne_zero_of_singletonOneWitness_one
#print axioms v13RealLinearShear01_branchRows_ne_zero_of_activeRowOne_one
#print axioms v13RealLinearShear01_branchRows_ne_one_of_singletonZeroWitness_one
#print axioms v13RealLinearShear01_branchRows_ne_one_of_activeRowZero_one
#print axioms v13RealLinearUniformCausalOneRowActiveRowPairExclusion_two_one
#print axioms v13RealLinearUniformTargetRowOccurrenceMass_two_zero_gt_half
#print axioms v13RealLinear_f2_equiv_two_card_le_six
#print axioms v13RealLinearUniformTargetRowOccurrenceMass_two_zero_gt_half_unconditional
#print axioms v13RealLinear_targetRowObserverGenerated_card_eq
#print axioms v13RealLinear_targetRowObserverGeneratedMass_eq_occurrenceMass
#print axioms V13RealLinearAdaptiveQRowExperiment.blocked_iff_generated
#print axioms V13RealLinearCausalRowObserver.branch_eq_of_same_branchRowsTranscript
#print axioms V13RealLinearAdaptiveQRowExperiment.generated_one_budget_exists_target_row
#print axioms V13RealLinearAdaptiveQRowExperiment.generated_one_budget_exists_singleton_target_row
#print axioms V13RealLinearAdaptiveQRowExperiment.targetRows_nonempty_of_generated_one_budget
#print axioms v13RealLinearUniformCausalOneRowGenerated_exists_targetRow_cylinder
#print axioms v13RealLinearUniformCausalOneRowGenerated_exists_generated_cylinder
#print axioms v13RealLinearAdaptiveQRowBlockedMass_eq_generatedMass
#print axioms v13RealLinearAdaptiveQRowGeneratedMass_le_one
#print axioms v13RealLinear_qrow_one_le_epsilon_of_m_le_q
#print axioms v13RealLinearAdaptiveQRowGeneratedMass_eq_zero_of_zero_budget
#print axioms v13RealLinearUniformInvertibleRowSpanCountingBound_of_zero_budget
#print axioms v13RealLinearAdaptiveRowSpanCountingBound_of_m_le_q
#print axioms v13RealLinearUniformInvertibleRowSpanCountingBound_of_m_le_q
#print axioms v13RealLinearUniformCausalRowSpanCountingBound_of_generated_counting
#print axioms v13RealLinearUniformCausalRowSpanCountingBound_of_zero_budget
#print axioms v13RealLinearUniformCausalRowSpanCountingBound_of_m_le_q
#print axioms v13RealLinear_targetRowObserver_spanCountingBound_fails_two_zero
#print axioms v13RealLinear_targetRowObserver_spanCountingBound_fails_two_zero_unconditional
#print axioms v13RealLinearQRowDeferredDecisionEpsilon_nonnegative
#print axioms v13RealLinearQRowEpsilon_le_deferredDecisionEpsilon_of_pos
#print axioms v13RealLinear_sum_range_two_pow
#print axioms v13RealLinear_sum_fin_two_pow_mul
#print axioms v13RealLinear_sum_fin_deferredDecisionWeights
#print axioms v13RealLinearSequentialRowRunAux_length
#print axioms v13RealLinearSequentialRowRunAux_add
#print axioms v13RealLinearSequentialRowRunAux_eq_append
#print axioms v13RealLinearSequentialRowRunAux_take_initial
#print axioms v13RealLinearSequentialRowRunAuxWithRowView_length
#print axioms v13RealLinearSequentialRowRunAuxWithRowView_add
#print axioms v13RealLinearSequentialRowPrefixTranscriptOfWithRowView_length
#print axioms v13RealLinearSequentialRowPrefixTranscriptRowsWithRowView_card_le
#print axioms v13RealLinearSequentialRowPrefixTranscriptOfWithRowView_succ
#print axioms v13RealLinearSequentialRowRunAuxWithRowView_congr
#print axioms v13RealLinearSequentialRowRunAuxWithRowView_rows_mono
#print axioms v13RealLinearSequentialRowRunAuxWithRowView_eq_of_final_rows_eq
#print axioms v13RealLinearSequentialRowPrefixTranscriptOfWithRowView_eq_of_final_rows_eq
#print axioms v13RealLinearSequentialRowRunAux_eq_withRowView
#print axioms v13RealLinearSequentialRowPrefixTranscriptOf_eq_withRowView
#print axioms v13RealLinearSequentialRowPrefixTraceOf_eq_withRowView
#print axioms v13RealLinearSequentialRowPrefixTranscriptOf_length
#print axioms v13RealLinearSequentialRowPrefixTraceOf_length
#print axioms v13RealLinearSequentialRowPrefixTranscriptRows_card_le
#print axioms v13RealLinearSequentialRowPrefixTranscriptOf_succ
#print axioms v13RealLinearSequentialRowPrefixTraceOf_succ
#print axioms v13RealLinearSequentialRowTranscriptOf_take_eq_prefix
#print axioms v13RealLinearSequentialRowTraceOf_take_eq_prefix
#print axioms v13RealLinearSequentialRowTranscriptOf_length
#print axioms v13RealLinearSequentialRowTraceOf_length
#print axioms v13RealLinearSequentialRowTranscriptRows_card_le_length
#print axioms v13RealLinearSequentialRowRunAux_rows_mono
#print axioms v13RealLinearRowsTranscript_eq_rowView_of_mem
#print axioms v13RealLinearSequentialRowRunAux_eq_of_final_rowsTranscript_eq
#print axioms v13RealLinearSequentialRowTranscriptOf_eq_of_rowsTranscript_eq
#print axioms V13RealLinearSequentialRowObserver.toCausal
#print axioms v13RealLinearUniformSequentialQRowTrace_realizesBranchRows
#print axioms v13RealLinearSequentialRowTracePrefixRows_eq_prefixTranscriptRows
#print axioms v13RealLinearSequentialRowTraceOf_get_eq_chooseRow
#print axioms v13RealLinearRowTracePrefixRows_succ
#print axioms v13RealLinearRowTraceNewCaptureCover
#print axioms v13RealLinearRowTraceNewCaptureCover_of_traceRows
#print axioms v13RealLinearRowFunctional_injective
#print axioms v13RealLinearFunctional_card
#print axioms v13RealLinearFunctionalTableRowView_of_equiv
#print axioms v13RealLinearFunctionalTableSequentialRowPrefixTranscriptOf_equiv
#print axioms v13RealLinearFunctionalTableSequentialRowPrefixTraceOf_equiv
#print axioms v13RealLinearFunctionalTableSequentialRowPrefixTranscriptOf_update_eq
#print axioms v13RealLinearFunctionalTableSequentialRowPrefixTraceOf_update_eq
#print axioms v13F2LinearEquiv_card_formula
#print axioms v13F2LinearEquiv_card_formula_rat
#print axioms v13RealLinear_gl_density_product_ge_quarter
#print axioms v13RealLinear_density_times_full_product
#print axioms v13F2LinearEquiv_card_density_quarter
#print axioms v13RealLinearRowFunctionalTable_card
#print axioms v13RealLinearRowFunctionalTable_card_le_four_mul_equiv
#print axioms v13RealLinearRowFunctionalTableOfEquiv_injective
#print axioms v13RealLinearFunctionalTableRowsSpan_eq_of_eq_on_rows
#print axioms v13RealLinearFunctionalTableRowsSpanCombination_surjective
#print axioms v13RealLinearFunctionalTableRowsSpan_card_le
#print axioms v13RealLinearFunctionalTableTargetCosetToSpan_injective
#print axioms v13RealLinearFunctionalTableTargetCoset_card_le_span
#print axioms v13RealLinearFunctionalTableTargetCoset_card_le
#print axioms v13RealLinearFunctionalTableSequentialWorldPrefixRows_card_le
#print axioms v13RealLinearFunctionalTableSequentialWorldPrefixTranscript_update_eq
#print axioms v13RealLinearFunctionalTableSequentialWorldPrefixRows_update_eq
#print axioms v13RealLinearFunctionalTableSequentialWorldNextRow_update_eq
#print axioms v13RealLinearFunctionalTableSequentialWorldPrefixRows_succ
#print axioms v13RealLinearFunctionalTableSequentialTargetCosetSigma_card_le
#print axioms v13RealLinearFunctionalTableSequentialFreshTargetCosetHit_card_mul_two_pow_le
#print axioms v13RealLinearTargetFunctional_ne_zero
#print axioms v13RealLinearFunctionalTable_not_rowsGenerateTarget_of_rows_card_zero
#print axioms v13RealLinearFunctionalTable_range_insert
#print axioms v13RealLinearFunctionalTableTargetCosetHit_of_insert_generates
#print axioms v13RealLinearFunctionalTableRowsGenerateTarget_of_rowsGenerateTarget
#print axioms v13RealLinearFunctionalTableSequentialGenerated_freshTargetCosetHit_cover
#print axioms v13RealLinearFunctionalTableSequentialGenerated_card_mul_two_pow_le
#print axioms v13RealLinearUniformSequentialWorldToFunctionalTableWorld_injective
#print axioms v13RealLinearFunctionalTableWorld_card_le_four_mul_uniformWorld
#print axioms v13RealLinearUniformSequentialGenerated_functionalTableGenerated
#print axioms v13RealLinearUniformSequentialGenerated_card_mul_two_pow_le_transfer
#print axioms v13RealLinearUniformSequentialGeneratedMass_le_transfer
#print axioms v13RealLinearFunctionalTableTargetCosetHit_card_mul_functional_le
#print axioms v13RealLinearFunctionalTableTargetCosetHit_card_mul_two_pow_le
#print axioms v13RealLinearFunctionalTableTargetCosetHit_card_mul_two_pow_le_of_rows_card_le
#print axioms v13RealLinearRowsGenerateTarget_iff_targetFunctional_mem_span
#print axioms v13RealLinearFunctionalTableTargetCosetHit_of_rowFunctionalTargetCosetHit
#print axioms v13RealLinear_rowFunctional_range_insert
#print axioms v13RealLinear_rowFunctionalTargetCosetHit_of_insert_generates
#print axioms v13RealLinearRowTraceCosetHit_of_newCapture
#print axioms v13RealLinearRowTraceNewCapture_get_not_mem
#print axioms v13RealLinearFunctionalTableTargetCosetHit_of_rowTraceNewCapture
#print axioms v13RealLinearSequentialRowTraceNewCapture_chooseRow_not_mem
#print axioms v13RealLinearSequentialRowTraceNewCapture_prefixRows_card_le
#print axioms v13RealLinearSequentialRowTraceNewCapture_functionalTableTargetCosetHit
#print axioms v13RealLinearRowsFunctionalSpanCombination_surjective
#print axioms v13RealLinearRowsFunctionalSpan_card_le
#print axioms v13RealLinearRowsFunctionalTargetCosetToSpan_injective
#print axioms v13RealLinearRowsFunctionalTargetCoset_card_le_span
#print axioms v13RealLinearRowsFunctionalTargetCoset_card_le
#print axioms v13RealLinearRowTracePrefixTargetCosetRows_card_le_coset
#print axioms v13RealLinearRowTracePrefixTargetCoset_card_le
#print axioms v13RealLinearRowTracePrefixTargetCosetRows_card_le
#print axioms v13RealLinearAdaptiveQRowBranchRowsTrace_realizesBranchRows
#print axioms v13RealLinearAdaptiveQRowTraceFirstNewCapture_imp_cosetHit
#print axioms v13RealLinearAdaptiveDeferredDecisionGeneratedMassBound_of_counting
#print axioms v13RealLinearAdaptiveDeferredDecisionNewCaptureCover_of_rowTrace
#print axioms v13RealLinearAdaptiveDeferredDecisionNewCaptureCountingBound_of_rowTraceCosetHit
#print axioms v13RealLinearAdaptiveDeferredDecisionCountingBound_of_newCapture
#print axioms v13RealLinearAdaptiveDeferredDecisionCountingBound_of_rowTraceNewCapture
#print axioms v13RealLinearAdaptiveDeferredDecisionCountingBound_of_rowTraceCosetHit
#print axioms v13RealLinear_adaptive_qrow_success_bound_of_spanCounting
#print axioms v13RealLinear_adaptive_qrow_success_bound_of_deferredDecision
#print axioms v13RealLinear_adaptive_qrow_success_bound_of_deferredDecisionCounting
#print axioms v13RealLinear_adaptive_qrow_success_bound_of_deferredDecisionNewCapture
#print axioms v13RealLinear_uniform_adaptive_qrow_success_bound_of_spanCounting
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_spanCounting
#print axioms v13RealLinearUniformCausalQRowBranchRowsTrace_realizesBranchRows
#print axioms V13RealLinearUniformCausalDeferredDecisionCountingBound_of_traceCosetHit
#print axioms V13RealLinearUniformSequentialDeferredDecisionCountingBound_of_traceCosetHit
#print axioms V13RealLinearUniformCausalDeferredDecisionCountingBound_of_newCapture
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_deferredDecision
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_deferredDecisionCounting
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_deferredDecisionNewCapture
#print axioms v13RealLinear_uniform_sequential_qrow_success_bound_of_transfer
#print axioms v13RealLinear_uniform_sequential_qrow_success_bound_of_deferredDecisionTraceCosetHit
#print axioms v13RealLinear_uniform_zero_row_success_bound
#print axioms v13RealLinear_uniform_causal_zero_row_success_bound
#print axioms v13RealLinear_uniform_high_budget_success_bound
#print axioms v13RealLinear_uniform_causal_high_budget_success_bound
#print axioms v13RealLinearAdaptiveQRowGeneratedCoefficient_card_eq_sum_fibers
#print axioms v13RealLinearAdaptiveQRowGenerated_card_le_coefficient
#print axioms v13RealLinear_f2vec_card
#print axioms v13RealLinearFixedTargetRowOccurrence_card_eq_of_swap
#print axioms v13RealLinearFixedTargetRowOccurrence_zero_card_le_two
#print axioms v13RealLinearFixedTargetRowOccurrence_two_card_le_two
#print axioms v13RealLinearFixedTargetRowOccurrence_counting
#print axioms v13RealLinear_bitAt_card_mul_two
#print axioms v13RealLinearFixedTargetRowBitCylinder_card_eq
#print axioms v13RealLinearFixedTargetRowBitCylinder_card_le_equiv
#print axioms v13RealLinearFixedTargetRowBitCylinder_counting
#print axioms v13RealLinearRowIndexedFixedTargetRowOccurrenceWorld_card_le
#print axioms v13RealLinearUniformOneRowGenerated_card_le_rowIndexedFixedOccurrence
#print axioms v13RealLinearUniformOneRowGenerated_counting_with_rowFactor
#print axioms v13RealLinearUniformCausalOneRowGenerated_counting_with_rowFactor
#print axioms v13RealLinearUniformOneRowGenerated_counting_by_activeBitCylinderIndex
#print axioms v13RealLinearUniformCausalOneRowGenerated_counting_by_activeBitCylinderIndex
#print axioms v13RealLinearUniformOneRowGeneratedCylinderIndex_card_le_rowIndex_mul_two
#print axioms v13RealLinearUniformCausalOneRow_branchRows_ne_empty_of_singletonWitness
#print axioms v13RealLinearUniformCausalOneRow_branchRows_ne_empty_of_activeRowIndex
#print axioms v13RealLinearUniformCausalOneRow_branchRows_eq_singleton_of_activeRowIndex
#print axioms v13RealLinearNoTargetRowShear_not_generated_one_budget
#print axioms v13RealLinearNoTargetRowShear_branchRows_eq_singleton_of_activeRowIndex
#print axioms v13RealLinearUniformCausalOneRow_restActiveSingleton_collision_of_bridge
#print axioms v13RealLinearNoTargetRowShear_branchRows_ne_of_activeRowIndex_of_bridgeFamily
#print axioms v13RealLinearNoTargetHardBridgeMap
#print axioms v13RealLinearNoTargetHardBridgeMap_activeRow
#print axioms v13RealLinearNoTargetHardBridgeMap_targetRow
#print axioms v13RealLinearNoTargetRowShear_exists_bridgeMap_for_rows
#print axioms v13RealLinearNoTargetRowShear_branchRows_ne_of_activeRowIndex_of_bridgeMapFamily
#print axioms v13RealLinearNoTargetRowShear_branchRows_ne_of_activeRowIndex
#print axioms V13RealLinearUniformCausalOneRowNoTargetRestMismatchExclusion_proved
#print axioms V13RealLinearUniformCausalOneRowActiveRowIndexBound_iff_pairExclusion
#print axioms V13RealLinearUniformCausalOneRowActiveBitCylinderIndexBound_of_rowIndexBound
#print axioms V13RealLinearUniformCausalOneRowActiveRowPairExclusion_of_noTargetRestMismatch
#print axioms V13RealLinearUniformCausalOneRowActiveRowIndexBound_of_noTargetRestMismatch
#print axioms V13RealLinearUniformCausalOneRowActiveBitCylinderIndexBound_of_noTargetRestMismatch
#print axioms v13RealLinearUniformCausalOneRowGenerated_counting_of_activeBitCylinderIndex_le_two
#print axioms v13RealLinearUniformCausalOneRowGenerated_counting_of_activeBitCylinderIndexBound
#print axioms v13RealLinearUniformCausalOneRowGenerated_counting_of_activeRowIndexBound
#print axioms v13RealLinearUniformCausalOneRowGenerated_counting_of_activeRowPairExclusion
#print axioms v13RealLinearUniformCausalOneRowGenerated_counting_of_noTargetRestMismatch
#print axioms v13RealLinearUniformCausalOneRowRowSpanCountingBound_of_activeBitCylinderIndexBound
#print axioms v13RealLinearUniformCausalOneRowRowSpanCountingBound_of_activeRowIndexBound
#print axioms v13RealLinearUniformCausalOneRowRowSpanCountingBound_of_activeRowPairExclusion
#print axioms v13RealLinearUniformCausalOneRowRowSpanCountingBound_of_noTargetRestMismatch
#print axioms v13RealLinear_uniform_causal_one_row_success_bound_of_activeBitCylinderIndexBound
#print axioms v13RealLinear_uniform_causal_one_row_success_bound_of_activeRowIndexBound
#print axioms v13RealLinear_uniform_causal_one_row_success_bound_of_activeRowPairExclusion
#print axioms v13RealLinear_uniform_causal_one_row_success_bound_of_noTargetRestMismatch
#print axioms V13RealLinearUniformCausalOneRowActiveRowPairExclusion_proved
#print axioms V13RealLinearUniformCausalOneRowActiveRowIndexBound_proved
#print axioms V13RealLinearUniformCausalOneRowActiveBitCylinderIndexBound_proved
#print axioms v13RealLinearUniformCausalOneRowGenerated_counting_proved
#print axioms v13RealLinearUniformCausalOneRowRowSpanCountingBound_proved
#print axioms v13RealLinear_uniform_causal_one_row_success_bound
#print axioms v13RealLinearUniformCausalOneRowActiveRowIndexBound_two_zero
#print axioms v13RealLinearUniformCausalOneRowActiveBitCylinderIndexBound_two_zero
#print axioms v13RealLinearUniformCausalOneRowGenerated_counting_two_zero
#print axioms v13RealLinearUniformCausalRowSpanCountingBound_one_two_zero
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_one_two_zero
#print axioms v13RealLinearUniformCausalOneRowActiveRowIndexBound_two_one
#print axioms v13RealLinearUniformCausalOneRowActiveBitCylinderIndexBound_two_one
#print axioms v13RealLinearUniformCausalOneRowGenerated_counting_two_one
#print axioms v13RealLinearUniformCausalRowSpanCountingBound_one_two_one
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_one_two_one
#print axioms v13RealLinearUniformCausalOneRowActiveRowPairExclusion_two
#print axioms v13RealLinearUniformCausalOneRowActiveRowIndexBound_one_two
#print axioms v13RealLinearUniformCausalOneRowActiveBitCylinderIndexBound_one_two
#print axioms v13RealLinearUniformCausalOneRowGenerated_counting_one_two
#print axioms v13RealLinearUniformCausalRowSpanCountingBound_one_two
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_one_two
#print axioms v13RealLinear_causalSingleRowGeneratedCoefficient_card_eq
#print axioms v13RealLinearUniformFixedTargetRowOccurrenceCountingBound_proved
#print axioms V13RealLinearUniformFixedTargetRowOccurrenceCountingBound_iff_representative
#print axioms v13RealLinearUniformRepresentativeFixedTargetRowOccurrenceCountingBound_proved
#print axioms v13RealLinear_causalSingleRow_coefficientCounting_of_fixedTargetRowOccurrenceCounting
#print axioms v13RealLinear_causalSingleRow_coefficientCounting_of_representativeFixedTargetRowOccurrenceCounting
#print axioms v13RealLinear_causalSingleRow_coefficientCounting
#print axioms v13RealLinear_causalSingleRow_generated_counting
#print axioms v13RealLinear_causalSingleRow_rowSpanCountingBound
#print axioms v13RealLinear_causalSingleRow_success_bound
#print axioms v13RealLinear_fixedTargetRowOccurrence_zero_two_counting
#print axioms v13RealLinear_fixedTargetRowOccurrence_two_counting
#print axioms v13RealLinear_causalSingleRow_zero_two_coefficientCounting
#print axioms v13RealLinear_causalSingleRow_two_coefficientCounting
#print axioms v13RealLinearCausalSingleRowIdentityFiber_card_four_le
#print axioms v13RealLinearUniformCausalLowPositiveFiberCoefficientCountingBound_fails_two_identity
#print axioms v13RealLinearUniformCausalLowPositiveCoefficientCountingBound_of_fiberCounting
#print axioms v13RealLinearUniformCausalLowPositiveCompletionCountingBound_of_coefficientCounting
#print axioms v13RealLinearUniformCausalLowPositiveRowSpanCountingBound_of_completionCounting
#print axioms v13RealLinearUniformCausalLowPositiveCompletionCountingBound_of_rowSpanCounting
#print axioms V13RealLinearUniformCausalLowPositiveRowSpanCountingBound_iff_completionCounting
#print axioms V13RealLinearUniformCausalLowPositiveRowSpanCountingBound_of_twoOrMore
#print axioms V13RealLinearUniformCausalLowPositiveCompletionCountingBound_of_twoOrMore
#print axioms V13RealLinearUniformCausalLowPositiveRowSpanCountingBound_of_twoOrMoreBound
#print axioms V13RealLinearUniformCausalTwoOrMoreRowSpanCountingBound_of_lowPositive
#print axioms V13RealLinearUniformCausalLowPositiveRowSpanCountingBound_iff_twoOrMore
#print axioms V13RealLinearUniformCausalLowPositiveCompletionCountingBound_of_twoOrMoreBound
#print axioms V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_lowPositive
#print axioms V13RealLinearUniformCausalLowPositiveCompletionCountingBound_iff_twoOrMore
#print axioms V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_coefficientCounting
#print axioms V13RealLinearUniformCausalLowPositiveCompletionCountingBound_of_twoOrMoreCoefficientCounting
#print axioms V13RealLinearUniformCausalTwoOrMoreCoefficientCountingBound_of_compression
#print axioms V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_counting
#print axioms V13RealLinearUniformCausalTwoOrMoreCoefficientCountingBound_iff_compression
#print axioms V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_coefficientCompression
#print axioms V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_fiberAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreFiberAverageCoefficientBound_of_compression
#print axioms V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_iff_fiberAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientFiberAverageBound_of_fiberAverageCoefficient
#print axioms V13RealLinearUniformCausalTwoOrMoreFiberAverageCoefficientBound_of_targetCoefficientFiberAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreFiberAverageCoefficientBound_iff_targetCoefficientFiberAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_targetCoefficientFiberAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_targetCoefficientFiberAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetAverageBound_of_targetCoefficientFiberAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientFiberAverageBound_of_rowsetAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientFiberAverageBound_iff_rowsetAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_targetCoefficientRowsetAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_targetCoefficientRowsetAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetProductAverageBound_of_rowsetAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetAverageBound_of_productAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetAverageBound_iff_productAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetProductAverageBound_of_productAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetProductAverageBound_of_budgetedRowsetProductAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientRowsetProductAverageBound_iff_budgetedRowsetProductAverage
#print axioms v13RealLinearUniformCausal_rowsetTranscriptCell_branch_eq
#print axioms v13RealLinearRowsTargetCoefficient_target_eq_of_rowsTranscript_eq
#print axioms v13RealLinearUniformCausal_rowsetTranscriptCell_target_eq_of_coefficient
#print axioms V13RealLinearCausalRowObserver.decision_eq_of_same_branchRowsTranscript
#print axioms v13RealLinearUniformCausal_rowsetTranscriptCell_decision_eq
#print axioms v13RealLinearUniformCausal_rowsetTranscriptCell_correct_iff_of_coefficient
#print axioms v13RealLinearRowsTargetCoefficient_subsingleton
#print axioms v13RealLinear_rowsTargetCoefficient_card_le_one
#print axioms v13RealLinear_rowsTargetCoefficient_card_eq_one_of_rowsGenerateTarget
#print axioms v13RealLinear_rowsTargetCoefficient_card_eq_zero_of_not_rowsGenerateTarget
#print axioms v13RealLinearRowsUnreadAssignment_card
#print axioms v13RealLinearRowsTranscriptCompletion_of_mem
#print axioms v13RealLinearRowsTranscriptCompletion_of_not_mem
#print axioms v13RealLinearAdaptiveQRowRowsetTranscriptCellToUnreadAssignment
#print axioms v13RealLinearAdaptiveQRowRowsetTranscriptCell_card_le_unreadAssignments
#print axioms v13RealLinearAdaptiveQRowGenerated_card_eq_sum_fibers
#print axioms v13RealLinearAdaptiveQRowGeneratedFiber_card_eq_sum_budgetedRowsetCells
#print axioms v13RealLinearAdaptiveQRowGeneratedBudgetedRowsetCell_card_eq_fiber_of_rowsGenerateTarget
#print axioms v13RealLinearAdaptiveQRowGeneratedBudgetedRowsetCell_card_eq_zero_of_not_rowsGenerateTarget
#print axioms v13RealLinearAdaptiveQRow_budgetedRowsetCell_sum_eq_targetGeneratingRowsetFibers
#print axioms v13RealLinearAdaptiveQRowGenerated_card_eq_sum_targetGeneratingBudgetedRowsetFibers
#print axioms v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCell_card_eq_product
#print axioms v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCell_card_le_transcriptCell
#print axioms v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCell_card_eq_zero_or_transcriptCell
#print axioms v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCell_card_eq_transcriptCell_of_rowsGenerateTarget
#print axioms v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCell_card_eq_zero_of_not_rowsGenerateTarget
#print axioms v13RealLinearAdaptiveQRow_budgetedRowsetTranscriptProductCell_sum_eq_targetGeneratingTranscriptCells
#print axioms v13RealLinearAdaptiveQRow_rowsetProduct_eq_sum_transcriptProductCells
#print axioms v13RealLinearAdaptiveQRowGeneratedTargetCoefficientRowsetTranscriptProductCell_generated
#print axioms v13RealLinearUniformCausal_rowsetTranscriptProductCell_correct_iff
#print axioms v13RealLinearUniformCausal_rowsetTranscriptProductCell_correctCard_eq_zero_or_card
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCellAverageBound_of_productCellAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductCellAverageBound_of_targetGeneratingTranscriptCellAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductCellAverageBound_iff_targetGeneratingTranscriptCellAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCellAverageBound_of_fiberAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetFiberAverageBound_of_transcriptCellAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCellAverageBound_iff_fiberAverage
#print axioms v13RealLinearUniformCausal_targetGeneratingBudgetedRowsetTranscriptCylinder_sum_eq
#print axioms v13RealLinearUniformCausal_targetGeneratingBudgetedRowsetTranscriptCylinder_card_le_capacity
#print axioms v13RealLinearUniformCausal_activeTargetGeneratingBudgetedRowsetTranscriptCylinder_capacity_le_card
#print axioms v13RealLinearUniformCausal_activeTargetGeneratingBudgetedRowsetTranscriptCylinder_card_eq_capacity
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound_of_capacity
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderCapacityBound_of_packing
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderCapacityBound_iff_packing
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound_of_transcriptCellAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCellAverageBound_of_cylinderPacking
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound_iff_transcriptCellAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetFiberAverageBound_of_cylinderPacking
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound_of_fiberAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound_iff_fiberAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetGeneratingBudgetedRowsetFiberAverageBound_of_completionCounting
#print axioms V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_targetGeneratingBudgetedRowsetFiberAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_iff_targetGeneratingBudgetedRowsetFiberAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductCellCorrectAverageBound_of_productCellAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductAverageBound_of_budgetedRowsetProductAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetProductAverageBound_of_budgetedRowsetTranscriptProductAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetProductAverageBound_iff_budgetedRowsetTranscriptProductAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductCellAverageBound_of_budgetedRowsetTranscriptProductAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductAverageBound_of_budgetedRowsetTranscriptProductCellAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductAverageBound_iff_budgetedRowsetTranscriptProductCellAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_targetCoefficientRowsetProductAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_targetCoefficientRowsetProductAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreDeferredDecisionCountingBound_of_traceCosetHit
#print axioms V13RealLinearUniformCausalTwoOrMoreDeferredDecisionCountingBound_of_newCapture
#print axioms V13RealLinearUniformCausalTwoOrMoreDeferredDecisionCountingBound_of_completionCounting
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreDeferredDecisionCountingBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreDeferredDecisionNewCaptureBound
#print axioms V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_targetCoefficientBudgetedRowsetProductAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_targetCoefficientBudgetedRowsetProductAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_targetCoefficientBudgetedRowsetTranscriptProductAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_targetCoefficientBudgetedRowsetTranscriptProductAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreCoefficientCompressionBound_of_targetCoefficientBudgetedRowsetTranscriptProductCellAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_targetCoefficientBudgetedRowsetTranscriptProductCellAverage
#print axioms V13RealLinearUniformCausalTwoOrMoreCompletionCountingBound_of_fiberAverageCoefficient
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_lowPositiveSpanCounting
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_completionCounting
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_coefficientCounting
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreSpanCounting
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreCompletionCounting
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreRowSpanCountingBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreCompletionCountingBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreCoefficientCountingBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreCoefficientCompressionBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreFiberAverageCoefficientBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientFiberAverageBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientRowsetAverageBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientRowsetProductAverageBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientBudgetedRowsetProductAverageBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductAverageBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetCoefficientBudgetedRowsetTranscriptProductCellAverageBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetGeneratingBudgetedRowsetTranscriptCellAverageBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetGeneratingBudgetedRowsetFiberAverageBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderPackingBound
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_twoOrMoreTargetGeneratingBudgetedRowsetTranscriptCylinderCapacityBound
#print axioms v13RealLinear_qrow_epsilon_nonnegative
#print axioms v13RealLinearQRowBoundRegression_conditional_shape
#print axioms v13RealLinearQRowBoundRegression_uniform_conditional_shape
#print axioms v13RealLinearQRowBoundRegression_causal_zero_shape
#print axioms v13RealLinearQRowBoundRegression_causal_global_shape
#print axioms v13RealLinearQRowBoundRegression_causal_completion_shape
#print axioms v13RealLinearQRowBoundRegression_causal_coefficient_shape
#print axioms v13RealLinearQRowBoundRegression_causal_fiber_shape
#print axioms v13RealLinearQRowBoundRegression_causal_targetCoefficientFiber_shape
#print axioms v13RealLinearQRowBoundRegression_causal_targetCoefficientRowset_shape
#print axioms v13RealLinearQRowBoundRegression_causal_targetCoefficientRowsetProduct_shape
#print axioms v13RealLinearQRowBoundRegression_causal_targetCoefficientBudgetedRowsetProduct_shape
#print axioms v13RealLinearQRowBoundRegression_causal_targetCoefficientBudgetedRowsetTranscriptProduct_shape
#print axioms v13RealLinearQRowBoundRegression_causal_targetGeneratingBudgetedRowsetTranscriptCell_shape
#print axioms v13RealLinearQRowBoundRegression_causal_targetGeneratingBudgetedRowsetTranscriptCylinder_shape
#print axioms v13RealLinearQRowBoundRegression_causal_targetGeneratingBudgetedRowsetTranscriptCylinderCapacity_shape
#print axioms v13RealLinearQRowBoundRegression_causal_targetGeneratingBudgetedRowsetFiber_shape

end Mettapedia.Computability.PNP
