import Mettapedia.Computability.PNP.V13RealRungOneQRowBound

namespace Mettapedia.Computability.PNP

set_option autoImplicit false

#check V13RealLinearAdaptiveQRowExperiment
#check V13RealLinearCausalRowObserver
#check V13RealLinearCausalRowObserver.staticBranch
#check V13RealLinearCausalRowObserver.toAdaptive
#check v13RealLinearUniformCausalQRowExperiment
#check v13RealLinearAdaptiveQRowSuccess
#check v13RealLinearUniformCausalQRowSuccess
#check v13RealLinearAdaptiveQRowBlockedMass
#check v13RealLinearAdaptiveQRowGeneratedMass
#check v13RealLinearQRowEpsilon
#check V13RealLinearAdaptiveQRowExperiment.branchRows_card_le
#check V13RealLinearRowCombination
#check v13RealLinearRowCombinationEval
#check V13RealLinearRowsGenerateTarget
#check v13RealLinear_not_rowsGenerateTarget_of_rows_card_zero
#check v13RealLinear_rowCombination_card
#check v13RealLinear_rowCombination_card_le_of_rows_card_le
#check v13RealLinear_rowCombination_card_le_for_branch
#check v13RealLinear_rowsBlockTarget_of_rowsGenerateTarget
#check v13RealLinear_rowsGenerateTarget_of_rowsBlockTarget
#check v13RealLinear_rowsBlockTarget_iff_rowsGenerateTarget
#check v13RealLinear_rowsGenerateTarget_singleton_iff
#check v13RealLinear_singletonRowCombination_eq_one_of_generates
#check V13RealLinearTargetRows
#check v13RealLinear_mem_targetRows_iff
#check v13RealLinear_targetRows_card_le_one
#check v13RealLinearTargetRowChoice
#check v13RealLinearTargetRowObserver
#check v13RealLinear_targetRowObserver_generated_iff_targetRows_nonempty
#check V13RealLinearUniformTargetRowOccurrence
#check V13RealLinearUniformFixedTargetRowOccurrence
#check v13RealLinearFixedTargetRowOccurrenceSwapEquiv
#check v13RealLinearFixedTargetRowOccurrence_card_eq_of_swap
#check v13RealLinearUniformTargetRowOccurrenceMass
#check v13RealLinearShear01
#check v13RealLinearShear10
#check v13RealLinearShear01Swap
#check v13RealLinearTargetRowOccurrenceFour
#check v13RealLinearTargetRowOccurrenceFour_injective
#check v13RealLinearUniformTargetRowOccurrence_card_four_le
#check v13RealLinearUniformTargetRowOccurrenceMass_two_zero_gt_half
#check V13RealLinearNonzeroF2Vec2
#check v13RealLinearNonzeroF2Vec2_card
#check v13RealLinearNonzeroF2Vec2_ne_card_le_two
#check v13_zmod2_cases
#check v13RealLinear_f2vec2_cases
#check v13RealLinear_f2vec2_eq_singleBit_one_of_ne_zero_of_coord_zero
#check v13RealLinear_f2vec2_eq_singleBit_zero_of_ne_zero_of_coord_one_zero
#check v13RealLinear_equiv_two_ext
#check V13RealLinearTwoBasisImagePairs
#check v13RealLinearTwoBasisImagePairs_card_le_six
#check v13RealLinear_f2_equiv_two_card_le_six
#check v13RealLinear_f2_equiv_two_card_four_le
#check v13RealLinearUniformTargetRowOccurrenceMass_two_zero_gt_half_unconditional
#check v13RealLinear_targetRowObserverGeneratedEquivOccurrenceProd
#check v13RealLinear_targetRowObserverGenerated_card_eq
#check v13RealLinear_targetRowObserverGeneratedMass_eq_occurrenceMass
#check V13RealLinearAdaptiveQRowExperiment.blocked_iff_generated
#check V13RealLinearAdaptiveQRowExperiment.generated_one_budget_exists_target_row
#check V13RealLinearAdaptiveQRowExperiment.targetRows_nonempty_of_generated_one_budget
#check v13RealLinearAdaptiveQRowBlockedGeneratedEquiv
#check v13RealLinearAdaptiveQRowBlockedMass_eq_generatedMass
#check v13RealLinearAdaptiveQRowGeneratedMass_le_one
#check v13RealLinear_qrow_one_le_epsilon_of_m_le_q
#check v13RealLinearAdaptiveQRowGeneratedMass_eq_zero_of_zero_budget
#check v13RealLinearAdaptiveRowSpanCountingBound_of_m_le_q
#check V13RealLinearAdaptiveRowSpanCountingBound
#check V13RealLinearUniformInvertibleRowSpanCountingBound
#check v13RealLinearUniformInvertibleRowSpanCountingBound_of_zero_budget
#check v13RealLinearUniformInvertibleRowSpanCountingBound_of_m_le_q
#check V13RealLinearUniformCausalRowSpanCountingBound
#check v13RealLinearUniformCausalRowSpanCountingBound_of_zero_budget
#check v13RealLinearUniformCausalRowSpanCountingBound_of_m_le_q
#check v13RealLinear_targetRowObserver_spanCountingBound_fails_two_zero
#check v13RealLinear_targetRowObserver_spanCountingBound_fails_two_zero_unconditional
#check v13RealLinearUniformAdaptiveQRowSuccess
#check V13RealLinearAdaptiveKernelFlipSurchargeBound
#check v13RealLinear_adaptiveKernelFlipSurchargeBound
#check v13RealLinear_adaptive_qrow_success_bound_of_spanCounting
#check v13RealLinear_uniform_adaptive_qrow_success_bound_of_spanCounting
#check v13RealLinear_uniform_causal_qrow_success_bound_of_spanCounting
#check v13RealLinear_uniform_zero_row_success_bound
#check v13RealLinear_uniform_causal_zero_row_success_bound
#check v13RealLinear_uniform_high_budget_success_bound
#check v13RealLinear_uniform_causal_high_budget_success_bound
#check V13RealLinearUniformCausalLowPositiveRowSpanCountingBound
#check V13RealLinearUniformCausalLowPositiveCompletionCountingBound
#check V13RealLinearAdaptiveQRowGeneratedCoefficient
#check V13RealLinearAdaptiveQRowGeneratedCoefficientFiber
#check v13RealLinearAdaptiveQRowGeneratedCoefficient_card_eq_sum_fibers
#check v13RealLinearAdaptiveQRowGenerated_card_le_coefficient
#check V13RealLinearUniformCausalLowPositiveCoefficientCountingBound
#check V13RealLinearUniformCausalLowPositiveFiberCoefficientCountingBound
#check v13RealLinear_f2vec_card
#check v13RealLinearCausalSingleRowObserver
#check v13RealLinearFixedTargetRowOccurrenceZeroEmbedding
#check v13RealLinearFixedTargetRowOccurrence_zero_card_le_two
#check v13RealLinearFixedTargetRowOccurrenceOneOneEmbedding
#check v13RealLinearFixedTargetRowOccurrence_one_one_card_le_two
#check v13RealLinearFixedTargetRowOccurrenceZeroOneEmbedding
#check v13RealLinearFixedTargetRowOccurrence_zero_one_card_le_two
#check v13RealLinearFixedTargetRowOccurrenceOneZeroEmbedding
#check v13RealLinearFixedTargetRowOccurrence_one_zero_card_le_two
#check v13RealLinearFixedTargetRowOccurrence_two_card_le_two
#check V13RealLinearZeroAt
#check v13RealLinearZeroAtProdBitEquiv
#check v13RealLinear_zeroAt_card_mul_two
#check v13RealLinearZeroAtRowShear
#check v13RealLinearFixedTargetRowOccurrenceZeroAtEmbedding
#check v13RealLinearFixedTargetRowOccurrence_mul_zeroAt_card_le
#check v13RealLinearFixedTargetRowOccurrence_counting
#check v13RealLinear_causalSingleRowGeneratedCoefficientEquivFixedOccurrenceProd
#check v13RealLinear_causalSingleRowGeneratedCoefficient_card_eq
#check V13RealLinearUniformFixedTargetRowOccurrenceCountingBound
#check v13RealLinearUniformFixedTargetRowOccurrenceCountingBound_proved
#check V13RealLinearUniformRepresentativeFixedTargetRowOccurrenceCountingBound
#check V13RealLinearUniformRepresentativeFixedTargetRowOccurrenceCountingBound_of_fixed
#check V13RealLinearUniformFixedTargetRowOccurrenceCountingBound_of_representative
#check V13RealLinearUniformFixedTargetRowOccurrenceCountingBound_iff_representative
#check v13RealLinearUniformRepresentativeFixedTargetRowOccurrenceCountingBound_proved
#check v13RealLinear_causalSingleRow_coefficientCounting_of_fixedTargetRowOccurrenceCounting
#check v13RealLinear_causalSingleRow_coefficientCounting_of_representativeFixedTargetRowOccurrenceCounting
#check v13RealLinear_causalSingleRow_coefficientCounting
#check v13RealLinear_fixedTargetRowOccurrence_zero_two_counting
#check v13RealLinear_fixedTargetRowOccurrence_two_counting
#check v13RealLinear_causalSingleRow_zero_two_coefficientCounting
#check v13RealLinear_causalSingleRow_two_coefficientCounting
#check v13RealLinearCausalSingleRowIdentityFiberEmbedding
#check v13RealLinearCausalSingleRowIdentityFiber_card_four_le
#check v13RealLinearUniformCausalLowPositiveFiberCoefficientCountingBound_fails_two_identity
#check v13RealLinearUniformCausalLowPositiveCoefficientCountingBound_of_fiberCounting
#check v13RealLinearUniformCausalLowPositiveCompletionCountingBound_of_coefficientCounting
#check v13RealLinearUniformCausalLowPositiveRowSpanCountingBound_of_completionCounting
#check v13RealLinear_uniform_causal_qrow_success_bound_of_lowPositiveSpanCounting
#check v13RealLinear_uniform_causal_qrow_success_bound_of_completionCounting
#check v13RealLinear_uniform_causal_qrow_success_bound_of_coefficientCounting
#check v13RealLinear_qrow_epsilon_nonnegative

def v13RealLinearQRowBoundRegression_staticConstant :
    V13RealLinearStaticRowObserver 2 0 where
  rows := ∅
  decide := fun _ => 0
  readBudget := by simp
  factorsThroughRows := by
    intro omega₀ omega₁ hsame
    rfl

def v13RealLinearQRowBoundRegression_adaptiveConstant :
    V13RealLinearAdaptiveRowObserver 2 0 where
  Branch := Unit
  branch := fun _ => ()
  staticBranch := fun _ => v13RealLinearQRowBoundRegression_staticConstant
  decide := fun _ => 0
  branchDecision := by
    intro omega
    rfl
  branchStable := by
    intro A x w b hbranch hkernel
    cases b
    rfl

def v13RealLinearQRowBoundRegression_causalConstant :
    V13RealLinearCausalRowObserver 2 0 where
  Branch := Unit
  branch := fun _ => ()
  rows := fun _ => ∅
  decideFromTranscript := fun _ _ => 0
  readBudget := by
    intro b
    cases b
    simp
  branchCausal := by
    intro public₀ public₁ b hbranch htranscript
    cases b
    rfl

def v13RealLinearQRowBoundRegression_experiment :
    V13RealLinearAdaptiveQRowExperiment 2 0 Unit where
  sampleA := fun _ => v13RealLinearIdentity 2
  observer := v13RealLinearQRowBoundRegression_adaptiveConstant

theorem v13RealLinearQRowBoundRegression_epsilon_nonnegative :
    0 ≤ v13RealLinearQRowEpsilon 0 2 :=
  v13RealLinear_qrow_epsilon_nonnegative 0 2

theorem v13RealLinearQRowBoundRegression_conditional_shape
    (hcount :
      V13RealLinearAdaptiveRowSpanCountingBound
        v13RealLinearQRowBoundRegression_experiment 0) :
    v13RealLinearAdaptiveQRowSuccess
        v13RealLinearQRowBoundRegression_experiment 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_adaptive_qrow_success_bound_of_spanCounting
      v13RealLinearQRowBoundRegression_experiment 0 hcount

theorem v13RealLinearQRowBoundRegression_uniform_conditional_shape
    (hcount :
      V13RealLinearUniformInvertibleRowSpanCountingBound
        v13RealLinearQRowBoundRegression_adaptiveConstant 0) :
    v13RealLinearUniformAdaptiveQRowSuccess
        v13RealLinearQRowBoundRegression_adaptiveConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_adaptive_qrow_success_bound_of_spanCounting
      v13RealLinearQRowBoundRegression_adaptiveConstant 0 hcount

theorem v13RealLinearQRowBoundRegression_causal_zero_shape :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_zero_row_success_bound
      v13RealLinearQRowBoundRegression_causalConstant 0

theorem v13RealLinearQRowBoundRegression_causal_global_shape
    (hcount : V13RealLinearUniformCausalLowPositiveRowSpanCountingBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_lowPositiveSpanCounting
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem v13RealLinearQRowBoundRegression_causal_completion_shape
    (hcount : V13RealLinearUniformCausalLowPositiveCompletionCountingBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_completionCounting
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem v13RealLinearQRowBoundRegression_causal_coefficient_shape
    (hcount : V13RealLinearUniformCausalLowPositiveCoefficientCountingBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_coefficientCounting
      hcount v13RealLinearQRowBoundRegression_causalConstant 0

theorem v13RealLinearQRowBoundRegression_causal_fiber_shape
    (hcount :
      V13RealLinearUniformCausalLowPositiveFiberCoefficientCountingBound) :
    v13RealLinearUniformCausalQRowSuccess
        v13RealLinearQRowBoundRegression_causalConstant 0 ≤
      (1 / 2 : Rat) + v13RealLinearQRowEpsilon 0 2 := by
  exact
    v13RealLinear_uniform_causal_qrow_success_bound_of_coefficientCounting
      (v13RealLinearUniformCausalLowPositiveCoefficientCountingBound_of_fiberCounting
        hcount)
      v13RealLinearQRowBoundRegression_causalConstant 0

#print axioms v13RealLinear_adaptiveKernelFlipSurchargeBound
#print axioms v13RealLinear_rowCombination_card_le_for_branch
#print axioms v13RealLinear_rowsBlockTarget_of_rowsGenerateTarget
#print axioms v13RealLinear_rowsGenerateTarget_of_rowsBlockTarget
#print axioms v13RealLinear_rowsBlockTarget_iff_rowsGenerateTarget
#print axioms v13RealLinear_rowsGenerateTarget_singleton_iff
#print axioms v13RealLinear_targetRows_card_le_one
#print axioms v13RealLinear_targetRowObserver_generated_iff_targetRows_nonempty
#print axioms v13RealLinearUniformTargetRowOccurrence_card_four_le
#print axioms v13RealLinearUniformTargetRowOccurrenceMass_two_zero_gt_half
#print axioms v13RealLinear_f2_equiv_two_card_le_six
#print axioms v13RealLinearUniformTargetRowOccurrenceMass_two_zero_gt_half_unconditional
#print axioms v13RealLinear_targetRowObserverGenerated_card_eq
#print axioms v13RealLinear_targetRowObserverGeneratedMass_eq_occurrenceMass
#print axioms V13RealLinearAdaptiveQRowExperiment.blocked_iff_generated
#print axioms V13RealLinearAdaptiveQRowExperiment.generated_one_budget_exists_target_row
#print axioms V13RealLinearAdaptiveQRowExperiment.targetRows_nonempty_of_generated_one_budget
#print axioms v13RealLinearAdaptiveQRowBlockedMass_eq_generatedMass
#print axioms v13RealLinearAdaptiveQRowGeneratedMass_le_one
#print axioms v13RealLinear_qrow_one_le_epsilon_of_m_le_q
#print axioms v13RealLinearAdaptiveQRowGeneratedMass_eq_zero_of_zero_budget
#print axioms v13RealLinearUniformInvertibleRowSpanCountingBound_of_zero_budget
#print axioms v13RealLinearAdaptiveRowSpanCountingBound_of_m_le_q
#print axioms v13RealLinearUniformInvertibleRowSpanCountingBound_of_m_le_q
#print axioms v13RealLinearUniformCausalRowSpanCountingBound_of_zero_budget
#print axioms v13RealLinearUniformCausalRowSpanCountingBound_of_m_le_q
#print axioms v13RealLinear_targetRowObserver_spanCountingBound_fails_two_zero
#print axioms v13RealLinear_targetRowObserver_spanCountingBound_fails_two_zero_unconditional
#print axioms v13RealLinear_adaptive_qrow_success_bound_of_spanCounting
#print axioms v13RealLinear_uniform_adaptive_qrow_success_bound_of_spanCounting
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_spanCounting
#print axioms v13RealLinear_uniform_zero_row_success_bound
#print axioms v13RealLinear_uniform_causal_zero_row_success_bound
#print axioms v13RealLinear_uniform_high_budget_success_bound
#print axioms v13RealLinear_uniform_causal_high_budget_success_bound
#print axioms v13RealLinearAdaptiveQRowGeneratedCoefficient_card_eq_sum_fibers
#print axioms v13RealLinearAdaptiveQRowGenerated_card_le_coefficient
#print axioms v13RealLinear_f2vec_card
#print axioms v13RealLinearFixedTargetRowOccurrence_card_eq_of_swap
#print axioms v13RealLinearFixedTargetRowOccurrence_zero_card_le_two
#print axioms v13RealLinearFixedTargetRowOccurrence_two_card_le_two
#print axioms v13RealLinearFixedTargetRowOccurrence_counting
#print axioms v13RealLinear_causalSingleRowGeneratedCoefficient_card_eq
#print axioms v13RealLinearUniformFixedTargetRowOccurrenceCountingBound_proved
#print axioms V13RealLinearUniformFixedTargetRowOccurrenceCountingBound_iff_representative
#print axioms v13RealLinearUniformRepresentativeFixedTargetRowOccurrenceCountingBound_proved
#print axioms v13RealLinear_causalSingleRow_coefficientCounting_of_fixedTargetRowOccurrenceCounting
#print axioms v13RealLinear_causalSingleRow_coefficientCounting_of_representativeFixedTargetRowOccurrenceCounting
#print axioms v13RealLinear_causalSingleRow_coefficientCounting
#print axioms v13RealLinear_fixedTargetRowOccurrence_zero_two_counting
#print axioms v13RealLinear_fixedTargetRowOccurrence_two_counting
#print axioms v13RealLinear_causalSingleRow_zero_two_coefficientCounting
#print axioms v13RealLinear_causalSingleRow_two_coefficientCounting
#print axioms v13RealLinearCausalSingleRowIdentityFiber_card_four_le
#print axioms v13RealLinearUniformCausalLowPositiveFiberCoefficientCountingBound_fails_two_identity
#print axioms v13RealLinearUniformCausalLowPositiveCoefficientCountingBound_of_fiberCounting
#print axioms v13RealLinearUniformCausalLowPositiveCompletionCountingBound_of_coefficientCounting
#print axioms v13RealLinearUniformCausalLowPositiveRowSpanCountingBound_of_completionCounting
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_lowPositiveSpanCounting
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_completionCounting
#print axioms v13RealLinear_uniform_causal_qrow_success_bound_of_coefficientCounting
#print axioms v13RealLinear_qrow_epsilon_nonnegative
#print axioms v13RealLinearQRowBoundRegression_conditional_shape
#print axioms v13RealLinearQRowBoundRegression_uniform_conditional_shape
#print axioms v13RealLinearQRowBoundRegression_causal_zero_shape
#print axioms v13RealLinearQRowBoundRegression_causal_global_shape
#print axioms v13RealLinearQRowBoundRegression_causal_completion_shape
#print axioms v13RealLinearQRowBoundRegression_causal_coefficient_shape
#print axioms v13RealLinearQRowBoundRegression_causal_fiber_shape

end Mettapedia.Computability.PNP
