import Mettapedia.Computability.PNP.V14PublicReadToy

/-!
# Regression checks for the v14 construction-side public-read toy
-/

namespace Mettapedia.Computability.PNP

set_option autoImplicit false

#check v14ToyPublicRead_neutralOnly_targetBlind
#check v14ToyPublicRead_decomposes
#check v14ToyPublicRead_skeleton_is_neutral_targetBlind
#check v14ToyPublicRead_lockLeft_is_neutral_targetBlind
#check v14ToyPublicRead_lockRight_is_neutral_targetBlind
#check v14ToyPublicRead_safeBuffer_has_charged_leaf
#check v14ToyPublicRead_quotient_has_charged_leaf
#check v14ToyPublicMessage_eq_target
#check v14ToySingleMessage
#check v14ToyVerifier_singleMessage
#check v14ToyGaugeEquation_preserved
#check v14ToyHiddenGaugeProduct
#check V14ToyRestrictedFormula
#check V14ToyPNPSATDecider
#check v14ToyRestricted_withRawHiddenQuotient_satisfiable_iff
#check v14ToyRestricted_complete_satisfiable_iff
#check v14ToyBitFixQuotient_satisfiable
#check v14ToyBitFixMessage_satisfiable
#check v14ToySelfReductionWitness_satisfies
#check v14ToySelfReduction_readout_eq_message
#check v14ToySelfReduction_readout_eq_validWitness_readout
#check v14ToySelfReductionDecoderCost
#check v14ToyConstantDecoderKpolyAt
#check v14ToyLinearEtaTimes
#check v14ToyConstantDecoderKpolyAt_eq
#check v14Toy_constantDecoder_lt_linearFloor
#check V14ToyConstantDecoderRegime
#check v14Toy_selfReductionUpperHypothesis_givenPNP
#check v14ToyQuotientRead_exposes_rawGaugeSupport
#check v14ToyNoPublicCoordinateDeterminesTarget
#check v14ToyNoPublicTargetTags
#check v14ToyHistory_admissible
#check SafeQSSMFrontier
#check BoundedGaugeIncidenceFrontier
#check BoundaryMixingFrontier
#check V14ToyAnalyticFrontier
#check v14ToyAtomCompleteness
#check v14ToyGaugeFaithfulness
#check v14ToyInterfaceHiddenGaugeProduct
#check v14ToyLockedInterface
#check v14ToyInterfaceBattery
#check v14ToyInterfaceBattery_test8
#check v14Toy_structuralReduction
#check V14ToyStructuralFieldsConstructed
#check v14Toy_structuralFields_constructed
#check V14ToyAnalyticFieldsCarried
#check v14Toy_analyticFields_carried
#check V14ToyResidualOpenInputs
#check v14Toy_residualOpenInputs
#check V14ToyParameterPayloadAudited
#check v14Toy_parameterPayload_audited
#check v14ToyParameterRecordWithPNPUpper
#check V14ToyExactFrontierUse
#check v14Toy_reduction_uses_exact_analytic_frontier
#check v14Toy_reduction_uses_exact_analytic_frontier_givenPNP
#check v14ToyReductionStatement
#check safeQSSM_weakened_frontier_insufficient
#check boundedGaugeIncidence_weakened_frontier_insufficient
#check boundaryMixing_weakened_frontier_insufficient
#check v14ToyConstructionLedger_length
#check v14ToyConstructionLedger_structural_fields_proved
#check v14ToyConstructionLedger_analytic_frontier_carried
#check v14ToyConstructionLedger_test8_proved
#check v14ToyExactUseLedger_length
#check v14ToyExactUseLedger_structural_proved
#check v14ToyExactUseLedger_analytic_carried
#check v14ToyExactUseLedger_selfReduction_upper_constructed_givenPNP
#check v14ToyExactUseLedger_residual_open_inputs

#print axioms v14ToyPublicRead_neutralOnly_targetBlind
#print axioms v14ToyPublicRead_decomposes
#print axioms v14ToyPublicRead_skeleton_is_neutral_targetBlind
#print axioms v14ToyPublicRead_lockLeft_is_neutral_targetBlind
#print axioms v14ToyPublicRead_lockRight_is_neutral_targetBlind
#print axioms v14ToyPublicRead_safeBuffer_has_charged_leaf
#print axioms v14ToyPublicRead_quotient_has_charged_leaf
#print axioms v14ToyPublicMessage_eq_target
#print axioms v14ToySingleMessage
#print axioms v14ToyVerifier_singleMessage
#print axioms v14ToyGaugeEquation_preserved
#print axioms v14ToyHiddenGaugeProduct
#print axioms v14ToyRestricted_withRawHiddenQuotient_satisfiable_iff
#print axioms v14ToyRestricted_complete_satisfiable_iff
#print axioms v14ToyBitFixQuotient_satisfiable
#print axioms v14ToyBitFixMessage_satisfiable
#print axioms v14ToySelfReductionWitness_satisfies
#print axioms v14ToySelfReduction_readout_eq_message
#print axioms v14ToySelfReduction_readout_eq_validWitness_readout
#print axioms v14ToyConstantDecoderKpolyAt_eq
#print axioms v14Toy_constantDecoder_lt_linearFloor
#print axioms v14Toy_selfReductionUpperHypothesis_givenPNP
#print axioms v14ToyQuotientRead_exposes_rawGaugeSupport
#print axioms v14ToyNoPublicCoordinateDeterminesTarget
#print axioms v14ToyNoPublicTargetTags
#print axioms v14ToyHistory_admissible
#print axioms v14ToyAtomCompleteness
#print axioms v14ToyGaugeFaithfulness
#print axioms v14ToyInterfaceHiddenGaugeProduct
#print axioms v14ToyLockedInterface
#print axioms v14ToyInterfaceBattery
#print axioms v14ToyInterfaceBattery_test8
#print axioms v14Toy_structuralReduction
#print axioms v14Toy_structuralFields_constructed
#print axioms v14Toy_analyticFields_carried
#print axioms v14Toy_residualOpenInputs
#print axioms v14Toy_parameterPayload_audited
#print axioms v14Toy_reduction_uses_exact_analytic_frontier
#print axioms v14Toy_reduction_uses_exact_analytic_frontier_givenPNP
#print axioms safeQSSM_weakened_frontier_insufficient
#print axioms boundedGaugeIncidence_weakened_frontier_insufficient
#print axioms boundaryMixing_weakened_frontier_insufficient
#print axioms v14ToyConstructionLedger_length
#print axioms v14ToyConstructionLedger_structural_fields_proved
#print axioms v14ToyConstructionLedger_analytic_frontier_carried
#print axioms v14ToyConstructionLedger_test8_proved
#print axioms v14ToyExactUseLedger_length
#print axioms v14ToyExactUseLedger_structural_proved
#print axioms v14ToyExactUseLedger_analytic_carried
#print axioms v14ToyExactUseLedger_selfReduction_upper_constructed_givenPNP
#print axioms v14ToyExactUseLedger_residual_open_inputs

end Mettapedia.Computability.PNP
