import Mettapedia.Computability.PNP.V15RealEnsembleSpine

/-!
# Regression seal for the v15 real ensemble spine
-/

namespace Mettapedia.Computability.PNP

set_option autoImplicit false

#check RealSingleMessageSATSpine
#check RealSingleMessageSATSpine.singleMessage
#check RealSingleMessageSATSpine.readout_eq_of_valid
#check RealSingleMessageSATSpine.worldWitness_readout_eq_target
#check v13RealLinearBit
#check v13RealLinearVerifier
#check v13RealLinearWitnessReadout
#check v13RealLinearMessageOfPublic
#check v13RealLinearTargetBit
#check v13RealLinearVerifier_readout_eq_message
#check v13RealLinear_worldWitness_valid
#check v13RealLinearTargetBit_eq_messageOfPublic
#check v13RealLinearSingleMessageSATSpine
#check v13RealLinearSingleMessageSATSpine_singleMessage
#check v13RealLinear_validWitness_readout_eq_publicMessage
#check v13RealLinearNoTargetRowsTargetBit
#check v13RealLinearBit_eq_true_iff
#check v13RealLinearBit_eq_false_iff
#check v13RealLinearNoTargetRowsTargetFlipEquiv
#check v13RealLinearNoTargetRowsTarget_false_card_eq_true
#check v13RealLinearNoTargetRows_constantTrue_correct_card_eq_true
#check v13RealLinearNoTargetRows_world_card_eq_two_mul_target_true
#check v13RealLinearNoTargetRowsTarget_true_card_pos
#check v13RealLinearNoTargetRows_target_balanced
#check v13RealLinearNoTargetRowsNeutralSkeleton
#check v13RealLinearNoTargetRowsOppositeSupport
#check v13RealLinearNoTargetRows_pairNeutral
#check v13RealLinearNoTargetRows_hasMessageOppositePair
#check v13RealLinearNoTargetRows_noPublicTargetTags
#check v13RealLinearNoTargetRowsHistoryField
#check v13RealLinearNoTargetRows_historyField_balancedConditioning
#check v13RealLinearNoTargetRows_historyField_admissible
#check v13RealLinearNoTargetRowsPublicCoordinateField
#check v13RealLinearNoTargetRows_publicCoordinate_balancedConditioning
#check v13RealLinearNoTargetRows_publicCoordinate_admissible
#check RealM4LockedCoreWorld
#check RealM4LockedCoreWitness
#check RealM4LockedCoreWorld.toWitness
#check realM4LockedCoreVerifier
#check realM4LockedCoreWitnessReadout
#check realM4LockedCoreMessageOfPublic
#check realM4LockedCoreWitness_readout_eq_publicMessage
#check realM4LockedCoreSingleMessageSATSpine
#check realM4LockedCore_singleMessage_of_publicMessageInvariant
#check realM4LockedCore_readout_eq_of_valid_of_publicMessageInvariant
#check realM4_lockedMessageRigidity_of_publicMessageInvariant
#check AppendixDLockedCore.publicMessageOfLockedRigidity
#check AppendixDLockedCore.publicMessageInvariant_of_lockSatisfiable_of_lockedMessageRigidity
#check AppendixDWitnessData.PublicLockCoveredBySupportedInstances
#check AppendixDWitnessData.core_lockSatisfiable_of_witnessExistsOnSupport_of_publicLockCovered
#check AppendixICNFReadoutData.witnessExistsOnSupport
#check AppendixICNFReadoutData.core_lockSatisfiable_of_publicLockCovered
#check RealM4PublicLockCoverageData
#check RealM4PublicLockCoverageData.publicLockCoverage
#check RealM4PublicLockCoverageData.lockSatisfiable
#check realM4_publicLockCoverage_of_representatives
#check realM4_lockSatisfiable_of_publicLockCoverageData
#check RealM4LockedMessageRigidityData
#check RealM4LockedMessageRigidityData.publicMessageInvariant
#check RealM4LockedMessageRigidityData.lockedMessageRigidity
#check realM4_publicMessageInvariant_of_lockedMessageData
#check realM4_lockedMessageRigidity_of_lockedMessageData
#check realM4_cnfSingleMessageReadout_of_publicMessageInvariant
#check realM4_semanticI26_of_publicMessageInvariant
#check realM4_exists_correctForAllSatSearchOutputs_of_publicMessageInvariant
#check realM4_supportedArbitraryOutputSATSearchCorrect_of_publicMessageInvariant
#check RealM4CNFWorld
#check RealM4CNFWitness
#check RealM4CNFWorld.toWitness
#check realM4CNFVerifier
#check realM4CNFWitnessReadout
#check realM4CNFMessageOfPublic
#check realM4CNFWitness_readout_eq_publicMessage
#check realM4CNFSingleMessageSATSpine
#check realM4CNF_singleMessage_of_publicMessageInvariant
#check realM4CNF_readout_eq_of_valid_of_publicMessageInvariant
#check ConcreteCNF.Literal.var
#check ConcreteCNF.unitLiteral
#check ConcreteCNF.unitClause
#check ConcreteCNF.prefixClauses
#check ConcreteCNF.restrictWithPrefix
#check ConcreteCNF.FormulaUsesOnly
#check ConcreteCNF.isSatClause_unitClause_iff
#check ConcreteCNF.isSatFormula_append_iff
#check CNFPrefix.Satisfied
#check CNFPrefix.value
#check CNFPrefix.assignment
#check CNFPrefix.satisfied_nil
#check CNFPrefix.satisfied_append_single
#check CNFPrefix.exists_pair_of_mem_keys
#check CNFPrefix.value_eq_of_mem
#check CNFPrefix.assignment_eq_of_mem
#check ConcreteCNF.isSatFormula_prefixClauses_iff
#check ConcreteCNF.isSatFormula_restrictWithPrefix_iff
#check ConcreteCNF.isSatFormula_of_agree_on_formulaUsesOnly
#check RealCNFRestrictedSatisfiable
#check RealCNFPNPSATDecider
#check realCNFRestricted_decideSat_true_iff
#check realCNFBitFixPrefixAux
#check realCNFBitFixPrefix
#check realCNFBitFixAssignment
#check realCNFBitFixPrefixAux_keys
#check realCNFBitFixPrefixAux_satisfiable
#check realCNFBitFixAssignment_satisfies
#check realM4_bitFixingAssignment_satisfies
#check realM4_bitFixingReadout_eq_publicMessage_of_publicMessageInvariant
#check RealM4CNFUniformBitFixingData
#check RealM4CNFUniformSupportData
#check RealM4ExplicitPNPDeciderFamily
#check RealM4FiniteCNFVariableFamilyData
#check RealM4FiniteCNFVariableFamilyData.uniformSupport
#check realM4_uniformCNFSupport_of_finiteVariables
#check RealM4CNFUniformSupportData.withPNPDecider
#check RealM4CNFUniformBitFixingData.bitFixingAssignment
#check RealM4CNFUniformBitFixingData.bitFixingAssignment_satisfies
#check realM4_uniformBitFixingAssignment_satisfies
#check realM4_uniformBitFixingReadout_eq_publicMessage_of_publicMessageInvariant
#check realM4_uniformSupportWithPNPDecider_assignment_satisfies
#check realM4_uniformSupportWithPNPDecider_readout_eq_publicMessage
#check realCNFRestrictedFormulaCompilerProgramLength
#check realCNFBitFixingDriverProgramLength
#check realCNFReadoutProgramLength
#check realCNFSelfReductionDecoderCost
#check realCNFConstantDecoderKpolyAt
#check realCNFLinearEtaTimes
#check realCNFConstantDecoderKpolyAt_eq
#check realM4UniformSelfReductionDecoderCost
#check realM4UniformSelfReductionDecoderCost_bounds_instance
#check realM4UniformConstantDecoderKpolyAt
#check realM4UniformConstantDecoderKpolyAt_eq
#check RealCNFConstantDecoderRegime
#check realCNF_selfReductionUpperHypothesis_givenPNP
#check RealM4UniformConstantDecoderRegime
#check realM4_uniformSelfReductionUpperHypothesis_givenPNP
#check RealM4CompressionLowerMachineData
#check RealM4CompressionLowerMachineData.lowerFramework
#check RealM4CompressionLowerMachineData.kernelNeutrality
#check RealM4CompressionLowerMachineData.compressionLower
#check realM4_lowerFramework_of_lowerMachineData
#check realM4_kernelNeutrality_of_lowerMachineData
#check RealM4SelfReductionUpperDischarge
#check RealM4SelfReductionUpperExplicitPNPDischarge
#check RealM4SelfReductionUpperDischarge.selfReductionUpper
#check RealM4SelfReductionUpperDischarge.bitFixingAssignment_satisfies
#check RealM4SelfReductionUpperDischarge.bitFixingReadout_eq_publicMessage
#check RealM4SelfReductionUpperDischarge.instanceDecoderCost_le_uniform
#check RealM4SelfReductionUpperExplicitPNPDischarge.ofLockedRigidity
#check RealM4SelfReductionUpperExplicitPNPDischarge.ofCoveredLocksAndRigidity
#check RealM4SelfReductionUpperExplicitPNPDischarge.ofCoverageDataAndRigidity
#check RealM4SelfReductionUpperExplicitPNPDischarge.ofLockedMessageData
#check RealM4SelfReductionUpperExplicitPNPDischarge.ofCoverageDataAndLockedMessageData
#check RealM4SelfReductionUpperExplicitPNPDischarge.uniformBitFixing
#check RealM4SelfReductionUpperExplicitPNPDischarge.toDischarge
#check RealM4SelfReductionUpperExplicitPNPDischarge.selfReductionUpper
#check RealM4SelfReductionUpperExplicitPNPDischarge.bitFixingAssignment_satisfies
#check RealM4SelfReductionUpperExplicitPNPDischarge.bitFixingReadout_eq_publicMessage
#check RealM4SelfReductionUpperExplicitPNPDischarge.instanceDecoderCost_le_uniform
#check realM4_selfReductionUpperDischarge_assignment_readout_cost_and_upper
#check realM4_selfReductionUpperExplicitPNPDischarge_assignment_readout_cost_and_upper
#check realM4PublicMessageInvariantConstructionInputs
#check realM4PublicMessageInvariantConstructionInputs_exact
#check realM4PublicLockCoverageDataConstructionInputs
#check realM4PublicLockCoverageDataConstructionInputs_exact
#check realM4LockedMessageRigidityDataConstructionInputs
#check realM4LockedMessageRigidityDataConstructionInputs_exact
#check realM4FiniteCNFVariableFamilyDataConstructionInputs
#check realM4FiniteCNFVariableFamilyDataConstructionInputs_exact
#check realM4CompressionLowerMachineDataConstructionInputs
#check realM4CompressionLowerMachineDataConstructionInputs_exact
#check realM4LockSatisfiableConstructionInputs
#check realM4LockSatisfiableConstructionInputs_exact
#check realM4SelfReductionUpperDischargePrerequisites
#check realM4SelfReductionUpperDischargePrerequisites_exact
#check realM4SelfReductionUpperConditionalInputs
#check realM4SelfReductionUpperConditionalInputs_exact
#check realM4SelfReductionUpperExplicitPNPConstructionInputs
#check realM4SelfReductionUpperExplicitPNPConstructionInputs_exact
#check realM4SelfReductionUpperExplicitPNPConditionalInputs
#check realM4SelfReductionUpperExplicitPNPConditionalInputs_exact
#check realM4_atomCompleteness_of_CDENF
#check realM4_gaugeFaithfulness_of_CDENF
#check RealM4MechanicalInterfaceData
#check RealM4MechanicalInterfaceData.ofCDENFComponents
#check RealM4MechanicalInterfaceData.withAnalyticFrontier
#check RealM4EndgameMechanicalData
#check RealM4EndgameMechanicalData.ofComponents
#check RealM4EndgameMechanicalData.ofComponentsWithLowerMachine
#check RealM4EndgameMechanicalData.ofCDENFComponents
#check RealM4EndgameMechanicalData.interfaceWithAnalyticFrontier
#check RealM4EndgameMechanicalData.parameterRecordWithUpper
#check RealM4EndgameMechanicalData.parameterRecord
#check RealM4EndgameMechanicalData.parameterRecordExplicitPNP
#check realM4_conditionalClash_from_endgameMechanicalData
#check realM4_conditionalClash_from_endgameMechanicalData_explicitPNP
#check realM4_conditionalClash_from_coveredLocksAndRigidity_explicitPNP
#check realM4_conditionalClash_from_coverageDataAndRigidity_explicitPNP
#check realM4_conditionalClash_from_coverageDataAndLockedMessageData_explicitPNP
#check realM4_conditionalClash_from_lowerMachine_coverageDataAndLockedMessageData_explicitPNP
#check realM4_conditionalClash_from_lowerMachine_finiteCNFVariables_coverageDataAndLockedMessageData_explicitPNP
#check realM4_conditionalClash_from_components_coveredLocksAndRigidity_explicitPNP
#check realM4_conditionalClash_from_CDENFComponents_coveredLocksAndRigidity_explicitPNP
#check realM4EndgameStagingConstructionInputs
#check realM4EndgameStagingConstructionInputs_exact
#check realM4EndgameStagingIrreducibleInputs
#check realM4EndgameStagingIrreducibleInputs_exact
#check realM4EndgameStagingStatement
#check realM4EndgameStagingConstructionInputsExplicitPNP
#check realM4EndgameStagingConstructionInputsExplicitPNP_exact
#check realM4EndgameStagingConditionalInputsExplicitPNP
#check realM4EndgameStagingConditionalInputsExplicitPNP_exact
#check realM4EndgameStagingHypothesisAuditExplicitPNP
#check realM4EndgameStagingHypothesisAuditExplicitPNP_exact
#check realM4EndgameStagingStatementExplicitPNP
#check realM4CoveredLocksEndgameConstructionInputsExplicitPNP
#check realM4CoveredLocksEndgameConstructionInputsExplicitPNP_exact
#check realM4CoveredLocksEndgameConditionalInputsExplicitPNP
#check realM4CoveredLocksEndgameConditionalInputsExplicitPNP_exact
#check realM4CoveredLocksEndgameIrreducibleInputsExplicitPNP
#check realM4CoveredLocksEndgameIrreducibleInputsExplicitPNP_exact
#check realM4CoveredLocksEndgameHypothesisAuditExplicitPNP
#check realM4CoveredLocksEndgameHypothesisAuditExplicitPNP_exact
#check realM4CoveredLocksEndgameStatementExplicitPNP
#check realM4CoverageDataEndgameConstructionInputsExplicitPNP
#check realM4CoverageDataEndgameConstructionInputsExplicitPNP_exact
#check realM4CoverageDataEndgameHypothesisAuditExplicitPNP
#check realM4CoverageDataEndgameHypothesisAuditExplicitPNP_exact
#check realM4CoverageDataEndgameStatementExplicitPNP
#check realM4CoverageAndLockedMessageDataEndgameConstructionInputsExplicitPNP
#check realM4CoverageAndLockedMessageDataEndgameConstructionInputsExplicitPNP_exact
#check realM4CoverageAndLockedMessageDataEndgameHypothesisAuditExplicitPNP
#check realM4CoverageAndLockedMessageDataEndgameHypothesisAuditExplicitPNP_exact
#check realM4CoverageAndLockedMessageDataEndgameStatementExplicitPNP
#check realM4LowerMachineCoverageAndLockedMessageDataEndgameConstructionInputsExplicitPNP
#check realM4LowerMachineCoverageAndLockedMessageDataEndgameConstructionInputsExplicitPNP_exact
#check realM4LowerMachineCoverageAndLockedMessageDataEndgameHypothesisAuditExplicitPNP
#check realM4LowerMachineCoverageAndLockedMessageDataEndgameHypothesisAuditExplicitPNP_exact
#check realM4LowerMachineCoverageAndLockedMessageDataEndgameStatementExplicitPNP
#check realM4LowerMachineFiniteCNFVariablesCoverageAndLockedMessageDataEndgameConstructionInputsExplicitPNP
#check realM4LowerMachineFiniteCNFVariablesCoverageAndLockedMessageDataEndgameConstructionInputsExplicitPNP_exact
#check realM4LowerMachineFiniteCNFVariablesCoverageAndLockedMessageDataEndgameHypothesisAuditExplicitPNP
#check realM4LowerMachineFiniteCNFVariablesCoverageAndLockedMessageDataEndgameHypothesisAuditExplicitPNP_exact
#check realM4LowerMachineFiniteCNFVariablesCoverageAndLockedMessageDataEndgameStatementExplicitPNP
#check realM4CDENFComponentCoveredLocksEndgameConstructionInputsExplicitPNP
#check realM4CDENFComponentCoveredLocksEndgameConstructionInputsExplicitPNP_exact
#check realM4CDENFComponentCoveredLocksEndgameHypothesisAuditExplicitPNP
#check realM4CDENFComponentCoveredLocksEndgameHypothesisAuditExplicitPNP_exact
#check realM4CDENFComponentCoveredLocksEndgameStatementExplicitPNP
#check RealM4LiftStatus
#check RealM4LiftLedgerRow
#check realM4LiftLedger
#check realM4LiftLedger_statuses_exact
#check realM4OpenConstructionItems
#check realM4OpenConstructionItems_exact
#check realM4AfterConstructionIrreducibleInputs
#check realM4AfterConstructionIrreducibleInputs_exact
#check realM4_deterministicReadoutOnly_counterexample
#check realM4_publicMessageInvariant_guardrails

#print axioms RealSingleMessageSATSpine
#print axioms RealSingleMessageSATSpine.singleMessage
#print axioms RealSingleMessageSATSpine.readout_eq_of_valid
#print axioms RealSingleMessageSATSpine.worldWitness_readout_eq_target
#print axioms v13RealLinearBit
#print axioms v13RealLinearVerifier
#print axioms v13RealLinearWitnessReadout
#print axioms v13RealLinearMessageOfPublic
#print axioms v13RealLinearTargetBit
#print axioms v13RealLinearVerifier_readout_eq_message
#print axioms v13RealLinear_worldWitness_valid
#print axioms v13RealLinearTargetBit_eq_messageOfPublic
#print axioms v13RealLinearSingleMessageSATSpine
#print axioms v13RealLinearSingleMessageSATSpine_singleMessage
#print axioms v13RealLinear_validWitness_readout_eq_publicMessage
#print axioms v13RealLinearNoTargetRowsTargetBit
#print axioms v13RealLinearBit_eq_true_iff
#print axioms v13RealLinearBit_eq_false_iff
#print axioms v13RealLinearNoTargetRowsTargetFlipEquiv
#print axioms v13RealLinearNoTargetRowsTarget_false_card_eq_true
#print axioms v13RealLinearNoTargetRows_constantTrue_correct_card_eq_true
#print axioms v13RealLinearNoTargetRows_world_card_eq_two_mul_target_true
#print axioms v13RealLinearNoTargetRowsTarget_true_card_pos
#print axioms v13RealLinearNoTargetRows_target_balanced
#print axioms v13RealLinearNoTargetRowsNeutralSkeleton
#print axioms v13RealLinearNoTargetRowsOppositeSupport
#print axioms v13RealLinearNoTargetRows_pairNeutral
#print axioms v13RealLinearNoTargetRows_hasMessageOppositePair
#print axioms v13RealLinearNoTargetRows_noPublicTargetTags
#print axioms v13RealLinearNoTargetRowsHistoryField
#print axioms v13RealLinearNoTargetRows_historyField_balancedConditioning
#print axioms v13RealLinearNoTargetRows_historyField_admissible
#print axioms v13RealLinearNoTargetRowsPublicCoordinateField
#print axioms v13RealLinearNoTargetRows_publicCoordinate_balancedConditioning
#print axioms v13RealLinearNoTargetRows_publicCoordinate_admissible
#print axioms RealM4LockedCoreWorld
#print axioms RealM4LockedCoreWitness
#print axioms RealM4LockedCoreWorld.toWitness
#print axioms realM4LockedCoreVerifier
#print axioms realM4LockedCoreWitnessReadout
#print axioms realM4LockedCoreMessageOfPublic
#print axioms realM4LockedCoreWitness_readout_eq_publicMessage
#print axioms realM4LockedCoreSingleMessageSATSpine
#print axioms realM4LockedCore_singleMessage_of_publicMessageInvariant
#print axioms realM4LockedCore_readout_eq_of_valid_of_publicMessageInvariant
#print axioms realM4_lockedMessageRigidity_of_publicMessageInvariant
#print axioms AppendixDLockedCore.publicMessageOfLockedRigidity
#print axioms AppendixDLockedCore.publicMessageInvariant_of_lockSatisfiable_of_lockedMessageRigidity
#print axioms AppendixDWitnessData.PublicLockCoveredBySupportedInstances
#print axioms AppendixDWitnessData.core_lockSatisfiable_of_witnessExistsOnSupport_of_publicLockCovered
#print axioms AppendixICNFReadoutData.witnessExistsOnSupport
#print axioms AppendixICNFReadoutData.core_lockSatisfiable_of_publicLockCovered
#print axioms RealM4PublicLockCoverageData
#print axioms RealM4PublicLockCoverageData.publicLockCoverage
#print axioms RealM4PublicLockCoverageData.lockSatisfiable
#print axioms realM4_publicLockCoverage_of_representatives
#print axioms realM4_lockSatisfiable_of_publicLockCoverageData
#print axioms RealM4LockedMessageRigidityData
#print axioms RealM4LockedMessageRigidityData.publicMessageInvariant
#print axioms RealM4LockedMessageRigidityData.lockedMessageRigidity
#print axioms realM4_publicMessageInvariant_of_lockedMessageData
#print axioms realM4_lockedMessageRigidity_of_lockedMessageData
#print axioms realM4_cnfSingleMessageReadout_of_publicMessageInvariant
#print axioms realM4_semanticI26_of_publicMessageInvariant
#print axioms realM4_exists_correctForAllSatSearchOutputs_of_publicMessageInvariant
#print axioms realM4_supportedArbitraryOutputSATSearchCorrect_of_publicMessageInvariant
#print axioms RealM4CNFWorld
#print axioms RealM4CNFWitness
#print axioms RealM4CNFWorld.toWitness
#print axioms realM4CNFVerifier
#print axioms realM4CNFWitnessReadout
#print axioms realM4CNFMessageOfPublic
#print axioms realM4CNFWitness_readout_eq_publicMessage
#print axioms realM4CNFSingleMessageSATSpine
#print axioms realM4CNF_singleMessage_of_publicMessageInvariant
#print axioms realM4CNF_readout_eq_of_valid_of_publicMessageInvariant
#print axioms ConcreteCNF.Literal.var
#print axioms ConcreteCNF.unitLiteral
#print axioms ConcreteCNF.unitClause
#print axioms ConcreteCNF.prefixClauses
#print axioms ConcreteCNF.restrictWithPrefix
#print axioms ConcreteCNF.FormulaUsesOnly
#print axioms ConcreteCNF.isSatClause_unitClause_iff
#print axioms ConcreteCNF.isSatFormula_append_iff
#print axioms CNFPrefix.Satisfied
#print axioms CNFPrefix.value
#print axioms CNFPrefix.assignment
#print axioms CNFPrefix.satisfied_nil
#print axioms CNFPrefix.satisfied_append_single
#print axioms CNFPrefix.exists_pair_of_mem_keys
#print axioms CNFPrefix.value_eq_of_mem
#print axioms CNFPrefix.assignment_eq_of_mem
#print axioms ConcreteCNF.isSatFormula_prefixClauses_iff
#print axioms ConcreteCNF.isSatFormula_restrictWithPrefix_iff
#print axioms ConcreteCNF.isSatFormula_of_agree_on_formulaUsesOnly
#print axioms RealCNFRestrictedSatisfiable
#print axioms RealCNFPNPSATDecider
#print axioms realCNFRestricted_decideSat_true_iff
#print axioms realCNFBitFixPrefixAux
#print axioms realCNFBitFixPrefix
#print axioms realCNFBitFixAssignment
#print axioms realCNFBitFixPrefixAux_keys
#print axioms realCNFBitFixPrefixAux_satisfiable
#print axioms realCNFBitFixAssignment_satisfies
#print axioms realM4_bitFixingAssignment_satisfies
#print axioms realM4_bitFixingReadout_eq_publicMessage_of_publicMessageInvariant
#print axioms RealM4CNFUniformBitFixingData
#print axioms RealM4CNFUniformSupportData
#print axioms RealM4ExplicitPNPDeciderFamily
#print axioms RealM4FiniteCNFVariableFamilyData
#print axioms RealM4FiniteCNFVariableFamilyData.uniformSupport
#print axioms realM4_uniformCNFSupport_of_finiteVariables
#print axioms RealM4CNFUniformSupportData.withPNPDecider
#print axioms RealM4CNFUniformBitFixingData.bitFixingAssignment
#print axioms RealM4CNFUniformBitFixingData.bitFixingAssignment_satisfies
#print axioms realM4_uniformBitFixingAssignment_satisfies
#print axioms realM4_uniformBitFixingReadout_eq_publicMessage_of_publicMessageInvariant
#print axioms realM4_uniformSupportWithPNPDecider_assignment_satisfies
#print axioms realM4_uniformSupportWithPNPDecider_readout_eq_publicMessage
#print axioms realCNFRestrictedFormulaCompilerProgramLength
#print axioms realCNFBitFixingDriverProgramLength
#print axioms realCNFReadoutProgramLength
#print axioms realCNFSelfReductionDecoderCost
#print axioms realCNFConstantDecoderKpolyAt
#print axioms realCNFLinearEtaTimes
#print axioms realCNFConstantDecoderKpolyAt_eq
#print axioms realM4UniformSelfReductionDecoderCost
#print axioms realM4UniformSelfReductionDecoderCost_bounds_instance
#print axioms realM4UniformConstantDecoderKpolyAt
#print axioms realM4UniformConstantDecoderKpolyAt_eq
#print axioms RealCNFConstantDecoderRegime
#print axioms realCNF_selfReductionUpperHypothesis_givenPNP
#print axioms RealM4UniformConstantDecoderRegime
#print axioms realM4_uniformSelfReductionUpperHypothesis_givenPNP
#print axioms RealM4CompressionLowerMachineData
#print axioms RealM4CompressionLowerMachineData.lowerFramework
#print axioms RealM4CompressionLowerMachineData.kernelNeutrality
#print axioms RealM4CompressionLowerMachineData.compressionLower
#print axioms realM4_lowerFramework_of_lowerMachineData
#print axioms realM4_kernelNeutrality_of_lowerMachineData
#print axioms RealM4SelfReductionUpperDischarge
#print axioms RealM4SelfReductionUpperExplicitPNPDischarge
#print axioms RealM4SelfReductionUpperDischarge.selfReductionUpper
#print axioms RealM4SelfReductionUpperDischarge.bitFixingAssignment_satisfies
#print axioms RealM4SelfReductionUpperDischarge.bitFixingReadout_eq_publicMessage
#print axioms RealM4SelfReductionUpperDischarge.instanceDecoderCost_le_uniform
#print axioms RealM4SelfReductionUpperExplicitPNPDischarge.ofLockedRigidity
#print axioms RealM4SelfReductionUpperExplicitPNPDischarge.ofCoveredLocksAndRigidity
#print axioms RealM4SelfReductionUpperExplicitPNPDischarge.ofCoverageDataAndRigidity
#print axioms RealM4SelfReductionUpperExplicitPNPDischarge.ofLockedMessageData
#print axioms RealM4SelfReductionUpperExplicitPNPDischarge.ofCoverageDataAndLockedMessageData
#print axioms RealM4SelfReductionUpperExplicitPNPDischarge.uniformBitFixing
#print axioms RealM4SelfReductionUpperExplicitPNPDischarge.toDischarge
#print axioms RealM4SelfReductionUpperExplicitPNPDischarge.selfReductionUpper
#print axioms RealM4SelfReductionUpperExplicitPNPDischarge.bitFixingAssignment_satisfies
#print axioms RealM4SelfReductionUpperExplicitPNPDischarge.bitFixingReadout_eq_publicMessage
#print axioms RealM4SelfReductionUpperExplicitPNPDischarge.instanceDecoderCost_le_uniform
#print axioms realM4_selfReductionUpperDischarge_assignment_readout_cost_and_upper
#print axioms realM4_selfReductionUpperExplicitPNPDischarge_assignment_readout_cost_and_upper
#print axioms realM4PublicMessageInvariantConstructionInputs
#print axioms realM4PublicMessageInvariantConstructionInputs_exact
#print axioms realM4PublicLockCoverageDataConstructionInputs
#print axioms realM4PublicLockCoverageDataConstructionInputs_exact
#print axioms realM4LockedMessageRigidityDataConstructionInputs
#print axioms realM4LockedMessageRigidityDataConstructionInputs_exact
#print axioms realM4FiniteCNFVariableFamilyDataConstructionInputs
#print axioms realM4FiniteCNFVariableFamilyDataConstructionInputs_exact
#print axioms realM4CompressionLowerMachineDataConstructionInputs
#print axioms realM4CompressionLowerMachineDataConstructionInputs_exact
#print axioms realM4LockSatisfiableConstructionInputs
#print axioms realM4LockSatisfiableConstructionInputs_exact
#print axioms realM4SelfReductionUpperDischargePrerequisites
#print axioms realM4SelfReductionUpperDischargePrerequisites_exact
#print axioms realM4SelfReductionUpperConditionalInputs
#print axioms realM4SelfReductionUpperConditionalInputs_exact
#print axioms realM4SelfReductionUpperExplicitPNPConstructionInputs
#print axioms realM4SelfReductionUpperExplicitPNPConstructionInputs_exact
#print axioms realM4SelfReductionUpperExplicitPNPConditionalInputs
#print axioms realM4SelfReductionUpperExplicitPNPConditionalInputs_exact
#print axioms realM4_atomCompleteness_of_CDENF
#print axioms realM4_gaugeFaithfulness_of_CDENF
#print axioms RealM4MechanicalInterfaceData
#print axioms RealM4MechanicalInterfaceData.ofCDENFComponents
#print axioms RealM4MechanicalInterfaceData.withAnalyticFrontier
#print axioms RealM4EndgameMechanicalData
#print axioms RealM4EndgameMechanicalData.ofComponents
#print axioms RealM4EndgameMechanicalData.ofComponentsWithLowerMachine
#print axioms RealM4EndgameMechanicalData.ofCDENFComponents
#print axioms RealM4EndgameMechanicalData.interfaceWithAnalyticFrontier
#print axioms RealM4EndgameMechanicalData.parameterRecordWithUpper
#print axioms RealM4EndgameMechanicalData.parameterRecord
#print axioms RealM4EndgameMechanicalData.parameterRecordExplicitPNP
#print axioms realM4_conditionalClash_from_endgameMechanicalData
#print axioms realM4_conditionalClash_from_endgameMechanicalData_explicitPNP
#print axioms realM4_conditionalClash_from_coveredLocksAndRigidity_explicitPNP
#print axioms realM4_conditionalClash_from_coverageDataAndRigidity_explicitPNP
#print axioms realM4_conditionalClash_from_coverageDataAndLockedMessageData_explicitPNP
#print axioms realM4_conditionalClash_from_lowerMachine_coverageDataAndLockedMessageData_explicitPNP
#print axioms realM4_conditionalClash_from_lowerMachine_finiteCNFVariables_coverageDataAndLockedMessageData_explicitPNP
#print axioms realM4_conditionalClash_from_components_coveredLocksAndRigidity_explicitPNP
#print axioms realM4_conditionalClash_from_CDENFComponents_coveredLocksAndRigidity_explicitPNP
#print axioms realM4EndgameStagingConstructionInputs
#print axioms realM4EndgameStagingConstructionInputs_exact
#print axioms realM4EndgameStagingIrreducibleInputs
#print axioms realM4EndgameStagingIrreducibleInputs_exact
#print axioms realM4EndgameStagingStatement
#print axioms realM4EndgameStagingConstructionInputsExplicitPNP
#print axioms realM4EndgameStagingConstructionInputsExplicitPNP_exact
#print axioms realM4EndgameStagingConditionalInputsExplicitPNP
#print axioms realM4EndgameStagingConditionalInputsExplicitPNP_exact
#print axioms realM4EndgameStagingHypothesisAuditExplicitPNP
#print axioms realM4EndgameStagingHypothesisAuditExplicitPNP_exact
#print axioms realM4EndgameStagingStatementExplicitPNP
#print axioms realM4CoveredLocksEndgameConstructionInputsExplicitPNP
#print axioms realM4CoveredLocksEndgameConstructionInputsExplicitPNP_exact
#print axioms realM4CoveredLocksEndgameConditionalInputsExplicitPNP
#print axioms realM4CoveredLocksEndgameConditionalInputsExplicitPNP_exact
#print axioms realM4CoveredLocksEndgameIrreducibleInputsExplicitPNP
#print axioms realM4CoveredLocksEndgameIrreducibleInputsExplicitPNP_exact
#print axioms realM4CoveredLocksEndgameHypothesisAuditExplicitPNP
#print axioms realM4CoveredLocksEndgameHypothesisAuditExplicitPNP_exact
#print axioms realM4CoveredLocksEndgameStatementExplicitPNP
#print axioms realM4CoverageDataEndgameConstructionInputsExplicitPNP
#print axioms realM4CoverageDataEndgameConstructionInputsExplicitPNP_exact
#print axioms realM4CoverageDataEndgameHypothesisAuditExplicitPNP
#print axioms realM4CoverageDataEndgameHypothesisAuditExplicitPNP_exact
#print axioms realM4CoverageDataEndgameStatementExplicitPNP
#print axioms realM4CoverageAndLockedMessageDataEndgameConstructionInputsExplicitPNP
#print axioms realM4CoverageAndLockedMessageDataEndgameConstructionInputsExplicitPNP_exact
#print axioms realM4CoverageAndLockedMessageDataEndgameHypothesisAuditExplicitPNP
#print axioms realM4CoverageAndLockedMessageDataEndgameHypothesisAuditExplicitPNP_exact
#print axioms realM4CoverageAndLockedMessageDataEndgameStatementExplicitPNP
#print axioms realM4LowerMachineCoverageAndLockedMessageDataEndgameConstructionInputsExplicitPNP
#print axioms realM4LowerMachineCoverageAndLockedMessageDataEndgameConstructionInputsExplicitPNP_exact
#print axioms realM4LowerMachineCoverageAndLockedMessageDataEndgameHypothesisAuditExplicitPNP
#print axioms realM4LowerMachineCoverageAndLockedMessageDataEndgameHypothesisAuditExplicitPNP_exact
#print axioms realM4LowerMachineCoverageAndLockedMessageDataEndgameStatementExplicitPNP
#print axioms realM4LowerMachineFiniteCNFVariablesCoverageAndLockedMessageDataEndgameConstructionInputsExplicitPNP
#print axioms realM4LowerMachineFiniteCNFVariablesCoverageAndLockedMessageDataEndgameConstructionInputsExplicitPNP_exact
#print axioms realM4LowerMachineFiniteCNFVariablesCoverageAndLockedMessageDataEndgameHypothesisAuditExplicitPNP
#print axioms realM4LowerMachineFiniteCNFVariablesCoverageAndLockedMessageDataEndgameHypothesisAuditExplicitPNP_exact
#print axioms realM4LowerMachineFiniteCNFVariablesCoverageAndLockedMessageDataEndgameStatementExplicitPNP
#print axioms realM4CDENFComponentCoveredLocksEndgameConstructionInputsExplicitPNP
#print axioms realM4CDENFComponentCoveredLocksEndgameConstructionInputsExplicitPNP_exact
#print axioms realM4CDENFComponentCoveredLocksEndgameHypothesisAuditExplicitPNP
#print axioms realM4CDENFComponentCoveredLocksEndgameHypothesisAuditExplicitPNP_exact
#print axioms realM4CDENFComponentCoveredLocksEndgameStatementExplicitPNP
#print axioms RealM4LiftStatus
#print axioms RealM4LiftLedgerRow
#print axioms realM4LiftLedger
#print axioms realM4LiftLedger_statuses_exact
#print axioms realM4OpenConstructionItems
#print axioms realM4OpenConstructionItems_exact
#print axioms realM4AfterConstructionIrreducibleInputs
#print axioms realM4AfterConstructionIrreducibleInputs_exact
#print axioms realM4_deterministicReadoutOnly_counterexample
#print axioms realM4_publicMessageInvariant_guardrails

end Mettapedia.Computability.PNP
