import Mettapedia.Computability.PNP.V15RealEnsembleSpine

/-!
# Regression seal for the v15 real ensemble spine
-/

namespace Mettapedia.Computability.PNP

set_option autoImplicit false

#check RealSingleMessageSATSpine
#check RealSingleMessageSATSpine.singleMessage
#check RealSingleMessageSATSpine.readout_eq_of_valid
#check RealSingleMessageSATSpine.worldWitness_readout_eq_target
#check v13RealLinearBit
#check v13RealLinearVerifier
#check v13RealLinearWitnessReadout
#check v13RealLinearMessageOfPublic
#check v13RealLinearTargetBit
#check v13RealLinearVerifier_readout_eq_message
#check v13RealLinear_worldWitness_valid
#check v13RealLinearTargetBit_eq_messageOfPublic
#check v13RealLinearSingleMessageSATSpine
#check v13RealLinearSingleMessageSATSpine_singleMessage
#check v13RealLinear_validWitness_readout_eq_publicMessage
#check RealM4LockedCoreWorld
#check RealM4LockedCoreWitness
#check RealM4LockedCoreWorld.toWitness
#check realM4LockedCoreVerifier
#check realM4LockedCoreWitnessReadout
#check realM4LockedCoreMessageOfPublic
#check realM4LockedCoreWitness_readout_eq_publicMessage
#check realM4LockedCoreSingleMessageSATSpine
#check realM4LockedCore_singleMessage_of_publicMessageInvariant
#check realM4LockedCore_readout_eq_of_valid_of_publicMessageInvariant
#check realM4_lockedMessageRigidity_of_publicMessageInvariant
#check realM4_cnfSingleMessageReadout_of_publicMessageInvariant
#check realM4_semanticI26_of_publicMessageInvariant
#check realM4_exists_correctForAllSatSearchOutputs_of_publicMessageInvariant
#check realM4_supportedArbitraryOutputSATSearchCorrect_of_publicMessageInvariant
#check RealM4CNFWorld
#check RealM4CNFWitness
#check RealM4CNFWorld.toWitness
#check realM4CNFVerifier
#check realM4CNFWitnessReadout
#check realM4CNFMessageOfPublic
#check realM4CNFWitness_readout_eq_publicMessage
#check realM4CNFSingleMessageSATSpine
#check realM4CNF_singleMessage_of_publicMessageInvariant
#check realM4CNF_readout_eq_of_valid_of_publicMessageInvariant
#check ConcreteCNF.Literal.var
#check ConcreteCNF.unitLiteral
#check ConcreteCNF.unitClause
#check ConcreteCNF.prefixClauses
#check ConcreteCNF.restrictWithPrefix
#check ConcreteCNF.FormulaUsesOnly
#check ConcreteCNF.isSatClause_unitClause_iff
#check ConcreteCNF.isSatFormula_append_iff
#check CNFPrefix.Satisfied
#check CNFPrefix.value
#check CNFPrefix.assignment
#check CNFPrefix.satisfied_nil
#check CNFPrefix.satisfied_append_single
#check CNFPrefix.exists_pair_of_mem_keys
#check CNFPrefix.value_eq_of_mem
#check CNFPrefix.assignment_eq_of_mem
#check ConcreteCNF.isSatFormula_prefixClauses_iff
#check ConcreteCNF.isSatFormula_restrictWithPrefix_iff
#check ConcreteCNF.isSatFormula_of_agree_on_formulaUsesOnly
#check RealCNFRestrictedSatisfiable
#check RealCNFPNPSATDecider
#check realCNFRestricted_decideSat_true_iff
#check realCNFBitFixPrefixAux
#check realCNFBitFixPrefix
#check realCNFBitFixAssignment
#check realCNFBitFixPrefixAux_keys
#check realCNFBitFixPrefixAux_satisfiable
#check realCNFBitFixAssignment_satisfies
#check realM4_bitFixingAssignment_satisfies
#check realM4_bitFixingReadout_eq_publicMessage_of_publicMessageInvariant
#check RealM4CNFUniformBitFixingData
#check RealM4CNFUniformBitFixingData.bitFixingAssignment
#check RealM4CNFUniformBitFixingData.bitFixingAssignment_satisfies
#check realM4_uniformBitFixingAssignment_satisfies
#check realM4_uniformBitFixingReadout_eq_publicMessage_of_publicMessageInvariant
#check realCNFRestrictedFormulaCompilerProgramLength
#check realCNFBitFixingDriverProgramLength
#check realCNFReadoutProgramLength
#check realCNFSelfReductionDecoderCost
#check realCNFConstantDecoderKpolyAt
#check realCNFLinearEtaTimes
#check realCNFConstantDecoderKpolyAt_eq
#check realM4UniformSelfReductionDecoderCost
#check realM4UniformSelfReductionDecoderCost_bounds_instance
#check realM4UniformConstantDecoderKpolyAt
#check realM4UniformConstantDecoderKpolyAt_eq
#check RealCNFConstantDecoderRegime
#check realCNF_selfReductionUpperHypothesis_givenPNP
#check RealM4UniformConstantDecoderRegime
#check realM4_uniformSelfReductionUpperHypothesis_givenPNP
#check RealM4LiftStatus
#check RealM4LiftLedgerRow
#check realM4LiftLedger
#check realM4LiftLedger_statuses_exact
#check realM4OpenConstructionItems
#check realM4OpenConstructionItems_exact
#check realM4AfterConstructionIrreducibleInputs
#check realM4AfterConstructionIrreducibleInputs_exact
#check realM4_deterministicReadoutOnly_counterexample
#check realM4_publicMessageInvariant_guardrails

#print axioms RealSingleMessageSATSpine
#print axioms RealSingleMessageSATSpine.singleMessage
#print axioms RealSingleMessageSATSpine.readout_eq_of_valid
#print axioms RealSingleMessageSATSpine.worldWitness_readout_eq_target
#print axioms v13RealLinearBit
#print axioms v13RealLinearVerifier
#print axioms v13RealLinearWitnessReadout
#print axioms v13RealLinearMessageOfPublic
#print axioms v13RealLinearTargetBit
#print axioms v13RealLinearVerifier_readout_eq_message
#print axioms v13RealLinear_worldWitness_valid
#print axioms v13RealLinearTargetBit_eq_messageOfPublic
#print axioms v13RealLinearSingleMessageSATSpine
#print axioms v13RealLinearSingleMessageSATSpine_singleMessage
#print axioms v13RealLinear_validWitness_readout_eq_publicMessage
#print axioms RealM4LockedCoreWorld
#print axioms RealM4LockedCoreWitness
#print axioms RealM4LockedCoreWorld.toWitness
#print axioms realM4LockedCoreVerifier
#print axioms realM4LockedCoreWitnessReadout
#print axioms realM4LockedCoreMessageOfPublic
#print axioms realM4LockedCoreWitness_readout_eq_publicMessage
#print axioms realM4LockedCoreSingleMessageSATSpine
#print axioms realM4LockedCore_singleMessage_of_publicMessageInvariant
#print axioms realM4LockedCore_readout_eq_of_valid_of_publicMessageInvariant
#print axioms realM4_lockedMessageRigidity_of_publicMessageInvariant
#print axioms realM4_cnfSingleMessageReadout_of_publicMessageInvariant
#print axioms realM4_semanticI26_of_publicMessageInvariant
#print axioms realM4_exists_correctForAllSatSearchOutputs_of_publicMessageInvariant
#print axioms realM4_supportedArbitraryOutputSATSearchCorrect_of_publicMessageInvariant
#print axioms RealM4CNFWorld
#print axioms RealM4CNFWitness
#print axioms RealM4CNFWorld.toWitness
#print axioms realM4CNFVerifier
#print axioms realM4CNFWitnessReadout
#print axioms realM4CNFMessageOfPublic
#print axioms realM4CNFWitness_readout_eq_publicMessage
#print axioms realM4CNFSingleMessageSATSpine
#print axioms realM4CNF_singleMessage_of_publicMessageInvariant
#print axioms realM4CNF_readout_eq_of_valid_of_publicMessageInvariant
#print axioms ConcreteCNF.Literal.var
#print axioms ConcreteCNF.unitLiteral
#print axioms ConcreteCNF.unitClause
#print axioms ConcreteCNF.prefixClauses
#print axioms ConcreteCNF.restrictWithPrefix
#print axioms ConcreteCNF.FormulaUsesOnly
#print axioms ConcreteCNF.isSatClause_unitClause_iff
#print axioms ConcreteCNF.isSatFormula_append_iff
#print axioms CNFPrefix.Satisfied
#print axioms CNFPrefix.value
#print axioms CNFPrefix.assignment
#print axioms CNFPrefix.satisfied_nil
#print axioms CNFPrefix.satisfied_append_single
#print axioms CNFPrefix.exists_pair_of_mem_keys
#print axioms CNFPrefix.value_eq_of_mem
#print axioms CNFPrefix.assignment_eq_of_mem
#print axioms ConcreteCNF.isSatFormula_prefixClauses_iff
#print axioms ConcreteCNF.isSatFormula_restrictWithPrefix_iff
#print axioms ConcreteCNF.isSatFormula_of_agree_on_formulaUsesOnly
#print axioms RealCNFRestrictedSatisfiable
#print axioms RealCNFPNPSATDecider
#print axioms realCNFRestricted_decideSat_true_iff
#print axioms realCNFBitFixPrefixAux
#print axioms realCNFBitFixPrefix
#print axioms realCNFBitFixAssignment
#print axioms realCNFBitFixPrefixAux_keys
#print axioms realCNFBitFixPrefixAux_satisfiable
#print axioms realCNFBitFixAssignment_satisfies
#print axioms realM4_bitFixingAssignment_satisfies
#print axioms realM4_bitFixingReadout_eq_publicMessage_of_publicMessageInvariant
#print axioms RealM4CNFUniformBitFixingData
#print axioms RealM4CNFUniformBitFixingData.bitFixingAssignment
#print axioms RealM4CNFUniformBitFixingData.bitFixingAssignment_satisfies
#print axioms realM4_uniformBitFixingAssignment_satisfies
#print axioms realM4_uniformBitFixingReadout_eq_publicMessage_of_publicMessageInvariant
#print axioms realCNFRestrictedFormulaCompilerProgramLength
#print axioms realCNFBitFixingDriverProgramLength
#print axioms realCNFReadoutProgramLength
#print axioms realCNFSelfReductionDecoderCost
#print axioms realCNFConstantDecoderKpolyAt
#print axioms realCNFLinearEtaTimes
#print axioms realCNFConstantDecoderKpolyAt_eq
#print axioms realM4UniformSelfReductionDecoderCost
#print axioms realM4UniformSelfReductionDecoderCost_bounds_instance
#print axioms realM4UniformConstantDecoderKpolyAt
#print axioms realM4UniformConstantDecoderKpolyAt_eq
#print axioms RealCNFConstantDecoderRegime
#print axioms realCNF_selfReductionUpperHypothesis_givenPNP
#print axioms RealM4UniformConstantDecoderRegime
#print axioms realM4_uniformSelfReductionUpperHypothesis_givenPNP
#print axioms RealM4LiftStatus
#print axioms RealM4LiftLedgerRow
#print axioms realM4LiftLedger
#print axioms realM4LiftLedger_statuses_exact
#print axioms realM4OpenConstructionItems
#print axioms realM4OpenConstructionItems_exact
#print axioms realM4AfterConstructionIrreducibleInputs
#print axioms realM4AfterConstructionIrreducibleInputs_exact
#print axioms realM4_deterministicReadoutOnly_counterexample
#print axioms realM4_publicMessageInvariant_guardrails

end Mettapedia.Computability.PNP
