import Mettapedia.Computability.PNP.V15SmallSingleMessageCNFEnsemble

/-!
# PNP v15: small concrete single-message CNF ensemble regression
-/

namespace Mettapedia.Computability.PNP

#check smallSingleMessageFormula
#check smallSingleMessageVerifierDecision
#check smallSingleMessageCNFReadoutData
#check SmallSingleMessageNoPublicCoordinateTargetTags
#check SmallSingleMessageNoPublicCoordinateReadoutTags

#print axioms smallSingleMessageVerifierDecision_correct
#print axioms smallSingleMessageFormula_satisfied_messageAssignment
#print axioms smallSingleMessageFormula_forces_message
#print axioms smallSingleMessageProjection_eq_M_of_sat
#print axioms smallSingleMessageCNFReadoutData
#print axioms smallSingleMessageCNFReadoutData_singleMessagePromise
#print axioms smallSingleMessageCNFReadoutData_supportedSatisfiable
#print axioms smallSingleMessageCNFReadoutData_projection_eq_M
#print axioms smallSingleMessageCNFReadoutData_supportedArbitraryOutputSATSearchCorrect
#print axioms smallSingleMessage_publicCoordinate_determines_message
#print axioms smallSingleMessage_noPublicTargetTags_obstruction
#print axioms smallSingleMessage_publicCoordinate_determines_satProjection
#print axioms smallSingleMessage_noPublicReadoutTags_obstruction

end Mettapedia.Computability.PNP
