#!/usr/bin/env python3
"""Exact degree-one source-multiplier audit for hard non-collapse chord kills.

Fix the hard generic `(vertex 0, colour 2)` non-collapse chart and one of
its four exhaustive domain factor leaves.  Let `J` be generated by the two
adjugate-supplied incident P-kills and the leaf's two zero factors.  This
program tests, over Q, whether each P-line needed by a minimal doily
completion satisfies

    theta * P(edge) in span_Q {m * A : A a normalized frozen amplitude row,
                                m = 1 or a gauge-fixed variable} + J.

Thus it exhausts every constant-or-linear source-multiplier certificate for
the desired localized chord kill.  The computation is exact sparse rational
linear algebra after exact quotient reduction; it is not a Gröbner search.
If a target is found, coefficient extraction and strict replay are required
next.  If none is found, only this degree-one source-multiplier family is
ruled out.
"""

from __future__ import annotations

import os
import hashlib
import itertools
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any

import sympy as sp
from sympy.polys.domains import ZZ
from sympy.polys.matrices import DomainMatrix


ROOT = Path(os.environ.get("KRENN_ARTIFACTS", "artifacts"))
PRIVATE = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(PRIVATE) not in sys.path:
    sys.path.insert(0, str(PRIVATE))

import c6_collapse_attack as c6  # noqa: E402
import f9_pipeline as pipeline  # noqa: E402
from audit_c6_noncollapse_factor_frontier import total_forced_zero  # noqa: E402


FRONTIER = ROOT / "noncollapse_case_artifacts" / "noncollapse_factor_frontier_audit_v1.json"
CONSTANT_SPAN = ROOT / "noncollapse_case_artifacts" / "noncollapse_chord_constant_span_factor_leaf_audit_v1.json"
TARGET = ROOT / "noncollapse_case_artifacts" / "noncollapse_chord_linear_macaulay_factor_leaf_audit_v1.json"


TermRow = list[tuple[tuple[int, ...], int]]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def digest(value: object) -> str:
    return hashlib.sha256(
        json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    ).hexdigest()


def profile(colours: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(sorted(Counter(colours).values(), reverse=True))


def terms(expression: sp.Expr, variables: list[sp.Symbol]) -> TermRow:
    return [
        (powers, int(coefficient))
        for powers, coefficient in sp.Poly(expression, *variables, domain=sp.ZZ).terms()
        if coefficient
    ]


def factor_symbol(record: dict[str, Any]) -> sp.Symbol:
    if record.get("kind") not in {"diagonal", "offdiagonal"}:
        raise RuntimeError("factor frontier supplied a non-weight factor")
    return sp.Symbol(record["symbol"])


def minimal_completions(
    base: set[tuple[int, int]], zeros: set[tuple[int, int]]
) -> list[tuple[tuple[int, int], ...]]:
    all_edges = [(a, b) for a in range(6) for b in range(a + 1, 6)]
    available = [edge for edge in all_edges if edge not in base]
    for size in range(1, len(available) + 1):
        hits = [
            candidate for candidate in itertools.combinations(available, size)
            if total_forced_zero(base | set(candidate), zeros)
        ]
        if hits:
            return hits
    raise RuntimeError("all P-lines should force a doily contradiction")


def multiply(row: TermRow, variable_index: int) -> TermRow:
    return [
        (tuple(exponent + (position == variable_index)
               for position, exponent in enumerate(powers)), coefficient)
        for powers, coefficient in row
    ]


def matrix_rank(rows: list[TermRow], monomial_index: dict[tuple[int, ...], int]) -> int:
    matrix = DomainMatrix.from_dod(
        {
            row: {monomial_index[monomial]: ZZ(coefficient)
                  for monomial, coefficient in terms_row}
            for row, terms_row in enumerate(rows)
        },
        (len(rows), len(monomial_index)),
        ZZ,
    ).to_field()
    return matrix.rank()


def main() -> int:
    frontier = json.loads(FRONTIER.read_text())
    if frontier.get("format") != "krenn-c6-noncollapse-factor-frontier-audit-v1":
        raise RuntimeError("factor-frontier format drift")
    constant_span = json.loads(CONSTANT_SPAN.read_text())
    if constant_span.get("format") != "krenn-c6-noncollapse-chord-constant-span-factor-leaf-audit-v1":
        raise RuntimeError("constant-span audit format drift")
    if constant_span["summary"] != {
        "constant_span_p_kill_matches": 0,
        "factor_leaves": 4,
        "minimal_completion_size": 3,
    }:
        raise RuntimeError("constant-span audit result drift")
    hard = next(row for row in frontier["frontier"] if row["pair_orbit_index"] == 2)

    vertex, colour = 0, 2
    left, right = c6.NBR[vertex]
    case0 = pipeline.cases_for(c6.X)[0]
    fixed = pipeline.max_fixable([
        (c6.X[index], source, target)
        for index, (source, target) in enumerate(case0)
    ])
    substitution = {c6.VAR[key]: sp.Integer(1) for key in fixed}
    p_left = sp.expand(c6.P(vertex, left, colour).xreplace(substitution))
    p_right = sp.expand(c6.P(vertex, right, colour).xreplace(substitution))
    theta = sp.expand(c6.theta_det(vertex, colour).xreplace(substitution))

    source_rows: list[sp.Expr] = []
    for colours in itertools.product(range(3), repeat=6):
        kind = profile(colours)
        source_rows.append(sp.expand(
            c6.pm_sum(dict(enumerate(colours))).xreplace(substitution)
            - (1 if kind == (6,) else 0)
        ))
    if len(source_rows) != 729:
        raise RuntimeError("frozen C6 row census drift")
    variables = sorted(
        {symbol for row in source_rows for symbol in row.free_symbols}
        | p_left.free_symbols | p_right.free_symbols,
        key=sp.default_sort_key,
    )

    leaf_records = []
    positive = []
    for branch_index, branch in enumerate(hard["branches"]):
        doily = branch["doily_constraints_by_colour"]
        if len(doily) != 1 or doily[0]["colour"] != colour:
            raise RuntimeError("hard leaf doily data drift")
        base = {tuple(edge) for edge in doily[0]["dead_p_edges"]}
        zeros = {tuple(edge) for edge in doily[0]["diagonal_zero_edges"]}
        completions = minimal_completions(base, zeros)
        factors = [factor_symbol(branch["x_factor"]), factor_symbol(branch["y_factor"])]
        groebner = sp.groebner([p_left, p_right, *factors], *variables, order="lex")
        reduced_source: list[TermRow] = []
        for source in source_rows:
            quotients, remainder = groebner.reduce(source)
            replay = sp.expand(source - remainder - sum(
                quotient * basis.as_expr()
                for quotient, basis in zip(quotients, groebner.polys, strict=True)
            ))
            if replay != 0:
                raise RuntimeError("leaf reduction replay drift")
            reduced_source.append(terms(remainder, variables))
        expanded_rows: list[TermRow] = []
        for row in reduced_source:
            expanded_rows.append(row)
            expanded_rows.extend(multiply(row, index) for index in range(len(variables)))
        if len(expanded_rows) != len(reduced_source) * (len(variables) + 1):
            raise RuntimeError("Macaulay source multiplier inventory drift")
        target_edges = sorted({edge for completion in completions for edge in completion})
        target_rows: dict[tuple[int, int], TermRow] = {}
        for edge in target_edges:
            _quotients, target_remainder = groebner.reduce(sp.expand(
                theta * c6.P(edge[0], edge[1], colour).xreplace(substitution)
            ))
            target_rows[edge] = terms(target_remainder, variables)
        monomials = {
            monomial for row in expanded_rows for monomial, _coefficient in row
        } | {
            monomial for row in target_rows.values() for monomial, _coefficient in row
        }
        monomial_index = {monomial: index for index, monomial in enumerate(sorted(monomials))}
        span_rank = matrix_rank(expanded_rows, monomial_index)
        target_records = []
        for edge in target_edges:
            target_row = target_rows[edge]
            if not target_row:
                target_records.append({
                    "edge": list(edge),
                    "theta_times_target_is_zero_mod_leaf_constraints": True,
                    "span_member": True,
                    "rank_with_target": span_rank,
                })
                positive.append({"branch_index": branch_index, "edge": list(edge), "kind": "zero_mod_constraints"})
                continue
            rank_with_target = matrix_rank([*expanded_rows, target_row], monomial_index)
            member = rank_with_target == span_rank
            target_records.append({
                "edge": list(edge),
                "theta_times_target_is_zero_mod_leaf_constraints": False,
                "target_terms": len(target_row),
                "span_member": member,
                "rank_with_target": rank_with_target,
            })
            if member:
                positive.append({"branch_index": branch_index, "edge": list(edge), "kind": "degree_one_source_span"})
        leaf_records.append({
            "branch_index": branch_index,
            "factor_zero_generators": [str(factor) for factor in factors],
            "minimal_doily_completion_size": len(completions[0]),
            "minimal_doily_completions": [[list(edge) for edge in completion] for completion in completions],
            "variables": len(variables),
            "source_rows": len(reduced_source),
            "source_multiplier_basis": "constant plus each gauge-fixed variable",
            "macaulay_rows": len(expanded_rows),
            "ambient_monomials": len(monomial_index),
            "source_span_rank": span_rank,
            "targets": target_records,
        })

    payload = {
        "format": "krenn-c6-noncollapse-chord-linear-macaulay-factor-leaf-audit-v1",
        "scope": {
            "pair_orbit_index": 2,
            "slot": {"vertex": vertex, "colour": colour, "neighbours": [left, right]},
            "theta": str(theta),
            "known_p_kills": [str(p_left), str(p_right)],
            "source_rows": len(source_rows),
        },
        "candidate_family": (
            "Every identity theta*P(edge) = sum_i q_i*A_i + J where each q_i is "
            "constant or one gauge-fixed variable, A_i is one normalized frozen amplitude "
            "row, and J is generated by the two incident P-kills and one exhaustive factor leaf."
        ),
        "factor_leaves": leaf_records,
        "summary": {
            "factor_leaves": len(leaf_records),
            "degree_one_source_span_matches": len(positive),
            "minimal_completion_size": 3,
        },
        "conclusion": {
            "established": (
                "No required chord theta*P target belongs to the stated exact degree-one "
                "source-multiplier span on any hard factor leaf."
                if not positive else
                "At least one required chord theta*P target belongs to the degree-one source span; "
                "extract and strictly replay its coefficients before using it."
            ),
            "not_established": (
                "Source multipliers of degree two or higher, non-Macaulay structural arguments, "
                "and other non-collapse chart types remain outside this audit."
            ),
        },
        "sources": {
            "factor_frontier_sha256": sha256(FRONTIER),
            "constant_span_audit_sha256": sha256(CONSTANT_SPAN),
            "c6_collapse_attack_sha256": sha256(ROOT / "c6_collapse_attack.py"),
            "f9_pipeline_sha256": sha256(ROOT / "f9_pipeline.py"),
            "audit_script_sha256": sha256(Path(__file__)),
        },
        "receipt_payload_sha256": digest({
            "factor_leaves": leaf_records,
            "positive": positive,
        }),
    }
    TARGET.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    if positive:
        print("C6 DEGREE-ONE FACTOR-LEAF MACAULAY AUDIT FOUND MEMBERS: " + str(len(positive)))
        return 2
    print(
        "C6 DEGREE-ONE FACTOR-LEAF MACAULAY AUDIT VERIFIED: "
        f"{len(leaf_records)} leaves, no required chord theta*P targets"
    )
    print("manifest_sha256=" + sha256(TARGET))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
