#!/usr/bin/env python3
"""Generate the result tables for the provenance-carrying fusion report.

Every number that appears in a result table of ``wm-pln-provenance-fusion.tex``
is written here from a machine-produced run receipt.  Nothing is typed by hand.

A receipt that is absent yields an explicit ``PENDING`` table stating that the
run has not been performed, rather than a value.  An experiment that has not
been run therefore cannot be reported as a result, and a table can never drift
away from the receipt it describes.

Receipt locations are supplied on the command line; no path is embedded here.

Usage:
  generate_wm_pln_fusion_tables.py --out generated \
      [--cafa5-differential SUMMARY.json] \
      [--cafa5-full RUN_SUMMARY.json] \
      [--biopathnet-candidate CANDIDATE_SUMMARY.json] \
      [--biopathnet-plan RUN_PLAN.json] \
      [--biopathnet-grid GRID_SUMMARY.json]
"""

from __future__ import annotations

import argparse
import json
import math
import re
from pathlib import Path
from typing import Any


PREAMBLE = (
    "% Generated by generate_wm_pln_fusion_tables.py from run receipts.\n"
    "% Do not edit by hand; edits will be overwritten and are not receipt-backed.\n"
)


HASH_RE = re.compile(r"^[0-9a-f]{64}$")


class ReceiptError(ValueError):
    """A supplied receipt cannot safely support the requested publication."""


class ReceiptFieldMissing(ReceiptError):
    """A receipt lacks a field the report intends to publish."""


def tex_escape(value: str) -> str:
    """Escape receipt text before embedding it in LaTeX."""

    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(character, character) for character in value)


def short_hash(value: str, keep: int = 12) -> str:
    if len(value) <= keep:
        return value
    return f"{value[:keep]}\\ldots"


def load(path: Path | None, label: str) -> dict[str, Any] | None:
    """Load an optional receipt.

    Omitting an option means the experiment is pending. Supplying a path is a
    publication request, so a missing, malformed, or non-object file is fatal.
    """

    if path is None:
        return None
    if not path.is_file():
        raise ReceiptError(f"{label} receipt does not exist: {path}")
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ReceiptError(f"cannot read {label} receipt {path}: {error}") from error
    if not isinstance(payload, dict):
        raise ReceiptError(f"{label} receipt must be a JSON object")
    return payload


def require(receipt: dict[str, Any], *keys: str) -> Any:
    """Fetch a receipt field, failing loudly if it is absent.

    A default here would silently publish a plausible wrong number -- exactly the
    failure this report argues against.  An unreadable receipt must stop the
    build instead.
    """
    cursor = receipt
    for index, key in enumerate(keys):
        if not isinstance(cursor, dict) or key not in cursor:
            path = " -> ".join(keys[: index + 1])
            raise ReceiptFieldMissing(
                f"receipt field {path!r} is absent; refusing to publish a default"
            )
        cursor = cursor[key]
    return cursor


def field_name(keys: tuple[str, ...]) -> str:
    return " -> ".join(keys)


def require_object(receipt: dict[str, Any], *keys: str) -> dict[str, Any]:
    value = require(receipt, *keys)
    if not isinstance(value, dict):
        raise ReceiptError(f"receipt field {field_name(keys)!r} must be an object")
    return value


def require_list(receipt: dict[str, Any], *keys: str) -> list[Any]:
    value = require(receipt, *keys)
    if not isinstance(value, list):
        raise ReceiptError(f"receipt field {field_name(keys)!r} must be an array")
    return value


def require_text(receipt: dict[str, Any], *keys: str) -> str:
    value = require(receipt, *keys)
    if not isinstance(value, str) or not value:
        raise ReceiptError(f"receipt field {field_name(keys)!r} must be nonempty text")
    return value


def require_int(receipt: dict[str, Any], *keys: str, minimum: int = 0) -> int:
    value = require(receipt, *keys)
    if isinstance(value, bool) or not isinstance(value, int) or value < minimum:
        raise ReceiptError(
            f"receipt field {field_name(keys)!r} must be an integer >= {minimum}"
        )
    return value


def require_number(receipt: dict[str, Any], *keys: str) -> float:
    value = require(receipt, *keys)
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ReceiptError(f"receipt field {field_name(keys)!r} must be numeric")
    result = float(value)
    if not math.isfinite(result):
        raise ReceiptError(f"receipt field {field_name(keys)!r} must be finite")
    return result


def require_probability(receipt: dict[str, Any], *keys: str) -> float:
    value = require_number(receipt, *keys)
    if not 0.0 <= value <= 1.0:
        raise ReceiptError(f"receipt field {field_name(keys)!r} must lie in [0,1]")
    return value


def require_bool(receipt: dict[str, Any], *keys: str) -> bool:
    value = require(receipt, *keys)
    if not isinstance(value, bool):
        raise ReceiptError(f"receipt field {field_name(keys)!r} must be boolean")
    return value


def require_hash(receipt: dict[str, Any], *keys: str) -> str:
    value = require_text(receipt, *keys)
    if HASH_RE.fullmatch(value) is None:
        raise ReceiptError(
            f"receipt field {field_name(keys)!r} must be a lowercase SHA-256 digest"
        )
    return value


def require_equal(left: Any, right: Any, message: str) -> None:
    if left != right:
        raise ReceiptError(message)


def pending(label: str, reason: str) -> str:
    return (
        PREAMBLE
        + "\\begin{center}\n\\fbox{\\parbox{0.9\\linewidth}{\\textbf{PENDING: "
        + label
        + ".} "
        + reason
        + " No receipt exists for this run, so no value is reported here.}}\n"
        + "\\end{center}\n"
    )


def reducer_equivalence_table(receipt: dict[str, Any] | None) -> str:
    if receipt is None:
        return pending(
            "reducer differential equivalence",
            "The real-shaped CeTTa/SQLite differential gate has not been run.",
        )
    backend = require_text(receipt, "backend")
    backend_role = require_text(receipt, "backend_role")
    fusion_policy = require_text(receipt, "fusion_policy")
    input_rows = require_int(receipt, "input_rows")
    packet_rows = require_int(receipt, "packet_rows")
    group_rows = require_int(receipt, "group_rows")
    candidate_rows = require_int(receipt, "candidate_rows")
    duplicates = require_int(receipt, "exact_duplicate_rows_collapsed")
    partition_shards = require_int(receipt, "partition_shards", minimum=1)
    active_shards = require_int(receipt, "active_shards", minimum=1)
    prediction_hash = require_hash(receipt, "prediction_sha256")
    manifest_hash = require_hash(receipt, "shard_manifest_sha256")

    oracle = require_object(receipt, "differential_oracle")
    status = require_text(oracle, "status")
    comparison = require_object(oracle, "comparison")
    compared_rows = require_int(comparison, "rows")
    maximum_error = require_number(comparison, "maximum_absolute_error")
    ref = require_object(oracle, "oracle")
    reference_backend = require_text(ref, "backend")
    reference_hash = require_hash(ref, "prediction_sha256")
    sources = require_object(oracle, "source_rows")
    if not sources:
        raise ReceiptError("receipt field 'differential_oracle -> source_rows' is empty")
    source_counts: list[tuple[str, int]] = []
    for name, count in sorted(sources.items()):
        if not isinstance(name, str) or not name:
            raise ReceiptError("differential source names must be nonempty text")
        if isinstance(count, bool) or not isinstance(count, int) or count < 0:
            raise ReceiptError(f"differential source row count for {name!r} is invalid")
        source_counts.append((name, count))

    require_equal(backend_role, "load-bearing-reducer", "primary reducer is not load-bearing")
    require_equal(status, "passed", "differential equivalence gate did not pass")
    require_equal(input_rows, packet_rows, "input and deduplicated packet counts differ")
    require_equal(sum(count for _, count in source_counts), input_rows, "source rows do not sum to input rows")
    require_equal(compared_rows, candidate_rows, "differential comparison omitted candidates")
    require_equal(maximum_error, 0.0, "differential comparison is not numerically exact")
    require_equal(prediction_hash, reference_hash, "primary and reference prediction digests differ")
    if active_shards > partition_shards:
        raise ReceiptError("active shard count exceeds configured partition count")

    rows = "\n".join(
        f"    {tex_escape(name)} & {count:,} \\\\" for name, count in source_counts
    )
    return PREAMBLE + f"""\\begin{{table}}[H]
  \\centering
  \\small
  \\caption{{Differential equivalence of the load-bearing reducer against the
  independent reference implementation on a real evidence slice.  Both
  implementations consume the same {input_rows:,} input rows and
  emit byte-identical fused predictions.  Status reported by the gate:
  \\texttt{{{tex_escape(status)}}}.}}
  \\label{{tab:reducer-equivalence}}
  \\begin{{tabular}}{{ll}}
    \\toprule
    Quantity & Value \\\\
    \\midrule
    Primary backend & \\texttt{{{tex_escape(backend)}}} \\\\
    Primary role & \\texttt{{{tex_escape(backend_role)}}} \\\\
    Reference backend & \\texttt{{{tex_escape(reference_backend)}}} \\\\
    Fusion policy & \\texttt{{{tex_escape(fusion_policy)}}} \\\\
    \\midrule
    Input rows & {input_rows:,} \\\\
    Evidence packets & {packet_rows:,} \\\\
    Dependence groups & {group_rows:,} \\\\
    Fused candidates & {candidate_rows:,} \\\\
    Exact duplicates collapsed & {duplicates:,} \\\\
    Partition shards (active) & {partition_shards} ({active_shards}) \\\\
    \\midrule
    Compared rows & {compared_rows:,} \\\\
    \\textbf{{Maximum absolute error}} & \\textbf{{{maximum_error}}} \\\\
    \\midrule
    Prediction digest (primary) & \\texttt{{{short_hash(prediction_hash)}}} \\\\
    Prediction digest (reference) & \\texttt{{{short_hash(reference_hash)}}} \\\\
    Shard manifest digest & \\texttt{{{short_hash(manifest_hash)}}} \\\\
    \\bottomrule
  \\end{{tabular}}

  \\vspace{{0.5em}}
  \\begin{{tabular}}{{lr}}
    \\toprule
    Evidence source & Rows \\\\
    \\midrule
{rows}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""


def biopathnet_candidate_table(receipt: dict[str, Any] | None) -> str:
    if receipt is None:
        return pending(
            "path-evidence validation candidate",
            "No validation candidate receipt is present.",
        )
    status = require_text(receipt, "status")
    job_id = require_text(receipt, "job_id")
    fingerprint = require_hash(receipt, "experiment_fingerprint")
    test_opened = require_bool(receipt, "test_split_opened")
    test_state = require_text(receipt, "test_plan_state")
    model = require_object(receipt, "model")
    params = require_object(model, "parameters")
    stats = require_object(model, "training_statistics")
    validation = require_object(receipt, "validation")
    metrics = require_object(validation, "metrics")
    candidates = require_object(validation, "candidate_count")

    model_hash = require_hash(model, "sha256")
    template_count = require_int(model, "template_count")
    max_depth = require_int(params, "max_depth", minimum=1)
    minimum_support = require_int(params, "minimum_support", minimum=1)
    path_cap = require_int(params, "path_cap", minimum=1)
    alpha = require_int(params, "alpha", minimum=1)
    beta = require_int(params, "beta", minimum=1)
    seed = require_int(params, "seed")
    shortfall_policy = require_text(stats, "sampled_negative_shortfall_policy")
    supervised = require_int(stats, "supervised_positive_count")
    requested_negatives = require_int(stats, "requested_sampled_negative_count")
    actual_negatives = require_int(stats, "actual_sampled_negative_count")
    negative_shortfall = require_int(stats, "sampled_negative_shortfall_count")
    no_control = require_int(stats, "positives_without_type_matched_negative_candidates")
    validation_queries = require_int(validation, "queries", minimum=1)
    mean_candidates = require_number(candidates, "mean")
    mrr = require_probability(metrics, "mrr")
    mean_rank = require_number(metrics, "mr")
    hits1 = require_probability(metrics, "hits@1")
    hits3 = require_probability(metrics, "hits@3")
    hits10 = require_probability(metrics, "hits@10")
    brier = require_probability(metrics, "sampled_negative_brier")
    brier_examples = require_int(metrics, "sampled_negative_brier_examples", minimum=1)

    require_equal(
        requested_negatives - actual_negatives,
        negative_shortfall,
        "sampled-negative shortfall is inconsistent with requested and obtained counts",
    )
    if test_opened:
        raise ReceiptError("validation-candidate receipt says the test split was opened")
    require_equal(test_state, "unarmed", "validation-candidate test plan is not unarmed")

    return PREAMBLE + f"""\\begin{{table}}[H]
  \\centering
  \\small
  \\caption{{Single unselected validation candidate of the relation-path evidence
  model.  Reported status: \\texttt{{{tex_escape(status)}}}.  These are
  validation-only observations for one hyperparameter point; they are not a test
  result, not a selected model, and not a comparison against any control.
  Shortfall policy recorded by the run:
  \\emph{{{tex_escape(shortfall_policy)}}}.}}
  \\label{{tab:biopathnet-candidate}}
  \\begin{{tabular}}{{ll}}
    \\toprule
    Quantity & Value \\\\
    \\midrule
    Job & \\texttt{{{tex_escape(job_id)}}} \\\\
    Experiment fingerprint & \\texttt{{{short_hash(fingerprint)}}} \\\\
    Model digest & \\texttt{{{short_hash(model_hash)}}} \\\\
    Path templates & {template_count:,} \\\\
    Depth / min.\\ support / path cap & {max_depth} / {minimum_support} / {path_cap} \\\\
    Evidence prior $(\\alpha,\\beta)$ & ({alpha}, {beta}) \\\\
    Seed & {seed} \\\\
    \\midrule
    Supervised positives & {supervised:,} \\\\
    Sampled negatives (requested) & {requested_negatives:,} \\\\
    Sampled negatives (obtained) & {actual_negatives:,} \\\\
    Sampled-negative shortfall & {negative_shortfall:,} \\\\
    Positives without exact-type control & {no_control} \\\\
    \\midrule
    Validation queries & {validation_queries:,} \\\\
    Candidates per query (mean) & {mean_candidates:.1f} \\\\
    MRR & {mrr:.6f} \\\\
    Mean rank & {mean_rank:.2f} \\\\
    Hits@1 / @3 / @10 & {hits1:.4f} / {hits3:.4f} / {hits10:.4f} \\\\
    Brier vs.\\ sampled negatives & {brier:.6f} \\\\
    Brier examples & {brier_examples:,} \\\\
    \\midrule
    Test split opened & \\texttt{{false}} \\\\
    Test plan state & \\texttt{{{tex_escape(test_state)}}} \\\\
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""


def preregistration_table(
    plan: dict[str, Any] | None, candidate: dict[str, Any] | None
) -> str:
    if plan is None and candidate is None:
        return pending("pre-registration state", "No plan receipt is present.")
    if plan is not None:
        fingerprint = require_hash(plan, "experiment_fingerprint")
        jobs = require_list(plan, "jobs")
        if not jobs:
            raise ReceiptError("pre-registration plan contains no jobs")
        policy = require_object(plan, "test_policy")
        state = require_text(policy, "state")
        required_jobs = require_list(policy, "required_job_ids")
        split = require_text(policy, "split")
        require_hash(policy, "split_sha256")
        require_equal(split, "test.txt", "pre-registration test policy does not name test.txt")
        require_equal(state, "unarmed", "pre-registration test policy is not unarmed")
        if len(required_jobs) != len(jobs):
            raise ReceiptError("pre-registration required-job count differs from frozen job count")
    else:
        assert candidate is not None
        fingerprint = require_hash(candidate, "experiment_fingerprint")
        state = require_text(candidate, "test_plan_state")
        if require_bool(candidate, "test_split_opened"):
            raise ReceiptError("candidate receipt says the test split was opened")
        require_equal(state, "unarmed", "candidate test policy is not unarmed")
        jobs = []

    if candidate is not None:
        candidate_fingerprint = require_hash(candidate, "experiment_fingerprint")
        candidate_state = require_text(candidate, "test_plan_state")
        candidate_opened = require_bool(candidate, "test_split_opened")
        require_equal(
            candidate_fingerprint,
            fingerprint,
            "candidate and pre-registration fingerprints disagree",
        )
        require_equal(candidate_state, state, "candidate and plan test states disagree")
        require_equal(candidate_opened, False, "candidate receipt says test was opened")

    return PREAMBLE + f"""\\begin{{table}}[H]
  \\centering
  \\small
  \\caption{{Pre-registration state of the frozen evaluation plan.  The test split
  is reported here solely to evidence that it remains unopened.}}
  \\label{{tab:preregistration}}
  \\begin{{tabular}}{{ll}}
    \\toprule
    Quantity & Value \\\\
    \\midrule
    Plan fingerprint & \\texttt{{{short_hash(fingerprint)}}} \\\\
    Frozen jobs & {len(jobs) if jobs else "not supplied by candidate receipt"} \\\\
    \\textbf{{Test policy state}} & \\textbf{{\\texttt{{{tex_escape(state)}}}}} \\\\
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""


def cafa5_full_table(receipt: dict[str, Any] | None) -> str:
    if receipt is None:
        return pending(
            "full partial-knowledge evaluation",
            "The frozen full-target CAFA5 evaluation has not been run.",
        )
    status = require_text(receipt, "status")
    require_equal(
        status,
        "full-data-cetta-group-fold-evaluation-complete",
        "CAFA5 receipt is not a full load-bearing CeTTa evaluation",
    )
    target_count = require_int(receipt, "target_count", minimum=1)
    source_inputs = require_list(receipt, "source_inputs")
    if not source_inputs:
        raise ReceiptError("full CAFA5 receipt contains no source inputs")
    for index, source in enumerate(source_inputs):
        if not isinstance(source, dict):
            raise ReceiptError(f"CAFA5 source_inputs[{index}] must be an object")
        require_text(source, "source")
        require_text(source, "dependence_group")
        require_int(source, "bytes", minimum=1)
        require_hash(source, "sha256")

    fusion = require_object(receipt, "fusion")
    require_equal(
        require_text(fusion, "backend_role"),
        "load-bearing-reducer",
        "full CAFA5 fusion backend is not load-bearing",
    )
    fusion_policy = require_text(fusion, "fusion_policy")
    candidate_rows = require_int(fusion, "candidate_rows", minimum=1)
    require_hash(fusion, "prediction_sha256")
    require_hash(fusion, "trail_sha256")
    differential = require_object(fusion, "differential_oracle")
    require_equal(
        require_text(differential, "status"),
        "passed",
        "full CAFA5 differential oracle did not pass",
    )

    evaluator = require_object(receipt, "official_evaluator")
    canonical = require_object(evaluator, "canonical_summary")
    require_equal(
        require_text(canonical, "result_kind"),
        "full-partial-knowledge-evaluation",
        "CAFA5 evaluator receipt is not a full partial-knowledge result",
    )
    semantic_hash = require_hash(canonical, "semantic_sha256")
    require_hash(evaluator, "canonical_summary_sha256")
    metrics = require_object(canonical, "metrics")
    metric_labels = (
        ("f_max", "F-max"),
        ("weighted_f_max", "weighted F-max"),
        ("unweighted_semantic_distance_min", "unweighted semantic distance min"),
        ("weighted_semantic_distance_min", "weighted semantic distance min"),
    )
    metric_rows: list[str] = []
    for metric_key, metric_label in metric_labels:
        entries = require_list(metrics, metric_key)
        if not entries:
            raise ReceiptError(f"CAFA5 evaluator metric {metric_key!r} is empty")
        for index, entry in enumerate(entries):
            if not isinstance(entry, dict):
                raise ReceiptError(f"CAFA5 metric {metric_key}[{index}] must be an object")
            method = require_text(entry, "method")
            namespace = require_text(entry, "namespace")
            threshold = require_number(entry, "threshold")
            value = require_number(entry, "value")
            coverage = require_probability(entry, "coverage")
            metric_rows.append(
                "    {} & {} & {:.6f} & {:.6f} & {:.4f} \\\\".format(
                    tex_escape(metric_label),
                    tex_escape(f"{method} / {namespace}"),
                    value,
                    threshold,
                    coverage,
                )
            )

    return PREAMBLE + f"""\\begin{{table}}[H]
  \\centering
  \\small
  \\caption{{Official full-target CAFA5 partial-knowledge evaluation.  The
  receipt reports {target_count:,} targets, {candidate_rows:,} fused candidates,
  fusion policy \\texttt{{{tex_escape(fusion_policy)}}}, and a passed real-shaped
  differential gate.  Canonical evaluator digest:
  \\texttt{{{short_hash(semantic_hash)}}}.}}
  \\label{{tab:cafa5-full}}
  \\begin{{tabular}}{{lllll}}
    \\toprule
    Metric & Method / namespace & Value & Threshold & Coverage \\\\
    \\midrule
{chr(10).join(metric_rows)}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""


def biopathnet_grid_table(receipt: dict[str, Any] | None) -> str:
    if receipt is None:
        return pending(
            "control / path-evidence / hybrid comparison",
            "The multi-seed training grid and the one-use test evaluation have not"
            " been run, so no comparison against a control exists.",
        )
    require_equal(
        require_int(receipt, "schema_version", minimum=1),
        1,
        "unsupported BioPathNet comparison receipt schema",
    )
    status = require_text(receipt, "status")
    require_equal(
        status,
        "frozen-one-use-test-complete",
        "BioPathNet comparison receipt is not a frozen one-use test result",
    )
    require_equal(
        require_text(receipt, "split"),
        "test",
        "BioPathNet comparison receipt does not describe the test split",
    )
    require_equal(
        require_bool(receipt, "test_split_opened"),
        True,
        "BioPathNet comparison receipt does not attest one-use test access",
    )
    plan_hash = require_hash(receipt, "experiment_fingerprint")
    systems = require_list(receipt, "systems")
    if not systems:
        raise ReceiptError("BioPathNet comparison receipt contains no system rows")
    system_rows: list[str] = []
    seen_systems: set[str] = set()
    seen_seeds: set[int] = set()
    for index, row in enumerate(systems):
        if not isinstance(row, dict):
            raise ReceiptError(f"BioPathNet systems[{index}] must be an object")
        system = require_text(row, "system")
        seed = require_int(row, "seed")
        row_metrics = require_object(row, "metrics")
        mrr = require_probability(row_metrics, "mrr")
        mean_rank = require_number(row_metrics, "mr")
        hits1 = require_probability(row_metrics, "hits@1")
        hits3 = require_probability(row_metrics, "hits@3")
        hits10 = require_probability(row_metrics, "hits@10")
        seen_systems.add(system)
        seen_seeds.add(seed)
        system_rows.append(
            "    {} & {} & {:.6f} & {:.2f} & {:.4f} & {:.4f} & {:.4f} \\\\".format(
                tex_escape(system), seed, mrr, mean_rank, hits1, hits3, hits10
            )
        )
    require_equal(
        seen_systems,
        {"biopathnet-control", "pln-path-evidence", "biopathnet-pln-hybrid"},
        "BioPathNet comparison does not contain exactly the three frozen systems",
    )
    if len(seen_seeds) != 5:
        raise ReceiptError("BioPathNet comparison must report exactly five seeds")
    if len(systems) != 15:
        raise ReceiptError("BioPathNet comparison must contain three systems by five seeds")

    primary = require_object(receipt, "primary_comparison")
    require_equal(require_text(primary, "left"), "biopathnet-pln-hybrid", "primary left system is not the hybrid")
    require_equal(require_text(primary, "right"), "biopathnet-control", "primary right system is not the fresh control")
    require_equal(require_text(primary, "metric"), "mrr", "primary comparison metric is not MRR")
    difference = require_number(primary, "mean_difference")
    confidence = require_probability(primary, "confidence")
    lower = require_number(primary, "lower")
    upper = require_number(primary, "upper")
    replicates = require_int(primary, "replicates", minimum=1)
    query_count = require_int(primary, "query_count", minimum=1)
    if lower > upper:
        raise ReceiptError("BioPathNet bootstrap interval is reversed")

    return PREAMBLE + f"""\\begin{{table}}[H]
  \\centering
  \\small
  \\caption{{Frozen five-seed BioPathNet one-use test result.  Plan fingerprint:
  \\texttt{{{short_hash(plan_hash)}}}.  The primary paired query-bootstrap
  comparison is hybrid minus fresh control: {difference:.6f} MRR
  ({confidence:.1%} interval [{lower:.6f}, {upper:.6f}], {replicates:,}
  replicates over {query_count:,} queries).}}
  \\label{{tab:biopathnet-grid}}
  \\begin{{tabular}}{{llrrrrr}}
    \\toprule
    System & Seed & MRR & MR & Hits@1 & Hits@3 & Hits@10 \\\\
    \\midrule
{chr(10).join(system_rows)}
    \\bottomrule
  \\end{{tabular}}
\\end{{table}}
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--cafa5-differential", type=Path)
    parser.add_argument("--cafa5-full", type=Path)
    parser.add_argument("--biopathnet-candidate", type=Path)
    parser.add_argument("--biopathnet-plan", type=Path)
    parser.add_argument("--biopathnet-grid", type=Path)
    args = parser.parse_args()

    args.out.mkdir(parents=True, exist_ok=True)

    differential = load(args.cafa5_differential, "CAFA5 differential")
    full_cafa5 = load(args.cafa5_full, "full CAFA5")
    candidate = load(args.biopathnet_candidate, "BioPathNet candidate")
    plan = load(args.biopathnet_plan, "BioPathNet plan")
    grid = load(args.biopathnet_grid, "BioPathNet comparison")

    written = {
        "wmpf_reducer_equivalence.tex": reducer_equivalence_table(differential),
        "wmpf_biopathnet_candidate.tex": biopathnet_candidate_table(candidate),
        "wmpf_preregistration.tex": preregistration_table(plan, candidate),
        "wmpf_cafa5_full.tex": cafa5_full_table(full_cafa5),
        "wmpf_biopathnet_grid.tex": biopathnet_grid_table(grid),
    }

    for name, body in written.items():
        (args.out / name).write_text(body, encoding="utf-8")
        status = "pending" if "PENDING" in body else "receipt-backed"
        print(f"{name}: {status}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
