"""Independent verifier for a goal-directed cap C-reducibility certificate.

Re-implements everything from scratch, differently from the producing
code:
  * extension test: DFS over vertices (not edges) with forward checking;
  * noncrossing matchings: generated by a different recursion (match the
    LAST point instead of the first) and compared as sets;
  * certificates re-checked in derivation order: a certified word w with
    pair (x,y) and per-matching subsets is accepted iff for EVERY matching
    of its pair-ports (independently enumerated) the listed subset's switch
    lands in supp (independent solver) or in an EARLIER accepted word;
  * finally every cap word must be in supp or accepted.
Reads: tangle.json, bestcaps.json (cap index), kgd_d*.json (certificates,
'results' with 'cert' fields).  Prints VERIFIED or the first failure.
"""
import sys, json, itertools
from collections import defaultdict

tpath, bpath, cpath = sys.argv[1], sys.argv[2], sys.argv[3]
ci = int(sys.argv[4]) if len(sys.argv) > 4 else 0
d = json.load(open(tpath)); n, nv = d['n'], d['nv']
E = []
for e in d['edges']:
    u, v = e
    u = ('p', u[1]) if isinstance(u, list) else u
    v = ('p', v[1]) if isinstance(v, list) else v
    E.append((u, v))
best = json.load(open(bpath))[ci]; cap = [tuple(p) for p in best['cap']]
cert = json.load(open(cpath))
# derivations may be streamed to a JSONL file (word, depth, x, y, entries), shallow first
if 'derivations_file' in cert:
    cert['derivations'] = [dict(word=r['word'], depth=r['depth'], cert=[r['x'], r['y'], r['entries']])
                           for r in (json.loads(l) for l in open(cert['derivations_file']))]

# ---------- independent extension solver: vertex-based DFS
adj = defaultdict(list)          # node -> list of (edge id, other)
for k, (u, v) in enumerate(E):
    adj[u].append((k, v)); adj[v].append((k, u))
assert all(len(adj[v]) == 3 for v in range(nv)), "internal vertex not cubic"
port_edge = {i: adj[('p', i)][0][0] for i in range(n)}
# vertex order: BFS from the vertices adjacent to ports
start = [adj[('p', i)][0][1] for i in range(n)]
order = []; seen = set()
frontier = [v for v in start if not isinstance(v, tuple)]
for v in frontier: seen.add(v)
while frontier:
    nxt = []
    for v in frontier:
        order.append(v)
        for (k, w) in adj[v]:
            if not isinstance(w, tuple) and w not in seen: seen.add(w); nxt.append(w)
    frontier = nxt
order += [v for v in range(nv) if v not in seen]
assert len(order) == nv

def extends(word):
    col = {}
    for i, c in enumerate(word): col[port_edge[i]] = c
    # vertex-based DFS: at each vertex assign colours to its uncoloured edges as a permutation of the free colours
    def consistent_at(v):
        cs = [col[k] for (k, _) in adj[v] if k in col]
        return len(cs) == len(set(cs))
    for v in range(nv):
        if not consistent_at(v): return False
    def rec(idx):
        if idx == nv: return True
        v = order[idx]
        free_edges = [k for (k, _) in adj[v] if k not in col]
        used = {col[k] for (k, _) in adj[v] if k in col}
        avail = [c for c in range(3) if c not in used]
        if len(avail) < len(free_edges): return False
        for perm in itertools.permutations(avail, len(free_edges)):
            for k, c in zip(free_edges, perm): col[k] = c
            ok = True
            for k in free_edges:
                u, w = E[k]
                for z in (u, w):
                    if not isinstance(z, tuple) and not consistent_at(z): ok = False; break
                if not ok: break
            if ok and rec(idx + 1): return True
            for k in free_edges: del col[k]
        return False
    return rec(0)

# ---------- independent noncrossing matchings: match the last point
def matchings(pts):
    if not pts: return [[]]
    out = []
    b = pts[-1]
    for i in range(len(pts) - 2, -1, -2):
        a = pts[i]
        inside = pts[i + 1:-1]; outside = pts[:i]
        for mi in matchings(inside):
            for mo in matchings(outside):
                out.append(mo + [(a, b)] + mi)
    return out

def switch(w, x, y, chains):
    w = list(w)
    for (i, j) in chains:
        for p in (i, j):
            assert w[p] in (x, y), "chain endpoint not of the pair"
            w[p] = y if w[p] == x else x
    return tuple(w)

accepted = set()
supp_cache = {}
def in_supp(w):
    if w not in supp_cache: supp_cache[w] = extends(w)
    return supp_cache[w]
n_ok = 0
for idx, r in enumerate(cert['derivations']):
    w = tuple(r['word']); c = r['cert']
    if in_supp(w):
        accepted.add(w); continue          # already a support word; certificate not needed
    x, y, entries = c[0], c[1], c[2]
    if x not in (0, 1, 2) or y not in (0, 1, 2) or x == y: print("FAIL: bad pair", w); sys.exit(1)
    P = [i for i in range(n) if w[i] in (x, y)]
    listed = {}
    for mu, sub in entries:
        key = frozenset(tuple(p) for p in mu)
        if key in listed: print("FAIL: duplicate matching listed", w); sys.exit(1)
        listed[key] = ([tuple(p) for p in mu], sub)
    mine = matchings(P)
    if len(mine) != len(listed) or any(frozenset(m) not in listed for m in mine):
        print("FAIL: matching set mismatch for", w, len(mine), len(listed)); sys.exit(1)
    for m in mine:
        mu_l, sub = listed[frozenset(m)]
        chains = [mu_l[t] for t in sub]
        sw = switch(w, x, y, chains)
        if not (in_supp(sw) or sw in accepted):
            print("FAIL: switched word neither in supp nor accepted earlier", w, m, sub); sys.exit(1)
    accepted.add(w); n_ok += 1
print(f"accepted derivations: {n_ok} (of {len(cert['derivations'])} listed); independent extension tests {len(supp_cache)}")
# cap coverage
missing = 0; total = 0
for cols in itertools.product(range(3), repeat=len(cap)):
    w = [None] * n
    for (i, j), c in zip(cap, cols): w[i] = c; w[j] = c
    w = tuple(w); total += 1
    # colour permutations preserve support (permute the colouring) and the Kempe rule
    # (permute the pair and the switched words), so the closure is permutation-closed
    perms = [dict(zip((0, 1, 2), pm)) for pm in itertools.permutations((0, 1, 2))]
    if not any((tuple(pm[c] for c in w) in accepted) or in_supp(tuple(pm[c] for c in w)) for pm in perms): missing += 1
print(f"cap words {total}, not covered {missing}")
print("VERIFIED: cap C-reducibility certificate complete" if missing == 0 else f"INCOMPLETE: {missing} cap words uncovered")
